Repository streamlit/streamlit, pull requests merged in 2020-09, with the labels that each got.

#1943 Add deprecation label to st.deck_gl_chart
  lib/streamlit/elements/deck_gl.py
Labels: docs

#1981 Components: support for bytes
  component-lib/src/streamlit.ts
  frontend/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/src/components/widgets/CustomComponent/enums.ts
  frontend/src/lib/WidgetStateManager.test.ts
  frontend/src/lib/WidgetStateManager.ts
  frontend/src/lib/immutableProto.ts
  lib/streamlit/components/v1/components.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/type_util_test.py
  proto/streamlit/proto/ComponentInstance.proto
  proto/streamlit/proto/WidgetStates.proto
Labels: release-notes

#1994 Bump component-lib to v1.1.0
  component-lib/package.json
Labels: release-notes

#2034 Fix machine id for analytics
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/hocs/withMapboxToken/MapboxToken.test.ts
  frontend/src/hocs/withMapboxToken/withMapboxToken.test.tsx
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/HttpClient.test.ts
  frontend/src/lib/MetricsManager.test.ts
  frontend/src/lib/MetricsManager.ts
  frontend/src/lib/SessionInfo.ts
  lib/streamlit/__init__.py
  lib/streamlit/metrics_util.py
  lib/streamlit/report_session.py
  lib/tests/streamlit/metrics_util_test.py
  lib/tests/streamlit/report_session_test.py
  proto/streamlit/proto/Initialize.proto
Labels: product review needed

#2046 Create Dropdown from BaseWeb's Menu
  e2e/specs/st_main_menu.spec.ts
  frontend/cypress/snapshots/linux/2x/st_disconnect.spec.ts/disconnected.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.ts/main_menu.snap.png
  frontend/src/App.tsx
  frontend/src/components/core/MainMenu/MainMenu.scss
  frontend/src/components/core/MainMenu/MainMenu.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/components/core/MainMenu/__snapshots__/MainMenu.test.tsx.snap
  frontend/src/components/core/MainMenu/component/ScreencastOption.tsx
Labels: product review needed
