Repository streamlit/streamlit, pull requests merged in 2020-10, with the labels that each got.

#2101 Default st.date_input's min to be 10 years ago
  lib/streamlit/elements/time_widgets.py
Labels: product review needed

#2140 [Blocker] Place delta generator with blocks in report context
  lib/streamlit/delta_generator.py
  lib/streamlit/report_thread.py
  lib/tests/streamlit/delta_generator_test.py
Labels: release-blocker

#2060 Adding experimental_rerun
  e2e/scripts/st_experimental_rerun.py
  e2e/specs/st_experimental_rerun.spec.ts
  lib/streamlit/__init__.py
  scripts/run_bare_integration_tests.py
Labels: synced

#2167 Add config option for server.allowRunOnSave
  books.jpg
  frontend/src/App.tsx
  frontend/src/components/core/StatusWidget/StatusWidget.test.tsx
  frontend/src/components/core/StatusWidget/StatusWidget.tsx
  frontend/src/components/core/StreamlitDialog/ScriptChangedDialog.tsx
  frontend/src/components/core/StreamlitDialog/SettingsDialog.tsx
  lib/streamlit/config.py
  lib/streamlit/report_session.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/report_queue_test.py
  proto/streamlit/proto/Initialize.proto
Labels: product review needed

#2102 Move set_page_config out of beta
  docs/api.md
  docs/changelog.md
  e2e/scripts/st_set_page_config.py
  lib/streamlit/__init__.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/report_thread.py
Labels: product review needed

#2097 Select the right x-axis type for bar charts
  docs/api-examples-source/layout.expander.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/altair.py
Labels: product review needed

#2269 Reset sort column index if the sorted column was removed
  e2e/scripts/st_dataframe_sort_column.py
  e2e/specs/st_dataframe.spec.js
  e2e/specs/st_dataframe_sort_column.spec.js
  frontend/src/components/elements/DataFrame/DataFrame.tsx
Labels: product review needed

#2292 Fix typo in expander docstring
  lib/streamlit/delta_generator.py
Labels: docs
