Repository streamlit/streamlit, pull requests merged in 2020-12, with the labels that each got.

#2372 Consolidate reruns for multiple file uploads
  frontend/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/src/lib/FileUploadClient.ts
  lib/streamlit/server/server.py
  lib/streamlit/server/upload_file_request_handler.py
  lib/streamlit/uploaded_file_manager.py
  lib/tests/streamlit/server_test.py
  lib/tests/streamlit/upload_file_request_handler_test.py
  lib/tests/streamlit/uploaded_file_manager_test.py
Labels: product review needed

#2403 Disable Git integration for ancient Gits
  lib/streamlit/bootstrap.py
  lib/streamlit/git_util.py
  lib/streamlit/server/server.py
  lib/tests/streamlit/bootstrap_test.py
  lib/tests/streamlit/git_util_test.py
Labels: product review needed

#2455 Using whitelist check cloud/core communication
  frontend/src/hocs/withS4ACommunication/withS4ACommunication.tsx
  frontend/src/urls.ts
Labels: release-blocker

#2452 Don't require pyarrow on 3.9, and show a warning on custom components
  lib/Pipfile
  lib/streamlit/components/v1/components.py
Labels: product review needed, release-blocker

#2472 Minor tweak to PyArrow warning message
  lib/streamlit/components/v1/components.py
Labels: release-blocker
