Repository streamlit/streamlit, pull requests merged in 2021-10, with the labels that each got.

#3852 [Security] Upgrade `css-what` to 5.0.1 or later
  frontend/package.json
  frontend/yarn.lock
Labels: security

#3851 [Security] Upgrade `immer` to 9.0.6 or later
  frontend/package.json
  frontend/yarn.lock
Labels: security

#3847 [Security] Upgrade `glob-parent` to 5.1.2 or later
  frontend/package.json
  frontend/yarn.lock
Labels: security

#3846 [Security] Upgrade `tar` to 6.1.9 or later
  frontend/package.json
  frontend/yarn.lock
Labels: security

#3845 [Security] Upgrade `set-value` to 4.0.1 or later
  frontend/package.json
  frontend/yarn.lock
Labels: security

#3849 [Arrow] Custom exception for `numpy.dtype` conversion error
  lib/streamlit/errors.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: arrow

#3840 [Arrow] Immutable add rows with `immer`
  e2e/scripts/st_arrow_line_chart_add_rows_special.py
  e2e/specs/st_arrow_line_chart_add_rows_special.spec.js
  frontend/cypress/snapshots/linux/2x/st_arrow_line_chart_add_rows_special.spec.js/arrowLineChartAddRows-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_line_chart_add_rows_special.spec.js/arrowLineChartAddRows.snap.png
  frontend/src/lib/Quiver.test.ts
  frontend/src/lib/Quiver.ts
  frontend/src/lib/ReportNode.ts
Labels: arrow

#3877 Fixes identation issue in `st.set_page_config` docstring
  lib/streamlit/commands/page_config.py
Labels: docs
