Repository streamlit/streamlit, pull requests merged in 2022-10, with the labels that each got.

#5438 For `st.image` return "GIF", not "PNG", if PIL image is a GIF
  e2e/scripts/st_image.py
  e2e/specs/st_image.spec.js
  frontend/cypress/snapshots/linux/2x/st_image.spec.js/gif-with-caption.snap.png
  lib/streamlit/elements/image.py
  lib/tests/streamlit/elements/image_test.py
Labels: regression, st.image

#5570 Snowpark integration: Show an uncollected dataframe when using st.dataframe
  e2e/scripts/st_arrow_unevaluated_snowpark_dataframe.py
  e2e/specs/st_arrow_unevaluated_snowpark_dataframe.js
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/dataframe_selector_test.py
  lib/tests/streamlit/snowpark_mocks.py
Labels: enhancement

#5594 Order of params in docstrings should match function signature
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/media.py
Labels: docs
