Repository streamlit/streamlit, pull requests merged in 2022-01, with the labels that each got.

#4184 st.memo/singleton: cache-specific clear() functionality
  lib/streamlit/caching/cache_utils.py
  lib/streamlit/caching/memo_decorator.py
  lib/streamlit/caching/singleton_decorator.py
  lib/tests/streamlit/caching/common_cache_test.py
  lib/tests/streamlit/caching/memo_test.py
Labels: product review needed

#4177 Add ability for an app's host to configure its toolbar items
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/core/MainMenu/__snapshots__/MainMenu.test.tsx.snap
  frontend/src/components/core/StatusWidget/__snapshots__/StatusWidget.test.tsx.snap
  frontend/src/components/core/ToolbarActions/ToolbarActions.test.tsx
  frontend/src/components/core/ToolbarActions/ToolbarActions.tsx
  frontend/src/components/core/ToolbarActions/__snapshots__/ToolbarActions.test.tsx.snap
  frontend/src/components/core/ToolbarActions/index.tsx
  frontend/src/components/core/ToolbarActions/styled-components.ts
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/components/shared/Button/styled-components.ts
  frontend/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/src/hocs/withS4ACommunication/types.ts
  frontend/src/hocs/withS4ACommunication/withS4ACommunication.test.tsx
  frontend/src/hocs/withS4ACommunication/withS4ACommunication.tsx
  frontend/src/theme/utils.ts
  frontend/src/urls.ts
  lib/streamlit/config.py
  lib/streamlit/report_session.py
  lib/tests/streamlit/config_test.py
  proto/streamlit/proto/NewReport.proto
Labels: product review needed

#4266 Add example to camera_input docstring
  lib/streamlit/elements/camera_input.py
Labels: docs

#4259 Get rid of preheated script runs
  frontend/src/App.tsx
  lib/streamlit/__main__.py
  lib/streamlit/app_session.py
  lib/streamlit/bootstrap.py
  lib/streamlit/cli.py
  lib/streamlit/server/server.py
  lib/tests/streamlit/cli_test.py
  scripts/cli_smoke_tests.py
  scripts/test_data/print_command_line.py
Labels: MADE 💖

#4298 Fix docstring formatting issues
  lib/streamlit/__init__.py
  lib/streamlit/elements/camera_input.py
Labels: docs

#4328 Increase `cy.loadApp` timeouts to 10s
  frontend/cypress/support/commands.js
Labels: tests

#4327 Get version using importlib-metadata instead of pkg_resources
  lib/Pipfile
  lib/streamlit/__init__.py
  lib/streamlit/version.py
  scripts/update_name.py
Labels: performance

#4323 Use force for refresh keypress in legacy add rows e2e test
  e2e/specs/st_legacy_add_rows.spec.js
Labels: tests
