Repository streamlit/streamlit, pull requests merged in 2022-08, with the labels that each got.

#5074 Make st.map use light or dark styles based on Streamlit's theme
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo.snap.png
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/map.py
  lib/streamlit/hello/pages/2_🌍_Mapping_Demo.py
  lib/tests/streamlit/map_test.py
Labels: enhancement, st.map

#5062 add .pre-commit-config.yaml
  .circleci/config.yml
  .pre-commit-config.yaml
  Makefile
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
  lib/Pipfile
  scripts/format.sh
  scripts/run_in_subdirectory.py
Labels: enhancement, onboarding

#5108 Add note about `map_style=None` to `st.pydeck_chart` docstring
  lib/streamlit/elements/deck_gl_json_chart.py
Labels: docs, st.pydeck_chart

#5116 Fix tabs switching couse scrolling up
  e2e/specs/st_tabs.spec.js
  frontend/src/components/elements/Tabs/Tabs.tsx
  frontend/src/components/elements/Video/Video.tsx
Labels: bug

#5060 Pytest ignore deprecation warnings
  lib/pytest.ini
  lib/tests/streamlit/legacy_add_rows_test.py
  lib/tests/streamlit/legacy_data_frame_test.py
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
Labels: infra, onboarding

#5172 ask for protobuf version only if we're not on circleci
  Makefile
Labels: bug, infra

#5135 Fix tabs switching couse scrolling up with YouTube's videos
  frontend/src/components/elements/Video/Video.test.tsx
  frontend/src/components/elements/Video/Video.tsx
  frontend/src/components/elements/Video/__snapshots__/Video.test.tsx.snap
Labels: bug

#5194 Upgrade baseui to 9.116.3
  e2e/specs/session_state_frontend_sync.spec.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/elements/DataFrame/DataFrame.test.tsx
  frontend/src/components/elements/Table/Table.test.tsx
  frontend/src/components/elements/VegaLiteChart/VegaLiteChart.test.tsx
  frontend/src/components/shared/AlertContainer/AlertContainer.test.tsx
  frontend/src/components/shared/AlertContainer/AlertContainer.tsx
  frontend/src/components/shared/ProgressBar/ProgressBar.tsx
  frontend/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/src/components/widgets/Slider/Slider.tsx
  frontend/src/hocs/withExpandable/withExpandable.tsx
  frontend/src/hocs/withFullScreenWrapper/withFullScreenWrapper.test.tsx
  frontend/src/lib/UriUtil.ts
  frontend/yarn.lock
Labels: bug

#5271 Fix convert sets to lists to handle iterables
  lib/streamlit/elements/json.py
  lib/tests/streamlit/delta_generator_test.py
Labels: bug
