Repository streamlit/streamlit, pull requests merged in 2023-08, with the labels that each got.

#7060 Feature/root style provider
  frontend/app/src/ThemedApp.tsx
  frontend/lib/src/RootStyleProvider.tsx
  frontend/lib/src/index.ts
Labels: security-assessment-completed, impact:internal, change:chore

#7093 Remove stale comments and group statements writing to protobufs
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7094 Add "ai" and "human" presets for `st.chat_message`
  e2e/scripts/st_chat_message.py
  frontend/lib/src/components/elements/ChatMessage/ChatMessage.tsx
  lib/streamlit/elements/widgets/chat.py
  lib/tests/streamlit/elements/chat_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7056 add type to download button
  e2e/scripts/st_download_button.py
  e2e/specs/st_download_button.spec.js
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/primary-download-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/primary-download-button.snap.png
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  lib/streamlit/elements/widgets/button.py
  lib/tests/streamlit/elements/download_button_test.py
  proto/streamlit/proto/DownloadButton.proto
Labels: security-assessment-completed, change:feature, impact:users

#7103 Don't build frontend assets when SNOWPARK_CONDA_BUILD=1
  Makefile
Labels: security-assessment-completed, impact:internal, change:chore

#7085 Enable the deploy button
  e2e/scripts/deploy_button.py
  e2e/specs/deploy_button.spec.js
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/lib/src/baseconsts.ts
  frontend/lib/src/index.ts
  frontend/lib/src/util/utils.ts
  lib/streamlit/runtime/app_session.py
Labels: security-assessment-completed, change:feature, impact:users

#7108 Add tests to ensure we don't forget to update widget id computation
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7106 Markdown: add gray & rainbow to supported colors
  e2e/scripts/st_markdown.py
  frontend/cypress/snapshots/linux/2x/st_markdown.spec.js/markdown-visuals-19-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown.spec.js/markdown-visuals-19.snap.png
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, change:feature, impact:users

#7114 Refactor expander frontend component
  e2e/playwright/st_expander_nested.py
  e2e/playwright/st_expander_nested_test.py
  e2e/playwright/st_expander_state.py
  e2e/playwright/st_expander_state_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/Expander/Expander.test.tsx
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/Expander/index.tsx
  frontend/lib/src/components/elements/Expander/styled-components.ts
  frontend/lib/src/hocs/withExpandable/withExpandable.test.tsx
  frontend/lib/src/hocs/withExpandable/withExpandable.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#7138 Fix issues with mixing short- and longhand props
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployCard.tsx
  frontend/lib/src/components/shared/Modal/Modal.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#7110 Convert some FE Enzyme tests to RTL
  e2e/scripts/st_text_area.py
  e2e/specs/st_text_area.spec.js
  frontend/cypress/snapshots/linux/2x/st_text_area.spec.js/text_area10-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_text_area.spec.js/text_area10.snap.png
  frontend/cypress/snapshots/linux/2x/st_text_area.spec.js/text_area9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_text_area.spec.js/text_area9.snap.png
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.test.tsx
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7122 specifying that md5 is not used for security
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/watcher/util.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7113 Cache JSON when using pydeck local data
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/hocs/withFullScreenWrapper/withFullScreenWrapper.tsx
  lib/streamlit/elements/deck_gl_json_chart.py
  proto/streamlit/proto/DeckGlJsonChart.proto
Labels: security-assessment-completed, change:bugfix, impact:users

#7146 File uploader request method
  e2e/specs/st_file_uploader.spec.js
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/tests/streamlit/web/server/upload_file_request_handler_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7141 Remove stale checks on sys.version_info
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/scriptrunner/magic.py
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/dataframe_selector_test.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
  lib/tests/streamlit/write_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed, impact:internal, change:chore

#7143 exclude async funcs docstring from magic prints
  lib/streamlit/runtime/scriptrunner/magic.py
  lib/tests/streamlit/runtime/scriptrunner/magic_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#7160 Remove attribution
  lib/streamlit/runtime/metrics_util.py
Labels: security-assessment-completed, change:other, impact:internal

#7149 Stop dropping file uploader state after websocket disconnect
  e2e/scripts/websocket_reconnects.py
  e2e/specs/st_camera_input.spec.js
  e2e/specs/websocket_reconnects.spec.js
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7150 Fix autofill browser by making sure we commit the value in text inputs
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7169 Add App.test.tsx tests to HostConfig feature
  frontend/app/src/App.test.tsx
Labels: security-assessment-completed, change:other, impact:internal

#7158 Allow metrics gathering even if interrupted by rerun, and track `st.rerun`
  lib/streamlit/commands/execution_control.py
  lib/streamlit/runtime/metrics_util.py
Labels: security-assessment-completed, change:other, impact:internal

#7170 Fix issue with duplicated widget ID for toggle
  lib/streamlit/elements/widgets/checkbox.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#7174 Add required=True to match behavior with embedded app
  lib/streamlit/elements/lib/column_types.py
Labels: security-assessment-completed, impact:internal, change:docs

#7177 Change logWarning to logError
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: impact:internal, change:chore

#7175 Add the disableUserTheme flag to host config
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/test_util.tsx
  lib/streamlit/web/server/routes.py
Labels: impact:internal, change:feature

#7162 Improve community voting
  .github/workflows/community-voting.yml
Labels: security-assessment-completed, change:other, impact:internal

#7185 Add github token to fix community voting
  .github/workflows/community-voting.yml
Labels: security-assessment-completed, change:other, impact:internal

#7179 Update allowed colors docstrings & allow grey
  e2e/scripts/st_markdown.py
  frontend/cypress/snapshots/linux/2x/st_markdown.spec.js/markdown-visuals-19-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown.spec.js/markdown-visuals-19.snap.png
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/progress.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
Labels: security-assessment-completed, impact:users, change:docs

#7182 Remove old deploy functionality
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/RepoIsAhead.test.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/RepoIsAhead.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/UncommittedChanges.test.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/UncommittedChanges.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/UntrackedFiles.test.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/UntrackedFiles.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/__snapshots__/RepoIsAhead.test.tsx.snap
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/__snapshots__/UncommittedChanges.test.tsx.snap
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/__snapshots__/UntrackedFiles.test.tsx.snap
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/index.ts
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu.snap.png
Labels: security-assessment-completed, impact:internal, change:refactor

#7190 Fix the bottom margin for code in markdown
  e2e/playwright/snapshots/linux/st_chat_message_test/chat_message-1[dark_theme-chromium].png
  e2e/playwright/snapshots/linux/st_chat_message_test/chat_message-1[dark_theme-firefox].png
  e2e/playwright/snapshots/linux/st_chat_message_test/chat_message-1[dark_theme-webkit].png
  e2e/playwright/snapshots/linux/st_chat_message_test/chat_message-1[light_theme-chromium].png
  e2e/playwright/snapshots/linux/st_chat_message_test/chat_message-1[light_theme-firefox].png
  e2e/playwright/snapshots/linux/st_chat_message_test/chat_message-1[light_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/expander_with_code[chromium].png
  e2e/playwright/snapshots/linux/st_code_test/expander_with_code[firefox].png
  e2e/playwright/snapshots/linux/st_code_test/expander_with_code[webkit].png
  e2e/playwright/snapshots/linux/st_code_test/expander_with_markdown_code[chromium].png
  e2e/playwright/snapshots/linux/st_code_test/expander_with_markdown_code[firefox].png
  e2e/playwright/snapshots/linux/st_code_test/expander_with_markdown_code[webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-auto_lang[dark_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-auto_lang[dark_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-auto_lang[dark_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-auto_lang[light_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-auto_lang[light_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-auto_lang[light_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-empty[dark_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-empty[dark_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-empty[dark_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-empty[light_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-empty[light_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-empty[light_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-line_numbers[dark_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-line_numbers[dark_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-line_numbers[dark_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-line_numbers[light_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-line_numbers[light_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-line_numbers[light_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-no_lang[dark_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-no_lang[dark_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-no_lang[dark_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-no_lang[light_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-no_lang[light_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-no_lang[light_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-python_lang[dark_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-python_lang[dark_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-python_lang[dark_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-python_lang[light_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-python_lang[light_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/st_code-python_lang[light_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/syntax_highlighting[dark_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/syntax_highlighting[dark_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/syntax_highlighting[dark_theme-webkit].png
  e2e/playwright/snapshots/linux/st_code_test/syntax_highlighting[light_theme-chromium].png
  e2e/playwright/snapshots/linux/st_code_test/syntax_highlighting[light_theme-firefox].png
  e2e/playwright/snapshots/linux/st_code_test/syntax_highlighting[light_theme-webkit].png
  e2e/playwright/st_code.py
  e2e/playwright/st_code_test.py
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-1.snap.png
  frontend/lib/src/components/elements/CodeBlock/CodeBlock.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#7154 Option to disable step buttons on number_input
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: security-assessment-completed, change:feature, impact:users

#7105 `st.radio` - markdown enabled captions
  e2e/scripts/st_radio.py
  e2e/specs/st_radio.spec.js
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio10-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio10.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio11-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio11.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio12-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio12.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio9.snap.png
  frontend/lib/src/components/shared/Radio/Radio.test.tsx
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/Button/Button.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
  frontend/lib/src/components/widgets/Radio/Radio.tsx
  lib/streamlit/elements/widgets/radio.py
  lib/tests/streamlit/elements/radio_test.py
  proto/streamlit/proto/Radio.proto
Labels: security-assessment-completed, change:feature, impact:users

#7197 Fix the error messaging for host-security-config
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/BokehChart/BokehChart.tsx
  frontend/lib/src/components/elements/IFrame/IFrame.test.tsx
  frontend/lib/src/components/elements/IFrame/IFrame.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.test.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/Markdown/Markdown.test.tsx
  frontend/lib/src/components/elements/Markdown/Markdown.tsx
  frontend/lib/src/components/shared/ErrorBoundary/ErrorBoundary.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/hostComm/types.ts
  frontend/lib/src/index.ts
Labels: security-assessment-completed, impact:internal, change:chore

#7203 Fix: Remove divider cypress tests
  e2e/scripts/st_heading_divider.py
  e2e/specs/st_heading_divider.spec.js
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-blue0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-blue0.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-blue5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-blue5.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-green1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-green1.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-orange2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-orange2.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-red3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-red3.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-violet4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_heading_divider.spec.js/divider-violet4.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#7200 Migrate exception and spinner tests to RTL
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.test.tsx
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/ExceptionElement/__snapshots__/ExceptionElement.test.tsx.snap
  frontend/lib/src/components/elements/Spinner/Spinner.test.tsx
  frontend/lib/src/components/elements/Spinner/Spinner.tsx
  frontend/lib/src/components/elements/Spinner/__snapshots__/Spinner.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7198 Resolve flaky `websocket_reconnects` & `camera_input` e2e tests
  e2e/specs/st_camera_input.spec.js
  e2e/specs/websocket_reconnects.spec.js
Labels: security-assessment-completed, impact:internal, change:chore

#7204 Fix: Toasts blocked by `st.chat_input`
  e2e/scripts/st_toast.py
  e2e/specs/st_toast.spec.js
  frontend/app/src/components/EventContainer/EventContainer.tsx
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast+chatInput-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast+chatInput-light.snap.png
Labels: security-assessment-completed, change:bugfix, impact:users

#7189 Fix/docstrings
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/radio.py
Labels: security-assessment-completed, impact:internal, change:docs

#7194 Deprecate allowed-message-origins endpoint
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
  frontend/lib/src/index.ts
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7205 Fix: `st.multiselect` No Results vs. max selection message
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7212 Update glide-data-grid to 5.3
  e2e/playwright/snapshots/linux/st_data_editor_config_test/data_editor-config-13[chromium].png
  e2e/playwright/snapshots/linux/st_data_editor_config_test/data_editor-config-13[firefox].png
  e2e/playwright/snapshots/linux/st_data_editor_config_test/data_editor-config-13[webkit].png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-3.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-4.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-5.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_column_types.js/data_editor-column-types-6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_config.spec.js/data_editor-config-13.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_input_data.spec.js/data_editor-input-data-30.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_input_data.spec.js/data_editor-input-data-31.snap.png
  frontend/lib/package.json
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/cells/DateTimeCell.test.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/DateTimeCell.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/index.ts
  frontend/lib/src/theme/globalStyles.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#7195 Cleaner `st.rerun` and `st.stop` implementations
  lib/streamlit/commands/execution_control.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/delta_generator_test_case.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/stop_test.py
Labels: feature:st.experimental_rerun, security-assessment-completed, impact:internal, change:refactor

#7219 Fix bug where we should actually be defaulting to test@example.com instead of test@localhost.com
  lib/streamlit/web/server/browser_websocket_handler.py
Labels: security-assessment-completed, change:chore, impact:users

#7217 Open up pydeck version to include the beta
  lib/min-constraints-gen.txt
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#7193 Vendor `pympler.asizeof`
  .github/codeql-config.yml
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/vendor/pympler/__init__.py
  lib/streamlit/vendor/pympler/asizeof.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
Labels: security-assessment-completed, change:chore, impact:users

#7222 Track st.stop usage
  lib/streamlit/commands/execution_control.py
Labels: security-assessment-completed, change:other, impact:internal

#7231 Resolve python dep min version test
  lib/test-requirements.txt
Labels: security-assessment-completed, impact:internal, change:chore

#7221 Fix: `st.slider` overlapping label values
  e2e/scripts/st_slider.py
  e2e/specs/st_slider.spec.js
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/labels-overlap-slider-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/labels-overlap-slider.snap.png
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7227 Add e2e tests for host config
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_bokeh_chart[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_bokeh_chart[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_bokeh_chart[webkit].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_camera_input[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_camera_input[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_camera_input[webkit].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_components_html[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_components_html[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_components_html[webkit].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_components_iframe[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_components_iframe[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_components_iframe[webkit].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_custom_components[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_custom_components[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_custom_components[webkit].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_download_button[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_download_button[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_download_button[webkit].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_file_uploader[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_file_uploader[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_file_uploader[webkit].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_unsafe_html[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_unsafe_html[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/disabled_unsafe_html[webkit].png
  e2e_playwright/host_config/__init__.py
  e2e_playwright/host_config/host_config.py
  e2e_playwright/host_config/host_config_test.py
  lib/streamlit/config.py
  lib/streamlit/config_util.py
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7246 Run autoformatter on frontend/lib/package.json
  frontend/lib/package.json
Labels: security-assessment-completed, impact:internal, change:chore

#7248 Fix: Exclude Altair v5.1.0
  lib/setup.py
Labels: security-assessment-completed, change:other, impact:internal

#7253 Update codeowners
  .github/CODEOWNERS
Labels: security-assessment-completed, change:other, impact:internal

#7254 Fix script to update @streamlit/lib
  scripts/update_version.py
Labels: security-assessment-completed, impact:internal, change:chore

#7252 Remove Altair exclusion v5.1.0
  lib/setup.py
Labels: security-assessment-completed, change:other, impact:internal

#7255 Fix: Improve typecheck in `calc_md5`
  lib/streamlit/util.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7263 Use cleaner test framework syntax in old tests
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/script_interactions_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7256 Fix: `st.pydeck_chart` with invalid JSON
  e2e/scripts/st_pydeck_chart.py
  e2e/specs/st_pydeck_chart.spec.js
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7264 Identical widgets on different pages are distinct
  e2e/scripts/multipage_apps/streamlit_app.py
  e2e/specs/multipage_apps.spec.js
  lib/streamlit/components/v1/components.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, change:bugfix, impact:users
