Repository streamlit/streamlit, pull requests merged in 2023-10, with the labels that each got.

#7470 Fix vertical button regression in toolbar actions
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
  frontend/app/src/components/ToolbarActions/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7474 Set min version of snowpark opt dep for constraint
  .github/workflows/python-versions.yml
  lib/min-constraints-gen.txt
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#7449 Upgrade plotly.js version
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, change:bugfix, impact:users

#7482 Revert _xsrf cookie options changes
  e2e/specs/st_file_uploader.spec.js
  lib/streamlit/web/server/server.py
Labels: security-assessment-completed, impact:internal, change:chore

#7489 another attempt to fix flaky camera_input
  e2e/specs/st_camera_input.spec.js
Labels: security-assessment-completed, impact:internal, change:chore

#7477 fixes pandas is_categorical_dtype deprecation warning
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed, change:chore, impact:users

#7362 Avoid confusion about file extensions: keep inner dots
  frontend/lib/src/components/widgets/FileUploader/FileDropzoneInstructions.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileDropzoneInstructions.tsx
Labels: type:enhancement, feature:st.file_uploader, security-assessment-completed, change:bugfix, impact:users

#7480 Remove outdated pandas version checks
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/arrow_table_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7481 Configure non-range indices as required for editing with `st.data_editor`
  lib/streamlit/elements/lib/column_config_utils.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7491 Add a test that will do a screenshot on the toolbar actions
  e2e/specs/hostframe.spec.js
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/toolbarActions.snap.png
  frontend/hostframe.html
Labels: security-assessment-completed, impact:internal, change:bugfix

#7492 Release Streamlit version 1.27.2
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#7496 Fix pandas 2.1 deprecation warnings
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed, change:chore, impact:users

#7497 Add user-friendly exception if dataframe exceeds max config of Pandas Styler
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7483 Add datetime index editing support for `st.data_editor`
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-date_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-date_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-date_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-date_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-date_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-date_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-datetime_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-datetime_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-datetime_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-datetime_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-datetime_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-datetime_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-float64_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-float64_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-float64_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-float64_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-float64_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-float64_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-int64_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-int64_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-int64_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-int64_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-int64_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-int64_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-string_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-string_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-string_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-string_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-string_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-string_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-time_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-time_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-time_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-time_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-time_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-time_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-uint64_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-uint64_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-uint64_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-uint64_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-uint64_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_index_types_test/st_data_editor-uint64_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Period_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Period_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Period_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Period_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Period_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Period_index[light_theme-webkit].png
  e2e_playwright/st_data_editor_index_types.py
  e2e_playwright/st_data_editor_index_types_test.py
  e2e_playwright/st_dataframe_index_types.py
  e2e_playwright/st_dataframe_index_types_test.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7479 Use the new string dtype for dataframe handling
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-7[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-7[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-7[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-7[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-7[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-7[light_theme-webkit].png
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:refactor, impact:users

#7431 Update `set_page_config` docstring
  lib/streamlit/commands/page_config.py
Labels: security-assessment-completed, impact:internal, change:docs

#7505 Support Graphviz layout engines
  e2e/specs/st_graphviz_chart.spec.js
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_dot_string[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_dot_string[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_dot_string[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-fdp[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-fdp[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-fdp[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-neato[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-neato[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-neato[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-osage[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-osage[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-osage[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-patchwork[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-patchwork[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-patchwork[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-twopi[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-twopi[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-twopi[webkit].png
  e2e_playwright/st_graphviz_chart.py
  e2e_playwright/st_graphviz_chart_test.py
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  lib/streamlit/elements/graphviz_chart.py
  lib/tests/streamlit/elements/graphviz_test.py
  proto/streamlit/proto/GraphVizChart.proto
Labels: feature:st.graphviz_chart, security-assessment-completed, change:feature, impact:users

#7478 Better input/output visibility in Langchain callback
  lib/streamlit/external/langchain/streamlit_callback_handler.py
Labels: security-assessment-completed, change:feature, impact:users

#7502 Only use get_active_session when running in SiS
  lib/streamlit/connections/snowpark_connection.py
  lib/tests/streamlit/connections/snowpark_connection_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7413 New test framework api structure
  lib/streamlit/testing/script_interactions.py
  lib/streamlit/testing/v1/__init__.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/streamlit/testing/v1/util.py
  lib/tests/streamlit/elements/date_input_test.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/elements/radio_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  lib/tests/streamlit/elements/slider_test.py
  lib/tests/streamlit/elements/text_area_test.py
  lib/tests/streamlit/elements/text_input_test.py
  lib/tests/streamlit/elements/time_input_test.py
  lib/tests/streamlit/testing/element_tree_test.py
  lib/tests/streamlit/testing/test_runner_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed, change:feature, impact:users

#7440 Docsting consistency of parameter types
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/legacy_caching/caching.py
Labels: security-assessment-completed, impact:internal, change:docs

#7516 Use more cores for `Javascript` and `Component-template` CI tests
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/js-tests.yml
Labels: security-assessment-completed, change:other, impact:internal

#7515 Scale down cypress workflow
  .github/workflows/cypress.yml
Labels: security-assessment-completed, change:other, impact:internal

#7514 Improve playwright execution to fix flakiness
  .github/workflows/playwright.yml
  Makefile
  e2e_playwright/conftest.py
  lib/test-requirements.txt
Labels: security-assessment-completed, change:other, impact:internal

#7373 Session state yield points
  e2e_playwright/fast_rerun_safety.py
  e2e_playwright/fast_rerun_safety_test.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/runtime/state/session_state_proxy.py
  lib/tests/delta_generator_test_case.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/state/safe_session_state_test.py
  lib/tests/streamlit/runtime/state/session_state_proxy_test.py
  lib/tests/streamlit/script_run_context_test.py
  lib/tests/streamlit/user_info_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed, change:other, impact:users

#7511 Call matplotlib crash fix for scripts run in tests
  lib/streamlit/testing/v1/app_test.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#7475 Improve decimal type support for `st.dataframe` and `st.data_editor`
  NOTICES
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-5[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-5[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-5[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-5[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-5[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/dataframe-column-types-5[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-Categorical_index[light_theme-webkit].png
  frontend/lib/package.json
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/mocks/arrow/types/decimal.ts
  frontend/yarn.lock
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/elements/data_editor_test.py
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7517 Remove running CI workflows on feature branches
  .github/workflows/build-streamlit-lib-prod.yml
  .github/workflows/cli-regression.yml
  .github/workflows/conda-build.yml
  .github/workflows/pr-preview.yml
  .github/workflows/py-prod-deps-smoke-test.yml
  .github/workflows/python-min-deps.yml
  .github/workflows/python-versions.yml
Labels: security-assessment-completed, change:other, impact:internal

#7342 Migrate allowed-message-origins to host-config endpoint
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
  frontend/lib/src/index.ts
  frontend/lib/src/test_util.tsx
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7518 Revert JS CI workflow from using 4 cores
  .github/workflows/js-tests.yml
Labels: security-assessment-completed, change:other, impact:internal

#7520 Make AppTest constructors and run methods require kwargs for timeouts
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
Labels: security-assessment-completed, change:refactor, impact:users, feature:app-testing

#7519 Arrow dataframe test wrapper
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7512 Move more stuff into connection util
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/util.py
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/util_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7454 Fix: Foreign language anchors
  e2e/scripts/st_title.py
  e2e/specs/st_title.spec.js
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7504 Fix Chat Message container to align and manage the autosizer handling
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-10[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-10[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-10[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-10[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-10[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-10[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-11[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-11[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-11[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-11[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-11[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-11[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-12[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-12[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-12[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-12[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-12[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-12[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-13[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-13[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-13[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-13[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-13[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-13[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-2[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-2[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-2[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-2[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-2[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-2[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-5[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-5[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-5[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-5[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-5[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/chat_message-5[light_theme-webkit].png
  e2e_playwright/st_chat_message.py
  e2e_playwright/st_chat_message_test.py
  frontend/lib/src/components/elements/ChatMessage/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#7529 Change column header hover color for dataframe
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
Labels: security-assessment-completed, change:other, impact:internal

#7528 Use memo in dataframe component hooks for better performance
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnSizer.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnSort.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#7090 Fix dataframe scrollbars by using negative padding
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#7524 Columns and tabs in script testing
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7487 Added permission to use Clipboard API in IFrame
  frontend/lib/src/util/IFrameUtil.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7540 Temp fix mypy upper bound, to avoid broken CI
  lib/dev-requirements.txt
Labels: security-assessment-completed, impact:internal, change:chore

#7535 Chat input and messages for app testing
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7488 Update `st.spinner`
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/elements/Spinner/Spinner.test.tsx
  frontend/lib/src/components/elements/Spinner/Spinner.tsx
  frontend/lib/src/components/elements/Spinner/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  lib/streamlit/elements/spinner.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/tests/streamlit/spinner_test.py
  proto/streamlit/proto/Spinner.proto
Labels: security-assessment-completed, change:feature, impact:users

#7537 Use python_requires from lib/setup.py in conda build
  lib/conda-recipe/meta.yaml
Labels: security-assessment-completed, impact:internal, change:chore

#7551 Relax mypy requirement, fix mypy 1.6 issues
  lib/dev-requirements.txt
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/widgets/time_widgets.py
Labels: security-assessment-completed, impact:internal, change:chore

#7498 Add file_uploader playwright tests
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_collapsed-label-file-uploader[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_collapsed-label-file-uploader[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_collapsed-label-file-uploader[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_collapsed-label-file-uploader[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_collapsed-label-file-uploader[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_collapsed-label-file-uploader[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_disabled-file-uploader[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_disabled-file-uploader[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_disabled-file-uploader[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_disabled-file-uploader[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_disabled-file-uploader[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_disabled-file-uploader[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-error[chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-error[firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-error[webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_hidden-label-file-uploader[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_hidden-label-file-uploader[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_hidden-label-file-uploader[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_hidden-label-file-uploader[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_hidden-label-file-uploader[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_hidden-label-file-uploader[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi-file-uploader[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi-file-uploader[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi-file-uploader[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi-file-uploader[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi-file-uploader[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi-file-uploader[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi_file_uploader-uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi_file_uploader-uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_multi_file_uploader-uploaded[webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single-file-uploader[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single-file-uploader[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single-file-uploader[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single-file-uploader[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single-file-uploader[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single-file-uploader[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single_file_uploader-uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single_file_uploader-uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_single_file_uploader-uploaded[webkit].png
  e2e_playwright/st_file_uploader.py
  e2e_playwright/st_file_uploader_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7542 Alert classes in app testing
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7560 Move label attribute to only widgets that have it
  lib/streamlit/testing/v1/element_tree.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#7541 Migrate script tests to AppTest
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/state/safe_session_state_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7561 Query params and secrets in app tests
  lib/streamlit/testing/v1/app_test.py
  lib/tests/streamlit/testing/test_runner_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7566 Fix select slider value setting with non-strings
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#7543 Fix attr access of session state in app tests
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#7527 Added FIPS compliance
  lib/streamlit/elements/bokeh_chart.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/graphviz_chart.py
  lib/streamlit/elements/map.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/streamlit/runtime/legacy_caching/hashing.py
  lib/streamlit/runtime/memory_media_file_storage.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/testing/script_interactions.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/util.py
  lib/streamlit/watcher/util.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7536 De-experimentalize st.connection
  lib/streamlit/__init__.py
  lib/streamlit/connections/__init__.py
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/connections/util.py
  lib/streamlit/deprecation_util.py
  lib/streamlit/runtime/connection_factory.py
  lib/tests/streamlit/connections/base_connection_test.py
  lib/tests/streamlit/connections/snowflake_connection_test.py
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/util_test.py
  lib/tests/streamlit/deprecation_util_test.py
  lib/tests/streamlit/runtime/connection_factory_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7562 Minor st.connection tweaks
  lib/streamlit/connections/__init__.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/runtime/connection_factory.py
  lib/tests/streamlit/connections/snowflake_connection_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7522 Send message to parent
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/hostComm/types.ts
  lib/streamlit/platform.py
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/platform_test.py
  lib/tests/streamlit/web/server/routes_test.py
  proto/streamlit/proto/ForwardMsg.proto
  proto/streamlit/proto/ParentMessage.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#7554 Remove keyword sentences from docstrings
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
Labels: security-assessment-completed, impact:internal, change:docs

#7531 Enlarge sidebar left and right padding to match MPA spacing
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-in-sidebar-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-in-sidebar.snap.png
  frontend/cypress/snapshots/linux/2x/st_sidebar.spec.js/date-popover-sidebar.snap.png
  frontend/cypress/snapshots/linux/2x/st_sidebar.spec.js/sidebar-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_sidebar.spec.js/sidebar.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/expander_thumb_value-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/expander_thumb_value.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/expander_thumb_value_in_range-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/expander_thumb_value_in_range.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/long_thumb_value-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/long_thumb_value.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/long_thumb_value_in_range-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/long_thumb_value_in_range.snap.png
  frontend/cypress/snapshots/linux/2x/st_tabs.spec.js/tabs0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_tabs.spec.js/tabs0.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/main-sidebar-top.snap.png
Labels: security-assessment-completed, change:bugfix, impact:users

#7573 Basic app test repr cleanup
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7575 Adjust style of how we're defining module reexports
  lib/streamlit/components/v1/__init__.py
  lib/streamlit/connections/__init__.py
  lib/streamlit/external/langchain/__init__.py
  lib/streamlit/runtime/__init__.py
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/storage/__init__.py
  lib/streamlit/runtime/legacy_caching/__init__.py
  lib/streamlit/runtime/scriptrunner/__init__.py
  lib/streamlit/runtime/state/__init__.py
  lib/streamlit/testing/v1/__init__.py
  lib/streamlit/watcher/__init__.py
  lib/streamlit/web/server/__init__.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7247 Convert Expander to Details/Summary Element
  e2e/specs/st_select_slider.spec.js
  e2e/specs/st_slider.spec.js
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-main[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-main[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-main[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-main[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-main[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-main[light_theme-webkit].png
  e2e_playwright/st_expander.py
  e2e_playwright/st_expander_state_test.py
  e2e_playwright/st_expander_test.py
  e2e_playwright/st_status_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/Expander/Expander.test.tsx
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/Expander/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7574 Fix chat_input repr and add repr tests
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#7579 Deactivate auto focus of script execution error
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#7576 Implement many remaining AppTest elements
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
  lib/tests/streamlit/testing/test_runner_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7580 Build releases directly from tags instead of release branches
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  scripts/get_latest_release_candidate.py
  scripts/get_prerelease_version.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7587 Docstrings for App testing
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
Labels: security-assessment-completed, impact:internal, change:docs

#7592 Make the outline for expanders appear on focus-visible and not focus
  frontend/lib/src/components/elements/Expander/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7507 Camera input playwright test
  e2e_playwright/__snapshots__/linux/st_camera_input_test/disabled-camera-input[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_camera_input_test/disabled-camera-input[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_camera_input_test/disabled-camera-input[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_camera_input_test/disabled-camera-input[light_theme-firefox].png
  e2e_playwright/conftest.py
  e2e_playwright/st_camera_input.py
  e2e_playwright/st_camera_input_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7599 Add new libraries to attributions
  lib/streamlit/runtime/metrics_util.py
Labels: security-assessment-completed, change:other, impact:internal

#7601 Add ability to add empty query params
  lib/streamlit/commands/query_params.py
  lib/tests/streamlit/commands/query_params_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7586 Set the correct color scheme in CSS
  frontend/app/src/styled-components.ts
Labels: security-assessment-completed, change:other, impact:internal

#7584 Deprecate unused config options
  lib/streamlit/config.py
Labels: security-assessment-completed, change:other, impact:users

#7583 Remove "Made by Streamlit" footer
  e2e/scripts/st_tooltips.py
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/styled-components.ts
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe_expanded.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_expanded.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_with_min_height.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_with_min_height_expanded.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/hello-mpa-sidebar-nav-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/hello-mpa-sidebar-nav.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit.snap.png
Labels: security-assessment-completed, change:other, impact:users

#7585 Remove usage of element dimension spec
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  proto/streamlit/proto/ForwardMsg.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#7374 Refactor withMapboxToken to be in DeckGLJsonChart
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/lib/src/SessionInfo.ts
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/MapboxTokenError.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/index.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/withMapboxToken.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/withMapboxToken.tsx
  frontend/lib/src/hocs/withMapboxToken/MapboxToken.test.ts
  frontend/lib/src/hocs/withMapboxToken/MapboxToken.ts
  frontend/lib/src/hocs/withMapboxToken/withMapboxToken.test.tsx
  frontend/lib/src/mocks/mocks.ts
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/runtime/app_session.py
  proto/streamlit/proto/DeckGlJsonChart.proto
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, impact:internal, change:chore

#7422 Use `NoReturn` annotation for stop and rerun
  lib/streamlit/commands/execution_control.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7408 Add Enum coercion to options elements, if input Enum classes "identical" but redefined on script run
  lib/streamlit/config.py
  lib/streamlit/elements/utils.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/elements/date_input_test.py
  lib/tests/streamlit/elements/element_utils_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/elements/radio_test.py
  lib/tests/streamlit/elements/select_slider_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  lib/tests/streamlit/elements/slider_test.py
  lib/tests/streamlit/elements/text_area_test.py
  lib/tests/streamlit/elements/text_input_test.py
  lib/tests/streamlit/elements/time_input_test.py
  lib/tests/streamlit/pyspark_mocks.py
  lib/tests/streamlit/snowpark_mocks.py
  lib/tests/streamlit/testing/element_tree_test.py
  lib/tests/streamlit/testing/test_runner_test.py
  lib/tests/streamlit/type_util_test.py
  scripts/check_license_headers.py
Labels: security-assessment-completed, change:feature, impact:users

#7609 Increase the top padding for embedded apps
  e2e/specs/embedded_chat_input_app.js
  frontend/app/src/components/AppView/styled-components.ts
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe_expanded.snap.png
Labels: security-assessment-completed, impact:internal, change:bugfix

#7611 Refactor arrow serialization logic for custom components
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/type_util.py
  lib/streamlit/util.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7604 Remove Recording Feature Menu Item when unsupported
  e2e/specs/st_main_menu.spec.js
  e2e_playwright/__snapshots__/linux/main_menu_test/main_menu[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/main_menu[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/main_menu[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/main_menu[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/main_menu[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/main_menu[light_theme-webkit].png
  e2e_playwright/main_menu.py
  e2e_playwright/main_menu_test.py
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/util/ScreenCastRecorder.ts
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu.snap.png
Labels: security-assessment-completed, change:feature, impact:users

#7398 Fix SVG scaling on fullscreen mode for `st.graphviz_chart`
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/graphviz_after_exit_fullscreen[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/graphviz_after_exit_fullscreen[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/graphviz_after_exit_fullscreen[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/graphviz_fullscreen[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/graphviz_fullscreen[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/graphviz_fullscreen[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[webkit].png
  e2e_playwright/st_graphviz_chart_test.py
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/elements/GraphVizChart/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7606 Add tests enforcing that file_uploader-related protos are stable
  lib/tests/streamlit/proto_compatibility_test.py
  proto/streamlit/proto/Common.proto
Labels: security-assessment-completed, impact:internal, change:chore

#7602 Allow query params to return a single element rather than always an array
  e2e/specs/st_experimental_get_query_params.spec.js
  lib/streamlit/commands/query_params.py
  lib/streamlit/util.py
  lib/tests/streamlit/commands/query_params_test.py
  lib/tests/streamlit/testing/test_runner_test.py
  lib/tests/streamlit/util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7630 Fix top padding when embedding an app with a sidebar
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7621 Add clear, __delitem__, __len__, __contains__, __init__ methods to a QueryParam class
  lib/streamlit/commands/query_params.py
  lib/tests/streamlit/commands/query_params_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#7608 Set both auth token and prev session ID on websocket connect
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/web/server/server_test_case.py
Labels: security-assessment-completed, impact:internal, change:feature

#7644 Fix app testing repr bug for `st.container`
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/test_runner_test.py
Labels: security-assessment-completed, change:bugfix, impact:users
