Repository streamlit/streamlit, pull requests merged in 2023-11, with the labels that each got.

#7641 Ensure file_uploader doesn't trigger needless reruns
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
Labels: type:regression, security-assessment-completed, change:bugfix, impact:users

#7643 Fix trigger value regression with `st.rerun`
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: type:regression, security-assessment-completed, change:bugfix, impact:users

#7640 Remove unwrapping single element lists method
  e2e/specs/st_experimental_get_query_params.spec.js
  lib/streamlit/commands/query_params.py
  lib/streamlit/util.py
  lib/tests/streamlit/commands/query_params_test.py
  lib/tests/streamlit/testing/test_runner_test.py
  lib/tests/streamlit/util_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7652 Tweak "forgot config" SnowflakeConnection error message
  lib/streamlit/connections/snowflake_connection.py
Labels: security-assessment-completed, impact:users, change:docs

#7634 Fix: MPA Nav expand arrow
  e2e/scripts/multipage_apps/pages/06_page_6.py
  e2e/scripts/multipage_apps/pages/07_page_7.py
  e2e/specs/multipage_apps.spec.js
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/cypress/snapshots/linux/2x/multipage_apps.spec.js/multipage-apps-sidebar-nav-dark.snap.png
  frontend/cypress/snapshots/linux/2x/multipage_apps.spec.js/multipage-apps-sidebar-nav.snap.png
  frontend/lib/src/util/Hooks.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7657 Remove old app test api
  lib/streamlit/testing/element_tree.py
  lib/streamlit/testing/local_script_runner.py
  lib/streamlit/testing/script_interactions.py
  lib/tests/streamlit/script_interactions_test.py
  lib/tests/streamlit/testing/app_test_test.py
  lib/tests/streamlit/testing/test_runner_test.py
Labels: security-assessment-completed, change:other, change:breaking, impact:users, feature:app-testing

#7646 Fix issue for st.camera_input and chat_input, add regression test for file_uploader
  e2e_playwright/st_chat_input_file_uploader_regression.py
  e2e_playwright/st_chat_input_file_uploader_regression_test.py
  frontend/lib/src/components/widgets/CameraInput/CameraInput.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7645 Greatly narrow errors that we retry in SnowflakeConnection
  lib/streamlit/connections/snowflake_connection.py
  lib/tests/streamlit/connections/snowflake_connection_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7658 Improved AppTest/ElementTree formatting
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#7666 Release Streamlit version 1.28.1
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#7671 Fix how connection is declared for typing purposes
  lib/streamlit/__init__.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7660 Migrate ScreencastDialog & ImageList to RTL
  e2e/specs/st_image.spec.js
  e2e/specs/st_image_replay.spec.js
  frontend/app/src/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.test.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7676 Migrate one more file_uploader test to playwright
  e2e_playwright/st_file_uploader_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7654 RTL Test Conversions
  frontend/lib/src/components/core/ThemeProvider.tsx
  frontend/lib/src/components/core/ThemeProvider/ThemeProvider.test.tsx
  frontend/lib/src/components/core/ThemeProvider/index.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.test.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7673 Migrate Selectbox to RTL
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7674 Migrate NumberInput to RTL
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7691 Poll for script completion much more often in AppTest
  lib/streamlit/testing/v1/local_script_runner.py
Labels: area:performance, security-assessment-completed, change:other, impact:users, feature:app-testing

#7681 Use slightly larger top padding for better toolbar handling
  e2e/specs/embedded_chat_input_app.js
  frontend/app/src/components/AppView/styled-components.ts
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe_expanded.snap.png
Labels: security-assessment-completed, impact:internal, change:bugfix

#7689 Add support for timedelta type to `st.dataframe`, `st.data_editor` and `st.table`.
  NOTICES
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-special_types[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_column_types_test/st_data_editor-unsupported_types[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-special_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-special_types[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-special_types[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-special_types[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-special_types[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-special_types[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-unsupported_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-unsupported_types[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-unsupported_types[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-unsupported_types[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-unsupported_types[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-unsupported_types[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-categorical[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-categorical[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-categorical[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-timedelta_index[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-timedelta_index[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_index_types_test/st_dataframe-timedelta_index[webkit].png
  e2e_playwright/st_data_editor_column_types.py
  e2e_playwright/st_data_editor_index_types.py
  e2e_playwright/st_dataframe_index_types.py
  e2e_playwright/st_dataframe_index_types_test.py
  frontend/lib/package.json
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/mocks/arrow/index.ts
  frontend/lib/src/mocks/arrow/types/timedelta.ts
  frontend/yarn.lock
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7663 Add Python 3.12 support
  .github/scripts/build_info.py
  .pre-commit-config.yaml
  lib/setup.py
  lib/streamlit/external/langchain/streamlit_callback_handler.py
  lib/test-requirements.txt
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/external/langchain/streamlit_callback_handler_test.py
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_cache_test.py
Labels: security-assessment-completed, change:chore, impact:users

#7455 Add border parameter to container and form
  e2e/specs/st_container.spec.js
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-has_border[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-has_border[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-has_border[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-has_border[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-has_border[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-has_border[light_theme-webkit].png
  e2e_playwright/st_code_test.py
  e2e_playwright/st_container.py
  e2e_playwright/st_container_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/widgets/Form/Form.test.tsx
  frontend/lib/src/components/widgets/Form/Form.tsx
  frontend/lib/src/components/widgets/Form/styled-components.ts
  lib/streamlit/elements/form.py
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/form_test.py
  lib/tests/streamlit/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#7635 Add exhaustive proto stability tests
  lib/tests/streamlit/proto_compatibility_test.py
  proto/streamlit/proto/Alert.proto
  proto/streamlit/proto/AppPage.proto
  proto/streamlit/proto/Exception.proto
  proto/streamlit/proto/NewSession.proto
  proto/streamlit/proto/ParentMessage.proto
  proto/streamlit/proto/SessionStatus.proto
Labels: security-assessment-completed, impact:internal, change:chore

#7713 Temp fix mypy upper bound, to avoid broken CI
  lib/dev-requirements.txt
Labels: security-assessment-completed, impact:internal, change:chore

#7695 Enforce pyarrow version for arrow-based custom components
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7716 Release Streamlit version 1.28.2
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#7717 Directly use package name in setup.py
  lib/setup.py
  scripts/update_name.py
Labels: security-assessment-completed, change:other, impact:internal

#7728 Remove unnecessary PIL dependency in st.image docstring
  lib/streamlit/elements/image.py
Labels: feature:st.image, security-assessment-completed, impact:internal, change:docs

#7712 Allow to access external server IP via https.
  lib/streamlit/net_util.py
  lib/tests/streamlit/net_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7544 Allow a service managing a Streamlit runtime to set its own session IDs
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/runtime/websocket_session_manager.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/websocket_session_manager_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#7715 Move dg_stack into a ContextVar to support with blocks in separate threads
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/form.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/tests/streamlit/delta_generator_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7730 Improve st.connection caching behavior
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/runtime/connection_factory.py
  lib/tests/streamlit/connections/snowflake_connection_test.py
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/sql_connection_test.py
  lib/tests/streamlit/runtime/connection_factory_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7747 Pin playwright version to < 1.40
  lib/test-requirements.txt
Labels: security-assessment-completed, change:other, impact:internal

#7755 Migrate `st.button` e2e test to playwright
  e2e/specs/st_button.spec.js
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-default[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-default[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-default[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-default[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-default[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-default[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled_primary[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled_primary[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled_primary[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled_primary[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled_primary[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-disabled_primary[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-in_columns[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-in_columns[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-in_columns[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-in_columns[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-in_columns[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-in_columns[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-on_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-on_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-on_hover[webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-primary[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-primary[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-primary[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-primary[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-primary[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-primary[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-styled_label[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-styled_label[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-styled_label[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-styled_label[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-styled_label[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-styled_label[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width_help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width_help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width_help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width_help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width_help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-use_container_width_help[light_theme-webkit].png
  e2e_playwright/st_button.py
  e2e_playwright/st_button_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7756 Replace deprecated `find_executable` from `distutils.spawn`
  lib/streamlit/env_util.py
Labels: security-assessment-completed, impact:internal, change:chore

#7682 add app_heartbeat BackMsg type and send it when receiving SEND_APP_HEARTBEAT window message
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/BackMsg.proto
Labels: security-assessment-completed, impact:internal, change:feature

#7758 Remove outdated cypress snapshots
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/button-widget-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/button-widget.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/disabled-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/disabled-button.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/disabled-primary-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/disabled-primary-button.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/primary-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/primary-button.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_0.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_1.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_2.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/stretched_buttons_3.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/use-container-width-and-help-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/use-container-width-and-help-button.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/use-container-width-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_button.spec.js/use-container-width-button.snap.png
Labels: security-assessment-completed, change:other, impact:internal

#7759 Update docstrings for release 1.29
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/widgets/data_editor.py
Labels: security-assessment-completed, impact:internal, change:docs

#7762 Fix minor typo in server.scriptHealthCheckEnabled help
  lib/streamlit/config.py
Labels: security-assessment-completed, change:other, impact:internal

#7746 fix: component dev url typo
  frontend/lib/src/urls.ts
Labels: security-assessment-completed, impact:users, change:docs

#7754 Don't use hash on floats in hashing.py
  lib/streamlit/runtime/caching/hashing.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7764 Fix another url typo
  frontend/lib/src/components/widgets/Form/Form.tsx
Labels: security-assessment-completed, impact:users, change:docs

#7769 Fix typing issues with altair
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/type_util.py
  lib/test-requirements.txt
Labels: security-assessment-completed, change:other, impact:internal

#7770 Fix parenthesis error messaging
  lib/streamlit/testing/v1/local_script_runner.py
Labels: security-assessment-completed, change:chore, impact:users

#7705 Add QueryParamsProxy to streamlit api
  lib/streamlit/__init__.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/state/query_params_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7718 Add inability to use both query param apis with tests
  e2e_playwright/st_both_query_params_error.py
  e2e_playwright/st_both_query_params_error_test.py
  lib/streamlit/commands/experimental_query_params.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/state/query_params.py
  lib/tests/streamlit/script_run_context_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7757 Remove Enzyme from Slider Tests
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#7761 Remove Enzyme from Plotly Charts
  frontend/lib/jest.config.js
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
  frontend/lib/src/components/elements/PlotlyChart/__snapshots__/PlotlyChart.test.tsx.snap
  frontend/lib/src/setupTestEnv.js
Labels: security-assessment-completed, impact:internal, change:refactor

#7698 Add Query Params Class in Session State
  lib/streamlit/__init__.py
  lib/streamlit/commands/experimental_query_params.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/util.py
  lib/tests/streamlit/commands/experimental_query_params_test.py
  lib/tests/streamlit/runtime/state/query_params_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7771 Fix handling of ordinal columns for builtin-charts
  lib/streamlit/type_util.py
  lib/tests/streamlit/elements/arrow_altair_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7783 Update SECURITY.md
  SECURITY.md
Labels: security-assessment-completed, impact:users, change:docs

#7704 QueryParamsProxy
  lib/streamlit/runtime/state/__init__.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/streamlit/runtime/state/safe_session_state.py
  lib/tests/streamlit/runtime/state/query_params_proxy_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7697 Add support for scroll container via the `height` parameter
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container[webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_chat[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_chat[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_chat[webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_empty[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_empty[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_empty[webkit].png
  e2e_playwright/st_container.py
  e2e_playwright/st_container_test.py
  frontend/lib/src/components/core/Block/Block.test.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users
