Repository streamlit/streamlit, pull requests merged in 2023-02, with the labels that each got.

#6032 Note whether user is currently running 'streamlit hello' app
  frontend/src/lib/MetricsManager.ts
Labels: security-assessment-completed

#6010 Dependency updates... - Part D
  NOTICES
  frontend/.eslintrc
  frontend/craco.config.js
  frontend/package.json
  frontend/src/components/core/StatusWidget/StatusWidget.test.tsx
  frontend/src/components/core/StreamlitDialog/StreamlitDialog.test.tsx
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/MetricsManagerTestUtils.ts
  frontend/src/lib/WebsocketConnection.test.tsx
  frontend/yarn.lock
Labels: security-assessment-completed

#6045 Use new annotation features in DeltaGenerator
  lib/streamlit/delta_generator.py
Labels: security-assessment-completed

#5691 Static files serving
  e2e/scripts/staticfiles_apps/static/streamlit-mark-color.png
  e2e/scripts/staticfiles_apps/streamlit_static_app.py
  e2e/specs/staticfiles_app.spec.js
  frontend/cypress/snapshots/linux/2x/staticfiles_app.spec.js/static_streamlit_logo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/staticfiles_app.spec.js/static_streamlit_logo.snap.png
  lib/streamlit/config.py
  lib/streamlit/file_util.py
  lib/streamlit/web/bootstrap.py
  lib/streamlit/web/server/app_static_file_handler.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/file_util_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
  lib/tests/streamlit/web/server/routes_test.py
  scripts/check_license_headers.py
  scripts/run_e2e_tests.py
Labels: security-assessment-completed

#6034 Fix on menu highlights
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu.snap.png
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/components/core/MainMenu/styled-components.ts
Labels: security-assessment-completed

#6056 Bump min tornado version to 6.0.3
  lib/setup.py
Labels: security-assessment-completed

#6055 Add ability to update layout for title
  e2e/scripts/st_plotly_chart.py
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart1.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart11-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart11.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart12-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart12.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart13-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart13.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart2.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart4.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart5.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_plotly_chart.spec.js/plotly_chart8.snap.png
  frontend/src/components/elements/PlotlyChart/CustomTheme.tsx
Labels: security-assessment-completed

#6051 Remove deprecation warnings for endpoints from app logs
  lib/streamlit/web/server/server_util.py
  lib/tests/streamlit/web/server/routes_test.py
  lib/tests/streamlit/web/server/server_test.py
  lib/tests/streamlit/web/server/stats_handler_test.py
Labels: security-assessment-completed

#6075 session_state: "common.py" module
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/streamlit/runtime/state/__init__.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/state/session_state_proxy.py
  lib/streamlit/runtime/state/widgets.py
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/runtime/state/session_state_proxy_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/runtime/state/strategies.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed

#6053 Dependency update/cleanup
  NOTICES
  frontend/package.json
  frontend/yarn.lock
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed

#6090 up version to 1.18.0
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed

#6069 Add sfc-gh-mnowotka as a protobuf CODEOWNER
  .github/CODEOWNERS
Labels: security-assessment-completed

#6094 Downgrade decamelize to avoid Safari break
  NOTICES
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed

#6100 Check availability of local storage to prevent exceptions
  frontend/src/components/core/Sidebar/Sidebar.tsx
  frontend/src/lib/storageUtils.test.ts
  frontend/src/lib/storageUtils.ts
  frontend/src/theme/utils.test.ts
  frontend/src/theme/utils.ts
Labels: security-assessment-completed

#6098 Improve readability of styled cells in dark mode
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_styler_support.spec.js/dataframe-pd-styler-1-dark.snap.png
  frontend/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/components/widgets/DataFrame/arrowUtils.ts
Labels: security-assessment-completed

#6016 Update repo's README
  README.md
Labels: type:docs, security-assessment-completed

#6113 Improve logging when arrow serialization fails
  lib/streamlit/type_util.py
Labels: security-assessment-completed

#6123 Pin unixodbc version to fix CI pipeline
  .github/actions/make_init/action.yml
Labels: security-assessment-completed

#6122 Add editing support for numeric index types
  lib/streamlit/elements/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed

#6114 Fix member function caching
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
Labels: security-assessment-completed

#6127 Fix detecting arrow df as widget when not editable
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/caching/test_data/arrow_replay.py
Labels: security-assessment-completed

#6128 cache_errors: don't refer to experimental_memo|singleton
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
Labels: security-assessment-completed

#6135 Improve data editor and dataframe docstring
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
Labels: security-assessment-completed

#6101 Up version to 1.18.1
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed

#6129 Fix `st.metric` tooltip position regression
  e2e/scripts/st_metric.py
  e2e/specs/st_metric.spec.js
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-help-and-ellipses-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-help-and-ellipses.snap.png
  frontend/src/components/elements/Metric/Metric.tsx
  frontend/src/components/elements/Metric/styled-components.ts
Labels: security-assessment-completed

#6139 Support a new 'do-not-merge' label
  .github/workflows/require-labels.yml
Labels: security-assessment-completed

#6144 Embed `st.experimental_data_editor` apps in docstring
  lib/streamlit/elements/data_editor.py
Labels: security-assessment-completed, feature:st.data_editor

#6148 Fix expander overflow during animation
  frontend/src/hocs/withExpandable/withExpandable.tsx
Labels: security-assessment-completed

#6172 Introduce make frontendFast command
  Makefile
  frontend/package.json
Labels: security-assessment-completed

#6080 Hamburger menu cleanup
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu.snap.png
  frontend/src/components/core/MainMenu/MainMenu.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/urls.ts
Labels: security-assessment-completed

#6181 Remove frontend dependencies codeowners
  .github/CODEOWNERS
Labels: security-assessment-completed

#6179 Up version to 1.19.0
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed

#6175 Add testing-library/jest-dom to our dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed

#6173 Allow overriding timeout arg for running a script
  lib/streamlit/testing/local_script_runner.py
Labels: security-assessment-completed

#6169 Allow tests bo to filtered by file
  Makefile
  frontend/package.json
Labels: security-assessment-completed

#6011 Fix ?embed and ?embedded params
  frontend/cypress/support/commands.js
  frontend/src/App.tsx
  frontend/src/components/core/AppContext/index.tsx
  frontend/src/components/core/AppView/AppView.tsx
  frontend/src/components/core/AppView/styled-components.ts
  frontend/src/components/core/Header/Header.tsx
  frontend/src/components/core/Header/styled-components.ts
  frontend/src/lib/utils.test.ts
  frontend/src/lib/utils.ts
Labels: security-assessment-completed

#6180 Printing adjustments
  frontend/src/components/core/AppView/styled-components.ts
  frontend/src/components/core/Sidebar/styled-components.ts
Labels: security-assessment-completed

#6188 Fix dtype check
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed

#6019 Disallow setting embed query param using set_query_param method
  lib/streamlit/commands/query_params.py
  lib/streamlit/util.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/util_test.py
Labels: security-assessment-completed

#5969 Add SSL support
  lib/streamlit/config.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/server_util.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/streamlit/web/cli_test.py
  lib/tests/streamlit/web/server/server_test.py
Labels: stale, security-assessment-completed
