Repository streamlit/streamlit, pull requests merged in 2023-04, with the labels that each got.

#6419 Fix `make notices`
  Makefile
  NOTICES
  frontend/yarn.lock
Labels: security-assessment-completed

#6418 Move semver to dev dependency, temporarily pin
  lib/Pipfile
  lib/setup.py
  lib/test-requirements.txt
Labels: security-assessment-completed

#6234 Generate constraints files for all supported Python versions
  .github/actions/build_info/action.yml
  .github/actions/make_init/action.yml
  .github/actions/set_python_versions/action.yml
  .github/scripts/build_info.py
  .github/workflows/cli-regression.yml
  .github/workflows/cypress-update-snapshots.yml
  .github/workflows/cypress.yml
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
  .github/workflows/py-prod-deps-smoke-test.yml
  .github/workflows/python-versions.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: security-assessment-completed

#6430 Unpin pillow
  lib/setup.py
  lib/test-requirements.txt
  lib/tests/streamlit/runtime/caching/common_cache_test.py
Labels: security-assessment-completed

#6265 Migrate to pip only and drop pipenv
  .github/actions/make_init/action.yml
  .github/scripts/build_info.py
  .github/workflows/js-tests.yml
  .github/workflows/python-versions.yml
  Makefile
  lib/MANIFEST.in
  lib/Pipfile
  lib/dev-requirements.txt
  lib/test-requirements-with-tensorflow.txt
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
  scripts/check_license_headers.py
Labels: security-assessment-completed

#6391 Printed / logged strings papercut fixes
  lib/streamlit/runtime/scriptrunner/script_requests.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/session_state.py
Labels: security-assessment-completed

#6438 Fix typo in `st.text_input`'s `on_change` param docstring
  lib/streamlit/elements/text_widgets.py
Labels: security-assessment-completed

#6444 Release 1.21.0
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed

#6445 Fix: Broken Nightly Build
  .github/workflows/nightly.yml
Labels: security-assessment-completed

#6439 Number input testing framework implementation
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6447 Color picker test framework class
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6373 Replace `:focus` with `:focus-visible` styles
  frontend/src/components/core/StreamlitDialog/__snapshots__/StreamlitDialog.test.tsx.snap
  frontend/src/components/shared/Button/styled-components.ts
  frontend/src/components/shared/Dropdown/styled-components.ts
  frontend/src/components/widgets/CameraInput/styled-components.ts
  frontend/src/components/widgets/FileUploader/styled-components.ts
  frontend/src/components/widgets/Slider/styled-components.ts
Labels: security-assessment-completed

#6377 Change root logger to be in streamlit namespace
  lib/streamlit/logger.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/logger_test.py
Labels: security-assessment-completed

#6459 Fix #6440: Add uuid to types we natively hash
  lib/streamlit/runtime/caching/hashing.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed

#6466 Add _repr_html_ implementations for the base and SQL connections
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/tests/streamlit/connections/base_connection_test.py
  lib/tests/streamlit/connections/sql_connection_test.py
Labels: security-assessment-completed

#6449 Support ttl and max_entries kwargs
  lib/streamlit/runtime/connection_factory.py
  lib/tests/streamlit/runtime/connection_factory_test.py
Labels: security-assessment-completed

#6475 Rename theme constants for better legibility
  frontend/src/components/core/Sidebar/Sidebar.test.tsx
  frontend/src/components/core/Sidebar/ThemedSidebar.test.tsx
  frontend/src/components/core/ThemeProvider/ThemeProvider.test.tsx
  frontend/src/components/core/ThemeProvider/ThemeProvider.tsx
  frontend/src/components/elements/Json/Json.test.tsx
  frontend/src/components/shared/TooltipIcon/TooltipIcon.test.tsx
  frontend/src/components/widgets/CameraInput/SwitchFacingModeButton.tsx
  frontend/src/components/widgets/CameraInput/WebcamComponent.tsx
  frontend/src/theme/baseui.ts
  frontend/src/theme/emotionBaseTheme/index.ts
  frontend/src/theme/emotionBaseTheme/themeColors.ts
  frontend/src/theme/emotionDarkTheme/index.ts
  frontend/src/theme/emotionDarkTheme/themeColors.ts
  frontend/src/theme/emotionLightTheme/index.ts
  frontend/src/theme/emotionLightTheme/themeColors.ts
  frontend/src/theme/themeConfigs.ts
  frontend/src/theme/types.ts
Labels: security-assessment-completed

#6476 Empty mocks
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.test.tsx
  frontend/src/components/core/StreamlitDialog/SettingsDialog.test.tsx
  frontend/src/lib/AppNode.test.ts
  frontend/src/lib/MetricsManagerTestUtils.ts
  frontend/src/lib/SegmentMetricsManager.test.ts
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6477 `Theme` -> `EmotionTheme`
  frontend/src/components/core/Block/styled-components.ts
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/components/core/MainMenu/styled-components.ts
  frontend/src/components/core/Sidebar/Sidebar.tsx
  frontend/src/components/core/StatusWidget/StatusWidget.tsx
  frontend/src/components/core/StatusWidget/styled-components.ts
  frontend/src/components/core/StreamlitDialog/DeployDialog/DeployCard.tsx
  frontend/src/components/core/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/src/components/core/StreamlitDialog/__snapshots__/StreamlitDialog.test.tsx.snap
  frontend/src/components/core/ThemeProvider/ThemeProvider.tsx
  frontend/src/components/elements/ArrowTable/styled-components.ts
  frontend/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  frontend/src/components/elements/DataFrame/styled-components.ts
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/src/components/elements/Json/Json.tsx
  frontend/src/components/elements/Metric/Metric.tsx
  frontend/src/components/elements/PlotlyChart/CustomTheme.tsx
  frontend/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/src/components/elements/Spinner/Spinner.tsx
  frontend/src/components/elements/Table/styled-components.ts
  frontend/src/components/elements/VegaLiteChart/VegaLiteChart.tsx
  frontend/src/components/shared/Button/styled-components.ts
  frontend/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/src/components/shared/Modal/Modal.tsx
  frontend/src/components/shared/ProgressBar/ProgressBar.tsx
  frontend/src/components/shared/Radio/Radio.tsx
  frontend/src/components/shared/Tooltip/Tooltip.tsx
  frontend/src/components/shared/TooltipIcon/TooltipIcon.tsx
  frontend/src/components/widgets/CameraInput/WebcamComponent.tsx
  frontend/src/components/widgets/CameraInput/styled-components.ts
  frontend/src/components/widgets/Checkbox/Checkbox.tsx
  frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
  frontend/src/components/widgets/DateInput/DateInput.tsx
  frontend/src/components/widgets/FileUploader/styled-components.ts
  frontend/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/src/components/widgets/Slider/Slider.tsx
  frontend/src/lib/test_util.tsx
  frontend/src/theme/emotion.d.ts
  frontend/src/theme/globalStyles.ts
  frontend/src/theme/types.ts
  frontend/src/theme/utils.ts
Labels: security-assessment-completed

#6479 Mock theme data in tests
  frontend/src/components/core/StatusWidget/StatusWidget.test.tsx
  frontend/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.test.tsx
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/src/components/elements/Json/Json.test.tsx
  frontend/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
  frontend/src/components/elements/VegaLiteChart/VegaLiteChart.test.tsx
  frontend/src/components/shared/Radio/Radio.test.tsx
  frontend/src/components/shared/TooltipIcon/TooltipIcon.test.tsx
  frontend/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/src/components/widgets/Slider/Slider.test.tsx
  frontend/src/lib/mocks/mockTheme.ts
  frontend/src/lib/test_util.tsx
Labels: security-assessment-completed

#6396 Use constraint files to install dependencies on PRs
  .github/actions/build_info/action.yml
  .github/scripts/build_info.py
  .github/workflows/python-versions.yml
  Makefile
Labels: security-assessment-completed

#6478 Allow users to specify name only for first party connections
  lib/streamlit/runtime/connection_factory.py
  lib/tests/streamlit/runtime/connection_factory_test.py
Labels: security-assessment-completed

#6468 Add retry behavior to the SQL/Snowpark read helper methods
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/runtime/connection_factory.py
  lib/test-requirements.txt
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/sql_connection_test.py
  lib/tests/streamlit/runtime/connection_factory_test.py
Labels: security-assessment-completed

#6453 Avoid storing GitHub token in .git directory
  .github/workflows/codeql-analysis.yml
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
  .github/workflows/python-versions.yml
Labels: security-assessment-completed

#6471 Update multiselect icon
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-invalid-table-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-invalid-table.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-valid-colored-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-valid-colored.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-valid-link-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-valid-link.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-valid-markdown-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/checkbox-valid-markdown.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-invalid-horizontal-rule-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-invalid-horizontal-rule.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-valid-colored-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-valid-colored.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-valid-link-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-valid-link.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-valid-markdown-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/numberInput-valid-markdown.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-invalid-heading1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-invalid-heading1.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-valid-colored-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-valid-colored.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-valid-link-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-valid-link.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-valid-markdown-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/radio-valid-markdown.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/tab-valid-colored-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/tab-valid-link-dark.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/tab-valid-link.snap.png
  frontend/cypress/snapshots/linux/2x/label_markdown.spec.js/tab-valid-markdown-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_multiselect.spec.js/multiselect-selection-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_multiselect.spec.js/multiselect-selection.snap.png
  frontend/cypress/snapshots/linux/2x/st_multiselect.spec.js/multiselect3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_multiselect.spec.js/multiselect3.snap.png
  frontend/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed

#6376 Restrict the setting of sensitive options by the CLI flag
  lib/streamlit/config.py
  lib/streamlit/config_option.py
  lib/streamlit/web/cli.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, QA-Needed

#6174 Add config option to control the hamburger menu
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/core/MainMenu/MainMenu.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/lib/baseconsts.ts
  frontend/src/lib/test_util.tsx
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed

#6503 Update metadata description
  lib/conda-recipe/meta.yaml
  lib/setup.py
Labels: security-assessment-completed

#6497 Autoformat yaml in .github dir and enforce formatting
  .github/actions/branch/action.yml
  .github/actions/build_info/action.yml
  .github/actions/make_init/action.yml
  .github/actions/preview_branch/action.yml
  .github/actions/tag_and_repo/action.yml
  .github/repo_meta.yaml
  .github/workflows/cli-regression.yml
  .github/workflows/cypress-update-snapshots.yml
  .github/workflows/cypress.yml
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
  .github/workflows/py-prod-deps-smoke-test.yml
  .github/workflows/python-versions.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
Labels: security-assessment-completed

#6495 Create tag with constraints files for new releases
  .github/actions/build_info/action.yml
  .github/actions/tag_and_repo/action.yml
  .github/scripts/build_info.py
  .github/workflows/python-versions.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  Makefile
Labels: security-assessment-completed

#6464 No longer send unnecessary identify calls from frontend
  frontend/src/lib/SegmentMetricsManager.test.ts
  frontend/src/lib/SegmentMetricsManager.ts
  frontend/src/lib/SessionInfo.test.ts
  frontend/src/lib/SessionInfo.ts
  frontend/src/lib/mocks/mocks.ts
  lib/streamlit/runtime/credentials.py
  lib/tests/streamlit/runtime/credentials_test.py
Labels: security-assessment-completed

#6517 Fix issue with deprecated asyncio test variable
  lib/tests/streamlit/web/server/server_test.py
Labels: security-assessment-completed, dev:upgrade-dependencies

#6511 Don't always retry on .query() errors for SQL and Snowpark connections
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/sql_connection_test.py
Labels: security-assessment-completed

#6512 Add Bokeh as a side effect import
  .github/codeql-config.yml
  .gitignore
  Makefile
  frontend/.eslintrc
  frontend/package.json
  frontend/public/index.html
  frontend/scripts/preload-bokeh.sh
  frontend/src/components/elements/BokehChart/BokehChart.test.tsx
  frontend/src/components/elements/BokehChart/BokehChart.tsx
  frontend/src/setupTests.js
  frontend/src/vendor/bokeh/bokeh-LICENSE.txt
  frontend/src/vendor/bokeh/bokeh-api-2.4.3.esm.min.js
  frontend/src/vendor/bokeh/bokeh-gl-2.4.3.esm.min.js
  frontend/src/vendor/bokeh/bokeh-mathjax-2.4.3.esm.min.d.ts
  frontend/src/vendor/bokeh/bokeh-mathjax-2.4.3.esm.min.js
  frontend/src/vendor/bokeh/bokeh-tables-2.4.3.esm.min.js
  frontend/src/vendor/bokeh/bokeh-widgets-2.4.3.esm.min.js
  frontend/src/vendor/bokeh/bokeh.esm.d.ts
  frontend/src/vendor/bokeh/bokeh.esm.js
  frontend/yarn.lock
Labels: security-assessment-completed

#6519 Don't forget only-name connection_factory overloads
  lib/streamlit/runtime/connection_factory.py
Labels: security-assessment-completed

#6501 Date and Time test classes
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6481 Reorganize tests from streamlit_test.py
  lib/tests/streamlit/commands/query_params_test.py
  lib/tests/streamlit/elements/alert_test.py
  lib/tests/streamlit/elements/arrow_altair_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/balllons_test.py
  lib/tests/streamlit/elements/doc_string_test.py
  lib/tests/streamlit/elements/empty_test.py
  lib/tests/streamlit/elements/exception_test.py
  lib/tests/streamlit/elements/json_test.py
  lib/tests/streamlit/elements/legacy_altair_test.py
  lib/tests/streamlit/elements/legacy_data_frame_test.py
  lib/tests/streamlit/elements/markdown_test.py
  lib/tests/streamlit/elements/plotly_chart_test.py
  lib/tests/streamlit/elements/text_test.py
  lib/tests/streamlit/elements/time_widgets_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed

#6470 Dont use constraints file in scheduled builds
  .github/scripts/build_info.py
  .github/workflows/python-versions.yml
Labels: security-assessment-completed

#6529 Add tenacity as dependency
  lib/setup.py
Labels: security-assessment-completed

#6524 Fix E2E image
  .dockerignore
  e2e/Dockerfile
Labels: security-assessment-completed

#6498 Fix regression in visibility of `st.code`'s copy-to-clipboard button
  e2e/specs/st_code.spec.js
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting-hover-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting-hover.snap.png
  frontend/cypress/support/index.js
  frontend/package.json
  frontend/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/src/components/elements/CodeBlock/styled-components.ts
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/yarn.lock
Labels: type:regression, security-assessment-completed, feature:st.code

#6507 Add support for pandas 2.0
  lib/setup.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed

#6532 Update emojis to latest state
  lib/streamlit/emojis.py
Labels: security-assessment-completed

#6463 Clarify what telemetry data our backend stores
  frontend/src/lib/SegmentMetricsManager.test.ts
  frontend/src/lib/SegmentMetricsManager.ts
Labels: security-assessment-completed

#6516 Fully remove email from new session message
  frontend/src/App.test.tsx
  lib/streamlit/runtime/app_session.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed

#6535 Fix code block font change
  frontend/src/theme/utils.ts
Labels: security-assessment-completed

#6530 Further st.experimental_connection polish omnibus PR
  lib/streamlit/connections/__init__.py
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/runtime/connection_factory.py
  lib/test-requirements.txt
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/sql_connection_test.py
  lib/tests/streamlit/runtime/connection_factory_test.py
Labels: security-assessment-completed

#6536 Add additional attributions
  lib/streamlit/runtime/metrics_util.py
Labels: security-assessment-completed

#6487 st.experimental_connection: The big merge
  .github/workflows/python-versions.yml
  lib/streamlit/__init__.py
  lib/streamlit/connections/__init__.py
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/connections/util.py
  lib/streamlit/runtime/connection_factory.py
  lib/test-requirements.txt
  lib/tests/streamlit/connections/__init__.py
  lib/tests/streamlit/connections/base_connection_test.py
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/sql_connection_test.py
  lib/tests/streamlit/connections/util_test.py
  lib/tests/streamlit/runtime/connection_factory_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, dev:full-matrix, dev:upgrade-dependencies

#6543 Move pandas styler logic to dedicated module
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed

#6548 Improve editing on touch devices for `st.data_editor`
  frontend/src/components/widgets/DataFrame/DataFrame.test.tsx
  frontend/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed

#6555 ESLint: use `--cache` flag (30x speedup!)
  frontend/package.json
Labels: security-assessment-completed

#6522 Clean up and reorganize element tree module
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6544 Unify missing values to None in the returned datastructure by `st.data_editor`.
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed

#6549 Show warning for unsafe integer cells in `st.dataframe`
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.ts
Labels: security-assessment-completed

#6554 Update dataframe column properties on frontend
  frontend/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/src/components/widgets/DataFrame/columns/BooleanColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/CategoricalColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/CategoricalColumn.ts
  frontend/src/components/widgets/DataFrame/columns/ListColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/src/components/widgets/DataFrame/columns/ObjectColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/TextColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
  frontend/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/src/components/widgets/DataFrame/hooks/useColumnSort.test.ts
  frontend/src/components/widgets/DataFrame/hooks/useDataEditor.test.ts
  frontend/src/components/widgets/DataFrame/hooks/useDataEditor.ts
  frontend/src/components/widgets/DataFrame/hooks/useDataLoader.test.ts
  lib/streamlit/elements/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed

#6561 Add support for cell and column header tooltips in the dataframe component
  frontend/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/src/components/widgets/DataFrame/Tooltip.test.tsx
  frontend/src/components/widgets/DataFrame/Tooltip.tsx
  frontend/src/components/widgets/DataFrame/columns/utils.ts
  frontend/src/components/widgets/DataFrame/hooks/index.ts
  frontend/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/src/components/widgets/DataFrame/hooks/useTooltips.test.ts
  frontend/src/components/widgets/DataFrame/hooks/useTooltips.ts
Labels: security-assessment-completed

#6565 Fix top padding on sidebar when embed is true
  frontend/src/components/core/Sidebar/Sidebar.tsx
  frontend/src/components/core/Sidebar/styled-components.ts
Labels: security-assessment-completed

#6562 Rename boolean and categorical columns
  frontend/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/src/components/widgets/DataFrame/columns/CheckboxColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/CheckboxColumn.ts
  frontend/src/components/widgets/DataFrame/columns/SelectboxColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
  frontend/src/components/widgets/DataFrame/columns/index.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
  frontend/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  lib/streamlit/elements/data_editor.py
Labels: security-assessment-completed

#6559 Make type=jpg and type=jpeg mean type=[jpg, jpeg] in file uploader.
  lib/streamlit/elements/file_uploader.py
  lib/tests/streamlit/elements/file_uploader_test.py
Labels: security-assessment-completed

#6558 Clean up old experimental and beta commands
  lib/streamlit/__init__.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/show.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/show_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed

#6563 Add input validation capabilities to `st.data_editor`
  frontend/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/src/components/widgets/DataFrame/columns/TextColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/TextColumn.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
  frontend/src/components/widgets/DataFrame/hooks/useDataEditor.test.ts
  frontend/src/components/widgets/DataFrame/hooks/useDataEditor.ts
Labels: security-assessment-completed

#6551 Add improved type parsing capabilities for `st.data_editor`
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/lib/__init__.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
Labels: security-assessment-completed

#6569 Remove deprecated metrics
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/core/MainMenu/MainMenu.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/components/core/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/src/components/core/StreamlitDialog/SettingsDialog.test.tsx
  frontend/src/components/core/StreamlitDialog/SettingsDialog.tsx
  frontend/src/lib/MetricsManager.ts
  frontend/src/lib/SegmentMetricsManager.test.ts
  frontend/src/lib/SegmentMetricsManager.ts
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6566 Testing property syntax
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6025 Add editable datetime, date and time column types
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-4.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-5.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-6.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-9.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_input_data.spec.js/data_editor-input-data-30.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_input_data.spec.js/data_editor-input-data-31.snap.png
  frontend/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/src/components/widgets/DataFrame/columns/DateTimeColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/src/components/widgets/DataFrame/columns/cells/DateTimeCell.test.tsx
  frontend/src/components/widgets/DataFrame/columns/cells/DateTimeCell.tsx
  frontend/src/components/widgets/DataFrame/columns/index.ts
  frontend/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
  frontend/src/lib/Quiver.ts
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed

#6564 `SQLConnection` and `ExperimentalBaseConnection` docstring improvements
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/runtime/connection_factory.py
Labels: type:docs, security-assessment-completed, feature:connections

#6573 Add link column type for `st.dataframe` and `st.data_editor`
  frontend/src/components/widgets/DataFrame/columns/LinkColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/src/components/widgets/DataFrame/columns/index.ts
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed

#6574 Fix text column validation
  frontend/src/components/widgets/DataFrame/columns/TextColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/TextColumn.ts
Labels: security-assessment-completed

#6581 Add image column type for `st.dataframe` and `st.data_editor`
  frontend/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/src/components/widgets/DataFrame/columns/ImageColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/ImageColumn.ts
  frontend/src/components/widgets/DataFrame/columns/cells/ImageCellEditor.test.tsx
  frontend/src/components/widgets/DataFrame/columns/cells/ImageCellEditor.tsx
  frontend/src/components/widgets/DataFrame/columns/index.ts
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed

#6583 Improve number column type for `st.dataframe` and `st.data_editor`
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed

#6582 Add chart column types for `st.dataframe` and `st.data_editor`
  frontend/src/components/widgets/DataFrame/columns/ChartColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/ChartColumn.ts
  frontend/src/components/widgets/DataFrame/columns/index.ts
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed

#6560 Support strings as TTL. So you can do ttl="1d12h", for example
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/streamlit/runtime/caching/cache_utils_test.py
Labels: security-assessment-completed

#6570 Remove usage of CIRCLECI environment variable
  Makefile
  frontend/craco.config.js
  scripts/run_e2e_tests.py
Labels: security-assessment-completed

#6591 Refactor `st.dataframe` and `st.data_editor` number formatting
  frontend/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/src/components/widgets/DataFrame/columns/ChartColumn.ts
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed

#6590 Change datetime column formatting to date-fns
  NOTICES
  frontend/package.json
  frontend/src/components/widgets/DataFrame/columns/DateTimeColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
  frontend/yarn.lock
Labels: security-assessment-completed

#6593 Add progress column type for `st.dataframe` and `st.data_editor`
  frontend/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/ProgressColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/ProgressColumn.ts
  frontend/src/components/widgets/DataFrame/columns/index.ts
  frontend/src/components/widgets/DataFrame/hooks/useDataEditor.ts
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed

#6575 Better test script loading
  lib/streamlit/testing/element_tree.py
  lib/streamlit/testing/script_interactions.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/script_interactions_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed
