Repository streamlit/streamlit, pull requests merged in 2023-05, with the labels that each got.

#6556 Add db client attributions
  lib/streamlit/runtime/metrics_util.py
Labels: security-assessment-completed

#6607 Split AppContext into AppContext, LibContext
  frontend/src/app/App.tsx
  frontend/src/app/components/AppContext.tsx
  frontend/src/app/components/AppView/AppView.tsx
  frontend/src/app/components/Header/Header.tsx
  frontend/src/app/components/Sidebar/ThemedSidebar.tsx
  frontend/src/app/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/src/app/components/StreamlitDialog/SettingsDialog.tsx
  frontend/src/app/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/src/lib/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/lib/components/core/LibContext.tsx
  frontend/src/lib/components/elements/Spinner/Spinner.tsx
  frontend/src/lib/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/src/lib/components/shared/ProgressBar/ProgressBar.tsx
  frontend/src/lib/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed

#6608 BaseBlockProps documentation
  frontend/src/lib/components/core/Block/utils.ts
Labels: security-assessment-completed

#6615 Add support for classes as argument type
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/runtime/metrics_util_test.py
Labels: security-assessment-completed

#6621 Fix rendering of line chart column
  frontend/src/lib/components/widgets/DataFrame/columns/ChartColumn.test.ts
  frontend/src/lib/components/widgets/DataFrame/columns/ChartColumn.ts
Labels: security-assessment-completed

#6614 Remove redundant BaseWeb ThemeProvider
  frontend/src/app/ThemedApp.test.tsx
  frontend/src/app/ThemedApp.tsx
  frontend/src/lib/mocks/mockTheme.ts
  frontend/src/lib/theme/themeConfigs.ts
  frontend/src/lib/theme/types.ts
Labels: security-assessment-completed

#6628 Allow disabling editing for individual columns in `st.data_editor`
  e2e/scripts/st_data_editor_config.py
  e2e/specs/st_data_editor_config.spec.js
  frontend/cypress/snapshots/linux/2x/st_data_editor_config.spec.js/data_editor-config-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_config.spec.js/data_editor-config-1.snap.png
  lib/streamlit/elements/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed

#6617 Fix memory leak in ForwardMsgCache
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/runtime.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/forward_msg_cache_test.py
Labels: security-assessment-completed

#6633 Ignore new vendor paths for codeql
  .github/codeql-config.yml
Labels: security-assessment-completed

#6632 Avoid thread safety mishap
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/runtime.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test.py
Labels: security-assessment-completed

#6634 Add basic widget rule checks to `st.data_editor`
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/utils.py
Labels: security-assessment-completed

#6631 Run build_info script in conda build workflow
  .github/workflows/conda-build.yml
Labels: security-assessment-completed

#6636 Move Text to TextElement so there is no same naming schema
  frontend/src/lib/StreamlitLib.test.tsx
  frontend/src/lib/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/lib/components/elements/TextElement/TextElement.test.tsx
  frontend/src/lib/components/elements/TextElement/TextElement.tsx
  frontend/src/lib/components/elements/TextElement/index.tsx
  frontend/src/lib/components/elements/TextElement/styled-components.ts
Labels: security-assessment-completed

#6627 Add `column_order` parameter to `st.dataframe` and `st.data_editor`
  e2e/scripts/st_arrow_dataframe_config.py
  e2e/scripts/st_data_editor_config.py
  e2e/specs/st_arrow_dataframe_config.spec.js
  e2e/specs/st_data_editor_config.spec.js
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_config.spec.js/dataframe-config-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_data_editor_config.spec.js/data_editor-config-4.snap.png
  frontend/src/lib/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useColumnLoader.ts
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/dataframe_selector.py
  lib/tests/streamlit/dataframe_selector_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  proto/streamlit/proto/Arrow.proto
Labels: security-assessment-completed

#6644 Fix issues with list column
  frontend/src/lib/components/widgets/DataFrame/columns/ListColumn.test.ts
  frontend/src/lib/components/widgets/DataFrame/columns/ListColumn.ts
  frontend/src/lib/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/lib/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed

#6648 Remove unused `AssetsFileHandler` endpoint and directory
  frontend/public/assets/streamlit.css
  lib/streamlit/file_util.py
  lib/streamlit/web/server/app_static_file_handler.py
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
Labels: security-assessment-completed

#6654 Change docstrings to list str options explicitly
  lib/streamlit/commands/page_config.py
  lib/streamlit/elements/camera_input.py
  lib/streamlit/elements/checkbox.py
  lib/streamlit/elements/color_picker.py
  lib/streamlit/elements/file_uploader.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/multiselect.py
  lib/streamlit/elements/number_input.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/radio.py
  lib/streamlit/elements/select_slider.py
  lib/streamlit/elements/selectbox.py
  lib/streamlit/elements/slider.py
  lib/streamlit/elements/text_widgets.py
  lib/streamlit/elements/time_widgets.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/connection_factory.py
Labels: type:docs, security-assessment-completed

#6661 Fix pytest warnings
  lib/streamlit/runtime/app_session.py
  lib/tests/conftest.py
  lib/tests/delta_generator_test_case.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/elements/media_test.py
Labels: security-assessment-completed

#6660 Refactor Duplicated Export Names
  frontend/src/app/components/DeployButton/DeployButton.tsx
  frontend/src/app/components/MainMenu/MainMenu.tsx
  frontend/src/app/components/Sidebar/Sidebar.tsx
  frontend/src/app/components/StatusWidget/StatusWidget.test.tsx
  frontend/src/app/components/StatusWidget/StatusWidget.tsx
  frontend/src/app/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/src/app/components/StreamlitDialog/ScriptChangedDialog.tsx
  frontend/src/app/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/src/app/components/StreamlitDialog/SettingsDialog.tsx
  frontend/src/app/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/src/app/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/src/app/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/src/app/components/StreamlitDialog/__snapshots__/SettingsDialog.test.tsx.snap
  frontend/src/app/components/StreamlitDialog/__snapshots__/StreamlitDialog.test.tsx.snap
  frontend/src/app/components/StreamlitDialog/__snapshots__/ThemeCreatorDialog.test.tsx.snap
  frontend/src/app/components/ToolbarActions/ToolbarActions.tsx
  frontend/src/app/components/ToolbarActions/__snapshots__/ToolbarActions.test.tsx.snap
  frontend/src/app/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.tsx
  frontend/src/app/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.tsx
  frontend/src/lib/StreamlitLib.test.tsx
  frontend/src/lib/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/lib/components/elements/AlertElement/AlertElement.test.tsx
  frontend/src/lib/components/elements/AlertElement/AlertElement.tsx
  frontend/src/lib/components/elements/AlertElement/index.tsx
  frontend/src/lib/components/elements/AlertElement/styled-components.tsx
  frontend/src/lib/components/elements/Json/Json.test.tsx
  frontend/src/lib/components/shared/BaseButton/BaseButton.test.tsx
  frontend/src/lib/components/shared/BaseButton/BaseButton.tsx
  frontend/src/lib/components/shared/BaseButton/BaseButtonTooltip.tsx
  frontend/src/lib/components/shared/BaseButton/index.tsx
  frontend/src/lib/components/shared/BaseButton/styled-components.ts
  frontend/src/lib/components/shared/BaseColorPicker/BaseColorPicker.test.tsx
  frontend/src/lib/components/shared/BaseColorPicker/BaseColorPicker.tsx
  frontend/src/lib/components/shared/BaseColorPicker/index.tsx
  frontend/src/lib/components/shared/BaseColorPicker/styled-components.ts
  frontend/src/lib/components/shared/ErrorElement/ErrorElement.test.tsx
  frontend/src/lib/components/shared/Modal/Modal.tsx
  frontend/src/lib/components/widgets/Button/Button.test.tsx
  frontend/src/lib/components/widgets/Button/Button.tsx
  frontend/src/lib/components/widgets/CameraInput/SwitchFacingModeButton.tsx
  frontend/src/lib/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/src/lib/components/widgets/ColorPicker/ColorPicker.tsx
  frontend/src/lib/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/src/lib/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/src/lib/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/src/lib/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/src/lib/components/widgets/FileUploader/FileDropzone.tsx
  frontend/src/lib/components/widgets/FileUploader/UploadedFile.tsx
  frontend/src/lib/components/widgets/Form/Form.test.tsx
  frontend/src/lib/components/widgets/Form/Form.tsx
  frontend/src/lib/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/src/lib/components/widgets/Form/FormSubmitButton.tsx
  frontend/src/lib/hocs/withMapboxToken/withMapboxToken.test.tsx
  frontend/src/lib/hocs/withMapboxToken/withMapboxToken.tsx
  frontend/src/lib/hocs/withPagination/Pagination.test.tsx
  frontend/src/lib/hocs/withPagination/Pagination.tsx
Labels: security-assessment-completed

#6669 Fix import name
  frontend/src/app/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/src/app/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/src/lib/components/widgets/Button/Button.test.tsx
  frontend/src/lib/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/src/lib/components/widgets/Form/FormSubmitButton.test.tsx
Labels: security-assessment-completed

#6666 Adding security policy
  SECURITY.md
  scripts/check_license_headers.py
Labels: security-assessment-completed

#6650 Update data_editor docstring re: supported types
  lib/streamlit/elements/data_editor.py
Labels: type:docs, security-assessment-completed, feature:st.data_editor

#6691 Python requirements: pin to < NEXT_MAJOR_VERSION
  lib/setup.py
Labels: security-assessment-completed

#6693 Fix typo in Arrow.proto
  proto/streamlit/proto/Arrow.proto
Labels: security-assessment-completed

#6695 Implement required parameter for `st.data_editor`
  frontend/src/lib/components/widgets/DataFrame/DataFrame.tsx
  frontend/src/lib/components/widgets/DataFrame/EditingState.test.ts
  frontend/src/lib/components/widgets/DataFrame/EditingState.ts
  frontend/src/lib/components/widgets/DataFrame/columns/CheckboxColumn.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/index.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useCustomRenderer.test.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useCustomRenderer.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useTooltips.test.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useTooltips.ts
Labels: security-assessment-completed

#6663 Preserve multiple whitespaces in `st.json` rendering of k:v pairs
  e2e/scripts/st_json.py
  e2e/specs/st_json.spec.js
  frontend/cypress/snapshots/linux/2x/st_json.spec.js/json-white-spaces-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_json.spec.js/json-white-spaces.snap.png
  frontend/src/lib/components/elements/Json/Json.tsx
Labels: feature:st.json, security-assessment-completed

#6673 Cache script bytecode
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/scriptrunner/script_cache.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/runtime/websocket_session_manager.py
  lib/streamlit/testing/local_script_runner.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/scriptrunner/script_cache_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/websocket_session_manager_test.py
Labels: security-assessment-completed

#6696 Prepare column config support
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-3.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-4.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-5.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-6.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-7-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_column_types.js/dataframe-column-types-7.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-3.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-4.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-5.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-6.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-7.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_dataframe_index_types.js/dataframe-index-types-9.snap.png
  frontend/src/lib/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/lib/components/widgets/DataFrame/arrowUtils.ts
  frontend/src/lib/components/widgets/DataFrame/columns/DateTimeColumn.test.ts
  frontend/src/lib/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useColumnLoader.ts
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed

#6630 Fix range input selection
  e2e/specs/st_date_input.spec.js
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_0.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_1.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_2.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_3.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_4.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_6.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_7-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_7.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_8.snap.png
  frontend/src/lib/components/widgets/DateInput/DateInput.tsx
Labels: security-assessment-completed

#6702 Migrate datetime column formatting from date-fns to momentJS
  NOTICES
  frontend/package.json
  frontend/src/lib/components/widgets/DataFrame/columns/DateTimeColumn.test.ts
  frontend/src/lib/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/src/lib/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/lib/components/widgets/DataFrame/columns/utils.ts
  frontend/yarn.lock
Labels: security-assessment-completed

#6640 Add a config option to disable warning for setting both a widget default and its key in session_state
  lib/streamlit/config.py
  lib/streamlit/elements/utils.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/elements/element_utils_test.py
Labels: security-assessment-completed

#6594 Clarify set_page_config docstring and exception message
  e2e/specs/st_set_page_config.spec.js
  lib/streamlit/commands/page_config.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
Labels: type:docs, security-assessment-completed

#6712 Remove experimental prefix from `st.data_editor`
  e2e/scripts/st_data_editor_column_types.py
  e2e/scripts/st_data_editor_config.py
  e2e/scripts/st_data_editor_input_data.py
  lib/streamlit/__init__.py
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/lib/column_types.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed

#6731 Fix: SidebarNav expansion
  frontend/src/lib/util/Hooks.ts
Labels: security-assessment-completed

#6727 Improve `st.columns` docstring
  lib/streamlit/elements/layouts.py
Labels: security-assessment-completed

#6733 Improve docstrings for `ttl` and `max_entries`
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
Labels: security-assessment-completed

#6688 Update modals
  e2e/scripts/modals.py
  e2e/specs/deploy_button.spec.js
  e2e/specs/modals.spec.js
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_dialog_opened-dark.snap.png
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_dialog_opened.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/about-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/about.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/cache-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/cache.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/screencast-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/screencast.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/settings-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/settings.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/theme-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/theme.snap.png
  frontend/src/app/components/StreamlitDialog/DeployDialog/DeployCard.tsx
  frontend/src/app/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/src/app/components/StreamlitDialog/DeployDialog/styled-components.tsx
  frontend/src/app/components/StreamlitDialog/SettingsDialog.tsx
  frontend/src/app/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/src/app/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/src/app/components/StreamlitDialog/__snapshots__/SettingsDialog.test.tsx.snap
  frontend/src/app/components/StreamlitDialog/__snapshots__/ThemeCreatorDialog.test.tsx.snap
  frontend/src/app/components/StreamlitDialog/styled-components.ts
  frontend/src/lib/components/shared/Modal/Modal.tsx
Labels: security-assessment-completed

#6618 Add support for Altair 5
  NOTICES
  e2e/scripts/st_arrow_altair_global_theme.py
  e2e/specs/st_arrow_altair_global_theme.spec.js
  frontend/cypress/snapshots/linux/2x/st_arrow_altair_global_theme.spec.js/altair_chart_0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_altair_global_theme.spec.js/altair_chart_0.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_line_chart_add_rows_special.spec.js/arrowLineChartAddRows-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_line_chart_add_rows_special.spec.js/arrowLineChartAddRows.snap.png
  frontend/package.json
  frontend/yarn.lock
  lib/setup.py
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/legacy_altair.py
  lib/tests/streamlit/elements/arrow_altair_test.py
  lib/tests/streamlit/elements/legacy_altair_test.py
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
Labels: security-assessment-completed

#6531 Improve startup performance by lazy loading some dependencies
  lib/streamlit/elements/legacy_data_frame.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/media.py
  lib/streamlit/net_util.py
  lib/streamlit/runtime/credentials.py
  lib/streamlit/version.py
Labels: security-assessment-completed

#6732 Use .genericFonts instead of .fonts to fix bug with theme postMessage.
  frontend/src/app/components/AppView/styled-components.ts
  frontend/src/app/components/StreamlitDialog/DeployDialog/styled-components.tsx
  frontend/src/lib/components/elements/ArrowTable/styled-components.ts
  frontend/src/lib/components/elements/DataFrame/styled-components.ts
  frontend/src/lib/components/elements/DocString/styled-components.ts
  frontend/src/lib/components/elements/Table/styled-components.ts
  frontend/src/lib/components/elements/TextElement/styled-components.ts
  frontend/src/lib/components/widgets/Slider/styled-components.ts
Labels: security-assessment-completed

#6729 Change default theme hash on app init
  frontend/src/app/App.test.tsx
  frontend/src/app/App.tsx
Labels: security-assessment-completed

#6724 Document integer size limit for number_input and slider
  lib/streamlit/elements/number_input.py
  lib/streamlit/elements/slider.py
Labels: security-assessment-completed

#6743 Cypress flaky test fixes
  e2e/specs/label_markdown.spec.js
  e2e/specs/st_map.spec.js
Labels: security-assessment-completed

#6711 Update `st.data_editor` session state format
  e2e/scripts/st_arrow_dataframe_config.py
  e2e/scripts/st_data_editor_config.py
  frontend/src/lib/components/widgets/DataFrame/EditingState.test.ts
  frontend/src/lib/components/widgets/DataFrame/EditingState.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/src/lib/components/widgets/DataFrame/hooks/useDataEditor.test.ts
  lib/streamlit/deprecation_util.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
Labels: security-assessment-completed

#6752 Update `st.data_editor` and `st.dataframe` docstrings
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed

#6753 Fix: Remove console.log
  frontend/src/lib/components/shared/Modal/Modal.tsx
Labels: security-assessment-completed

#6744 enzyme -> react-testing-library (Countdown, Modal, ProgressBar)
  frontend/src/app/components/Countdown/Countdown.test.tsx
  frontend/src/lib/components/shared/Modal/Modal.test.tsx
  frontend/src/lib/components/shared/ProgressBar/ProgressBar.test.tsx
Labels: security-assessment-completed

#6757 Replace curly with straight quotes in docstring examples
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/markdown.py
Labels: security-assessment-completed

#6750 Make st.write pretty-print dataclasses using st.help
  lib/streamlit/elements/write.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed

#6764 Upgrade react-range to fix memory usage of sliders
  frontend/yarn.lock
Labels: security-assessment-completed

#6664 Fix 3218, patch pydantic in_ipython function
  lib/streamlit/web/bootstrap.py
  lib/test-requirements.txt
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed
