Repository streamlit/streamlit, pull requests merged in 2023-07, with the labels that each got.

#6944 Add missing border radius
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert-spacing-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert-spacing.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert0.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert1.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert2.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert3.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert4.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert5.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert6.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert7-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert7.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert8.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert9.snap.png
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting-hover-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting-hover.snap.png
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting.snap.png
  frontend/cypress/snapshots/linux/2x/st_exception.spec.js/long_exception-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_exception.spec.js/long_exception.snap.png
  frontend/cypress/snapshots/linux/2x/st_expander.spec.js/expanders-in-main-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_expander.spec.js/expanders-in-main.snap.png
  frontend/cypress/snapshots/linux/2x/st_expander.spec.js/expanders-in-sidebar-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_expander.spec.js/expanders-in-sidebar.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-3.snap.png
  frontend/src/lib/components/elements/CodeBlock/styled-components.ts
  frontend/src/lib/components/shared/AlertContainer/AlertContainer.tsx
  frontend/src/lib/hocs/withExpandable/withExpandable.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#6917 Fix: description of config options
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#6947 Update hamburger menu icon to overflow
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_button.snap.png
  frontend/cypress/snapshots/linux/2x/st_disconnect.spec.js/disconnected-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_disconnect.spec.js/disconnected.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit.snap.png
  frontend/src/app/App.tsx
  frontend/src/app/components/Header/styled-components.ts
  frontend/src/app/components/MainMenu/MainMenu.test.tsx
  frontend/src/app/components/MainMenu/MainMenu.tsx
  frontend/src/app/components/MainMenu/styled-components.ts
  frontend/src/app/components/Sidebar/Sidebar.tsx
  frontend/src/app/components/StreamlitDialog/__snapshots__/StreamlitDialog.test.tsx.snap
  frontend/src/lib/components/shared/BaseButton/BaseButton.tsx
  frontend/src/lib/components/shared/BaseButton/styled-components.ts
  lib/streamlit/config.py
Labels: security-assessment-completed, change:other, impact:users

#6959 [Snyk] Security upgrade protobufjs from 7.2.1 to 7.2.4
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:users

#6976 Fix baseweb warnings by using longhand properties
  frontend/src/lib/components/shared/AlertContainer/AlertContainer.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#6972 Slightly simplify bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: security-assessment-completed, impact:internal, change:chore

#6964 Update st.audio/st.video docstrings
  lib/streamlit/elements/media.py
Labels: security-assessment-completed, change:bugfix, impact:users

#6965 Release 1.24.1
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#6977 Remove unused import
  lib/streamlit/string_util.py
Labels: security-assessment-completed, change:other, impact:internal

#6979 Also use bottom padding in embedded mode for chat input
  e2e/scripts/embedded_chat_input_app.py
  e2e/specs/embedded_chat_input_app.js
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#6901 Allow setting placeholder for st.multiselect
  e2e/scripts/st_multiselect.py
  e2e/specs/st_multiselect.spec.js
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  lib/streamlit/elements/multiselect.py
  lib/tests/streamlit/elements/multiselect_test.py
  proto/streamlit/proto/MultiSelect.proto
Labels: security-assessment-completed, change:feature, impact:users

#6913 Allow setting placeholder for st.selectbox
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.tsx
  lib/streamlit/elements/selectbox.py
  lib/tests/streamlit/elements/selectbox_test.py
  proto/streamlit/proto/Selectbox.proto
Labels: security-assessment-completed, change:feature, impact:users

#6980 Remove unnecessary code and Add rm commands to make clean
  Makefile
  frontend/package.json
  scripts/watch_frontend_lib.py
Labels: security-assessment-completed, impact:internal, change:chore

#6987 Re-add homepage to package.json
  frontend/app/package.json
Labels: security-assessment-completed, impact:internal, change:chore

#6806 Add host communication e2e tests
  e2e/scripts/hostframe/hostframe_app.py
  e2e/scripts/hostframe/pages/02_App_Page_2.py
  e2e/scripts/hostframe/pages/03_App_Page_3.py
  e2e/specs/hostframe.spec.js
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-after.snap.png
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-before.snap.png
  frontend/hostframe.html
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/util/UriUtil.test.ts
  frontend/lib/src/util/UriUtil.ts
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/web/server/routes_test.py
  scripts/run_e2e_tests.py
Labels: security-assessment-completed, impact:internal, change:chore

#6974 Add `format` parameter to `date_input`
  e2e/scripts/st_date_input.py
  e2e/specs/st_date_input.spec.js
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input10-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input10.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input11-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input11.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input8.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input9.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_11-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_11.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_8.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_date_input.spec.js/date_input_calendar_9.snap.png
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
  lib/streamlit/elements/time_widgets.py
  lib/tests/streamlit/elements/date_input_test.py
  proto/streamlit/proto/DateInput.proto
Labels: security-assessment-completed, change:feature, impact:users

#6911 Add ability to click enter on textInput, NumberInput, and TextArea when in st.form
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.test.tsx
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.test.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.test.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#6997 Docs/toast - update of parameter description
  lib/streamlit/elements/toast.py
Labels: security-assessment-completed, impact:internal, change:chore

#6896 Add support for latitude, longitude, color, and size args in st.map
  e2e/scripts/st_map.py
  e2e/specs/st_map.spec.js
  frontend/cypress/snapshots/linux/2x/st_map.spec.js/stDeckGlJsonChart-complexMap-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_map.spec.js/stDeckGlJsonChart-complexMap.snap.png
  lib/streamlit/color_util.py
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/map_test.py
Labels: security-assessment-completed, change:feature, impact:users

#6994 Fix overflow menu
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/MainMenu/styled-components.ts
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/dev_main_menu.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu.snap.png
Labels: security-assessment-completed, change:bugfix, impact:users

#6992 Ignore iframe resizer anchor for apps with `st.chat_input`
  e2e/specs/embedded_chat_input_app.js
  frontend/app/src/components/AppView/AppView.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#7008 Update require-labels.yml to include changes to documentation
  .github/workflows/require-labels.yml
Labels: security-assessment-completed, impact:internal, change:chore

#7006 Remove unused import
  lib/streamlit/elements/alert.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7011 Toast design adjustments
  frontend/lib/src/components/elements/Toast/Toast.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7014 Update st.map docstring for color and size
  lib/streamlit/elements/map.py
Labels: feature:st.map, security-assessment-completed, impact:internal, change:docs

#6933 Point out that editable columns cannot be styled via Pandas Styler
  lib/streamlit/elements/data_editor.py
Labels: security-assessment-completed, impact:users, change:docs

#7005 Remove useless condition
  frontend/app/src/connection/ConnectionManager.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#7009 add property in LibContext to remove fullScreenButton for widgets and elements
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.test.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/lib/src/hocs/withFullScreenWrapper/withFullScreenWrapper.test.tsx
  frontend/lib/src/test_util.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#7002 Re-enable Jest rules in ESLint
  frontend/.eslintrc.js
  frontend/app/src/App.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.test.tsx
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/components/elements/Metric/Metric.test.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.test.tsx
  frontend/lib/src/components/shared/BaseButton/BaseButton.test.tsx
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Tooltip/OverflowTooltip.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentRegistry.test.ts
  frontend/lib/src/components/widgets/DataFrame/Tooltip.test.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/DateTimeCell.test.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.test.ts
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/hocs/withMapboxToken/MapboxToken.test.ts
  frontend/lib/src/hocs/withMapboxToken/MapboxToken.ts
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/util/FileHelper.test.ts
Labels: security-assessment-completed, impact:internal, change:chore

#7026 Bump protobufjs to 7.2.4
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#7020 Update st.selectbox description of placeholder
  lib/streamlit/elements/selectbox.py
Labels: security-assessment-completed, impact:internal, change:docs

#6919 Dont use constraints files in python-min-deps.yml workflow in canary builds
  .github/workflows/python-min-deps.yml
Labels: security-assessment-completed, impact:internal, change:chore

#6993 ignore Enter on inputing with IME
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7052 Fix UpdateVersion.py script to modify app and lib package.json
  scripts/update_version.py
Labels: security-assessment-completed, impact:internal, change:chore

#7043 Update docstrings for st.form, st.toast, st.date_input
  lib/streamlit/elements/form.py
  lib/streamlit/elements/time_widgets.py
  lib/streamlit/elements/toast.py
Labels: security-assessment-completed, impact:internal, change:docs

#7042 Move widgets to their own submodule
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/widgets/__init__.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/elements/chat_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/file_uploader_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/form_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7059 `USE_CONSTRAINT_FILE` should be plural
  .github/actions/build_info/action.yml
  .github/scripts/build_info.py
  .github/workflows/python-versions.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  Makefile
Labels: security-assessment-completed, impact:internal, change:bugfix

#7053 Fix: AppNode compatible w/o Event in RootContainer
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#7028 Create proper relative paths in the dist folder for js and ts code
  .github/workflows/build-streamlit-lib-prod.yml
  Makefile
  frontend/lib/package.json
  frontend/lib/scripts/create.js
  frontend/lib/tsconfig.prod.json
  frontend/package.json
  frontend/yarn.lock
  scripts/ensure_relative_imports.sh
Labels: security-assessment-completed, impact:internal, change:chore

#7029 Allow conda build number to be set via envvar
  lib/conda-recipe/meta.yaml
Labels: security-assessment-completed, impact:internal, change:chore

#7050 Assorted visual tweaks
  e2e/scripts/st_number_input.py
  e2e/specs/st_number_input.spec.js
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/cypress/snapshots/linux/2x/modals.spec.js/about-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/about.snap.png
  frontend/cypress/snapshots/linux/2x/st_number_input.spec.js/number_input9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_number_input.spec.js/number_input9.snap.png
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/theme/primitives/breakpoints.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#6998 Add RTL Rules to eslint config
  frontend/.eslintrc.js
  frontend/app/src/App.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/ChatMessage/ChatMessage.test.tsx
  frontend/lib/src/components/elements/ChatMessage/ChatMessage.tsx
  frontend/lib/src/components/elements/DataFrame/DataFrame.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.test.tsx
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/widgets/BaseWidget/WidgetLabel.tsx
  frontend/lib/src/components/widgets/BaseWidget/__snapshots__/WidgetLabel.test.tsx.snap
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/DataFrame/Tooltip.test.tsx
  frontend/lib/src/components/widgets/DataFrame/Tooltip.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/DateTimeCell.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.test.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.tsx
  frontend/lib/src/hooks/useScrollAnimation.test.ts
Labels: security-assessment-completed, impact:internal, change:chore

#7018 Markdown support for radio button labels
  e2e/scripts/st_radio.py
  e2e/specs/st_radio.spec.js
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio10-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio10.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio8.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_radio.spec.js/radio9.snap.png
  frontend/lib/src/components/shared/Radio/Radio.test.tsx
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/Checkbox/Checkbox.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
Labels: security-assessment-completed, change:feature, impact:users

#7051 Up version to 1.25.0
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#7070 Make background color transparent for tabs
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7067 Convert some FE Enzyme tests to RTL
  frontend/lib/src/components/elements/Balloons/Balloons.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.tsx
  frontend/lib/src/components/elements/Snow/Snow.test.tsx
  frontend/lib/src/components/elements/Table/Table.test.tsx
  frontend/lib/src/components/shared/TooltipIcon/TooltipIcon.test.tsx
  frontend/lib/src/components/shared/TooltipIcon/TooltipIcon.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7080 Fix flaky playwright test
  e2e/playwright/conftest.py
  e2e/playwright/st_checkbox_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7065 Update feature request template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/community-voting.yml
Labels: security-assessment-completed, impact:internal, change:chore

#7003 Fix widget id stability
  lib/streamlit/components/v1/components.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/slider_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7081 Replace imghdr with pillow
  lib/streamlit/elements/image.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7092 Don't require new methods/args in StreamlitEndpoints and FileUploadClient
  frontend/lib/src/FileUploadClient.ts
  frontend/lib/src/StreamlitEndpoints.ts
Labels: security-assessment-completed, impact:internal, change:chore

#7025 Feature/file uploader abstractions
  NOTICES
  e2e/specs/st_file_uploader.spec.js
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/lib/package.json
  frontend/lib/src/FileUploadClient.test.ts
  frontend/lib/src/FileUploadClient.ts
  frontend/lib/src/ForwardMessageCache.test.ts
  frontend/lib/src/StreamlitEndpoints.ts
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadFileInfo.ts
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.test.tsx
  frontend/lib/src/mocks/mocks.ts
  frontend/lib/src/util/Resolver.ts
  frontend/package.json
  frontend/yarn.lock
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/memory_uploaded_file_manager.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/uploaded_file_manager.py
  lib/streamlit/testing/local_script_runner.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/tests/delta_generator_test_case.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/elements/file_uploader_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/runtime_threading_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/runtime/uploaded_file_manager_test.py
  lib/tests/streamlit/script_run_context_test.py
  lib/tests/streamlit/web/server/upload_file_request_handler_test.py
  lib/tests/testutil.py
  proto/streamlit/proto/BackMsg.proto
  proto/streamlit/proto/Common.proto
  proto/streamlit/proto/ForwardMsg.proto
Labels: security-assessment-completed, impact:internal, change:refactor
