Repository streamlit/streamlit, pull requests merged in 2023-06, with the labels that each got.

#6770 Fix typo in data_editor docstring and deprecation msg: `edited_rows` -> `edited_cells`
  lib/streamlit/elements/data_editor.py
Labels: security-assessment-completed

#6776 Fix dependency: typing-extensions >= 4.0.1, < 5
  lib/setup.py
Labels: security-assessment-completed

#6777 Release/1.23.1
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed

#6786 Add python 3.11 to classifiers list.
  lib/setup.py
Labels: security-assessment-completed

#6746 Refactor: withHostCommunication -> HostCommunicationManager
  frontend/hostframe.html
  frontend/src/app/App.test.tsx
  frontend/src/app/App.tsx
  frontend/src/app/SegmentMetricsManager.ts
  frontend/src/app/components/AppContext.tsx
  frontend/src/app/components/AppView/AppView.test.tsx
  frontend/src/app/components/AppView/AppView.tsx
  frontend/src/app/components/MainMenu/MainMenu.test.tsx
  frontend/src/app/components/MainMenu/MainMenu.tsx
  frontend/src/app/components/Sidebar/Sidebar.test.tsx
  frontend/src/app/components/Sidebar/Sidebar.tsx
  frontend/src/app/components/Sidebar/SidebarNav.test.tsx
  frontend/src/app/components/Sidebar/SidebarNav.tsx
  frontend/src/app/components/Sidebar/ThemedSidebar.test.tsx
  frontend/src/app/components/ToolbarActions/ToolbarActions.tsx
  frontend/src/app/connection/ConnectionManager.ts
  frontend/src/app/connection/WebsocketConnection.tsx
  frontend/src/lib/components/elements/Favicon/Favicon.tsx
  frontend/src/lib/hocs/withHostCommunication/withHostCommunication.test.tsx
  frontend/src/lib/hocs/withHostCommunication/withHostCommunication.tsx
  frontend/src/lib/hostComm/HostCommunicationManager.test.tsx
  frontend/src/lib/hostComm/HostCommunicationManager.tsx
  frontend/src/lib/hostComm/index.tsx
  frontend/src/lib/hostComm/types.ts
Labels: security-assessment-completed

#6789 Add uuid as a dependency
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed

#6762 Feature/uploaded file manager protocol
  lib/streamlit/elements/camera_input.py
  lib/streamlit/elements/file_uploader.py
  lib/streamlit/runtime/memory_uploaded_file_manager.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/uploaded_file_manager.py
  lib/streamlit/testing/local_script_runner.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/tests/delta_generator_test_case.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/runtime_threading_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/uploaded_file_manager_test.py
  lib/tests/streamlit/script_run_context_test.py
  lib/tests/streamlit/web/server/upload_file_request_handler_test.py
  lib/tests/testutil.py
  proto/streamlit/proto/Common.proto
Labels: security-assessment-completed

#6780 README.md updated with links to docs
  README.md
Labels: security-assessment-completed

#6679 Update PR template to be simpler and more approachable
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/require-labels.yml
Labels: security-assessment-completed, impact:internal, change:chore

#6800 target="_blank" to README links
  README.md
Labels: security-assessment-completed, impact:internal, change:chore

#6807 Remove tensorflow and pytorch from test requirements
  .github/actions/make_init/action.yml
  Makefile
  lib/test-requirements-with-tensorflow.txt
  lib/tests/streamlit/elements/keras_test.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
  scripts/check_license_headers.py
  scripts/should_install_tensorflow.py
Labels: security-assessment-completed, impact:internal, change:chore

#6502 hash_funcs for st.cache_data and st.cache_resource
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/legacy_caching/hashing.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed, change:feature, impact:users

#6754 Start supporting configurable file upload URLs in StreamlitEndpoints and FileUploadClient
  frontend/src/app/connection/DefaultStreamlitEndpoints.test.ts
  frontend/src/app/connection/DefaultStreamlitEndpoints.ts
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/FileUploadClient.ts
  frontend/src/lib/ForwardMessageCache.test.ts
  frontend/src/lib/StreamlitEndpoints.ts
  frontend/src/lib/StreamlitLib.test.tsx
  frontend/src/lib/components/widgets/CameraInput/CameraInput.tsx
  frontend/src/lib/components/widgets/FileUploader/FileUploader.tsx
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6668 Add `to_pandas` method to convert inputs to pandas DataFrames
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:other, impact:internal

#6580 Add tests for component-lib
  .github/workflows/js-tests.yml
  component-lib/babel.config.js
  component-lib/jest.config.ts
  component-lib/package.json
  component-lib/src/ArrowTable.test.ts
  component-lib/src/StreamlitReact.test.tsx
  component-lib/src/mock_data.ts
  component-lib/src/setupTests.ts
  component-lib/src/streamlit.test.ts
  component-lib/src/test_utils.ts
  component-lib/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#6833 Update comments on magic.py
  lib/streamlit/runtime/scriptrunner/magic.py
Labels: security-assessment-completed, change:other, impact:internal

#6758 Make `streamlit config show` honor newlines
  lib/streamlit/config_util.py
  lib/tests/streamlit/config_util_test.py
Labels: feature:config, security-assessment-completed, change:bugfix, impact:users

#6832 Set default filename for if it missing in `st.download_button` widget.
  frontend/src/lib/components/widgets/DownloadButton/DownloadButton.tsx
  lib/streamlit/string_util.py
  lib/streamlit/web/server/media_file_handler.py
  lib/tests/streamlit/string_util_test.py
  lib/tests/streamlit/web/server/media_file_handler_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#6846 Fix: Embedded apps link updates
  lib/streamlit/elements/bokeh_chart.py
  lib/streamlit/elements/button.py
  lib/streamlit/elements/checkbox.py
  lib/streamlit/elements/color_picker.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/file_uploader.py
  lib/streamlit/elements/graphviz_chart.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/multiselect.py
  lib/streamlit/elements/number_input.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/radio.py
  lib/streamlit/elements/select_slider.py
  lib/streamlit/elements/selectbox.py
  lib/streamlit/elements/slider.py
  lib/streamlit/elements/text_widgets.py
  lib/streamlit/elements/time_widgets.py
  lib/streamlit/elements/write.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#6852 Setup String Trigger Value type for Widget State
  frontend/src/lib/WidgetStateManager.test.ts
  frontend/src/lib/WidgetStateManager.ts
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/state/widgets.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  proto/streamlit/proto/Common.proto
  proto/streamlit/proto/WidgetStates.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#6853 Add annotations to fix mypy error with latest numpy release
  e2e/scripts/st_image.py
  lib/streamlit/elements/media.py
Labels: security-assessment-completed, impact:internal, change:chore

#6861 Add `st.chat_message` element
  e2e/scripts/st_chat_message.py
  e2e/specs/st_chat_message.spec.js
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-3.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-4.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-5.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_message.spec.js/chat_message-6.snap.png
  frontend/src/lib/components/core/Block/Block.tsx
  frontend/src/lib/components/elements/ChatMessage/ChatMessage.test.tsx
  frontend/src/lib/components/elements/ChatMessage/ChatMessage.tsx
  frontend/src/lib/components/elements/ChatMessage/index.tsx
  frontend/src/lib/components/elements/ChatMessage/styled-components.ts
  lib/streamlit/__init__.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/chat.py
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/chat_test.py
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#6859 Fix stale element issue caused by spinners
  lib/streamlit/elements/spinner.py
  lib/tests/streamlit/runtime/caching/test_data/arrow_replay.py
  lib/tests/streamlit/runtime/caching/test_data/cached_widget_replay_dynamic.py
  lib/tests/streamlit/script_interactions_test.py
  lib/tests/streamlit/spinner_test.py
  lib/tests/streamlit/test_data/cached_widget_replay.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#6825 SiS theming fixes
  frontend/src/app/components/Sidebar/ThemedSidebar.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#6866 Camera width debounce logic
  frontend/src/lib/components/widgets/CameraInput/WebcamComponent.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#6868 Drop Python 3.7 support
  .github/scripts/build_info.py
  e2e/scripts/st_pyplot_kwargs.py
  lib/dev-requirements.txt
  lib/setup.py
  lib/streamlit/elements/doc_string.py
  lib/streamlit/runtime/legacy_caching/hashing.py
  lib/streamlit/runtime/runtime.py
  lib/tests/isolated_asyncio_test_case.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/runtime_threading_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/streamlit/web/server/browser_websocket_handler_test.py
  scripts/check_license_headers.py
Labels: security-assessment-completed, change:chore, impact:users

#6871 Fixed Chat Input Resizing Issues and Width
  frontend/src/lib/components/widgets/ChatInput/ChatInput.tsx
  frontend/src/lib/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#6876 Show a better exception for invalid avatar value
  lib/streamlit/elements/chat.py
  lib/tests/streamlit/elements/chat_test.py
Labels: security-assessment-completed, change:other, impact:users

#6872 Show empty chat messages
  e2e/scripts/st_chat_message.py
  frontend/src/lib/components/core/Block/Block.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#6874 Add e2e tests for st.chat_input
  e2e/scripts/st_chat_input.py
  e2e/specs/st_chat_input.spec.js
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-focused-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-focused-light.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-grows-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-grows.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-maxChars-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-maxChars.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-shiftEnter-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-shiftEnter.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-shrinks-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput-shrinks.snap.png
  frontend/cypress/snapshots/linux/2x/st_chat_input.spec.js/chatInput.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#6877 Make Chat Input remain opaque when stale
  frontend/src/lib/components/core/Block/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#6812 add datetime hashing for st.cache_data and st.cache_resource
  lib/streamlit/runtime/caching/hashing.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed, change:feature, impact:users

#6880 Change API from participant to name
  frontend/src/lib/components/elements/ChatMessage/ChatMessage.test.tsx
  frontend/src/lib/components/elements/ChatMessage/ChatMessage.tsx
  lib/streamlit/elements/chat.py
  lib/tests/streamlit/elements/chat_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#6884 Ensure script cache is cleared before the script is rerun if necessary
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/runtime.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#6834 Do not rerun when a url contains an anchor
  frontend/src/app/App.test.tsx
  frontend/src/app/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#6847 Add more correct out of bounds checks for min_value and max_value for st.number_input
  lib/streamlit/elements/number_input.py
  lib/tests/streamlit/elements/number_input_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#6886 Expose script timeout in testing API
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:feature, impact:users

#6885 Fix a bunch of type errors
  frontend/src/app/connection/DefaultStreamlitEndpoints.ts
  frontend/src/lib/FileUploadClient.ts
  frontend/src/lib/StreamlitEndpoints.ts
  frontend/src/lib/StreamlitLib.test.tsx
  frontend/src/lib/components/widgets/CameraInput/CameraInput.tsx
  frontend/src/lib/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/src/lib/components/widgets/FileUploader/FileUploader.tsx
  frontend/src/lib/components/widgets/FileUploader/UploadFileInfo.ts
  frontend/src/lib/components/widgets/FileUploader/UploadedFile.test.tsx
  proto/streamlit/proto/Common.proto
Labels: security-assessment-completed, impact:internal, change:feature

#6826 Add color_util.py, which will be used by native charts in next few PRs.
  lib/streamlit/color_util.py
  lib/streamlit/errors.py
  lib/tests/streamlit/color_util_test.py
Labels: security-assessment-completed, change:other, impact:internal

#6828 Delay slider `thumbValueAlignment` to allow page layout to complete
  e2e/scripts/st_select_slider.py
  e2e/specs/st_select_slider.spec.js
  e2e/specs/st_slider.spec.js
  frontend/src/lib/components/widgets/Slider/Slider.tsx
Labels: feature:st.slider, security-assessment-completed, change:bugfix, impact:users

#6802 Minimum version dependency testing
  .github/actions/make_init/action.yml
  .github/workflows/python-min-deps.yml
  Makefile
  e2e/scripts/st_arrow_altair_chart.py
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/testing/element_tree.py
  lib/test-requirements.txt
  scripts/check_license_headers.py
  scripts/get_min_versions.py
Labels: security-assessment-completed, impact:internal, change:chore

#6909 Fix protobuf gen in min deps workflow
  .github/workflows/python-min-deps.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#6890 LangChain CallbackHandler
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/external/__init__.py
  lib/streamlit/external/langchain/__init__.py
  lib/streamlit/external/langchain/mutable_expander.py
  lib/streamlit/external/langchain/streamlit_callback_handler.py
  lib/test-requirements.txt
  lib/tests/streamlit/external/__init__.py
  lib/tests/streamlit/external/langchain/__init__.py
  lib/tests/streamlit/external/langchain/capturing_callback_handler.py
  lib/tests/streamlit/external/langchain/streamlit_callback_handler_test.py
  lib/tests/streamlit/external/langchain/test_data/alanis.pickle
Labels: security-assessment-completed, impact:internal, change:feature

#6816 Allow the use of general number types in st.slider
  lib/streamlit/elements/slider.py
  lib/tests/streamlit/elements/slider_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#6842 Bump component-lib version to 2.0.0 and add release notes
  component-lib/RELEASE_NOTES.md
  component-lib/package.json
Labels: security-assessment-completed, impact:internal, change:chore

#6902 Feature/file uploader file urls
  frontend/src/lib/FileUploadClient.ts
  frontend/src/lib/components/widgets/CameraInput/CameraInput.tsx
  frontend/src/lib/components/widgets/FileUploader/FileUploader.tsx
  frontend/src/lib/components/widgets/FileUploader/UploadFileInfo.ts
  lib/streamlit/elements/camera_input.py
  lib/streamlit/elements/file_uploader.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/uploaded_file_manager.py
  proto/streamlit/proto/Common.proto
Labels: security-assessment-completed, change:feature, impact:users

#6891 Start work on fixing file uploader and camera input e2e tests
  e2e/specs/st_file_uploader.spec.js
  frontend/src/lib/components/widgets/CameraInput/CameraInput.tsx
  frontend/src/lib/components/widgets/FileUploader/FileUploader.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#6915 Fix styler support for data editor
  lib/streamlit/elements/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#6924 Strong typing for `withExpandable` HOC
  frontend/src/lib/components/core/Block/Block.tsx
  frontend/src/lib/hocs/withExpandable/withExpandable.test.tsx
  frontend/src/lib/hocs/withExpandable/withExpandable.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#5375 modify st.echo to use ast to handle indenting properly
  lib/streamlit/echo.py
  lib/tests/streamlit/echo_test_data/multiline_param_echo.py
  lib/tests/streamlit/elements/echo_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#6905 Up version to 1.24.0
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore
