Repository streamlit/streamlit, pull requests merged in 2023-01, with the labels that each got.

#5904 Fix type issues for classes from Watchdog
  lib/streamlit/watcher/event_based_path_watcher.py
Labels: security-assessment-completed

#5876 Singleton: `validate` support
  lib/streamlit/runtime/caching/singleton_decorator.py
  lib/tests/streamlit/runtime/caching/singleton_test.py
Labels: security-assessment-completed

#5906 Use new annotations features in session state module
  lib/streamlit/runtime/state/session_state.py
Labels: security-assessment-completed

#5896 Deduplicate FE packages
  NOTICES
  frontend/yarn.lock
Labels: security-assessment-completed

#5907 st.memo: `persist` can take True or False
  lib/streamlit/runtime/caching/memo_decorator.py
  lib/tests/streamlit/runtime/caching/memo_test.py
Labels: security-assessment-completed

#5905 Rename runtime session methods
  lib/streamlit/runtime/runtime.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/web/server/browser_websocket_handler_test.py
Labels: security-assessment-completed

#5910 cache_data/resource: rearrange kwargs; remove `suppress_st_warning`
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
Labels: security-assessment-completed

#5909 Update Minor dependencies - Part A
  NOTICES
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed

#5912 Update Minor devDependencies - Part A
  NOTICES
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed

#5892 Revert SCRIPT_RUN_FINISHED signal changes, add window.prerenderReady
  frontend/public/index.html
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/hocs/withHostCommunication/types.ts
Labels: security-assessment-completed

#5836 Made very minor change to comment.
  frontend/src/urls.ts
Labels: security-assessment-completed

#5890 Update source_util.get_pages
  lib/streamlit/source_util.py
  lib/tests/streamlit/source_util_test.py
Labels: security-assessment-completed

#5914 Update Minor devDependencies - Part B
  frontend/package.json
  frontend/src/lib/test_util.tsx
  frontend/src/theme/utils.ts
  frontend/yarn.lock
Labels: security-assessment-completed

#5913 Fix slider overlap values for ranges
  e2e/scripts/st_slider.py
  e2e/specs/st_slider.spec.js
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/expander_thumb_value_in_range-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/expander_thumb_value_in_range.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/long_thumb_value_in_range-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_slider.spec.js/long_thumb_value_in_range.snap.png
  frontend/src/components/widgets/Slider/Slider.tsx
Labels: security-assessment-completed

#5919 Deprecate `st.cache`
  lib/streamlit/deprecation_util.py
  lib/streamlit/hello/pages/2_Mapping_Demo.py
  lib/streamlit/hello/pages/3_DataFrame_Demo.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_type.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/tests/streamlit/elements/cache_spinner_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/legacy_caching/caching_test.py
Labels: security-assessment-completed

#5894 Add Iframe resizing ability
  NOTICES
  e2e/scripts/iframe_resizer.py
  e2e/specs/iframe_resizer.spec.js
  frontend/cypress/assets/iframed_streamlit.html
  frontend/cypress/assets/vendor/iframerResizer.min.js
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/embedded_iframe_expanded.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_expanded.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_with_min_height.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_with_min_height_expanded.snap.png
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_code.spec.js/syntax_highlighting.snap.png
  frontend/cypress/support/commands.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/AppView/AppView.tsx
  frontend/src/components/core/AppView/styled-components.ts
  frontend/src/lib/MetricsManager.test.ts
  frontend/src/lib/utils.ts
  frontend/src/theme/primitives/sizes.ts
  frontend/yarn.lock
Labels: security-assessment-completed

#5924 singleton/memo deprecation - take 2
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
Labels: security-assessment-completed

#5933 Widget overflow fixes
  frontend/src/components/elements/Metric/styled-components.ts
  frontend/src/components/elements/Tabs/Tabs.tsx
  frontend/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed

#5917 Convert widget replay test to test framework
  e2e/specs/cached_widget_replay_dynamic.spec.js
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/test_data/cached_widget_replay_dynamic.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#5921 Update Minor dependencies (and some majors/patches) - Part B
  NOTICES
  e2e/specs/st_tooltips.spec.js
  frontend/cypress/snapshots/linux/2x/st_arrow_bar_chart.spec.js/arrow_bar_chart7-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_bar_chart.spec.js/arrow_bar_chart7.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_pydeck_geo_layers.spec.js/h3-hexagon-layer-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_pydeck_geo_layers.spec.js/h3-hexagon-layer.snap.png
  frontend/package.json
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/yarn.lock
  lib/streamlit/hello/pages/2_Mapping_Demo.py
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed

#5945 "client.showErrorDetails" controls whether deprecation warnings appear in-browser
  lib/streamlit/config.py
  lib/streamlit/deprecation_util.py
  lib/tests/streamlit/deprecation_util_test.py
Labels: security-assessment-completed

#5923 Add all markdown elements to testing framework
  lib/streamlit/elements/markdown.py
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
  proto/streamlit/proto/Markdown.proto
Labels: security-assessment-completed

#5946 Update major dependencies - Part A
  NOTICES
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed

#5950 Up version to 1.17.0
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed

#5959 Allow cypress tests to run when calculations produce 0
  .github/workflows/cypress.yml
Labels: security-assessment-completed

#5955 Add header, subheader and title elements to testing framework
  lib/streamlit/elements/heading.py
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#5960 Github Actions: $PYTHON_MIN_VERSION, $PYTHON_MAX_VERSION
  .github/actions/set_python_versions/action.yml
  .github/workflows/cli-regression.yml
  .github/workflows/cypress.yml
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
  .github/workflows/py-prod-deps-smoke-test.yml
  .github/workflows/python-versions.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: security-assessment-completed

#5958 Python 3.11 support
  .github/actions/set_python_versions/action.yml
  lib/mypy.ini
  lib/test-requirements.txt
  lib/tests/streamlit/dataframe_selector_test.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
  lib/tests/streamlit/write_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed

#5967 FE Dependencies - more minor/patch updates
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed

#5951 Test interface for slider and select_slider
  e2e/scripts/linked_sliders.py
  e2e/specs/linked_sliders.spec.js
  lib/streamlit/elements/select_slider.py
  lib/streamlit/elements/slider.py
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/test_data/linked_sliders.py
  lib/tests/streamlit/testing/element_tree_test.py
  proto/streamlit/proto/Slider.proto
Labels: security-assessment-completed

#5944 Add S3 URL to wheel file as Github status
  .github/workflows/pr-preview.yml
Labels: security-assessment-completed

#5952 Rename the confusingly named SessionState proto type
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/lib/SessionInfo.test.ts
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/ForwardMsg.proto
  proto/streamlit/proto/NewSession.proto
  proto/streamlit/proto/SessionStatus.proto
Labels: security-assessment-completed

#5975 SNOW-667402:Semgrep workflow update
  .github/workflows/semgrep.yml
Labels: security-assessment-completed

#5982 Fix flaky legacy hashing test
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
Labels: security-assessment-completed

#5980 Cache docs URL; updated docstrings
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/legacy_caching/caching_test.py
Labels: security-assessment-completed

#5984 Update S3 URL conditional
  .github/workflows/pr-preview.yml
Labels: security-assessment-completed

#5978 Add docs for unsupported Markdown in element labels
  lib/streamlit/elements/button.py
  lib/streamlit/elements/camera_input.py
  lib/streamlit/elements/checkbox.py
  lib/streamlit/elements/color_picker.py
  lib/streamlit/elements/file_uploader.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/multiselect.py
  lib/streamlit/elements/number_input.py
  lib/streamlit/elements/radio.py
  lib/streamlit/elements/select_slider.py
  lib/streamlit/elements/selectbox.py
  lib/streamlit/elements/slider.py
  lib/streamlit/elements/text_widgets.py
  lib/streamlit/elements/time_widgets.py
Labels: security-assessment-completed

#5534 Rename endpoints
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/FileUploadClient.ts
  frontend/src/lib/WebsocketConnection.test.tsx
  frontend/src/lib/WebsocketConnection.tsx
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/server_util.py
  lib/streamlit/web/server/stats_request_handler.py
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/tests/streamlit/web/server/routes_test.py
  lib/tests/streamlit/web/server/server_test.py
  lib/tests/streamlit/web/server/server_test_case.py
  lib/tests/streamlit/web/server/stats_handler_test.py
  lib/tests/streamlit/web/server/upload_file_request_handler_test.py
Labels: security-assessment-completed

#5971 Add fonts-noto-color-emoji to e2e/Dockerfile
  e2e/Dockerfile
Labels: security-assessment-completed

#5948 @st.cache_data, @st.cache_resource decorators
  lib/streamlit/__init__.py
  lib/streamlit/hello/pages/2_Mapping_Demo.py
  lib/streamlit/hello/pages/3_DataFrame_Demo.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_type.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/web/cli.py
  lib/tests/streamlit/elements/cache_spinner_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/legacy_caching/caching_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed

#5979 Do not show keyboard on `st.selectbox` on mobile if `options < 10`
  frontend/src/components/shared/Dropdown/Selectbox.tsx
  frontend/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed

#5974 Update FE dep major versions - part B
  NOTICES
  frontend/package.json
  frontend/yarn.lock
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed

#5943 Switch to new functioning twemoji url
  e2e/specs/st_set_page_config.spec.js
  frontend/src/components/elements/Favicon/Favicon.test.tsx
  frontend/src/components/elements/Favicon/Favicon.tsx
Labels: security-assessment-completed

#5994 Component key stability tests
  lib/tests/delta_generator_test_case.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/number_input_test.py
Labels: security-assessment-completed

#5991 Security Vulnerability Resolutions
  NOTICES
  frontend/package.json
  frontend/yarn.lock
  lib/Pipfile
  lib/test-requirements-with-tensorflow.txt
  lib/test-requirements.txt
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed

#5999 Fix reStructuredText issues in cache_data and cache_resource docstrings
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
Labels: security-assessment-completed

#5856 Define the SessionManager protocol and improve our websocket reconnect behavior
  e2e/scripts/websocket_reconnects.py
  e2e/specs/websocket_reconnects.spec.js
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/src/lib/ConnectionManager.ts
  frontend/src/lib/SessionInfo.test.ts
  frontend/src/lib/SessionInfo.ts
  frontend/src/lib/WebsocketConnection.test.tsx
  frontend/src/lib/WebsocketConnection.tsx
  lib/streamlit/runtime/__init__.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/memory_session_storage.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/websocket_session_manager.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/memory_session_storage_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/runtime_threading_test.py
  lib/tests/streamlit/runtime/websocket_session_manager_test.py
  lib/tests/streamlit/web/server/browser_websocket_handler_test.py
  lib/tests/streamlit/web/server/server_test.py
  lib/tests/streamlit/web/server/server_test_case.py
  lib/tests/streamlit/web/server/websocket_headers_test.py
Labels: security-assessment-completed

#5997 More major dependency updates - Part C
  NOTICES
  frontend/package.json
  frontend/src/components/elements/CodeBlock/CodeBlock.tsx
  frontend/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/yarn.lock
  scripts/run_e2e_tests.py
Labels: security-assessment-completed

#5928 Upgrade Cypress tests to 8 core GH Action Runners
  .github/workflows/cypress.yml
Labels: security-assessment-completed

#6006 Add Github workflow to produce Cypress snapshots
  .github/workflows/cypress-update-snapshots.yml
Labels: security-assessment-completed

#6012 Rearrange + rename "cached message replay" code
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
Labels: security-assessment-completed

#5973 Selectbox wrapper class implementation for testing framework
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6015 Fix deprecation warning for new health endpoint
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/stats_request_handler.py
  lib/tests/streamlit/web/server/routes_test.py
  lib/tests/streamlit/web/server/stats_handler_test.py
Labels: security-assessment-completed

#6020 Don't install SQLAlchemy 2.0
  lib/test-requirements.txt
Labels: security-assessment-completed

#5990 Move InteractiveScriptTests to main testing module
  lib/streamlit/testing/__init__.py
  lib/streamlit/testing/script_interactions.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/caching/test_data/cached_widget_replay_dynamic.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/runtime/state/test_data/linked_sliders.py
  lib/tests/streamlit/script_interactions_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6024 Handle page_cache in script test setup to remove patch
  lib/streamlit/testing/script_interactions.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/script_interactions_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6017 Cache only once
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
Labels: security-assessment-completed

#6027 Allow pytest unit test to be discoverable via IDE
  lib/tests/conftest.py
Labels: security-assessment-completed

#6031 Upgrade isort to 5.11.5
  .pre-commit-config.yaml
Labels: type:bug, security-assessment-completed

#6001 Adds option Print to the app’s hamburger menu
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_main_menu.spec.js/main_menu.snap.png
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/core/MainMenu/MainMenu.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/lib/utils.ts
Labels: type:enhancement, security-assessment-completed

#6023 Add improvements to quiver
  frontend/src/lib/Quiver.test.ts
  frontend/src/lib/Quiver.ts
  frontend/src/lib/mocks/arrow/index.ts
  frontend/src/lib/mocks/arrow/namedIndex.ts
  frontend/src/lib/mocks/arrow/types/categoricalColumn.ts
  frontend/src/lib/mocks/arrow/types/decimal.ts
  frontend/src/lib/mocks/arrow/types/dictionary.ts
Labels: security-assessment-completed

#6026 Improve dataframe handling utils
  lib/streamlit/type_util.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed

#6039 Add display: none to hamburger menu when printing
  frontend/src/components/core/MainMenu/styled-components.ts
Labels: type:bug, security-assessment-completed
