Repository streamlit/streamlit, pull requests merged in 2023-03, with the labels that each got.

#6143 Clearly state we don't guarantee Streamlit's mapbox token will work indefinitely
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/map.py
Labels: feature:st.pydeck_chart, feature:st.map, security-assessment-completed

#6202 Fixate pandas version <2
  lib/setup.py
Labels: security-assessment-completed

#6200 Enable fastReruns by default
  lib/streamlit/config.py
Labels: security-assessment-completed

#6052 Cache storage abstraction
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/storage/__init__.py
  lib/streamlit/runtime/caching/storage/cache_storage_protocol.py
  lib/streamlit/runtime/caching/storage/dummy_cache_storage.py
  lib/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py
  lib/streamlit/runtime/caching/storage/local_disk_cache_storage.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/stats.py
  lib/streamlit/testing/script_interactions.py
  lib/streamlit/web/cache_storage_manager_config.py
  lib/streamlit/web/cli.py
  lib/streamlit/web/server/server.py
  lib/tests/delta_generator_test_case.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_utils_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/caching/storage/__init__.py
  lib/tests/streamlit/runtime/caching/storage/dummy_cache_storage_test.py
  lib/tests/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper_test.py
  lib/tests/streamlit/runtime/caching/storage/local_disk_cache_storage_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/runtime_threading_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed

#6213 List `str` as supported type for `show_spinner` in cache data docs
  lib/streamlit/runtime/caching/cache_data_api.py
Labels: feature:cache, type:docs, security-assessment-completed

#6219 Pin altair version to <5
  lib/setup.py
Labels: security-assessment-completed

#6210 Fix retrieving messages from the server's ForwardMsgCache
  e2e/scripts/forward_msg_cache.py
  e2e/specs/forward_msg_cache.spec.js
  frontend/src/App.tsx
  frontend/src/lib/ForwardMessageCache.test.ts
  frontend/src/lib/ForwardMessageCache.ts
Labels: security-assessment-completed

#6212 Make ping and websocket timeouts far more forgiving
  frontend/src/lib/WebsocketConnection.tsx
Labels: security-assessment-completed

#6059 Update ALLOWED_MESSAGE_ORIGINS to include address used for local development
  lib/streamlit/web/server/routes.py
Labels: security-assessment-completed

#6240 Remove unused "StyledForm" div
  frontend/src/components/core/Block/styled-components.ts
Labels: security-assessment-completed

#6239 [Snyk] Security upgrade vega from 5.22.1 to 5.23.0
  NOTICES
  frontend/package.json
  frontend/yarn.lock
Labels: area:security, security-assessment-completed

#6217 `CachedStFunctionWarning` should include `experimental_allow_widgets`, not `suppress_st_warning`
  lib/streamlit/runtime/caching/cache_errors.py
Labels: feature:cache, security-assessment-completed

#6232 Use HTTPS to load external resources in the hello demo
  lib/streamlit/hello/pages/2_Mapping_Demo.py
  lib/streamlit/hello/pages/3_DataFrame_Demo.py
Labels: security-assessment-completed

#6241 MetricsManager: de-singleton, interface-ize
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.test.tsx
  frontend/src/components/core/MainMenu/MainMenu.tsx
  frontend/src/components/core/StreamlitDialog/SettingsDialog.test.tsx
  frontend/src/components/core/StreamlitDialog/SettingsDialog.tsx
  frontend/src/lib/AppNode.test.ts
  frontend/src/lib/AppNode.ts
  frontend/src/lib/MetricsManager.ts
  frontend/src/lib/MetricsManagerTestUtils.ts
  frontend/src/lib/SegmentMetricsManager.test.ts
  frontend/src/lib/SegmentMetricsManager.ts
Labels: security-assessment-completed

#6088 Avoid showing emoji on non-UTF-8 terminals.
  lib/streamlit/runtime/credentials.py
  lib/tests/streamlit/runtime/credentials_test.py
Labels: security-assessment-completed

#6043 Add support for tooltips on text elements
  e2e/scripts/st_tooltips_2.py
  e2e/specs/st_tooltips_2.spec.js
  e2e/specs/typography.spec.js
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipCaption.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipHeader.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipLatex.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipMarkdown.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipSubheader.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipText.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipTitle.snap.png
  frontend/src/components/elements/Markdown/Markdown.test.tsx
  frontend/src/components/elements/Markdown/Markdown.tsx
  frontend/src/components/elements/Text/Text.test.tsx
  frontend/src/components/elements/Text/Text.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/src/components/shared/Tooltip/Tooltip.tsx
  frontend/src/components/shared/TooltipIcon/TooltipIcon.tsx
  frontend/src/components/shared/TooltipIcon/index.tsx
  frontend/src/components/shared/TooltipIcon/styled-components.ts
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/text.py
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/Heading.proto
  proto/streamlit/proto/Markdown.proto
  proto/streamlit/proto/Text.proto
Labels: security-assessment-completed

#6171 Move typecheck and eslint to manual stage of pre-commit
  .github/workflows/js-tests.yml
  .pre-commit-config.yaml
Labels: security-assessment-completed

#6211 Stop waiting for a browser to connect before opening a new tab
  frontend/src/lib/WebsocketConnection.tsx
  lib/streamlit/web/bootstrap.py
Labels: security-assessment-completed

#6263 Fix mypy cache data api and script runner
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
Labels: security-assessment-completed

#6273 Fix `make tstypecheck`
  Makefile
Labels: security-assessment-completed

#6205 Enable no-else-return rule in ESLint
  frontend/.eslintrc
Labels: security-assessment-completed

#6071 Add step parameter to st.time_input
  frontend/src/components/widgets/TimeInput/TimeInput.test.tsx
  frontend/src/components/widgets/TimeInput/TimeInput.tsx
  lib/streamlit/elements/time_widgets.py
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/TimeInput.proto
Labels: security-assessment-completed

#6275 `withMapboxToken`: add types
  frontend/src/hocs/withMapboxToken/withMapboxToken.test.tsx
  frontend/src/hocs/withMapboxToken/withMapboxToken.tsx
Labels: security-assessment-completed

#6067 Allow control of st.pyplot() width
  e2e/scripts/st_pyplot.py
  e2e/specs/st_pyplot.spec.js
  frontend/cypress/snapshots/linux/2x/st_pyplot.spec.js/pyplot-check-if-cleared.snap.png
  lib/streamlit/elements/image.py
  lib/streamlit/elements/pyplot.py
  lib/tests/streamlit/elements/pyplot_test.py
Labels: security-assessment-completed

#6285 `withFullscreenWrapper`: types
  frontend/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/src/components/elements/VegaLiteChart/VegaLiteChart.tsx
  frontend/src/hocs/withFullScreenWrapper/withFullScreenWrapper.test.tsx
  frontend/src/hocs/withFullScreenWrapper/withFullScreenWrapper.tsx
Labels: security-assessment-completed

#6283 Support `st.exception` in testing framework
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6294 SessionInfo: de-singleton-ify
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/AppView/AppView.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/components/core/Block/utils.ts
  frontend/src/components/core/StreamlitDialog/StreamlitDialog.test.tsx
  frontend/src/components/core/StreamlitDialog/StreamlitDialog.tsx
  frontend/src/hocs/withMapboxToken/MapboxToken.test.ts
  frontend/src/hocs/withMapboxToken/MapboxToken.ts
  frontend/src/hocs/withMapboxToken/withMapboxToken.test.tsx
  frontend/src/hocs/withMapboxToken/withMapboxToken.tsx
  frontend/src/lib/ConnectionManager.ts
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/FileUploadClient.ts
  frontend/src/lib/HttpClient.test.ts
  frontend/src/lib/MetricsManagerTestUtils.ts
  frontend/src/lib/SegmentMetricsManager.test.ts
  frontend/src/lib/SegmentMetricsManager.ts
  frontend/src/lib/SessionInfo.test.ts
  frontend/src/lib/SessionInfo.ts
  frontend/src/lib/WebsocketConnection.test.tsx
  frontend/src/lib/WebsocketConnection.tsx
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6281 Fix pre commit regex
  .pre-commit-config.yaml
Labels: security-assessment-completed

#6270 Refactoring App.test.tsx
  frontend/src/App.test.tsx
Labels: security-assessment-completed

#6266 Skip pushing a new history if the new page hash is the same as the current one
  frontend/src/App.test.tsx
  frontend/src/App.tsx
Labels: security-assessment-completed

#6286 withScreencast, withHostCommunication: types
  frontend/src/hocs/withHostCommunication/withHostCommunication.test.tsx
  frontend/src/hocs/withHostCommunication/withHostCommunication.tsx
  frontend/src/hocs/withScreencast/withScreencast.test.tsx
  frontend/src/hocs/withScreencast/withScreencast.tsx
Labels: security-assessment-completed

#6300 Activate the no-unused-vars rule in eslint.
  frontend/.eslintrc
  frontend/src/components/core/AppContext/index.tsx
  frontend/src/components/core/Header/styled-components.ts
  frontend/src/components/core/MainMenu/styled-components.ts
  frontend/src/components/core/Maybe/Maybe.tsx
  frontend/src/components/core/Sidebar/styled-components.ts
  frontend/src/components/core/StatusWidget/StatusWidget.tsx
  frontend/src/components/core/StatusWidget/styled-components.ts
  frontend/src/components/core/StreamlitDialog/styled-components.ts
  frontend/src/components/core/ToolbarActions/ToolbarActions.test.tsx
  frontend/src/components/core/ToolbarActions/ToolbarActions.tsx
  frontend/src/components/core/ToolbarActions/styled-components.ts
  frontend/src/components/elements/ImageList/styled-components.ts
  frontend/src/components/elements/VegaLiteChart/VegaLiteChart.tsx
  frontend/src/components/shared/ColorPicker/ColorPicker.tsx
  frontend/src/components/shared/ColorPicker/styled-components.ts
  frontend/src/components/shared/ErrorBoundary/ErrorBoundary.tsx
  frontend/src/components/shared/ProgressBar/ProgressBar.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/src/components/shared/TooltipIcon/styled-components.ts
  frontend/src/components/widgets/CameraInput/styled-components.ts
  frontend/src/components/widgets/Checkbox/styled-components.tsx
  frontend/src/components/widgets/DataFrame/hooks/useDataEditor.test.ts
  frontend/src/components/widgets/FileUploader/styled-components.ts
  frontend/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/src/components/widgets/TextInput/styled-components.ts
  frontend/src/hocs/withHostCommunication/withHostCommunication.test.tsx
  frontend/src/hocs/withScreencast/components/UnsupportedBrowserDialog/styled-components.ts
  frontend/src/lib/AppNode.ts
Labels: security-assessment-completed

#6307 Pull ComponentRegistry's URL generation into an interface
  frontend/src/App.tsx
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/src/components/widgets/CustomComponent/ComponentRegistry.test.ts
  frontend/src/components/widgets/CustomComponent/ComponentRegistry.ts
  frontend/src/components/widgets/CustomComponent/StreamlitComponentEndpoint.test.ts
  frontend/src/components/widgets/CustomComponent/StreamlitComponentEndpoint.ts
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6220 ASCII diagrams for CacheStorage*, and for LocalDiskCacheStorage
  lib/streamlit/runtime/caching/storage/cache_storage_protocol.py
  lib/streamlit/runtime/caching/storage/local_disk_cache_storage.py
Labels: security-assessment-completed

#6312 Fix timeout on label-markdown e2e test
  e2e/specs/label_markdown.spec.js
Labels: security-assessment-completed

#6315 Fix: File Uploader's File Selection Dialog limits available extensions
  frontend/src/components/widgets/FileUploader/FileDropzone.tsx
Labels: security-assessment-completed

#6222 Minor documentation fixes for cache storage
  lib/streamlit/runtime/caching/storage/cache_storage_protocol.py
  lib/streamlit/runtime/caching/storage/local_disk_cache_storage.py
Labels: security-assessment-completed

#6306 Deploy nightly build to core-previews
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
Labels: security-assessment-completed

#6314 Make using @ts-ignore illegal
  frontend/.eslintrc
Labels: security-assessment-completed

#6321 Fix issue #6310
  lib/streamlit/runtime/caching/storage/local_disk_cache_storage.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/storage/local_disk_cache_storage_test.py
Labels: security-assessment-completed

#6323 FileUploadClient: interface-ize endpoint
  frontend/src/App.tsx
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/src/components/widgets/CustomComponent/ComponentRegistry.test.ts
  frontend/src/components/widgets/CustomComponent/ComponentRegistry.ts
  frontend/src/components/widgets/CustomComponent/StreamlitComponentEndpoint.test.ts
  frontend/src/components/widgets/CustomComponent/StreamlitComponentEndpoint.ts
  frontend/src/lib/DefaultStreamlitEndpoints.test.ts
  frontend/src/lib/DefaultStreamlitEndpoints.ts
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/FileUploadClient.ts
  frontend/src/lib/HttpClient.test.ts
  frontend/src/lib/HttpClient.ts
  frontend/src/lib/StreamlitEndpoints.ts
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6271 Add an event handler for popstate event to reflect user's back button…
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/lib/utils.ts
Labels: security-assessment-completed

#6326 ForwardMessageCache: interface-ize endpoint
  frontend/src/App.tsx
  frontend/src/lib/ConnectionManager.ts
  frontend/src/lib/DefaultStreamlitEndpoints.test.ts
  frontend/src/lib/DefaultStreamlitEndpoints.ts
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/ForwardMessageCache.test.ts
  frontend/src/lib/ForwardMessageCache.ts
  frontend/src/lib/StreamlitEndpoints.ts
  frontend/src/lib/WebsocketConnection.test.tsx
  frontend/src/lib/WebsocketConnection.tsx
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6158 Add ability to turn off anchors
  e2e/scripts/st_heading.py
  e2e/specs/st_heading.spec.js
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  lib/streamlit/elements/heading.py
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/elements/heading_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/testing/element_tree_test.py
  proto/streamlit/proto/Heading.proto
Labels: security-assessment-completed

#6248 Add support for number and boolean types in categorical columns
  frontend/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/src/components/widgets/DataFrame/columns/BooleanColumn.ts
  frontend/src/components/widgets/DataFrame/columns/CategoricalColumn.test.ts
  frontend/src/components/widgets/DataFrame/columns/CategoricalColumn.ts
  frontend/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed

#6230 Allow users to set a secrets.toml file in their home directory
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/secrets.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/secrets_test.py
Labels: security-assessment-completed

#6343 Tweak no-else-return config options
  frontend/.eslintrc
  frontend/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed

#6345 sendMessageToHost: no longer a global function
  frontend/src/App.tsx
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/AppView/AppView.tsx
  frontend/src/components/elements/Favicon/Favicon.test.tsx
  frontend/src/components/elements/Favicon/Favicon.tsx
  frontend/src/hocs/withHostCommunication/index.tsx
  frontend/src/hocs/withHostCommunication/withHostCommunication.tsx
Labels: security-assessment-completed

#6353 AppContext docstrings
  frontend/src/App.tsx
  frontend/src/components/core/AppContext.tsx
  frontend/src/components/core/AppView/AppView.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/components/core/Header/Header.tsx
  frontend/src/components/core/Sidebar/SidebarNav.tsx
  frontend/src/components/core/Sidebar/ThemedSidebar.tsx
  frontend/src/components/core/StreamlitDialog/SettingsDialog.tsx
  frontend/src/components/core/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/src/components/elements/Audio/Audio.tsx
  frontend/src/components/elements/ImageList/ImageList.tsx
  frontend/src/components/elements/Spinner/Spinner.tsx
  frontend/src/components/elements/Video/Video.tsx
  frontend/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/src/components/shared/ProgressBar/ProgressBar.tsx
  frontend/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/src/components/widgets/DownloadButton/DownloadButton.tsx
Labels: security-assessment-completed

#6331 Add `.webp` to list of safe static file extensions
  lib/streamlit/web/server/app_static_file_handler.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
Labels: security-assessment-completed

#6333 Return whether a secrets.toml file is successfully parsed
  lib/streamlit/runtime/secrets.py
  lib/tests/streamlit/runtime/secrets_test.py
Labels: security-assessment-completed

#6332 Add a skeleton implementation of st.experimental_connection
  lib/streamlit/__init__.py
  lib/streamlit/connections/__init__.py
  lib/streamlit/connections/base_connection.py
  lib/streamlit/runtime/connection_factory.py
  lib/tests/streamlit/runtime/connection_factory_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed

#6358 Have util.calc_md5 also take bytes
  lib/streamlit/util.py
  lib/tests/streamlit/util_test.py
Labels: security-assessment-completed

#6348 Fix regression with query_params
  lib/streamlit/commands/query_params.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed

#6364 FullScreenWrapper: add a type declaration for react context usage
  frontend/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
Labels: security-assessment-completed

#6361 Set a default for RuntimeConfig.cache_storage_manager
  lib/streamlit/runtime/runtime.py
  lib/tests/streamlit/runtime/runtime_test.py
Labels: security-assessment-completed

#6366 StreamlitEndpoints.buildMediaURL
  frontend/src/App.tsx
  frontend/src/components/core/AppView/AppView.test.tsx
  frontend/src/components/core/AppView/AppView.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/components/core/Block/utils.ts
  frontend/src/components/elements/Audio/Audio.test.tsx
  frontend/src/components/elements/Audio/Audio.tsx
  frontend/src/lib/DefaultStreamlitEndpoints.test.ts
  frontend/src/lib/DefaultStreamlitEndpoints.ts
  frontend/src/lib/FileUploadClient.test.ts
  frontend/src/lib/ForwardMessageCache.test.ts
  frontend/src/lib/StreamlitEndpoints.ts
  frontend/src/lib/UriUtil.ts
  frontend/src/lib/mocks/mocks.ts
Labels: security-assessment-completed

#6165 Allow session state to only allow serializable items
  lib/streamlit/config.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/runtime/state/session_state.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
Labels: security-assessment-completed

#6374 Allow pytest unit test to be discoverable via IDE v2
  lib/tests/conftest.py
Labels: security-assessment-completed

#6379 Remove UriUtil.buildMediaUri
  frontend/src/App.tsx
  frontend/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/src/components/elements/Favicon/Favicon.test.tsx
  frontend/src/components/elements/Favicon/Favicon.tsx
  frontend/src/components/elements/ImageList/ImageList.test.tsx
  frontend/src/components/elements/ImageList/ImageList.tsx
  frontend/src/components/elements/Video/Video.test.tsx
  frontend/src/components/elements/Video/Video.tsx
  frontend/src/components/elements/Video/__snapshots__/Video.test.tsx.snap
  frontend/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/src/lib/UriUtil.test.ts
  frontend/src/lib/UriUtil.ts
Labels: security-assessment-completed

#6378 Add support for Pandas 2.0
  e2e/scripts/st_arrow_table.py
  frontend/cypress/snapshots/linux/2x/st_data_editor_input_data.spec.js/data_editor-input-data-17.snap.png
  lib/streamlit/elements/legacy_data_frame.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/legacy_data_frame_test.py
Labels: security-assessment-completed

#6371 Improve typing annotations for file_uploader and text_input
  lib/streamlit/elements/file_uploader.py
  lib/streamlit/elements/text_widgets.py
Labels: security-assessment-completed

#6392 Rename query param ?testing to ?_stcore_testing
  e2e/scripts/deploy_button.py
  e2e/specs/deploy_button.spec.js
  frontend/src/lib/utils.ts
Labels: security-assessment-completed

#6387 Add AttrDict.to_dict()
  lib/streamlit/runtime/secrets.py
  lib/tests/streamlit/runtime/secrets_test.py
Labels: security-assessment-completed

#6399 Fix https tests by changing port
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed

#6380 TextInput and TextArea testing classes
  lib/streamlit/testing/element_tree.py
  lib/streamlit/testing/script_interactions.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed

#6360 Relax session reconnect asserts
  lib/streamlit/runtime/websocket_session_manager.py
  lib/tests/streamlit/runtime/websocket_session_manager_test.py
Labels: security-assessment-completed

#6382 Embed example apps in `st.help` docstring
  lib/streamlit/elements/doc_string.py
Labels: type:docs, security-assessment-completed, feature:st.help

#6397 Prepare support for pandas styler in data editor
  frontend/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/src/components/widgets/DataFrame/arrowUtils.ts
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed

#6393 Implement host->guest postMessage to update theme details
  frontend/hostframe.html
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/ThemedApp.test.tsx
  frontend/src/ThemedApp.tsx
  frontend/src/components/core/FontFaceDeclaration/FontFaceDeclaration.tsx
  frontend/src/components/core/FontFaceDeclaration/index.tsx
  frontend/src/components/widgets/Checkbox/Checkbox.tsx
  frontend/src/components/widgets/NumberInput/styled-components.ts
  frontend/src/hocs/withHostCommunication/types.ts
  frontend/src/hocs/withHostCommunication/withHostCommunication.test.tsx
  frontend/src/hocs/withHostCommunication/withHostCommunication.tsx
  frontend/src/theme/baseTheme/themeColors.ts
  frontend/src/theme/globalStyles.ts
  frontend/src/theme/utils.ts
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed

#6407 fix ThemedApp and PlotlyChart eslint warnings
  frontend/src/ThemedApp.tsx
  frontend/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/src/components/widgets/DataFrame/hooks/useTableSizer.ts
Labels: security-assessment-completed

#6375 SVG image from e2e tests render in Firefox
  e2e/scripts/st_image.py
Labels: security-assessment-completed
