Repository streamlit/streamlit, pull requests merged in 2023-09, with the labels that each got.

#7183 Remove deprecated usage of inline SVG
  NOTICES
  e2e/scripts/st_image.py
  e2e/scripts/st_image_replay.py
  e2e/specs/st_image.spec.js
  e2e/specs/st_image_replay.spec.js
  e2e/specs/st_image_svg_sizing.spec.js
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/cypress/snapshots/linux/2x/st_image.spec.js/karriebear-avatar.snap.png
  frontend/cypress/snapshots/linux/2x/st_image.spec.js/svg-image-11.snap.png
  frontend/cypress/snapshots/linux/2x/st_image.spec.js/svg-image-12.snap.png
  frontend/cypress/snapshots/linux/2x/st_image_replay.spec.js/karriebear-avatar.snap 2.png
  frontend/cypress/snapshots/linux/2x/st_image_replay.spec.js/karriebear-avatar.snap.png
  frontend/lib/package.json
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/util/UriUtil.test.ts
  frontend/lib/src/util/UriUtil.ts
  frontend/yarn.lock
  lib/streamlit/elements/image.py
  lib/streamlit/elements/widgets/chat.py
  lib/tests/streamlit/elements/image_test.py
  proto/streamlit/proto/Image.proto
Labels: security-assessment-completed, change:refactor, impact:users

#7257 Fix: Handle `start_time` changes in `st.video`
  e2e/scripts/st_video.py
  e2e/specs/st_video.spec.js
  frontend/cypress/snapshots/linux/2x/st_video.spec.js/video-updated-start.snap.png
  frontend/lib/src/components/elements/Video/Video.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7164 Scatter chart
  e2e/scripts/st_arrow_scatter_chart.py
  e2e/specs/st_arrow_scatter_chart.spec.js
  frontend/cypress/snapshots/linux/2x/st_arrow_bar_chart.spec.js/arrow_bar_chart7.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_align_color_and_few_sizes-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_align_color_and_few_sizes.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_align_color_and_many_sizes-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_align_color_and_many_sizes.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_align_quant_color_and_size-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_align_quant_color_and_size.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_no_data-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_no_data.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_snowpark-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_scatter_chart.spec.js/arrow_scatter_chart_snowpark.snap.png
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  lib/streamlit/__init__.py
  lib/streamlit/elements/altair_utils.py
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/legacy_altair.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/arrow_add_rows_test.py
  lib/tests/streamlit/elements/arrow_altair_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#7178 Add config options to configure magic for other Snowflake surfaces, and also add support for magic in methods
  lib/streamlit/config.py
  lib/streamlit/config_util.py
  lib/streamlit/runtime/scriptrunner/magic.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/scriptrunner/magic_test.py
Labels: security-assessment-completed, QA-Done, impact:internal, change:feature

#7268 Increase tzlocal upper bound
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#7267 Remove unused information from error message
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/tests/streamlit/web/server/upload_file_request_handler_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7272 Migrate settings dialog test to RTL
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/__snapshots__/SettingsDialog.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7258 Move `st.rerun` out of experimental
  e2e/scripts/st_rerun.py
  e2e/specs/st_rerun.spec.js
  lib/streamlit/__init__.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/runtime/state/session_state.py
  lib/tests/streamlit/rerun_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:breaking, impact:users

#7280 Catch KeyError exceptions within Compact Session State
  lib/streamlit/runtime/state/session_state.py
  lib/tests/streamlit/runtime/state/session_state_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7233 Make the Streamlit frontend play nicely with CSPs
  frontend/lib/package.json
  frontend/lib/src/RootStyleProvider.tsx
  frontend/lib/src/assets/css/vega-embed.css
  frontend/lib/src/assets/css/vega-embed.scss
  frontend/lib/src/assets/css/vega-tooltip.css
  frontend/lib/src/assets/css/vega-tooltip.scss
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/VegaLiteChart/VegaLiteChart.tsx
Labels: security-assessment-completed, impact:internal, change:feature

#7213 Add description in docstring on how to remove progress bar
  lib/streamlit/elements/progress.py
Labels: type:docs, security-assessment-completed, impact:internal, change:docs

#7151 Use `target="_self"` and `download` attribute for download button
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
Labels: security-assessment-completed, change:chore, impact:users

#7304 Fix deploy cards radius
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployCard.tsx
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_dialog_opened-dark.snap.png
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_dialog_opened.snap.png
Labels: security-assessment-completed, change:bugfix, impact:users

#7295 Simplify internal storage and use of client state
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/testing/local_script_runner.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#7307 Add id to map api
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/map_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7297 Fix: Sidebar covers header decoration line
  e2e/specs/st_expander.spec.js
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-sidebar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-sidebar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-sidebar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-sidebar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-sidebar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/expanders-in-sidebar[light_theme-webkit].png
  frontend/app/src/components/Header/Header.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/cypress/snapshots/linux/2x/st_expander.spec.js/expanders-in-sidebar-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_expander.spec.js/expanders-in-sidebar.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo.snap.png
Labels: security-assessment-completed, change:bugfix, impact:users

#7287 Fix: `st.tabs` selected tab logic
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-change-all-names[chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-change-all-names[firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-change-all-names[webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-change-some-names[chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-change-some-names[firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-change-some-names[webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-default[chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-default[firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-default[webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-remove-selected[chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-remove-selected[firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-remove-selected[webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-selection-add-tab[chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-selection-add-tab[firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-selection-add-tab[webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-selection-remove-tab[chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-selection-remove-tab[firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_selection_test/tabs-selection-remove-tab[webkit].png
  e2e_playwright/st_tabs_selection.py
  e2e_playwright/st_tabs_selection_test.py
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7291 Fix: Preload custom fonts to reduce FOUT
  e2e/specs/hostframe.spec.js
  frontend/app/public/index.html
  frontend/app/src/FontPreload.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7306 Add `st.code` and `st.link_button` to NONWIDGET_ELEMENTS list
  lib/streamlit/elements/__init__.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#7316 Exclude download_button data from the list of arguments for computing…
  e2e/scripts/st_download_button.py
  e2e/specs/st_download_button.spec.js
  lib/streamlit/elements/widgets/button.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#7283 Fix trigger resets with fast reruns
  lib/streamlit/runtime/state/session_state.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7310 Fix: Update `st.tabs` visuals to make stale tabs more obvious
  frontend/lib/src/components/elements/Tabs/Tabs.test.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7326 Fix JS Tests github actions
  .nvmrc
Labels: security-assessment-completed, impact:internal, change:chore

#7320 StreamlitDialog RTL Migration
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/__snapshots__/StreamlitDialog.test.tsx.snap
  frontend/lib/src/components/shared/Modal/Modal.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7330 Fix flaky playwright `st.code` test
  e2e_playwright/__snapshots__/linux/st_code_test/expander_with_code[chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/expander_with_code[firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/expander_with_code[webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/expander_with_markdown_code[chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/expander_with_markdown_code[firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/expander_with_markdown_code[webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_markdown-code_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_markdown-code_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_markdown-code_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_markdown-code_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_markdown-code_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_markdown-code_block[light_theme-webkit].png
  e2e_playwright/st_code.py
  e2e_playwright/st_code_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7323 Text Element RTL Migration
  frontend/lib/src/components/elements/TextElement/TextElement.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7324 AlertContainer RTL Migration
  frontend/lib/src/components/shared/AlertContainer/AlertContainer.test.tsx
  frontend/lib/src/components/shared/AlertContainer/AlertContainer.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7333 Upgrade playwright to use 16 cores
  .github/workflows/playwright.yml
Labels: security-assessment-completed, change:other, impact:internal

#7332 Migrate arrowTable to RTL
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.test.tsx
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7319 Dataframe RTL Migration
  frontend/lib/src/components/widgets/DataFrame/DataFrame.test.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7286 Finalize `None` as initial value
  e2e_playwright/__snapshots__/linux/st_date_input_test/date_input-value_from_state[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/date_input-value_from_state[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/date_input-value_from_state[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/date_input-value_from_state[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/date_input-value_from_state[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/date_input-value_from_state[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-clearable_input[chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-clearable_input[firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-clearable_input[webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-input_instructions[chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-input_instructions[firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-input_instructions[webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-value_none[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-value_none[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-value_none[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-value_none[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-value_none[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-value_none[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-clearable_input[chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-clearable_input[firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-clearable_input[webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-empty_selection[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-empty_selection[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-empty_selection[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-empty_selection[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-empty_selection[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-empty_selection[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-value_from_state[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-value_from_state[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-value_from_state[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-value_from_state[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-value_from_state[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-value_from_state[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-value_from_state[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-value_from_state[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-value_from_state[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-value_from_state[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-value_from_state[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-value_from_state[light_theme-webkit].png
  e2e_playwright/st_date_input.py
  e2e_playwright/st_date_input_test.py
  e2e_playwright/st_number_input.py
  e2e_playwright/st_number_input_test.py
  e2e_playwright/st_radio.py
  e2e_playwright/st_radio_test.py
  e2e_playwright/st_selectbox.py
  e2e_playwright/st_selectbox_test.py
  e2e_playwright/st_time_input.py
  e2e_playwright/st_time_input_test.py
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/NumberInput/styled-components.ts
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/runtime/state/__init__.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  proto/streamlit/proto/NumberInput.proto
Labels: security-assessment-completed, QA-Done, change:other, impact:internal

#7341 Fix python typing issue in pyplot
  lib/streamlit/elements/pyplot.py
Labels: security-assessment-completed, change:other, impact:internal

#7284 Update docstrings for 1.27.0 features
  lib/streamlit/elements/dataframe_selector.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/text_widgets.py
Labels: security-assessment-completed, impact:internal, change:docs

#7344 Add common dataframe libraries to attributions
  lib/streamlit/runtime/metrics_util.py
Labels: security-assessment-completed, change:other, impact:internal

#7334 Migrate Selectbox to RTL
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7339 Remove `change:breaking` from required labels
  .github/workflows/require-labels.yml
Labels: security-assessment-completed, change:other, impact:internal

#7340 Add playwright to nightly & release workflows
  .github/workflows/nightly.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  scripts/slack_notifications.py
Labels: security-assessment-completed, change:other, impact:internal

#7346 Additional docstring updates for version 1.27.0
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/number_input.py
Labels: security-assessment-completed, impact:internal, change:docs

#7337 Migrate FileDropzone to RTL
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7351 Migrate BokehChart to RTL
  frontend/lib/src/components/elements/BokehChart/BokehChart.test.tsx
  frontend/lib/src/components/elements/BokehChart/BokehChart.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7355 Migrate Pagination to RTL
  frontend/lib/src/hocs/withPagination/Pagination.test.tsx
  frontend/lib/src/hocs/withPagination/Pagination.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7327 Add overrideable default timeout for script tests
  lib/streamlit/testing/element_tree.py
  lib/streamlit/testing/local_script_runner.py
  lib/streamlit/testing/script_interactions.py
  lib/tests/streamlit/script_interactions_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7356 Migrate Markdown to RTL
  frontend/lib/src/components/elements/Markdown/Markdown.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7364 Migrate StreamlitLib to RTL
  frontend/app/src/StreamlitLib.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7365 Fix: Python 3.9 & 3.10 type check errors
  lib/streamlit/external/langchain/streamlit_callback_handler.py
Labels: security-assessment-completed, dev:full-matrix, change:other, impact:internal

#7369 Fix `st.metric` playwright test
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[light_theme-chromium].png
  e2e_playwright/conftest.py
  lib/streamlit/external/langchain/streamlit_callback_handler.py
Labels: security-assessment-completed, change:other, impact:internal

#7361 Migrate overflow tooltip to RTL
  frontend/lib/src/components/shared/Tooltip/OverflowTooltip.test.tsx
  frontend/lib/src/components/shared/Tooltip/__snapshots__/OverflowTooltip.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7363 Migrate VirtualDropdown to RTL
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.test.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7375 Migrate StatusWidget to RTL
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7377 Migrate SidebarNav to RTL
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/lib/src/components/shared/Icon/Icon.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7381 Migrate to CopyButton to RTL
  frontend/lib/src/components/elements/CodeBlock/CopyButton.test.tsx
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7379 Migrate FileDropzoneInstructions to RTL
  frontend/lib/src/components/widgets/FileUploader/FileDropzoneInstructions.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileDropzoneInstructions.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7331 Better dataframe hashing
  lib/streamlit/runtime/caching/hashing.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#7378 Migrate ToolbarActions to RTL
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
  frontend/app/src/components/ToolbarActions/__snapshots__/ToolbarActions.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7386 Fix wording for a test
  frontend/app/src/StreamlitLib.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7387 Migrate WidgetLabel to RTL
  frontend/lib/src/components/widgets/BaseWidget/WidgetLabel.test.tsx
  frontend/lib/src/components/widgets/BaseWidget/__snapshots__/WidgetLabel.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7388 Update script to auto generate the release notes correctly
  scripts/create_release.py
Labels: security-assessment-completed, impact:internal, change:chore

#7389 Migrate ErrorElement to RTL
  frontend/lib/src/components/shared/ErrorElement/ErrorElement.test.tsx
  frontend/lib/src/components/shared/ErrorElement/ErrorElement.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7325 Fluent asserts and type narrowing for widgets in tests
  lib/streamlit/testing/element_tree.py
  lib/tests/streamlit/script_interactions_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7390 Migrate withPagination to RTL
  frontend/lib/src/hocs/withPagination/withPagination.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7385 Migrate DateInput to RTL
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7394 Migrate MainMenu to RTL
  e2e/specs/st_main_menu.spec.js
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7380 Migrate Metric to RTL and Playwright
  e2e/scripts/st_metric.py
  e2e/specs/label_markdown.spec.js
  e2e/specs/st_metric.spec.js
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-container-gray[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-container-gray[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-container-green[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-container-green[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-container-red[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-container-red[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[light_theme-webkit].png
  e2e_playwright/st_metric_test.py
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-container-gray-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-container-gray.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-container-green-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-container-green.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-container-red-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-container-red.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-help-and-ellipses-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-help-and-ellipses.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-label-collapse-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-label-collapse.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-label-hidden-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-label-hidden.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-with-help-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-with-help.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-with-none-value-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_metric.spec.js/metric-with-none-value.snap.png
  frontend/lib/src/components/elements/Metric/Metric.test.tsx
  frontend/lib/src/components/elements/Metric/Metric.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7396 Migrate Audio to RTL
  frontend/lib/src/components/elements/Audio/Audio.test.tsx
  frontend/lib/src/components/elements/Audio/Audio.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7395 Migrate IFrame to RTL
  frontend/lib/src/components/elements/IFrame/IFrame.test.tsx
  frontend/lib/src/components/elements/IFrame/IFrame.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7399 Skip langchain `test_agent_run` failing test
  lib/test-requirements.txt
  lib/tests/streamlit/external/langchain/streamlit_callback_handler_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7392 Migrate Progress to RTL
  frontend/lib/src/components/elements/Progress/Progress.test.tsx
  frontend/lib/src/components/elements/Progress/Progress.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7384 Try to fix flaky e2e camera_input test
  e2e/specs/st_camera_input.spec.js
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#7400 Migrate JSON to RTL
  frontend/lib/src/components/elements/Json/Json.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7401 Migrate Video to RTL
  frontend/lib/src/components/elements/Video/Video.test.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/elements/Video/__snapshots__/Video.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7391 Migrate Docstring to RTL
  frontend/lib/src/components/elements/DocString/DocString.test.tsx
  frontend/lib/src/components/elements/DocString/DocString.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7382 Migrate AlertElement to RTL
  frontend/lib/src/components/elements/AlertElement/AlertElement.test.tsx
  frontend/lib/src/components/elements/AlertElement/AlertElement.tsx
  frontend/lib/src/components/shared/AlertContainer/AlertContainer.tsx
  frontend/lib/src/components/shared/Icon/Icon.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7403 Migrate Form to RTL
  frontend/lib/src/components/widgets/Form/Form.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7368 Remove the experimental prefix from `st.experimental_connection`
  lib/streamlit/__init__.py
  lib/streamlit/connections/__init__.py
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/deprecation_util.py
  lib/streamlit/runtime/connection_factory.py
  lib/tests/streamlit/connections/base_connection_test.py
  lib/tests/streamlit/deprecation_util_test.py
  lib/tests/streamlit/runtime/connection_factory_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7404 Migrate UnsupportedBrowserDialog to RTL
  frontend/app/src/hocs/withScreencast/components/UnsupportedBrowserDialog/UnsupportedBrowserDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/UnsupportedBrowserDialog/UnsupportedBrowserDialog.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7406 Migrate Sidebar to RTL
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7366 Make some minor changes to SQLConnection
  lib/streamlit/connections/sql_connection.py
Labels: security-assessment-completed, change:feature, impact:users

#7414 [Fix]: Python Dependency Resolutions
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/test-requirements.txt
  lib/tests/streamlit/external/langchain/streamlit_callback_handler_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7407 Migrate Tooltip to RTL
  frontend/lib/src/components/shared/Tooltip/Tooltip.test.tsx
  frontend/lib/src/components/shared/Tooltip/Tooltip.tsx
  frontend/lib/src/components/shared/Tooltip/__snapshots__/OverflowTooltip.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7412 Fix AST walk in `st.echo`
  lib/streamlit/echo.py
  lib/tests/streamlit/elements/echo_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7424 Migrate ThemedSidebar to RTL
  frontend/app/src/components/Sidebar/ThemedSidebar.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7425 Migrate VideoRecordedDialog to RTL
  e2e/specs/modals.spec.js
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7432 Teach st.write how to not set unsafe_allow_html when possible
  lib/streamlit/elements/write.py
  lib/streamlit/string_util.py
  lib/tests/streamlit/string_util_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7430 Fix potentially flaky playwright tests
  e2e_playwright/st_checkbox_test.py
  e2e_playwright/st_multiselect_test.py
  e2e_playwright/st_number_input_test.py
  e2e_playwright/st_radio_test.py
  e2e_playwright/st_toggle_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7442 Allow pillow 10.0.1
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#7423 Migrate GraphViz to RTL
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/elements/GraphVizChart/__snapshots__/GraphVizChart.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7450 Release 1.27.1
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#7441 Fix bokeh slider by adding in side effects to package json
  e2e/specs/st_bokeh_chart.spec.js
  e2e_flaky/specs/st_bokeh_chart.spec.ts
  e2e_playwright/st_bokeh_chart.py
  e2e_playwright/st_bokeh_chart_test.py
  frontend/lib/package.json
  frontend/lib/src/vendor/bokeh/bokeh-api-2.4.3.esm.min.d.ts
  frontend/lib/src/vendor/bokeh/bokeh-gl-2.4.3.esm.min.d.ts
  frontend/lib/src/vendor/bokeh/bokeh-tables-2.4.3.esm.min.d.ts
  frontend/lib/src/vendor/bokeh/bokeh-widgets-2.4.3.esm.min.d.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7457 Use Mapping instead of Dict in for column config mapping
  lib/streamlit/elements/lib/column_config_utils.py
Labels: security-assessment-completed, change:other, impact:internal

#7460 Upgrade vega-embed and get rid of small hack
  frontend/lib/package.json
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor
