Repository streamlit/streamlit, pull requests merged in 2023-12, with the labels that each got.

#7788 Fix `st.toggle` background color
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-1[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-1[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-1[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-1[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-1[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-1[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-2[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-2[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-2[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-2[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-2[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-2[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-3[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-4[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-4[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-4[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-4[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-4[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-4[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-5[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-5[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-5[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-5[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-5[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-5[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-6[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-6[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-6[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-6[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-6[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-6[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-7[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-7[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-7[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-7[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-7[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/toggle-7[light_theme-webkit].png
  frontend/lib/src/components/widgets/Checkbox/Checkbox.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7787 Don't send command used to start streamlit to frontend
  frontend/app/src/App.test.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/lib/src/SessionInfo.test.ts
  frontend/lib/src/SessionInfo.ts
  frontend/lib/src/mocks/mocks.ts
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/script_data.py
  lib/streamlit/web/bootstrap.py
  lib/streamlit/web/cli.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/script_data_test.py
  lib/tests/streamlit/runtime/websocket_session_manager_test.py
  lib/tests/streamlit/web/server/server_test.py
  lib/tests/streamlit/web/server/server_test_case.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:bugfix, impact:users

#7789 Release 1.29.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#7707 Add Initial URL Parameters to query params state
  e2e_playwright/conftest.py
  e2e_playwright/st_query_params.py
  e2e_playwright/st_query_params_test.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/state/query_params.py
  lib/tests/streamlit/runtime/state/query_params_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7800 Ensure only one query param api usage
  e2e_playwright/st_both_query_params_error.py
  e2e_playwright/st_both_query_params_error_test.py
  lib/streamlit/commands/experimental_query_params.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/state/query_params.py
  lib/tests/streamlit/script_run_context_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7741 Add display_text to LinkColumn
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/cells/LinkCell.test.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/LinkCell.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/UriOverlayEditor.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/uri-overlay-editor-style.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/index.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.ts
  lib/streamlit/elements/lib/column_types.py
  lib/tests/streamlit/elements/lib/column_types_test.py
Labels: security-assessment-completed, change:feature, impact:users

#7802 Accept Tuples and Sets, Don't accept dicts
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/state/query_params_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7782 Deprecate Experimental query commands
  e2e/specs/st_experimental_get_query_params.spec.js
  lib/streamlit/__init__.py
Labels: security-assessment-completed, impact:internal, change:chore

#7781 Add metric tracking for query params
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/metrics_util_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7784 Add Pandas styler support to `LinkColumn`
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[light_theme-webkit].png
  e2e_playwright/st_data_editor_config.py
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_styler_support.py
  e2e_playwright/st_dataframe_styler_support_test.py
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/index.ts
  lib/streamlit/elements/lib/column_types.py
Labels: security-assessment-completed, change:feature, impact:users

#7806 Send Rerun message also for newly created pages
  lib/streamlit/runtime/app_session.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#7809 Support direct editing for link column
  frontend/lib/src/components/widgets/DataFrame/columns/cells/LinkCell.test.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/LinkCell.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/UriOverlayEditor.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/uri-overlay-editor-style.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#7799 Add config option for storing messages content in ForwardMsgCache
  lib/streamlit/config.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/forward_msg_cache_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7803 Migrate CameraInput to RTL
  frontend/lib/src/components/widgets/CameraInput/CameraInput.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/CameraInput/SwitchFacingModeButton.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.test.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7804 Migrate ThemeCreatorDialog to RTL
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/app/src/components/StreamlitDialog/__snapshots__/ThemeCreatorDialog.test.tsx.snap
Labels: security-assessment-completed, impact:internal, change:chore

#7805 Migrate Maybe Component to RTL
  frontend/lib/src/components/core/Maybe/Maybe.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7821 Fix iframe background for dark color scheme
  e2e/scripts/components_html.py
  e2e/scripts/components_iframe.py
  e2e/specs/components_declare_component.spec.js
  e2e/specs/components_html.spec.js
  e2e/specs/components_iframe.spec.js
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe[light_theme-webkit].png
  e2e_playwright/st_components_v1.py
  e2e_playwright/st_components_v1_test.py
  frontend/lib/src/components/elements/IFrame/IFrame.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/elements/PlotlyChart/__snapshots__/PlotlyChart.test.tsx.snap
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/elements/Video/__snapshots__/Video.test.tsx.snap
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7744 Rename Tornado default `_xsrf` cookie name
  e2e/specs/st_camera_input.spec.js
  e2e/specs/st_file_uploader.spec.js
  e2e/specs/websocket_reconnects.spec.js
  frontend/app/src/App.tsx
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
Labels: security-assessment-completed, impact:internal, change:chore

#7824 Convert withFullScreen to RTL
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7835 Fix resize observer error
  frontend/cypress/snapshots/linux/2x/st_pyplot.spec.js/pyplot-check-if-cleared.snap.png
  frontend/lib/src/components/core/Block/Block.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#7832 Remove numpy.ndarray from list of supported types from docstring
  lib/streamlit/elements/map.py
Labels: security-assessment-completed, impact:internal, change:docs

#7861 Fix playwright port selection
  e2e_playwright/conftest.py
Labels: security-assessment-completed, change:other, impact:internal

#7842 Optimize `lodash` imports
  frontend/app/src/App.tsx
  frontend/app/src/SegmentMetricsManager.ts
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/lib/src/FileUploadClient.ts
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  frontend/lib/src/components/elements/PlotlyChart/CustomTheme.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/ListColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/util/UriUtil.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, impact:internal, change:chore

#7859 Migrate MPA e2e test to playwright
  e2e/specs/multipage_apps.spec.js
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_collapsed[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_collapsed[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/multipage_apps/__init__.py
  e2e_playwright/multipage_apps/mpa_basics.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/multipage_apps/mpa_configure_sidebar.py
  e2e_playwright/multipage_apps/mpa_configure_sidebar_test.py
  e2e_playwright/multipage_apps/pages/02_page2.py
  e2e_playwright/multipage_apps/pages/03_page3.py
  e2e_playwright/multipage_apps/pages/04_page_with_duplicate_name.py
  e2e_playwright/multipage_apps/pages/05_page_with_duplicate_name.py
  e2e_playwright/multipage_apps/pages/06_page_6.py
  e2e_playwright/multipage_apps/pages/07_page_7.py
  e2e_playwright/pytest.ini
  frontend/cypress/snapshots/linux/2x/multipage_apps.spec.js/multipage-apps-sidebar-nav-dark.snap.png
  frontend/cypress/snapshots/linux/2x/multipage_apps.spec.js/multipage-apps-sidebar-nav.snap.png
  frontend/lib/src/components/shared/StreamlitMarkdown/Heading.tsx
  scripts/check_license_headers.py
  scripts/run_e2e_tests.py
Labels: security-assessment-completed, change:other, impact:internal

#7857 Add modification time not zero check for path changed
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/streamlit/watcher/polling_path_watcher.py
  lib/tests/streamlit/watcher/event_based_path_watcher_test.py
  lib/tests/streamlit/watcher/polling_path_watcher_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7860 Speed up plotly figures by 8x for users with "orjson"
  lib/streamlit/elements/plotly_chart.py
Labels: security-assessment-completed, change:refactor, impact:users
