Repository streamlit/streamlit, pull requests merged in 2024-10, with the labels that each got.

#9566 Update st.audio_input docstring
  lib/streamlit/elements/widgets/audio_input.py
Labels: security-assessment-completed, impact:internal, change:docs

#9574 Revert "Allow array parameters in CLI (#9539)"
  lib/streamlit/config_option.py
  lib/streamlit/web/cli.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9583 Fix various hardcoded CSS props in lib - part 1
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-input_instructions[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-input_instructions[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-input_instructions[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-input_instructions[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-input_instructions[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-input_instructions[webkit].png
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/PlotlyChart/CustomTheme.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/elements/Popover/styled-components.ts
  frontend/lib/src/components/elements/Spinner/styled-components.ts
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  frontend/lib/src/components/elements/Toast/styled-components.tsx
  frontend/lib/src/components/shared/BaseColorPicker/styled-components.ts
  frontend/lib/src/components/shared/InputInstructions/styled-components.ts
  frontend/lib/src/components/shared/Modal/Modal.tsx
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
  frontend/lib/src/components/widgets/CameraInput/CameraInputButton.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
  frontend/lib/src/theme/index.ts
  frontend/lib/src/theme/primitives/sizes.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9561 [Fix] Error on invalid `st.text_area` height
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-height_75[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-height_75[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-height_75[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-height_75[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-height_75[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-height_75[light_theme-webkit].png
  e2e_playwright/st_text_area.py
  e2e_playwright/st_text_area_test.py
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  lib/streamlit/elements/widgets/text_widgets.py
  lib/tests/streamlit/elements/text_area_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9589 [Fix] `st.navigation` reconciles `client.showSidebarNavigation` config
  frontend/app/src/util/AppNavigation.ts
  lib/streamlit/commands/navigation.py
  lib/tests/streamlit/commands/navigation_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9576 [Fix] Show input instructions in form when allowed and focused
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9602 [chore] Replace `getByTestId` with `getByText` for Input tests
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#9586 [chore] Modernize Selectbox code
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.tsx
Labels: feature:st.selectbox, security-assessment-completed, impact:internal, change:chore

#9593 [chore] Modernize ColorPicker code
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#9547 [feat] Add `use_container_width` to `st.image`
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_container_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_container_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_container_width[webkit].png
  e2e_playwright/st_image.py
  e2e_playwright/st_image_test.py
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  lib/streamlit/elements/image.py
  lib/tests/streamlit/elements/exception_test.py
  lib/tests/streamlit/elements/image_test.py
  proto/streamlit/proto/Image.proto
Labels: feature:st.image, security-assessment-completed, change:feature, impact:users

#9479 [Fix] MPA page layout
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[webkit].png
  e2e_playwright/multipage_apps/mpa_layout.py
  e2e_playwright/multipage_apps/mpa_layout_test.py
  e2e_playwright/multipage_apps/pages/14_default_layout_page.py
  e2e_playwright/multipage_apps/pages/15_wide_layout_page.py
  e2e_playwright/multipage_apps/pages/16_dynamic_layout_page.py
  e2e_playwright/multipage_apps_v2/mpa_v2_layout.py
  e2e_playwright/multipage_apps_v2/mpa_v2_layout_test.py
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9605 Replace some hardcoded style values with theme values
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-webkit].png
  e2e_playwright/deploy_dialog_test.py
  e2e_playwright/shared/app_utils.py
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/app/src/components/StatusWidget/styled-components.ts
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployCard.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployModal.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/app/src/hocs/withScreencast/components/UnsupportedBrowserDialog/styled-components.ts
  frontend/lib/src/components/elements/ArrowTable/styled-components.ts
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  frontend/lib/src/components/shared/AlertContainer/AlertContainer.tsx
  frontend/lib/src/components/shared/Modal/Modal.test.tsx
  frontend/lib/src/components/shared/Modal/Modal.tsx
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/types.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9610 Rename `SegmentMetricsManager`
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#9625 Fix page link margin regression
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/st_page_link-correct_margin[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/st_page_link-correct_margin[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/st_page_link-correct_margin[webkit].png
  e2e_playwright/multipage_apps/mpa_configure_sidebar.py
  e2e_playwright/multipage_apps/mpa_configure_sidebar_test.py
  frontend/lib/src/components/core/Block/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9626 Fix various hardcoded CSS props in lib - part 2
  frontend/lib/src/components/elements/ArrowTable/styled-components.ts
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/GraphVizChart/styled-components.ts
  frontend/lib/src/components/elements/Skeleton/styled-components.ts
  frontend/lib/src/components/shared/Icon/Material/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/Tooltip/Tooltip.tsx
  frontend/lib/src/components/widgets/DataFrame/Tooltip.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.tsx
  frontend/lib/src/components/widgets/Slider/styled-components.ts
  frontend/lib/src/mocks/mockTheme.ts
  frontend/lib/src/theme/emotionBaseTheme/index.ts
  frontend/lib/src/theme/primitives/index.ts
  frontend/lib/src/theme/primitives/typography.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9627 Refactor vega embed CSS
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[light_theme-webkit].png
  e2e_playwright/st_altair_chart_test.py
  frontend/lib/src/assets/css/vega-embed.css
  frontend/lib/src/assets/css/vega-embed.scss
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9606 [chore] Modernize DeployButton.tsx
  frontend/app/src/components/DeployButton/DeployButton.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#9622 [chore] Modernize Multiselect code
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
Labels: feature:st.multiselect, security-assessment-completed, impact:internal, change:chore

#9623 [chore] Modernize TextArea code
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/useBasicWidgetState.ts
Labels: feature:st.text_area, security-assessment-completed, impact:internal, change:chore

#9591 make useWidgetManagerElementState respect form clearing
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
  frontend/lib/src/hooks/useWidgetManagerElementState.test.ts
  frontend/lib/src/hooks/useWidgetManagerElementState.test.tsx
  frontend/lib/src/hooks/useWidgetManagerElementState.tsx
Labels: security-assessment-completed, change:other, impact:internal

#9630 Replace react-hotkeys with more modern library (react-hot-keys)
  NOTICES
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/components/StreamlitDialog/ScriptChangedDialog.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/lib/src/baseconsts.ts
  frontend/lib/src/index.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#9636 Upgrade deck.gl to the latest version
  NOTICES
  frontend/lib/package.json
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/types.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/colors.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/jsonConverter.ts
  frontend/yarn.lock
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed, change:refactor, impact:users

#9639 Remove functions from styled components where needed
  frontend/app/src/components/AppView/styled-components.ts
  frontend/app/src/components/MainMenu/styled-components.ts
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/app/src/components/StatusWidget/styled-components.ts
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/styled-components.tsx
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/app/src/hocs/withScreencast/components/UnsupportedBrowserDialog/styled-components.ts
  frontend/lib/src/components/elements/ImageList/styled-components.ts
  frontend/lib/src/components/elements/PageLink/styled-components.ts
  frontend/lib/src/components/elements/Particles/styled-components.ts
  frontend/lib/src/components/shared/BaseColorPicker/styled-components.ts
  frontend/lib/src/components/shared/TooltipIcon/styled-components.ts
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
  frontend/lib/src/components/widgets/BaseWidget/styled-components.ts
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.tsx
  frontend/lib/src/components/widgets/CameraInput/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
  frontend/lib/src/components/widgets/DataFrame/columns/cells/ImageCellEditor.tsx
  frontend/lib/src/components/widgets/FileUploader/styled-components.ts
  frontend/lib/src/components/widgets/Form/styled-components.ts
  frontend/lib/src/components/widgets/TimeInput/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9612 Expose the st.pills command again
  e2e_playwright/st_pills.py
  lib/streamlit/__init__.py
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9617 [Fix] Clear fragment autoreruns when changing pages
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9642 Fix clear cached class method regression
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9644 Adjust eslint and type rules
  e2e_playwright/shared/toolbar_utils.py
  frontend/app/src/App.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/lib/src/ForwardMessageCache.test.ts
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/tsconfig.json
Labels: security-assessment-completed, impact:internal, change:refactor

#9590 Adds WindowDimensionProvider and passing fullscreen props via context
  frontend/app/src/ThemedApp.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/types.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/shared/ElementFullscreen/ElementFullscreenContext.tsx
  frontend/lib/src/components/shared/ElementFullscreen/ElementFullscreenWrapper.tsx
  frontend/lib/src/components/shared/ElementFullscreen/testUtils.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/lib/src/components/shared/Tooltip/OverflowTooltip.test.tsx
  frontend/lib/src/components/shared/WindowDimensions/Provider.test.tsx
  frontend/lib/src/components/shared/WindowDimensions/Provider.tsx
  frontend/lib/src/components/shared/WindowDimensions/index.tsx
  frontend/lib/src/components/shared/WindowDimensions/useWindowDimensions.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
  frontend/lib/src/hooks/useRequiredContext.tsx
  frontend/lib/src/test_util.tsx
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, change:other, impact:internal

#9629 [chore] Modernize Maybe component
  frontend/lib/src/components/core/Maybe/Maybe.test.tsx
  frontend/lib/src/components/core/Maybe/Maybe.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#9643 Fix various hardcoded CSS props in lib - part 4
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-dropdown_narrow_column[firefox].png
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.tsx
  frontend/lib/src/theme/primitives/sizes.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9615 Add eslint rule to detect hardcoded style values
  frontend/.eslintrc.js
  frontend/app/src/components/Countdown/styled-components.ts
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/eslint-plugin-streamlit-custom/index.js
  frontend/eslint-plugin-streamlit-custom/no-hardcoded-theme-values.js
  frontend/eslint-plugin-streamlit-custom/no-hardcoded-theme-values.test.js
  frontend/eslint-plugin-streamlit-custom/package.json
  frontend/eslint-plugin-streamlit-custom/use-strict-null-equality-checks.js
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  frontend/lib/src/components/elements/PlotlyChart/CustomTheme.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/styled-components.ts
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
  frontend/tsconfig.dev.json
  frontend/tsconfig.json
Labels: security-assessment-completed, impact:internal, change:chore

#9678 [chore] Modernize Fullscreen components
  frontend/lib/src/components/shared/ElementFullscreen/ElementFullscreenWrapper.tsx
  frontend/lib/src/components/shared/ElementFullscreen/useFullscreen.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.test.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.tsx
  frontend/lib/src/test_util.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#9654 deexperiment audio_input widget
  e2e_playwright/st_audio_input.py
  e2e_playwright/st_experimental_audio_input.py
  e2e_playwright/st_experimental_audio_input_test.py
  lib/streamlit/__init__.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9611 Extend `host_config` endpoint with `metricsUrl` configuration
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  frontend/lib/src/hostComm/types.ts
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9681 Deploy dialog redesign
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-webkit].png
  frontend/app/src/assets/svg/rocket.svg
  frontend/app/src/assets/svg/snowflake.svg
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployCard.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployListElement.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployModal.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/styled-components.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/__snapshots__/NoRepositoryDetected.test.tsx.snap
  frontend/app/src/urls.ts
Labels: security-assessment-completed, change:refactor, impact:users

#9418 Feature/button group: st.segmented_control
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[light_theme-webkit].png
  e2e_playwright/st_segmented_control.py
  e2e_playwright/st_segmented_control_test.py
  frontend/lib/src/components/shared/BaseButton/BaseButton.tsx
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
  lib/streamlit/__init__.py
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  lib/tests/streamlit/typing/pills.py
  lib/tests/streamlit/typing/segmented_control.py
  proto/streamlit/proto/ButtonGroup.proto
Labels: security-assessment-completed, change:feature, impact:users

#9685 [chore] use `assert_type` for feedback typing test
  lib/tests/streamlit/typing/feedback.py
  lib/tests/streamlit/typing/number_input_types.py
  lib/tests/streamlit/typing/slider_types.py
Labels: security-assessment-completed, impact:internal, change:chore

#9699 Fix typo in docstring for `selection_mode` of `st.dataframe`
  lib/streamlit/elements/arrow.py
Labels: security-assessment-completed, impact:users, change:docs

#9701 For button group commands, rename 'multiple' to 'multi' for selection_mode
  e2e_playwright/st_pills.py
  e2e_playwright/st_segmented_control.py
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/typing/pills.py
  lib/tests/streamlit/typing/segmented_control.py
Labels: security-assessment-completed, change:feature, impact:users

#9693 Remove pre & code from globalstyles
  .ruff.toml
  e2e_playwright/__snapshots__/linux/compilation_error_dialog_test/compilation_error-dialog[chromium].png
  e2e_playwright/__snapshots__/linux/compilation_error_dialog_test/compilation_error-dialog[firefox].png
  e2e_playwright/__snapshots__/linux/compilation_error_dialog_test/compilation_error-dialog[webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_inline_error[chromium].png
  e2e_playwright/__snapshots__/linux/websocket_disconnect_test/websocket_connection-disconnected_dialog[chromium].png
  e2e_playwright/__snapshots__/linux/websocket_disconnect_test/websocket_connection-disconnected_dialog[firefox].png
  e2e_playwright/__snapshots__/linux/websocket_disconnect_test/websocket_connection-disconnected_dialog[webkit].png
  e2e_playwright/compilation_error_dialog.py
  e2e_playwright/compilation_error_dialog_test.py
  e2e_playwright/st_code.py
  e2e_playwright/websocket_disconnect_test.py
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/ModuleIsNotAdded.tsx
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/__snapshots__/ModuleIsNotAdded.test.tsx.snap
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/MapboxTokenError.tsx
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/ExceptionElement/styled-components.ts
  frontend/lib/src/components/shared/ErrorElement/ErrorElement.tsx
  frontend/lib/src/components/shared/ErrorElement/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/theme/globalStyles.ts
  scripts/run_bare_execution_tests.py
Labels: security-assessment-completed, change:refactor, impact:users

#9712 changing icon and label for st.audio_input
  e2e_playwright/st_audio_input_test.py
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
Labels: security-assessment-completed, change:other, impact:users

#9715 Add click metrics for theme editing dialog
  frontend/app/src/App.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
Labels: security-assessment-completed, change:other, impact:internal

#9653 Improve tests for AppNodes and Quiver
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/test_util.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9702 Update `GUEST_READY` message
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/ThemedApp.test.tsx
  frontend/app/src/ThemedApp.tsx
  frontend/app/src/index.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9695 Add `MetricsEvent` proto & Fivetran infrastructure
  frontend/app/package.json
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  frontend/yarn.lock
  proto/streamlit/proto/MetricsEvent.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#9718 Deploy dialog feedback
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-webkit].png
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployListElement.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/styled-components.tsx
Labels: security-assessment-completed, change:refactor, impact:users

#9713 Clean up reboot global scss styles
  frontend/app/src/assets/css/reboot.scss
  frontend/app/src/assets/css/theme.scss
  frontend/app/src/assets/css/variables.scss
  frontend/app/src/assets/css/vendor/rfs.scss
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9728 [Fix] pydeck e2e snapshot
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_selection_state_remains_after_unmounting[chromium].png
Labels: security-assessment-completed, impact:internal, change:chore

#9733 FIx button cursor regression
  e2e_playwright/st_button_test.py
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9691 Simplify e2e snapshot handling
  Makefile
  e2e_playwright/conftest.py
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, change:other, impact:internal

#9735 Round pixels of calculated slider label pixel values
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_left[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_left[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_left[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_left[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_left[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_right[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_right[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_right[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_near_right[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-overlap_right[dark_theme-firefox].png
  frontend/lib/src/components/widgets/Slider/Slider.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#9731 Remove eval from frontend bundle
  frontend/lib/package.json
  frontend/package.json
  frontend/patches/@protobufjs+inquire+1.1.0.patch
  frontend/yarn.lock
  scripts/check_license_headers.py
Labels: security-assessment-completed, change:other, impact:internal

#9742 Allow Pillow 11
  lib/setup.py
Labels: security-assessment-completed, change:other, impact:users

#9736 Modernize markdown component
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9684 [chore] Modernize SettingsDialog
  frontend/app/package.json
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9744 Fix issue with local storage in Android webview
  frontend/.eslintrc.js
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9734 Modernize countdown component
  frontend/app/src/components/Countdown/Countdown.test.tsx
  frontend/app/src/components/Countdown/Countdown.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9698 Fixing alignment issues for `st.latex` with `help` tooltip
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-webkit].png
  frontend/lib/src/components/elements/Markdown/Markdown.tsx
  frontend/lib/src/components/shared/TooltipIcon/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#9741 Deploy dialog feedback cont’d
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-webkit].png
  frontend/app/src/assets/svg/logo.svg
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployCard.tsx
Labels: security-assessment-completed, change:refactor, impact:users

#9732 Add a delay before displaying the running man icon.
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
Labels: security-assessment-completed, change:feature, impact:users

#9729 [Refactor] Metrics Provider Transition
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  frontend/app/src/SegmentMetricsManager.test.ts
  frontend/app/src/SegmentMetricsManager.ts
  frontend/app/src/ThemedApp.test.tsx
  frontend/app/src/ThemedApp.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
  frontend/app/src/index.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/web/server/routes_test.py
  proto/streamlit/proto/MetricsEvent.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#9723 [fix] Revamp `preferredLayouts` state for `set_page_config` and layout in User Settings
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[webkit].png
  e2e_playwright/multipage_apps/mpa_layout_test.py
  e2e_playwright/multipage_apps/pages/17_fragment_layout_page.py
  e2e_playwright/multipage_apps_v2/mpa_v2_layout.py
  e2e_playwright/multipage_apps_v2/mpa_v2_layout_test.py
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9721 Use toolbar for fullscreen button
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list[webkit].png
  e2e_playwright/host_config_test.py
  e2e_playwright/responsive_test.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_graphviz_chart_test.py
  e2e_playwright/st_image_test.py
  e2e_playwright/st_popover_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.test.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.test.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/ImageList/styled-components.ts
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.test.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/index.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/styled-components.ts
  frontend/lib/src/components/shared/FullScreenWrapper/styled-components.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.test.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.tsx
  frontend/lib/src/components/shared/Toolbar/index.tsx
  frontend/lib/src/components/shared/Toolbar/styled-components.ts
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:refactor, impact:users

#9706 [feat] Localize calendar week start date in st.date_input
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-ar-EG-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-ar-EG-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-ar-EG-webkit].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-de-DE-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-de-DE-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-de-DE-webkit].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-en-US-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-en-US-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-en-US-webkit].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-ja-JP-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-ja-JP-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[dark_theme-ja-JP-webkit].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-ar-EG-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-ar-EG-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-ar-EG-webkit].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-de-DE-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-de-DE-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-de-DE-webkit].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-en-US-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-en-US-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-en-US-webkit].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-ja-JP-chromium].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-ja-JP-firefox].png
  e2e_playwright/__snapshots__/linux/i18n_test/st_date_input-range_two_dates_calendar[light_theme-ja-JP-webkit].png
  e2e_playwright/i18n.py
  e2e_playwright/i18n_test.py
  frontend/app/src/App.tsx
  frontend/lib/package.json
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
  frontend/lib/src/components/widgets/DateInput/useIntlLocale.tsx
  frontend/lib/src/test_util.tsx
Labels: feature:st.date_input, security-assessment-completed, change:feature, impact:users

#9757 Revert the MPA Layout changes
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[webkit].png
  e2e_playwright/multipage_apps/mpa_layout.py
  e2e_playwright/multipage_apps/mpa_layout_test.py
  e2e_playwright/multipage_apps/pages/14_default_layout_page.py
  e2e_playwright/multipage_apps/pages/15_wide_layout_page.py
  e2e_playwright/multipage_apps/pages/16_dynamic_layout_page.py
  e2e_playwright/multipage_apps/pages/17_fragment_layout_page.py
  e2e_playwright/multipage_apps_v2/mpa_v2_layout.py
  e2e_playwright/multipage_apps_v2/mpa_v2_layout_test.py
  frontend/app/src/App.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#9661 Update docs for st.connection
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/runtime/connection_factory.py
Labels: security-assessment-completed, impact:internal, change:docs

#9754 Disallow double slash paths to redirect
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9758 Improve update snapshots script
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, change:other, impact:internal
