Repository streamlit/streamlit, pull requests merged in 2024-02, with the labels that each got.

#8039 Add support for PIL images in `st.write`
  e2e_playwright/st_write.py
  e2e_playwright/st_write_test.py
  lib/streamlit/elements/write.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8056 Fix `time_input` menu colors in dark mode
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[light_theme-webkit].png
  e2e_playwright/st_time_input_test.py
  frontend/lib/src/theme/createThemeUtil.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8060 Migrate form e2e tests to playwright
  e2e/scripts/form_multiple_buttons.py
  e2e/scripts/st_form.py
  e2e/scripts/st_form_use_container_width_submit_button.py
  e2e/specs/form_multiple_buttons.spec.js
  e2e/specs/st_form.spec.js
  e2e/specs/st_form_column_association.spec.js
  e2e/specs/st_form_use_container_width_submit_button.spec.js
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-borderless[chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-borderless[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-borderless[webkit].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-with_stretched_submit_button[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-with_stretched_submit_button[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-with_stretched_submit_button[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-with_stretched_submit_button[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-with_stretched_submit_button[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-with_stretched_submit_button[light_theme-webkit].png
  e2e_playwright/st_form.py
  e2e_playwright/st_form_test.py
  frontend/cypress/snapshots/linux/2x/st_form_use_container_width_submit_button.spec.js/form-submit-button-container-and-help-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_form_use_container_width_submit_button.spec.js/form-submit-button-container-and-help.snap.png
  frontend/cypress/snapshots/linux/2x/st_form_use_container_width_submit_button.spec.js/use-container-width-submit-form-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_form_use_container_width_submit_button.spec.js/use-container-width-submit-form-button.snap.png
Labels: security-assessment-completed, change:other, impact:internal

#8062 Remove `assert` uses from playwright tests to fix flakiness
  e2e_playwright/conftest.py
  e2e_playwright/fast_rerun_safety_test.py
  e2e_playwright/label_markdown_test.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_expander_test.py
  e2e_playwright/st_graphviz_chart_test.py
  e2e_playwright/st_multiselect_test.py
Labels: security-assessment-completed, change:other, impact:internal

#8064 Make shallow copies of options returned from ensure_indexable
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8063 Make DeltaGenerators deepcopyable
  lib/streamlit/delta_generator.py
  lib/tests/streamlit/delta_generator_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#8068 Fix memory leak in runtime coroutine loop
  lib/streamlit/runtime/runtime.py
  lib/tests/streamlit/runtime/runtime_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8067 Migrated last file uploader tests to playwright
  e2e_playwright/st_file_uploader_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8079 Prevent pandas keyerror when checking color column format in st.map
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/map_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8082 Remove unnecessary deb repository from init action
  .github/actions/make_init/action.yml
  .github/workflows/python-min-deps.yml
Labels: security-assessment-completed, change:other, impact:internal

#8087 Remove local e2e environment
  .dockerignore
  Makefile
  e2e/Dockerfile
  e2e/docker-compose.yml
  e2e/run_compose.py
  frontend/app/craco.config.js
  scripts/check_license_headers.py
  scripts/diffmazing_cropper.sh
Labels: security-assessment-completed, change:other, impact:internal

#8017 Update README.md
  README.md
Labels: security-assessment-completed, impact:internal, change:chore

#8094 Remove importlib-metadata dependency
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/version.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8092 Fix issue using a local path with `st.image` on windows.
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/media.py
  lib/streamlit/url_util.py
  lib/streamlit/web/cli.py
  lib/tests/streamlit/commands/page_config_test.py
  lib/tests/streamlit/url_util_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8101 More st.experimental_fragment skeleton code
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/delta_generator_test_case.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/script_run_context_test.py
  lib/tests/streamlit/user_info_test.py
  lib/tests/testutil.py
  proto/streamlit/proto/ClientState.proto
  proto/streamlit/proto/Delta.proto
  proto/streamlit/proto/ForwardMsg.proto
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#8083 Expire session storage cache on an async timer
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py
  lib/streamlit/runtime/memory_session_storage.py
  lib/streamlit/util.py
  lib/tests/streamlit/util_test.py
Labels: area:performance, security-assessment-completed, change:other, impact:users

#8109 Lazy-load emoji module to improve performance
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  lib/streamlit/emojis.py
  lib/streamlit/string_util.py
  lib/tests/streamlit/string_util_test.py
  scripts/update_emojis.py
Labels: security-assessment-completed, change:refactor, impact:users

#8117 Add additional chars to special char check in `string_util`
  lib/streamlit/string_util.py
  lib/tests/streamlit/string_util_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8110 Refactor plotly theme creation
  lib/streamlit/elements/lib/streamlit_plotly_theme.py
  lib/streamlit/elements/plotly_chart.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8111 Lazy-load the watchdog event watcher module
  e2e_playwright/conftest.py
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/streamlit/watcher/path_watcher.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
  lib/tests/streamlit/watcher/path_watcher_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8085 Fix: `st.page_link` & `st.switch_page` handling / prefixed paths
  e2e_playwright/multipage_apps/pages/02_page2.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8103 Normalize main script path in `st.switch_page` and `st.page_link`
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8086 Fix: `st.page_link` URL preview shows file path
  e2e_playwright/multipage_apps/mpa_configure_sidebar_test.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8124 Lazy-load vendored pympler asizeof module
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/streamlit/runtime/state/session_state.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8125 Lazy-load pandas and pyarrow to improve performance
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/connections/sql_connection_test.py
Labels: security-assessment-completed, change:refactor, impact:users

#8132 Fix broken emoji in e2e tests
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-disabled[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-disabled[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-disabled[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-disabled[light_theme-webkit].png
  e2e_playwright/multipage_apps/mpa_configure_sidebar.py
  e2e_playwright/multipage_apps/pages/04_page_with_duplicate_name.py
Labels: security-assessment-completed, change:other, impact:internal

#8130 Migrate pyplot e2e tests to playwright
  e2e/scripts/st_pyplot.py
  e2e/scripts/st_pyplot_kwargs.py
  e2e/specs/st_pyplot.spec.js
  e2e/specs/st_pyplot_kwargs.spec.js
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_false[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_false[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_false[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_false[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_false[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_false[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_true[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_true[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_true[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_true[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_true[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-container_width_true[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-global_figure[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-global_figure[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-global_figure[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-global_figure[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-global_figure[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-global_figure[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-normal_figure[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-normal_figure[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-normal_figure[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-normal_figure[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-normal_figure[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-normal_figure[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-resized_figure[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-resized_figure[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-resized_figure[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-resized_figure[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-resized_figure[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-resized_figure[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn_using_kwargs[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn_using_kwargs[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn_using_kwargs[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn_using_kwargs[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn_using_kwargs[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-seaborn_using_kwargs[light_theme-webkit].png
  e2e_playwright/st_pyplot.py
  e2e_playwright/st_pyplot_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8127 Support multiple path characteristics for switch_page and page_link
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/file_util.py
  lib/tests/streamlit/file_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8122 Add backend changes for st.experimental_fragment aside from the decorator itself
  lib/streamlit/__init__.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/script_requests.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8118 Miscellaneous docstring edits and argument names
  lib/streamlit/config.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/spinner.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/tests/streamlit/spinner_test.py
Labels: security-assessment-completed, impact:users, change:docs

#8133 Deprecate the `deprecation.showPyplotGlobalUse` config option
  lib/streamlit/config.py
Labels: security-assessment-completed, change:other, impact:users

#8113 Use env variable to configure matplotlib backend
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  lib/streamlit/__init__.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/web/bootstrap_test.py
Labels: security-assessment-completed, change:refactor, impact:users

#8134 Lazy-load numpy and pillow to improve performance
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/write.py
  lib/streamlit/watcher/path_watcher.py
Labels: security-assessment-completed, change:refactor, impact:users

#8139 Update `browser.serverPort` config option
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:docs

#8146 Release/1.31.1
  e2e_playwright/multipage_apps/mpa_basics_test.py
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#8126 Implement the fragment decorator
  lib/streamlit/runtime/fragment.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8138 Attempt to fix Github package detection
  lib/setup.py
Labels: security-assessment-completed, change:other, impact:internal

#8145 add: Supprt for HTTP <Head> method to /healthz endpoint
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8152 Show a warning when server port `3000` is used
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/server_util.py
Labels: security-assessment-completed, change:other, impact:users

#8107 Add support for AzureOpenAI chat stream
  lib/streamlit/elements/write.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8150 Lazy-load `unittest`, `packaging`, and openmetrics proto
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/legacy_caching/hashing.py
  lib/streamlit/runtime/stats.py
  lib/streamlit/testing/v1/util.py
  lib/streamlit/version.py
  lib/streamlit/web/server/stats_request_handler.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8128 React 18 Infrastructure
  NOTICES
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.tsx
  frontend/app/src/index.tsx
  frontend/app/src/setupTests.js
  frontend/lib/jest.config.js
  frontend/lib/package.json
  frontend/lib/src/components/core/Maybe/Maybe.tsx
  frontend/lib/src/components/core/ThemeProvider.tsx
  frontend/lib/src/components/elements/Balloons/Balloons.tsx
  frontend/lib/src/components/elements/ChatMessage/ChatMessage.tsx
  frontend/lib/src/components/elements/CodeBlock/CodeBlock.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/withMapboxToken.tsx
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/Particles/Particles.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.tsx
  frontend/lib/src/components/elements/Skeleton/AppSkeleton.tsx
  frontend/lib/src/components/elements/Skeleton/Skeleton.tsx
  frontend/lib/src/components/elements/Snow/Snow.tsx
  frontend/lib/src/components/shared/ErrorBoundary/ErrorBoundary.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.tsx
  frontend/lib/src/components/shared/Modal/Modal.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInputButton.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInputButton.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/UriOverlayEditor.tsx
  frontend/lib/src/hocs/withPagination/withPagination.test.tsx
  frontend/lib/src/hocs/withPagination/withPagination.tsx
  frontend/lib/src/hooks/useScrollAnimation.ts
  frontend/lib/src/hooks/useScrollSpy.ts
  frontend/lib/src/hooks/useScrollToBottom.ts
  frontend/lib/src/index.ts
  frontend/lib/src/setupTestEnv.js
  frontend/lib/src/setupTests.js
  frontend/lib/src/test_util.tsx
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#8158 Fix chart exception where color-handling code expected DF index to start at 0
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/arrow_altair_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8090 Migrate toast e2e tests to playwright
  e2e/specs/st_toast.spec.js
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[light_theme-webkit].png
  e2e_playwright/st_toast.py
  e2e_playwright/st_toast_test.py
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast+chatInput-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast+chatInput-light.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast-default-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast-default-light.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast-expanded-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast-expanded-light.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast-long-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_toast.spec.js/toast-long-light.snap.png
  frontend/lib/src/components/elements/Toast/Toast.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#8162 Fixed typos in example documentation
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, impact:users, change:docs

#8163 Automatically attach fragmentIds to delta messages
  lib/streamlit/delta_generator.py
  lib/tests/streamlit/delta_generator_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8170 Remove dangling quote from data_editor docstring
  lib/streamlit/elements/widgets/data_editor.py
Labels: security-assessment-completed, impact:internal, change:docs

#8171 Remove .ttf font files
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-Black.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-BlackItalic.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-Bold.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-BoldItalic.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-ExtraLight.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-ExtraLightItalic.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-Italic.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-Light.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-LightItalic.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-Medium.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-MediumItalic.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-Regular.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-SemiBold.ttf
  frontend/app/src/assets/fonts/Source_Code_Pro/SourceCodePro-SemiBoldItalic.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-Black.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-BlackItalic.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-BoldItalic.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLight.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLightItalic.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-Italic.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-LightItalic.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
  frontend/app/src/assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBoldItalic.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-Black.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-BlackItalic.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-Bold.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-BoldItalic.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-ExtraLight.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-ExtraLightItalic.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-Italic.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-Light.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-LightItalic.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-Regular.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-SemiBold.ttf
  frontend/app/src/assets/fonts/Source_Serif_Pro/SourceSerifPro-SemiBoldItalic.ttf
  frontend/app/src/assets/fonts/open-iconic/open-iconic.ttf
Labels: security-assessment-completed, impact:internal, change:chore

#8183 AppTest `from_function` args
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/tests/streamlit/testing/app_test_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#8057 Subtitles changes for `st.video`
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_third[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_webm_with_subtitles[chromium].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_webm_with_subtitles[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_with_subtitles[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_with_subtitles[webkit].png
  e2e_playwright/st_video.py
  e2e_playwright/st_video_test.py
  e2e_playwright/test_assets/sintel-de.vtt
  e2e_playwright/test_assets/sintel-en.vtt
  frontend/lib/src/components/elements/Video/Video.tsx
  lib/streamlit/elements/lib/subtitle_utils.py
  lib/streamlit/elements/media.py
  lib/streamlit/runtime/memory_media_file_storage.py
  lib/tests/streamlit/elements/lib/subtitle_utils_test.py
  lib/tests/streamlit/elements/video_test.py
  proto/streamlit/proto/Video.proto
  scripts/check_license_headers.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#8187 Expander and Status AppTest wrappers
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/app_test_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#8194 Fix: Alert element overflow
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[light_theme-webkit].png
  e2e_playwright/st_alert.py
  e2e_playwright/st_alert_test.py
  frontend/lib/src/components/elements/AlertElement/AlertElement.tsx
  frontend/lib/src/components/elements/AlertElement/styled-components.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8202 Fix popover button padding
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-disabled[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-disabled[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-disabled[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-disabled[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-empty[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-empty[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-empty[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-empty[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-empty[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-empty[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-normal[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-normal[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-normal[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-normal[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-normal[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-normal[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-sidebar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-sidebar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-sidebar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-sidebar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-sidebar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-sidebar[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width[light_theme-webkit].png
  frontend/lib/src/components/elements/Popover/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#8208 Fully clear App State on page change
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8190 Allow the run_every argument to accept the same types as ttl
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/time_util.py
  lib/tests/streamlit/elements/time_widgets_test.py
  lib/tests/streamlit/runtime/caching/cache_utils_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/time_util_test.py
  lib/tests/streamlit/util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8217 Make protobufjs-cli a dev dependency to fix js_test merge gate
  Makefile
  NOTICES
  frontend/lib/package.json
Labels: security-assessment-completed, impact:internal, change:chore
