Repository streamlit/streamlit, pull requests merged in 2024-09, with the labels that each got.

#9385 Remove usage of `stHidden` class
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/Balloons/Balloons.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.tsx
  frontend/lib/src/components/elements/Snow/Snow.test.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9354 Update watchdog so Streamlit can use version 5.X
  lib/setup.py
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/tests/streamlit/watcher/event_based_path_watcher_test.py
Labels: security-assessment-completed, change:chore, impact:users

#9375 Do not format title for MPAv2 in Sidebar nav
  e2e_playwright/multipage_apps_v2/mpa_v2_title.py
  e2e_playwright/multipage_apps_v2/mpa_v2_title_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.test.tsx
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/runtime/app_session_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9333 Fix dialogs not re-opening in some cases after dismiss
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  lib/streamlit/elements/lib/dialog.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9374 Fix edge case where title can be empty string
  lib/streamlit/navigation/page.py
  lib/tests/streamlit/navigation/page_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9393 Fix: Material icon color in buttons
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_hover[webkit].png
  e2e_playwright/st_button_test.py
  frontend/lib/src/components/shared/BaseButton/DynamicButtonLabel.tsx
Labels: security-assessment-completed, change:chore, impact:users

#9379 Fix: Make `showSidebarNavigation` config work in MPAv2
  frontend/app/src/util/AppNavigation.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9390 Determine common mime types by extension
  lib/streamlit/web/server/component_request_handler.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9179 Add config option to set TTL for disconnected sessions
  lib/streamlit/config.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/config_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9395 Fix bold font in header showing less weight
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[webkit].png
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9408 Update page script hash on script start if necessary
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/runtime/app_session_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9414 Replace emails with `test.com` domain to `example.com`. See #9371 for…
  lib/streamlit/testing/v1/local_script_runner.py
  lib/tests/delta_generator_test_case.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/credentials_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/scriptrunner_utils/script_run_context_test.py
  lib/tests/streamlit/user_info_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed, impact:internal, change:chore

#9318 Adding more specific exceptions
  e2e_playwright/st_multiselect_test.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/tests/streamlit/commands/page_config_test.py
  lib/tests/streamlit/elements/chat_test.py
  lib/tests/streamlit/elements/element_policies_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:chore, impact:users

#9394 Update overflowing pages to be more deterministic
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-sidebar-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-sidebar-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_collapsed[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_collapsed[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav_expanded[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/sidebar-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/sidebar-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-sidebar-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-sidebar-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[webkit].png
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/multipage_apps/pages/12_page12.py
  e2e_playwright/multipage_apps/pages/13_page13.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  frontend/app/src/components/Sidebar/NavSection.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9413 Add missing `in` operator to docstring example
  lib/streamlit/runtime/state/query_params_proxy.py
Labels: security-assessment-completed, impact:users, change:docs

#9426 Update websocket reconnect e2e test to use the data-test-connection-state attribute
  e2e_playwright/websocket_reconnects_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#9423 Attempt to remove some e2e flakiness
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_large[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_large[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_large[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_medium[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_medium[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_medium[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_small[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_small[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_small[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_absolute[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_absolute[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_absolute[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_relative[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_relative[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_relative[webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[light_theme-webkit].png
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_columns.py
  e2e_playwright/st_columns_test.py
  e2e_playwright/st_date_input_test.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_plotly_chart_select_test.py
  e2e_playwright/st_pydeck_chart_test.py
  e2e_playwright/st_vega_lite_chart.py
  e2e_playwright/st_vega_lite_chart_test.py
  e2e_playwright/st_video_test.py
  e2e_playwright/st_write_test.py
Labels: security-assessment-completed, change:other, impact:internal

#9436 Migrate hostframe test from Cypress to Playwright
  e2e/scripts/hostframe/pages/02_App_Page_2.py
  e2e/scripts/hostframe/pages/03_App_Page_3.py
  e2e/specs/hostframe.spec.js
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[webkit].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[webkit].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/hostframe_app.py
  e2e_playwright/hostframe_app_test.py
  e2e_playwright/iframe_resizer_test.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/test_assets/hostframe.html
  e2e_playwright/websocket_reconnects_test.py
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-after.snap.png
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-before.snap.png
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/toolbarActions.snap.png
  scripts/run_bare_execution_tests.py
Labels: security-assessment-completed, impact:internal, change:chore

#9314 Remove Cypress
  .github/workflows/cypress-update-snapshots.yml
  .github/workflows/cypress.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Makefile
  frontend/app/craco.config.js
  frontend/app/package.json
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/cypress.json
  frontend/cypress/assets/iframed_streamlit.html
  frontend/cypress/fixtures/example.json
  frontend/cypress/fixtures/file1.txt
  frontend/cypress/fixtures/file2.txt
  frontend/cypress/plugins/index.js
  frontend/cypress/snapshots/linux/2x/st_sidebar.spec.js/date-popover-sidebar.snap.png
  frontend/cypress/snapshots/linux/2x/st_sidebar.spec.js/sidebar-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_sidebar.spec.js/sidebar.snap.png
  frontend/cypress/support/commands.js
  frontend/cypress/support/index.js
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/package.json
  lib/streamlit/elements/lib/built_in_chart_utils.py
  scripts/run_e2e_tests.py
  scripts/slack_notifications.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9359 Convert checkbox and radio to React functional components
  frontend/lib/src/components/shared/Radio/Radio.test.tsx
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.test.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.tsx
  frontend/lib/src/components/widgets/Form/FormClearHelper.ts
  frontend/lib/src/components/widgets/Form/index.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
  frontend/lib/src/components/widgets/Radio/Radio.tsx
  frontend/lib/src/useBasicWidgetState.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9434 Update semver dev dependency
  lib/dev-requirements.txt
  lib/test-requirements.txt
  scripts/update_version.py
Labels: security-assessment-completed, change:other, impact:internal

#9435 Fix codeql warnings
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/runtime/caching/cache_utils.py
Labels: security-assessment-completed, change:other, impact:internal

#9440 Remove Snowpark Pandas integration test
  lib/tests/streamlit/dataframe_util_test.py
Labels: security-assessment-completed, change:other, impact:internal

#9443 Update vega frontend dependencies to support new features
  NOTICES
  frontend/lib/package.json
  frontend/lib/src/setupTestEnv.js
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:users

#9451 Fix python deprecation warnings
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/doc_string.py
  lib/streamlit/runtime/credentials.py
  lib/streamlit/runtime/scriptrunner/magic.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9449 Update vega lite frontend dependency
  NOTICES
  frontend/lib/package.json
  frontend/yarn.lock
  lib/streamlit/elements/vega_charts.py
Labels: security-assessment-completed, change:other, impact:internal

#9453 Fix accidentally watching parent folder for changes
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/streamlit/watcher/path_watcher.py
  lib/tests/streamlit/watcher/event_based_path_watcher_test.py
  lib/tests/streamlit/watcher/path_watcher_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9406 Fix: Disable form submission & instructions
  e2e_playwright/st_form.py
  e2e_playwright/st_form_test.py
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.test.tsx
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9432 Upload pytest test coverage report in CI workflows
  .github/workflows/playwright-changed-files.yml
  .github/workflows/python-tests.yml
  Makefile
  lib/.coveragerc
  lib/pytest.ini
  lib/streamlit/watcher/folder_black_list.py
Labels: security-assessment-completed, change:other, impact:internal

#9448 Enable jest test coverage and upload in CI workflow
  .github/workflows/js-tests.yml
  Makefile
  frontend/lib/jest.config.js
  frontend/lib/src/components/widgets/Radio/styled-components.ts
  frontend/package.json
Labels: security-assessment-completed, impact:internal, change:chore

#9389 Do not clear nodes for fragment-finished-via-rerun messages
  e2e_playwright/st_rerun.py
  e2e_playwright/st_rerun_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/components/core/Block/Block.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9381 Clear queue also for fragment-runs to prevent vanishing elements
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/forward_msg_queue.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/forward_msg_queue_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9439 Add .pdf to the list of safe static files
  lib/streamlit/web/server/app_static_file_handler.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9416 Update descriptions in config.py
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:docs

#9478 Ensure completeness of element mocks for unit tests
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:other, impact:internal

#9441 Migrate Active Script hash to ScriptRunContext
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  lib/streamlit/commands/navigation.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/navigation/page.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/pages_manager_test.py
  lib/tests/streamlit/runtime/scriptrunner_utils/script_run_context_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9472 Replace ad-hoc computation of reversed session_state map with in-memory version
  lib/streamlit/runtime/state/session_state.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/runtime/state/strategies.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9493 Add assert note to element mock test
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:other, impact:internal

#9475 Simplify correct usage of element ID computation
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/utils.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/layouts_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9463 Remove unused metric events
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/SegmentMetricsManager.test.ts
  frontend/app/src/SegmentMetricsManager.ts
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9480 Feature: Add `enter_to_submit` param to `st.form`
  e2e_playwright/st_form.py
  e2e_playwright/st_form_test.py
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.test.tsx
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.test.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/Form/Form.test.tsx
  frontend/lib/src/components/widgets/Form/Form.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.test.tsx
  lib/streamlit/elements/form.py
  lib/tests/streamlit/form_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#9484 Add expanded param to st.navigation
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  frontend/app/src/App.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
  lib/streamlit/commands/navigation.py
  lib/tests/streamlit/commands/navigation_test.py
  proto/streamlit/proto/Navigation.proto
Labels: security-assessment-completed, change:feature, impact:users

#9490 Fix dataframe maximum update depth error
  e2e_playwright/st_dataframe_stable_rendering.py
  e2e_playwright/st_dataframe_stable_rendering_test.py
  e2e_playwright/st_popover.py
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9499 Add warning for nested paths in url path
  lib/streamlit/navigation/page.py
  lib/tests/streamlit/navigation/page_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9464 [feat] Add width and height to st.{map|pydeck_chart}
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-width_and_height[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-width_and_height[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-width_and_height[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-width_and_height[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-custom_width_height[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-custom_width_height[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-custom_width_height[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-custom_width_height[light_theme-webkit].png
  e2e_playwright/st_map.py
  e2e_playwright/st_map_test.py
  e2e_playwright/st_pydeck_chart.py
  e2e_playwright/st_pydeck_chart_test.py
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/styled-components.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/hooks/useStWidthHeight.test.ts
  frontend/lib/src/hooks/useStWidthHeight.ts
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/map_test.py
  proto/streamlit/proto/DeckGlJsonChart.proto
Labels: feature:st.pydeck_chart, feature:st.map, security-assessment-completed, change:feature, impact:users

#9497 [chore] Add VSCode Launch file
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
Labels: area:debugging, security-assessment-completed, impact:internal, change:chore, area:backend

#9501 [feat] Utilize new fullscreen Toolbar for st.{map|pydeck_chart}
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-fullscreen_collapsed[chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-fullscreen_collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-fullscreen_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-fullscreen_expanded[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_collapsed[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_expanded[webkit].png
  e2e_playwright/shared/toolbar_utils.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_map_test.py
  e2e_playwright/st_pydeck_chart_test.py
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/types.ts
Labels: feature:st.pydeck_chart, feature:st.map, security-assessment-completed, change:feature, impact:users

#9506 [fix] Remove unneeded margin on map components
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-fullscreen_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-fullscreen_expanded[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_expanded[webkit].png
  frontend/lib/src/components/elements/DeckGlJsonChart/styled-components.ts
Labels: feature:st.pydeck_chart, feature:st.map, security-assessment-completed, change:bugfix, impact:users

#9283 [Feature] Add new st.pills widget
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[light_theme-webkit].png
  e2e_playwright/st_feedback_test.py
  e2e_playwright/st_pills.py
  e2e_playwright/st_pills_test.py
  frontend/lib/src/components/shared/BaseButton/BaseButton.tsx
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/shared/Icon/DynamicIcon.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
  frontend/lib/src/theme/primitives/radii.ts
  lib/streamlit/__init__.py
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/ButtonGroup.proto
Labels: security-assessment-completed, change:feature, impact:users

#9500 Redirect pages with removed trailing slashes
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/server_util.py
  lib/tests/streamlit/web/server/routes_test.py
  lib/tests/streamlit/web/server/server_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9462 [chore] Add packageManager to package.json
  frontend/package.json
Labels: security-assessment-completed, impact:internal, change:chore

#9526 Hide st.pills command for now
  e2e_playwright/st_pills.py
  lib/streamlit/__init__.py
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9528 Remove fullscreen button for `st.bokeh_chart`
  frontend/lib/src/components/elements/BokehChart/BokehChart.tsx
Labels: security-assessment-completed, change:refactor, impact:users

#9521 Fix `st.json` to keep container bounds
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-keep_bounds[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-keep_bounds[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-keep_bounds[webkit].png
  e2e_playwright/st_json.py
  e2e_playwright/st_json_test.py
  frontend/lib/src/components/elements/Json/Json.tsx
  frontend/lib/src/components/elements/Json/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9377 [feat] Selection on `st.pydeck_chart`
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_select-deselected[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_select-multi-selection[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_select-no-selections[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_select-single-selection[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_selection_state_remains_after_unmounting[chromium].png
  e2e_playwright/shared/pydeck_utils.py
  e2e_playwright/st_pydeck_chart_select.py
  e2e_playwright/st_pydeck_chart_select_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/types.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/colors.test.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/colors.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/jsonConverter.ts
  frontend/lib/src/useBasicWidgetState.ts
  frontend/lib/src/util/assertNever.ts
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/pydeck_test.py
  proto/streamlit/proto/DeckGlJsonChart.proto
Labels: feature:st.pydeck_chart, security-assessment-completed, change:feature, impact:users

#9525 [metrics] adds info about user's browser to pageProfile object
  NOTICES
  frontend/app/src/App.tsx
  frontend/lib/package.json
  frontend/lib/src/util/getBrowserInfo.test.ts
  frontend/lib/src/util/getBrowserInfo.ts
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#9524 [Fix] Embedded app spacing
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9540 super small pr adjusting browser metrics
  frontend/app/src/App.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#9536 [fix] DeckGl zoom button borders and styling
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[light_theme-webkit].png
  e2e_playwright/st_map_test.py
  frontend/lib/src/components/elements/DeckGlJsonChart/styled-components.ts
Labels: feature:st.pydeck_chart, feature:st.map, security-assessment-completed, change:bugfix, impact:users

#9539 Allow array parameters in CLI
  lib/streamlit/config_option.py
  lib/streamlit/web/cli.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9483 Support hierarchical (multi-index) column headers in `st.dataframe`
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
Labels: security-assessment-completed, change:feature, impact:users

#9538 Prefer column config formatting over Pandas styler
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-column_config_over_styler[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-column_config_over_styler[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-column_config_over_styler[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-column_config_over_styler[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-column_config_over_styler[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-column_config_over_styler[light_theme-webkit].png
  e2e_playwright/st_dataframe_styler_support.py
  e2e_playwright/st_dataframe_styler_support_test.py
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/index.ts
Labels: security-assessment-completed, change:feature, impact:users

#9542 Simplify tests to only have a single place to add new commands
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9529 [Fix] Tooltip code block styling
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-code_in_help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-code_in_help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-code_in_help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-code_in_help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-code_in_help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-code_in_help[light_theme-webkit].png
  e2e_playwright/st_metric.py
  e2e_playwright/st_metric_test.py
  frontend/lib/src/components/shared/Tooltip/styled-components.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9552 [fix] st.pydeck_chart selection fixes
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_select-scatterplot-single-selection[chromium].png
  e2e_playwright/shared/pydeck_utils.py
  e2e_playwright/st_pydeck_chart_select.py
  e2e_playwright/st_pydeck_chart_select_test.py
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/colors.ts
  lib/streamlit/elements/deck_gl_json_chart.py
Labels: feature:st.pydeck_chart, security-assessment-completed, change:bugfix, impact:users

#9555 [Fix] Message box title colors
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_with_heading[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_with_heading[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_with_heading[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_with_heading[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_with_heading[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_with_heading[light_theme-webkit].png
  e2e_playwright/st_alert.py
  e2e_playwright/st_alert_test.py
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9511 Remove static element to value_type map & take id in register_widget instead of proto
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9557 Docstrings for 1.39.0
  lib/streamlit/commands/logo.py
  lib/streamlit/commands/navigation.py
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/config.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/empty.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/navigation/page.py
  lib/streamlit/testing/v1/app_test.py
Labels: security-assessment-completed, impact:internal, change:docs

#9554 [Fix] Tooltip visibility in `st.sidebar` & `st.dialog`
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[light_theme-webkit].png
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_sidebar.py
  e2e_playwright/st_sidebar_test.py
  frontend/lib/src/assets/css/vega-tooltip.css
  frontend/lib/src/assets/css/vega-tooltip.scss
Labels: security-assessment-completed, change:bugfix, impact:users
