Repository streamlit/streamlit, pull requests merged in 2024-12, with the labels that each got.

#9913 Remove internal Streamlit details from exception traces
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_inline_error[chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-webkit].png
  lib/streamlit/elements/exception.py
  lib/streamlit/navigation/page.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/tests/streamlit/elements/exception_test.py
  lib/tests/streamlit/elements/support_files/__init__.py
  lib/tests/streamlit/elements/support_files/exception_test_utils.py
Labels: security-assessment-completed, change:feature, impact:users

#9937 [chore] Add eslint-plugin-react-compiler
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_select_test/st_pydeck_chart_selection_state_remains_after_unmounting[chromium].png
  frontend/.eslintrc.js
  frontend/app/package.json
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Maybe/Maybe.test.tsx
  frontend/lib/src/components/elements/BokehChart/BokehChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
  frontend/lib/src/components/shared/ElementFullscreen/useFullscreen.tsx
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomRenderer.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/hooks/useBasicWidgetState.ts
  frontend/lib/src/hooks/useScrollAnimation.ts
  frontend/lib/src/hooks/useScrollSpy.ts
  frontend/lib/src/hooks/useScrollToBottom.ts
  frontend/lib/src/hooks/useStateRef.ts
  frontend/lib/src/util/Hooks.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#9885 Update audio buffer to handle channels better
  frontend/lib/src/components/widgets/AudioInput/convertAudioToWav.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9956 Only show st.cache decorator spinners for cache misses and outermost function
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_closed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_closed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[light_theme-firefox].png
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9961 client.showErrorDetails docstring
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:docs

#9909 Improvements to the showErrorDetails config
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.test.tsx
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  lib/streamlit/config.py
  lib/streamlit/elements/exception.py
  lib/streamlit/error_util.py
  lib/streamlit/errors.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/elements/exception_test.py
  lib/tests/streamlit/error_util_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: feature:config, security-assessment-completed, change:feature, impact:users

#9963 Update metric docstring
  lib/streamlit/elements/metric.py
Labels: security-assessment-completed, impact:internal, change:docs

#9962 Column borders docstring
  lib/streamlit/elements/layouts.py
Labels: security-assessment-completed, impact:internal, change:docs

#9928 Border for `st.metric`
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-border[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-border[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-border[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-border[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-border[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-border[light_theme-webkit].png
  e2e_playwright/st_metric.py
  e2e_playwright/st_metric_test.py
  frontend/lib/src/components/elements/Metric/Metric.test.tsx
  frontend/lib/src/components/elements/Metric/Metric.tsx
  frontend/lib/src/components/elements/Metric/styled-components.ts
  lib/streamlit/elements/metric.py
  lib/tests/streamlit/elements/metric_test.py
  proto/streamlit/proto/Metric.proto
Labels: security-assessment-completed, change:feature, impact:users

#9958 Have Images List not utilize the individual image width parameter
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list_overflow[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list_overflow[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list_overflow[webkit].png
  e2e_playwright/st_image.py
  e2e_playwright/st_image_test.py
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/ImageList/styled-components.ts
  frontend/lib/src/components/shared/Toolbar/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9927 Border for `st.columns`
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_large[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_large[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_medium[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_medium[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_medium[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_small[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_small[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-nested_one_level[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-nested_one_level[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_absolute[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_absolute[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_relative[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_relative[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_relative[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-with_border[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-with_border[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-with_border[webkit].png
  e2e_playwright/st_columns.py
  e2e_playwright/st_columns_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/elements/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#9941 Misc docstring edits for 1.41.0
  lib/streamlit/config.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/bokeh_chart.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
Labels: security-assessment-completed, impact:internal, change:docs

#9968 Update clean command to ignore the e2e_playwright/.streamlit directory
  Makefile
Labels: security-assessment-completed, impact:internal, change:chore

#9966 fixes _does_file_end_in_semicolon function to handle empty tree body
  lib/streamlit/runtime/scriptrunner/magic.py
  lib/tests/streamlit/runtime/scriptrunner/magic_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#9969 Harden more e2e tests
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_second[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_webm_with_subtitles[chromium].png
  e2e_playwright/hello_app_test.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_graphviz_chart_test.py
  e2e_playwright/st_video.py
  e2e_playwright/st_video_test.py
  frontend/lib/src/components/core/Block/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:chore

#9979 Dependency Resolution Cleanup
  NOTICES
  frontend/app/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#9954 Recognise spark connect datatype.
  lib/streamlit/dataframe_util.py
  lib/tests/streamlit/data_mocks/pyspark_connect_mocks.py
  lib/tests/streamlit/data_test_cases.py
Labels: feature:st.dataframe, security-assessment-completed, change:feature, impact:users

#9986 [refactor] Move `st.file_uploader` file type normalization to utils
  lib/streamlit/elements/lib/file_uploader_utils.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/tests/streamlit/file_uploader_utils_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9987 Add AcceptFile enum for proto
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/util/utils.ts
  lib/streamlit/elements/lib/utils.py
  lib/streamlit/elements/widgets/chat.py
  lib/tests/streamlit/elements/chat_test.py
  proto/streamlit/proto/ChatInput.proto
Labels: security-assessment-completed, impact:internal, change:chore

#9996 Release/1.41.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#9994 Preserve target='_blank' for html elements
  frontend/lib/src/components/elements/Html/Html.test.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
Labels: security-assessment-completed, change:bugfix, impact:users, feature:st.html

#10001 make video tests network independent
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video-updated-start[webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_first[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_first[webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_second[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_second[webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_third[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_third[webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_webm_with_subtitles[chromium].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_webm_with_subtitles[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_with_subtitles[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_with_subtitles[webkit].png
  e2e_playwright/st_video.py
  e2e_playwright/st_video_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#9999 Fix: Round corners of `st.image`
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-channels_bgr_red[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-channels_bgr_red[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-channels_bgr_red[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-channels_rgb_blue[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-channels_rgb_blue[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-channels_rgb_blue[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-gif_image[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file_path[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file_path[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file_path[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file_str[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file_str[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_from_file_str[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list_overflow[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list_overflow[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-image_list_overflow[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_red_circle_300[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_red_circle_300[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_red_circle_300[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_red_circle_internal_dim[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_red_circle_internal_dim[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_red_circle_internal_dim[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_0[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_0[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_0[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_0_300[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_0_300[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_0_300[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_100[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_100[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_100[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_100_300[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_100_300[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_100_300[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_50[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_50[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_50[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_50_300[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_50_300[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-svg_yellow_green_rectangle_50_300[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_column_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_column_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_column_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_container_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_container_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-use_container_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-with_caption[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-with_caption[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-with_caption[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-with_caption[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-with_caption[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-with_caption[light_theme-webkit].png
  frontend/lib/src/components/elements/ImageList/styled-components.ts
Labels: security-assessment-completed, change:chore, impact:users

#10003 Update material icons script
  Makefile
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
  scripts/update_material_icon_font_and_names.py
Labels: security-assessment-completed, impact:internal, change:chore

#9990 Update dependency patch versions - Part 1
  frontend/app/package.json
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#10006 Fix #10005
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/typing/date_input_types.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10002 Add an Enum for showErrorDetails Config Options
  lib/streamlit/config.py
  lib/streamlit/elements/exception.py
  lib/tests/streamlit/config_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10011 Do not include source map files in release builds
  .github/workflows/cli-regression.yml
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/conda-build.yml
  .github/workflows/performance-lighthouse.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/playwright.yml
  .github/workflows/pr-preview.yml
  Makefile
  frontend/app/package.json
  frontend/app/vite.config.ts
  frontend/lib/vite.config.ts
  frontend/package.json
Labels: security-assessment-completed, change:bugfix, impact:users

#9938 [feat] Add Playwright Performance Measurements
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright.yml
  Makefile
  e2e_playwright/.gitignore
  e2e_playwright/conftest.py
  e2e_playwright/shared/performance.py
  e2e_playwright/st_form_test.py
  frontend/app/package.json
  frontend/app/src/App.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/vite.config.ts
  frontend/lib/src/components/shared/Profiler/CircularBuffer.test.ts
  frontend/lib/src/components/shared/Profiler/CircularBuffer.ts
  frontend/lib/src/components/shared/Profiler/Profiler.tsx
  frontend/lib/src/components/shared/Profiler/index.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/theme/utils.ts
  frontend/lib/src/util/performance/fns.ts
  frontend/lib/src/util/performance/index.ts
  frontend/lib/src/util/performance/types.ts
  frontend/package.json
  scripts/check_license_headers.py
Labels: security-assessment-completed, impact:internal, change:feature

#10016 [fix] Utilize profiler build for e2e tests
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#10010 Initialize mimetypes on server initialization
  lib/streamlit/web/server/app_static_file_handler.py
  lib/streamlit/web/server/component_request_handler.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9991 Update dependency patch versions - Part 2
  frontend/app/package.json
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#10009 Move `showDevelopmentOptions` out of App.tsx
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/showDevelopmentOptions.ts
Labels: security-assessment-completed, impact:internal, change:chore

#10014 `AppView` prop refactor - Part 1
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/Block/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10021 Release/1.41.1
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#10018 Schedule trigger events at the end of the event loop
  e2e_playwright/widget_state.py
  e2e_playwright/widget_state_test.py
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10030 Fix visualization of disabled feedback
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[light_theme-webkit].png
  e2e_playwright/st_feedback.py
  e2e_playwright/st_feedback_test.py
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10032 Update setTriggerValueAtEndOfEventLoop docstring
  frontend/lib/src/WidgetStateManager.ts
Labels: security-assessment-completed, impact:internal, change:docs

#9983 Prevent tooltips from overflowing on the left or right side
  e2e_playwright/help_tooltip.py
  e2e_playwright/help_tooltip_test.py
  frontend/lib/src/components/shared/Tooltip/Tooltip.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10034 Use configured column order for pinned columns
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10033 [refactor] Utilize userEvent in tests
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/Dialog/Dialog.test.tsx
  frontend/lib/src/components/elements/Expander/Expander.test.tsx
  frontend/lib/src/components/elements/Markdown/Markdown.test.tsx
  frontend/lib/src/components/elements/PageLink/PageLink.test.tsx
  frontend/lib/src/components/elements/Popover/Popover.test.tsx
  frontend/lib/src/components/elements/TextElement/TextElement.test.tsx
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/shared/BaseButton/BaseButton.test.tsx
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Radio/Radio.test.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.test.tsx
  frontend/lib/src/components/shared/Tooltip/OverflowTooltip.test.tsx
  frontend/lib/src/components/shared/Tooltip/Tooltip.test.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInputActionButtons.test.tsx
  frontend/lib/src/components/widgets/Button/Button.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.test.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.test.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.test.tsx
  frontend/lib/src/components/widgets/FileUploader/withPagination/Pagination.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.test.tsx
  frontend/lib/src/hooks/useWidgetManagerElementState.test.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#10035 Fix handling of empty hierarchical column headers
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-hierarchical_headers[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10036 Fix issue with dataframe width getting ignored
  e2e_playwright/st_dataframe_dimensions.py
  e2e_playwright/st_dataframe_dimensions_test.py
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10039 [fix] Ensure all e2e_playwright artifacts are relative to git root
  e2e_playwright/conftest.py
  e2e_playwright/shared/git_utils.py
  e2e_playwright/shared/performance.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10058 Add back `CONTRIBUTING.md` with shortened text
  CONTRIBUTING.md
  README.md
Labels: security-assessment-completed, change:other, impact:internal

#10048 Update chat input send button hover UI
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[webkit].png
  e2e_playwright/st_chat_input_test.py
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10044 Refactor debounce callbacks to allow dependency inspection
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/hooks/useDebouncedCallback.test.ts
  frontend/lib/src/hooks/useDebouncedCallback.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9860 Modernize shared selectbox component
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#10062 preserve white space sequences and segment breaks in `st.text`
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-rendering[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-rendering[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-rendering[webkit].png
  e2e_playwright/st_text.py
  e2e_playwright/st_text_test.py
  frontend/lib/src/components/elements/TextElement/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10066 Add size limitation note to audio_input
  lib/streamlit/elements/widgets/audio_input.py
Labels: security-assessment-completed, impact:internal, change:docs

#10064 Set `use_container_width=True` by default for charts
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-bar_chart_overwritten_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-bar_chart_overwritten_theme[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-bar_chart_overwritten_theme[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-bar_chart_overwritten_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-bar_chart_overwritten_theme[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-bar_chart_overwritten_theme[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-menu_styling[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_default_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_default_theme[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_default_theme[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_default_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_default_theme[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_default_theme[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_overwritten_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_overwritten_theme[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_overwritten_theme[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_overwritten_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_overwritten_theme[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_overwritten_theme[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_streamlit_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_streamlit_theme[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_streamlit_theme[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_streamlit_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_streamlit_theme[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-scatter_chart_streamlit_theme[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line_chart_specific_height_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line_chart_specific_height_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line_chart_specific_height_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line_chart_specific_height_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line_chart_specific_height_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line_chart_specific_height_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[light_theme-webkit].png
  e2e_playwright/st_altair_chart.py
  e2e_playwright/st_vega_lite_chart.py
  lib/streamlit/elements/bokeh_chart.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/plotly_chart_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10094 [Fix] Status Widget Test
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore
