Repository streamlit/streamlit, pull requests merged in 2024-07, with the labels that each got.

#9008 Fix: MPA duplicate page name key error
  frontend/app/src/components/Sidebar/SidebarNav.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#8989 Set theme hash properly on load if a custom theme is active to start
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9010 Don't remove session refs on fragment runs
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8972 Clarify page execution
  lib/streamlit/commands/navigation.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/media.py
  lib/streamlit/navigation/page.py
Labels: security-assessment-completed, impact:internal, change:docs

#8842 Allow custom theme to be inserted before our theme
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9005 Remove old config options - part 1
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:chore, impact:users

#9013 Remove old config options - part 2
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/watcher/path_watcher.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:chore, impact:users

#9017 Fix: Typing for image.py
  lib/streamlit/elements/image.py
Labels: security-assessment-completed, impact:internal, change:chore

#9018 Remove `deprecation.showPyplotGlobalUse` config option
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_pyplot_test.py
  lib/streamlit/config.py
  lib/streamlit/elements/exception.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/errors.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/elements/pyplot_test.py
Labels: security-assessment-completed, change:other, impact:users

#9023 Fix lag when closing dialog
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
Labels: security-assessment-completed, change:feature, impact:users

#9022 Refactor and clean-up `type_util` module
  e2e_playwright/shared/data_mocks.py
  e2e_playwright/st_data_editor_input_data.py
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/elements/lib/utils.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/state/session_state_proxy.py
  lib/streamlit/runtime/state/widgets.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/dataframe_coercion_test.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/arrow_add_rows_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/arrow_table_test.py
  lib/tests/streamlit/elements/checkbox_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/element_utils_test.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/elements/metric_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9028 Simplify `convert_anything_to_df` utility method
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/tests/streamlit/dataframe_coercion_test.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/arrow_table_test.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9027 Fix broken `st.navigation` docstring
  lib/streamlit/commands/navigation.py
Labels: security-assessment-completed, impact:users, change:docs

#9029 Refactor and simplify the `ensure_indexable` utility method
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/multiselect_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9024 Bundle policy checks in convenient function for widget checks
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/element_policies_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9033 Refactor and simplify dataframe related type checks
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/arrow_add_rows_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/arrow_table_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9042 Centralize data type alias
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/vega_charts.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9044 Add `convert_anything_to_arrow_bytes` method
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/dataframe_util_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9035 Improvements to NumberInput formatting
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  lib/streamlit/elements/widgets/number_input.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8897 Format code in docstrings via ruff
  .ruff.toml
  e2e_playwright/conftest.py
  lib/streamlit/code_util.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/commands/logo.py
  lib/streamlit/commands/navigation.py
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/bokeh_chart.py
  lib/streamlit/elements/code.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/doc_string.py
  lib/streamlit/elements/empty.py
  lib/streamlit/elements/exception.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/graphviz_chart.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/html.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/spinner.py
  lib/streamlit/elements/text.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/legacy_cache_api.py
  lib/streamlit/runtime/connection_factory.py
  lib/streamlit/testing/v1/util.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9053 Hide all Particles upon printing
  frontend/lib/src/components/elements/Particles/Particles.tsx
  frontend/lib/src/components/elements/Particles/styled-components.ts
Labels: area:ux/ui, security-assessment-completed, change:bugfix, impact:users

#8994 Fix: MPA support of custom themes
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[webkit].png
  e2e_playwright/multipage_apps/mpa_v2_custom_theme.py
  e2e_playwright/multipage_apps/mpa_v2_custom_theme_test.py
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-after.snap.png
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-before.snap.png
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/toolbarActions.snap.png
  frontend/lib/src/theme/emotionDarkTheme/themeColors.ts
  frontend/lib/src/theme/emotionLightTheme/themeColors.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9059 `st.switch_page` clears non-embed query params
  e2e_playwright/multipage_apps/mpa_basics.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/multipage_apps/pages/02_page2.py
  lib/streamlit/commands/execution_control.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8992 Stacking options - `st.area_chart`
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-11[chromium].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-11[firefox].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-11[webkit].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-12[chromium].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-12[firefox].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-12[webkit].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-13[chromium].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-13[firefox].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-13[webkit].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-14[chromium].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-14[firefox].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-14[webkit].png
  e2e_playwright/st_area_chart.py
  e2e_playwright/st_area_chart_test.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9062 Fix issue with button clicks for enqueued fragments being dropped
  e2e_playwright/st_fragment_queue.py
  e2e_playwright/st_fragment_queue_test.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9061 Fix secrets.toml Windows Path Bug
  lib/streamlit/file_util.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9041 Fix fragment exception impacts queued fragments
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_inline_error[chromium].png
  e2e_playwright/st_fragment_multiple_fragments.py
  e2e_playwright/st_fragment_multiple_fragments_test.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/elements/layouts_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/scriptrunner/code_exec_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8976 READ only headers and cookies
  lib/streamlit/__init__.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/context.py
  lib/streamlit/web/server/websocket_headers.py
  lib/tests/streamlit/runtime/context_tests.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/web/server/websocket_headers_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9012 Improve chat input docstring for fragment usage
  lib/streamlit/elements/widgets/chat.py
Labels: security-assessment-completed, impact:users, change:docs

#9019 De-experimentalize st.fragment
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_inline_error[chromium].png
  e2e_playwright/__snapshots__/linux/st_fragment_chat_response_test/chart_after_fragment_rerun[chromium].png
  e2e_playwright/__snapshots__/linux/st_fragment_chat_response_test/chart_before_fragment_rerun[chromium].png
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_color_picker.py
  e2e_playwright/st_dataframe_selections.py
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_experimental_fragment_multiple_fragments_test.py
  e2e_playwright/st_fragment_basics.py
  e2e_playwright/st_fragment_basics_test.py
  e2e_playwright/st_fragment_chat_response.py
  e2e_playwright/st_fragment_chat_response_test.py
  e2e_playwright/st_fragment_dynamic_form.py
  e2e_playwright/st_fragment_dynamic_form_test.py
  e2e_playwright/st_fragment_mixed_execution_flow.py
  e2e_playwright/st_fragment_mixed_execution_flow_test.py
  e2e_playwright/st_fragment_multiple_fragments.py
  e2e_playwright/st_fragment_multiple_fragments_test.py
  e2e_playwright/st_fragment_queue.py
  e2e_playwright/st_fragment_queue_test.py
  e2e_playwright/st_fragment_run_every.py
  e2e_playwright/st_fragment_run_every_test.py
  e2e_playwright/st_fragments_nested.py
  e2e_playwright/st_fragments_nested_test.py
  e2e_playwright/st_rerun.py
  e2e_playwright/st_rerun_test.py
  e2e_playwright/st_select_slider.py
  e2e_playwright/st_slider.py
  lib/streamlit/__init__.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/forward_msg_queue.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/metrics_util.py
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/streamlit/runtime/scriptrunner/script_requests.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/commands/execution_control_test.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/layouts_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/forward_msg_queue_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/runtime/scriptrunner/code_exec_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_requests_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#9020 De-experimentalize st.dialog
  e2e_playwright/st_dialog.py
  lib/streamlit/__init__.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/tests/streamlit/elements/layouts_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#8873 Only expose selected objects in `components` module
  lib/streamlit/components/v1/components.py
Labels: stale, security-assessment-completed, impact:internal, change:refactor

#9094 Update the feedback widget design
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-faces[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-stars[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_feedback_test/st_feedback-thumbs[light_theme-webkit].png
  e2e_playwright/st_feedback_test.py
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  lib/streamlit/elements/widgets/button_group.py
Labels: security-assessment-completed, change:chore, impact:users

#9097 Move the filled star icon for feedback widget from python code to web app
  frontend/lib/src/components/shared/Icon/DynamicIcon.test.tsx
  frontend/lib/src/components/shared/Icon/DynamicIcon.tsx
  frontend/lib/src/components/shared/Icon/index.tsx
  frontend/lib/src/components/shared/Icon/styled-components.ts
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
  lib/streamlit/elements/widgets/button_group.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9111 Adding functionality for st.audio_input on python side
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  lib/streamlit/elements/widgets/audio_input.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/AudioInput.proto
  proto/streamlit/proto/Element.proto
Labels: security-assessment-completed, impact:internal, change:chore

#8990 Validate the path using Tornado before performing checks
  lib/streamlit/web/server/app_static_file_handler.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9114 Reset ctx.current_fragment_id to last ID instead of None
  lib/streamlit/runtime/fragment.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9113 Temp solution to fix invalid material icon error rendering
  lib/streamlit/string_util.py
  lib/tests/streamlit/elements/layouts_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#9096 Refactor: NumberInput
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: feature:st.number_input, security-assessment-completed, impact:internal, change:refactor

#9115 Docstrings for 1.37.0
  lib/streamlit/commands/execution_control.py
  lib/streamlit/config.py
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/progress.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/context.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/testing/v1/app_test.py
Labels: security-assessment-completed, impact:internal, change:docs

#9129 Print bottom container always at the end of the app content
  frontend/app/src/components/AppView/styled-components.ts
Labels: security-assessment-completed, change:chore, impact:users

#9110 Make the magic support for-else, while-else, try-else, try-except*, and match
  lib/streamlit/runtime/scriptrunner/magic.py
  lib/tests/streamlit/runtime/scriptrunner/magic_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9126 Migrate websocket-reconnect from Cypress to Playwright
  e2e/specs/websocket_reconnects.spec.js
  e2e_playwright/websocket_reconnects.py
  e2e_playwright/websocket_reconnects_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#9130 Fix copy-buttons in dialogs
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_dataframe_selections_test.py
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
  frontend/lib/src/components/elements/Json/Json.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9103 Support theming in embed better
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/util/useThemeManager.ts
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
  frontend/lib/src/index.ts
  frontend/lib/src/theme/types.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9083 [RFC] Only rerun script on reconnect if a script run was interrupted
  e2e_playwright/websocket_reconnects.py
  e2e_playwright/websocket_reconnects_test.py
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:feature, impact:users

#9101 Fix #8638
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9092 Bugfix: Multiple Stale Maps
  e2e_playwright/st_map_ensure_no_stale_maps.py
  e2e_playwright/st_map_ensure_no_stale_maps_test.py
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9144 Bugfix: Upgrade plotly.js to resolve hover tooltip bug
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, change:bugfix, impact:users

#9149 Remove a type ignore
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/time_widgets.py
Labels: security-assessment-completed, change:chore, impact:users

#9167 Make ScriptControlException inherit from BaseException again
  e2e_playwright/st_rerun.py
  e2e_playwright/st_rerun_test.py
  lib/streamlit/runtime/scriptrunner/exceptions.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9172 Add syntax highlighting for diff
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-diff_lang[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-diff_lang[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-diff_lang[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-diff_lang[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-diff_lang[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-diff_lang[light_theme-webkit].png
  e2e_playwright/st_code.py
  e2e_playwright/st_code_test.py
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#9175 Support `to_pandas` method to return a Pandas Series
  lib/streamlit/dataframe_util.py
Labels: security-assessment-completed, change:feature, impact:users

#9173 Remove EXCLUDE_FILES from scripts/mypy
  scripts/mypy
Labels: security-assessment-completed, impact:internal, change:chore

#9153 Utilize null or undefined helpers & add lint rule
  frontend/.eslintrc.js
  frontend/app/src/App.tsx
  frontend/app/src/SegmentMetricsManager.ts
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.tsx
  frontend/app/src/util/ScreenCastRecorder.ts
  frontend/eslint-plugin-streamlit-custom/index.js
  frontend/eslint-plugin-streamlit-custom/package.json
  frontend/eslint-plugin-streamlit-custom/use-strict-null-equality-checks.js
  frontend/eslint-plugin-streamlit-custom/use-strict-null-equality-checks.test.js
  frontend/lib/package.json
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  frontend/lib/src/ForwardMessageCache.ts
  frontend/lib/src/SessionInfo.ts
  frontend/lib/src/WidgetStateManager.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.ts
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.test.tsx
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/IFrame/IFrame.tsx
  frontend/lib/src/components/widgets/BaseWidget/WidgetLabel.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentRegistry.ts
  frontend/lib/src/components/widgets/CustomComponent/componentUtils.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/components/widgets/Form/FormClearHelper.ts
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/util/utils.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore
