Repository streamlit/streamlit, pull requests merged in 2024-08, with the labels that each got.

#9181 Enable a little additional strictness in mypy.ini
  lib/mypy.ini
Labels: security-assessment-completed, impact:internal, change:chore

#9178 Revert "Remove fragment_ids_this_run from script run context (#8953)" and tweaks some types
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_rerun.py
  e2e_playwright/st_rerun_test.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/metrics_util.py
  lib/streamlit/runtime/scriptrunner/script_requests.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/session_state.py
  lib/tests/streamlit/commands/execution_control_test.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9190 Allow adding Plotly toolbar buttons
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-toolbar_customization[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-toolbar_customization[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-toolbar_customization[webkit].png
  e2e_playwright/st_plotly_chart.py
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9189 Ignore all headings in markdown labels
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9183 Don't raise FragmentStorageKeyError for auto_rerun fragments
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/scriptrunner/script_requests.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  proto/streamlit/proto/ClientState.proto
Labels: security-assessment-completed, change:bugfix, impact:users

#9199 Fix uncaught exception metrics tracking
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/scriptrunner/code_exec_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#9078 Add support for Kubernetes / directory with mounted file style secrets
  lib/streamlit/config.py
  lib/streamlit/runtime/secrets.py
  lib/streamlit/testing/v1/app_test.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/connection_factory_test.py
  lib/tests/streamlit/runtime/secrets_test.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#9186 Fix ghost tabs issue in fragments
  e2e_playwright/st_fragment_dynamic_containers.py
  e2e_playwright/st_fragment_dynamic_containers_test.py
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9191 Treat @streamlit as an internal import for eslint
  frontend/.eslintrc.js
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/SegmentMetricsManager.ts
  frontend/app/src/SessionEventDispatcher.ts
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/ThemedApp.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Countdown/Countdown.test.tsx
  frontend/app/src/components/EventContainer/EventContainer.test.tsx
  frontend/app/src/components/EventContainer/EventContainer.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/MainMenu/styled-components.ts
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.test.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/components/StatusWidget/styled-components.ts
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployCard.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployModal.tsx
  frontend/app/src/components/StreamlitDialog/ScriptChangedDialog.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/app/src/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/UnsupportedBrowserDialog/UnsupportedBrowserDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.test.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.test.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.tsx
  frontend/app/src/styled-components.ts
  frontend/app/src/util/useThemeManager.test.ts
Labels: security-assessment-completed, impact:internal, change:chore

#9206 Fix empty anchor scrolling
  e2e_playwright/st_heading.py
  e2e_playwright/st_heading_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9215 Only clear up fragment-related stale widgets
  e2e_playwright/st_rerun.py
  e2e_playwright/st_rerun_test.py
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9200 Release/1.37.1
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#9214 Make pre renderer more generic
  e2e_playwright/st_code_test.py
  frontend/lib/src/components/elements/CodeBlock/CodeBlock.test.tsx
  frontend/lib/src/components/elements/CodeBlock/CodeBlock.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/CodeBlock/index.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9219 Update dataframe-related frontend dependencies
  frontend/lib/package.json
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#9205 Extend dataframe-handling support for collection-like types
  e2e_playwright/__snapshots__/linux/st_data_editor_input_data_test/st_data_editor-input_data_21[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_input_data_test/st_data_editor-input_data_21[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_input_data_test/st_data_editor-input_data_21[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_input_data_test/st_dataframe-input_data_21[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_input_data_test/st_dataframe-input_data_21[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_input_data_test/st_dataframe-input_data_21[webkit].png
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
  lib/tests/streamlit/snowpandas_mocks.py
  lib/tests/streamlit/snowpark_mocks.py
  lib/tests/streamlit/type_util_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9220 Fix CI issue with `bash -login`
  .github/actions/build_info/action.yml
  .github/actions/make_init/action.yml
  .github/actions/preview_branch/action.yml
  .github/workflows/cli-regression.yml
  .github/workflows/conda-build.yml
  .github/workflows/cypress-update-snapshots.yml
  .github/workflows/cypress.yml
  .github/workflows/ensure-relative-imports.yml
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/playwright.yml
  .github/workflows/pr-preview.yml
  .github/workflows/python-bare-executions.yml
  .github/workflows/python-min-deps.yml
  .github/workflows/python-tests.yml
  .github/workflows/release.yml
Labels: security-assessment-completed, change:other, impact:internal

#9222 Add support for Snowpark Pandas Index
  .github/workflows/python-tests.yml
  Makefile
  lib/setup.py
  lib/streamlit/dataframe_util.py
  lib/tests/conftest.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/snowpandas_mocks.py
Labels: security-assessment-completed, change:feature, impact:users

#9234 Fix issue with empty Azure OpenAI chunk
  lib/streamlit/elements/write.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9230 Add data handling support for Polars
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  lib/streamlit/dataframe_util.py
  lib/test-requirements.txt
  lib/tests/streamlit/data_mocks.py
Labels: security-assessment-completed, change:feature, impact:users

#9231 Fix grey-out for selectbox index columns
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9225 Use material icons in streamlit hello page nav and favicons
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[webkit].png
  e2e_playwright/hello_app_test.py
  lib/streamlit/hello/Animation_Demo.py
  lib/streamlit/hello/Dataframe_Demo.py
  lib/streamlit/hello/Hello.py
  lib/streamlit/hello/Mapping_Demo.py
  lib/streamlit/hello/Plotting_Demo.py
  lib/streamlit/hello/streamlit_app.py
Labels: security-assessment-completed, change:chore, impact:users

#9235 Add data handling support for xarray
  lib/streamlit/dataframe_util.py
  lib/test-requirements.txt
  lib/tests/streamlit/data_mocks.py
Labels: security-assessment-completed, change:feature, impact:users

#9241 Fix options support for `dict.items()`
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/metrics_util.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/elements/radio_test.py
  lib/tests/streamlit/elements/select_slider_test.py
  lib/tests/streamlit/elements/selectbox_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9244 Use shlex.join in mypy (script) instead of backporting it
  scripts/mypy
Labels: security-assessment-completed, impact:internal, change:refactor

#9240 Add data handling support for Dask
  lib/streamlit/dataframe_util.py
  lib/test-requirements.txt
  lib/tests/streamlit/dask_mocks.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/dataframe_util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9254 Fix mypy errors
  lib/dev-requirements.txt
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/metric.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/streamlit/source_util.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9256 Add data handling support for Ray
  e2e_playwright/__snapshots__/linux/st_data_editor_input_data_test/st_data_editor-input_data_24[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_input_data_test/st_data_editor-input_data_24[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_input_data_test/st_data_editor-input_data_24[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_input_data_test/st_dataframe-input_data_24[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_input_data_test/st_dataframe-input_data_24[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_input_data_test/st_dataframe-input_data_24[webkit].png
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
  lib/tests/streamlit/ray_mocks.py
Labels: security-assessment-completed, change:feature, impact:users

#9255 Fix Circular Imports: Move functions out of delta_generator
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/dialog.py
  lib/streamlit/elements/lib/mutable_status_container.py
  lib/streamlit/runtime/scriptrunner/__init__.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/tests/streamlit/script_run_context_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9131 Migrate to test-state attribute to capture e2e script state
  e2e_playwright/app_hotkeys.py
  e2e_playwright/app_hotkeys_test.py
  e2e_playwright/conftest.py
  e2e_playwright/shared/app_utils.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/cypress/support/commands.js
  frontend/lib/src/ScriptRunState.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9245 Remove custom globbing from the mypy script & rename
  .github/workflows/python-tests.yml
  Makefile
  scripts/mypy_custom_script.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9263 Refactor integration test setup
  .github/workflows/python-tests.yml
  Makefile
  lib/integration-requirements.txt
  lib/pytest.ini
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/external/langchain/streamlit_callback_handler.py
  lib/streamlit/web/bootstrap.py
  lib/test-requirements.txt
  lib/tests/conftest.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/connections/snowflake_connection_test.py
  lib/tests/streamlit/connections/snowpark_connection_test.py
  lib/tests/streamlit/connections/sql_connection_test.py
  lib/tests/streamlit/connections/util_test.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/audio_test.py
  lib/tests/streamlit/external/langchain/streamlit_callback_handler_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/streamlit/web/cli_test.py
  scripts/check_license_headers.py
Labels: security-assessment-completed, dev:upgrade-dependencies, impact:internal, change:refactor

#9048 Type-hint improvements for #8717 and #7801
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/typing/__init__.py
  lib/tests/streamlit/typing/number_input_types.py
  lib/tests/streamlit/typing/selectbox_types.py
  lib/tests/streamlit/typing/slider_types.py
  scripts/mypy_custom_script.py
Labels: security-assessment-completed, change:feature, impact:users

#8984 Allow configurable expansion depth for `st.json`
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-empty_dict[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-expanded_2[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-expanded_2[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-expanded_2[webkit].png
  e2e_playwright/st_json.py
  e2e_playwright/st_json_test.py
  frontend/lib/src/components/elements/Json/Json.tsx
  lib/streamlit/elements/json.py
  lib/tests/streamlit/elements/json_test.py
  proto/streamlit/proto/Json.proto
Labels: security-assessment-completed, change:feature, impact:users

#9266 Fix Circular Imports: Move deltagenerator static variable to own file
  lib/streamlit/__init__.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/delta_generator_singletons.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/form_utils.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/tests/streamlit/delta_generator_singletons_test.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/form_utils_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9257 Remove pydantic fix in bootstrap
  lib/integration-requirements.txt
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/external/pydantic_integration.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed, change:breaking, change:refactor, impact:users

#9269 Add a build option for easier embedding of Streamlit.
  frontend/app/craco.config.js
  frontend/app/package.json
Labels: security-assessment-completed, change:other, impact:internal

#9274 Add data handling support for DB API 2.0
  .github/workflows/python-tests.yml
  lib/integration-requirements.txt
  lib/streamlit/dataframe_util.py
  lib/tests/streamlit/dataframe_util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9187 When clearing forward queue add a stopped for rerun message
  lib/streamlit/runtime/forward_msg_queue.py
  lib/tests/streamlit/runtime/forward_msg_queue_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9280 Fix codeql warnings
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/error_util.py
  lib/streamlit/runtime/context.py
  lib/streamlit/runtime/fragment.py
  lib/tests/streamlit/error_util_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:other, impact:internal

#9276 Do not preserve children of a block if the block type changes
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9285 Unstale just updated fragments
  frontend/lib/src/components/core/Block/utils.test.ts
  frontend/lib/src/components/core/Block/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9246 Fix nested fragment stale elements
  e2e_playwright/st_fragments_nested.py
  e2e_playwright/st_fragments_nested_test.py
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  lib/streamlit/runtime/fragment.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:refactor, impact:users

#9286 Adding issue template for kudos
  .github/ISSUE_TEMPLATE/thank_streamlit_team.yml
Labels: security-assessment-completed, change:other, impact:internal

#9290 Add data handling support for Pydantic instances
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/write.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9289 Add support for dataframe interchange protocol
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/write.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/data_mocks.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/arrow_table_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/snowpandas_mocks.py
Labels: security-assessment-completed, change:feature, impact:users

#9216 Use overloads to make the return types of st.feedback more precise. (with type tests)
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  lib/tests/streamlit/typing/feedback.py
  lib/tests/streamlit/typing/readme.md
  scripts/mypy_custom_script.py
Labels: security-assessment-completed, change:refactor, impact:users

#9294 Migrate the copy button to functional component
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9291 Refactor frontend styles, class names and test-ids - Part 2
  e2e/specs/st_image.spec.js
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-hover_copy[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-hover_copy[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-hover_copy[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-hover_copy[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-hover_copy[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-hover_copy[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/syntax_highlighting-hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/syntax_highlighting-hover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/syntax_highlighting-hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/syntax_highlighting-hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/syntax_highlighting-hover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/syntax_highlighting-hover[light_theme-webkit].png
  e2e_playwright/deploy_dialog_test.py
  e2e_playwright/main_menu_test.py
  e2e_playwright/st_code_test.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_help_test.py
  e2e_playwright/st_pyplot_test.py
  e2e_playwright/st_write_test.py
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/UnsupportedBrowserDialog/UnsupportedBrowserDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.test.tsx
  frontend/lib/src/components/elements/AlertElement/AlertElement.test.tsx
  frontend/lib/src/components/elements/AlertElement/styled-components.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/Dialog/Dialog.test.tsx
  frontend/lib/src/components/elements/DocString/DocString.test.tsx
  frontend/lib/src/components/elements/DocString/DocString.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/Json/Json.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.test.tsx
  frontend/lib/src/components/elements/Skeleton/AppSkeleton.test.tsx
  frontend/lib/src/components/elements/Skeleton/AppSkeleton.tsx
  frontend/lib/src/components/elements/Skeleton/Skeleton.test.tsx
  frontend/lib/src/components/elements/Skeleton/Skeleton.tsx
  frontend/lib/src/components/shared/AlertContainer/AlertContainer.test.tsx
  frontend/lib/src/components/shared/AlertContainer/AlertContainer.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/shared/ErrorElement/ErrorElement.test.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/lib/src/components/shared/Icon/Material/styled-components.ts
  frontend/lib/src/components/shared/Modal/Modal.test.tsx
  frontend/lib/src/components/shared/Modal/Modal.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.test.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.tsx
  frontend/lib/src/components/shared/Tooltip/Tooltip.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9293 Clean up data handling utils
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/tests/streamlit/data_mocks/__init__.py
  lib/tests/streamlit/data_mocks/dask_mocks.py
  lib/tests/streamlit/data_mocks/modin_mocks.py
  lib/tests/streamlit/data_mocks/pyspark_mocks.py
  lib/tests/streamlit/data_mocks/ray_mocks.py
  lib/tests/streamlit/data_mocks/snowpandas_mocks.py
  lib/tests/streamlit/data_mocks/snowpark_mocks.py
  lib/tests/streamlit/data_test_cases.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/elements/radio_test.py
  lib/tests/streamlit/elements/select_slider_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9298 Fix logo + sidebar sizing interaction
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/lib/src/theme/primitives/sizes.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9311 completely remove mypy_custom_script.py
  .github/workflows/python-tests.yml
  Makefile
  scripts/mypy_custom_script.py
Labels: security-assessment-completed, change:other, impact:internal

#9308 Migrate `set_page_config` e2e test to playwright
  e2e/scripts/st_set_page_config.py
  e2e/specs/st_set_page_config.spec.js
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_set_page_config.py
  e2e_playwright/st_set_page_config_icon.py
  e2e_playwright/st_set_page_config_icon_test.py
  e2e_playwright/st_set_page_config_test.py
  frontend/cypress/snapshots/linux/2x/st_set_page_config.spec.js/wide-mode-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_set_page_config.spec.js/wide-mode.snap.png
Labels: security-assessment-completed, impact:internal, change:refactor

#9307 Migrate `st.sidebar` e2e test to playwright
  e2e/specs/hostframe.spec.js
  e2e/specs/st_sidebar.spec.js
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-display[light_theme-webkit].png
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/multipage_apps/mpa_configure_sidebar_test.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_caption_test.py
  e2e_playwright/st_markdown_test.py
  e2e_playwright/st_sidebar.py
  e2e_playwright/st_sidebar_test.py
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9305 Remove experimental cached widget replay logic
  e2e_playwright/st_cache_data.py
  e2e_playwright/st_cache_data_test.py
  e2e_playwright/st_cache_resource.py
  e2e_playwright/st_cache_resource_test.py
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/streamlit/runtime/caching/legacy_cache_api.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/elements/element_policies_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/caching/test_data/cached_widget_replay_dynamic.py
  lib/tests/streamlit/testing/app_test_test.py
Labels: security-assessment-completed, change:breaking, change:refactor, impact:users

#9309 Migrate `download_button` e2e test to playwright
  e2e/specs/st_download_button.spec.js
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-default[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-default[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-default[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-default[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-default[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-default[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-disabled[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-disabled[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-disabled[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-disabled[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-primary[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-primary[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-primary[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-primary[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-primary[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-primary[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width_help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width_help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width_help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width_help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width_help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-use_container_width_help[light_theme-webkit].png
  e2e_playwright/st_download_button.py
  e2e_playwright/st_download_button_test.py
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/container-width-help-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/container-width-help-button.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/disabled-download-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/disabled-download-button.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/download-button-widget-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/download-button-widget.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/primary-download-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/primary-download-button.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/use-container-width-button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_download_button.spec.js/use-container-width-button.snap.png
Labels: security-assessment-completed, impact:internal, change:refactor

#9296 Add type hinting and tests for `select_slider` and `radio` widgets
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/tests/streamlit/typing/radio_types.py
  lib/tests/streamlit/typing/select_slider_types.py
Labels: security-assessment-completed, change:other, impact:internal

#9317 Reformat some comments so that `make help` works.
  Makefile
Labels: security-assessment-completed, impact:internal, change:docs

#8558 Add line wrapping to st code
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-wrap[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-wrap[light_theme-webkit].png
  e2e_playwright/st_code.py
  e2e_playwright/st_code_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  lib/streamlit/elements/code.py
  lib/tests/streamlit/elements/code_test.py
  proto/streamlit/proto/Code.proto
Labels: security-assessment-completed, change:feature, impact:users

#9319 Docs for release 1.38.0
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
Labels: security-assessment-completed, impact:internal, change:docs

#9321 Disable Python integration tests temporarily
  .github/workflows/python-tests.yml
Labels: security-assessment-completed, impact:internal, change:chore

#9301 Add icon to `st.button`
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-emoji_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-emoji_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-emoji_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-emoji_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-emoji_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-emoji_icon[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon[light_theme-webkit].png
  e2e_playwright/st_button.py
  e2e_playwright/st_button_test.py
  frontend/lib/src/components/widgets/Button/Button.test.tsx
  frontend/lib/src/components/widgets/Button/Button.tsx
  frontend/lib/src/theme/primitives/iconSizes.ts
  lib/streamlit/elements/widgets/button.py
  lib/tests/streamlit/elements/button_test.py
  proto/streamlit/proto/Button.proto
Labels: security-assessment-completed, change:feature, impact:users

#9304 Remove `_streamlit_xsrf` cookie value replacement with empty string
  frontend/app/src/App.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#9322 Add icon to `st.download_button`
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-emoji_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-emoji_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-emoji_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-emoji_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-emoji_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-emoji_icon[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-material_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-material_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-material_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-material_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-material_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-material_icon[light_theme-webkit].png
  e2e_playwright/st_download_button.py
  e2e_playwright/st_download_button_test.py
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  lib/streamlit/elements/widgets/button.py
  lib/tests/streamlit/elements/download_button_test.py
  proto/streamlit/proto/DownloadButton.proto
Labels: security-assessment-completed, change:feature, impact:users

#9334 [fix] Multiselect label truncation in narrow columns
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-11[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-dropdown_narrow_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-dropdown_narrow_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-dropdown_narrow_column[webkit].png
  e2e_playwright/st_multiselect.py
  e2e_playwright/st_multiselect_test.py
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9327 Add icon to `st.form_submit_button`
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit-emoji_icon[chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit-emoji_icon[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit-emoji_icon[webkit].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit-material_icon[chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit-material_icon[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit-material_icon[webkit].png
  e2e_playwright/st_form.py
  e2e_playwright/st_form_test.py
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
  lib/streamlit/elements/form.py
  lib/tests/streamlit/form_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9344 Up version to 1.38.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#9348 Allow tenacity version 9.x
  lib/setup.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:other, impact:users

#9335 [fix] `st.{balloons|snow}` fixes when rendered in `st.dialog`
  frontend/app/src/ThemedApp.tsx
  frontend/app/src/styled-components.ts
  frontend/lib/src/components/core/Portal/PortalContext.tsx
  frontend/lib/src/components/core/Portal/PortalProvider.tsx
  frontend/lib/src/components/core/Portal/RenderInPortalIfExists.tsx
  frontend/lib/src/components/elements/Balloons/Balloons.tsx
  frontend/lib/src/components/elements/Snow/Snow.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9324 Reapply Snowflake integration tests with new secure format
  .credentials/.gitignore
  .credentials/README.md
  .credentials/snowflake.example.json
  .github/scripts/decrypt_credentials.sh
  .github/scripts/encrypted_credentials_snowflake.json.gpg
  .github/workflows/nightly.yml
  .github/workflows/python-tests.yml
  .github/workflows/release.yml
  lib/tests/conftest.py
  lib/tests/constants.py
  lib/tests/testutil.py
Labels: security-assessment-completed, impact:internal, change:chore

#9338 Improve logo rendering w/ sidebar state transition
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9350 [feat] Add `icon` to `st.link_button`
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-6[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-6[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-6[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-6[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-6[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-6[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-7[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-7[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-7[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-7[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-7[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-7[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_6[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_6[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_6[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_6[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_6[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_6[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_7[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_7[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_7[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_7[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_7[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-focus_7[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_6[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_6[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_6[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_6[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_6[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_6[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_7[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_7[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_7[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_7[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_7[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-hover_7[light_theme-webkit].png
  e2e_playwright/st_link_button.py
  e2e_playwright/st_link_button_test.py
  frontend/lib/src/components/elements/LinkButton/LinkButton.test.tsx
  frontend/lib/src/components/elements/LinkButton/LinkButton.tsx
  lib/streamlit/elements/widgets/button.py
  lib/tests/streamlit/elements/link_button_test.py
  proto/streamlit/proto/LinkButton.proto
Labels: security-assessment-completed, change:feature, impact:users, feature:st.link_button

#9337 Remove `st.logo` if stale
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9320 Refactor frontend styles, class names and test-ids - Part 4
  e2e/specs/hostframe.spec.js
  e2e_playwright/st_caption_test.py
  e2e_playwright/st_chat_input_test.py
  e2e_playwright/st_expander_test.py
  e2e_playwright/st_markdown_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/ScrollToBottomContainer.tsx
  frontend/app/src/components/AppView/styled-components.ts
  frontend/app/src/components/EventContainer/EventContainer.test.tsx
  frontend/app/src/components/EventContainer/EventContainer.tsx
  frontend/app/src/components/Header/Header.tsx
  frontend/app/src/components/Header/styled-components.ts
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/MainMenu/mainMenuTestHelpers.ts
  frontend/app/src/components/MainMenu/styled-components.ts
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/components/StatusWidget/styled-components.ts
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
  frontend/app/src/components/ToolbarActions/styled-components.ts
  frontend/cypress/support/commands.js
  frontend/lib/src/components/core/Block/Block.test.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/shared/Tooltip/styled-components.tsx
  frontend/lib/src/theme/primitives/sizes.ts
  frontend/lib/src/theme/primitives/zIndices.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9358 [chore] Fix typedefs for deck.gl
  NOTICES
  frontend/lib/package.json
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/declarations.d.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#9369 Deactivate cached venv usage for integration test
  .github/workflows/python-tests.yml
Labels: security-assessment-completed, change:other, impact:internal

#9368 [Fix] Logo maintains aspect ratio on width resize
  e2e_playwright/__snapshots__/linux/mpa_basics_test/collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[firefox].png
  frontend/app/src/components/Sidebar/styled-components.ts
Labels: security-assessment-completed, change:other, impact:users

#8864 Fix issue with re-adding deleted row in data editor with same index
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9367 Add icon to `st.popover`
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-emoji_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-emoji_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-emoji_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-emoji_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-emoji_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-emoji_icon[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-material_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-material_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-material_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-material_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-material_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-material_icon[light_theme-webkit].png
  e2e_playwright/st_popover.py
  e2e_playwright/st_popover_test.py
  frontend/lib/src/components/elements/Popover/Popover.test.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/elements/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users, feature:st.popover

#9361 [Fix] Logo blink on MPA v1 page change
  frontend/app/src/App.test.tsx
  frontend/app/src/util/AppNavigation.ts
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, change:refactor, impact:users

#9373 Rename widget ID to element ID
  frontend/app/src/App.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/util/utils.ts
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/state/widgets.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/runtime/state/session_state_proxy_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/runtime/state/strategies.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#9378 Fix: Margin on button icons
  frontend/lib/src/components/elements/LinkButton/LinkButton.test.tsx
  frontend/lib/src/components/elements/LinkButton/LinkButton.tsx
  frontend/lib/src/components/elements/Popover/Popover.test.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/shared/BaseButton/DynamicButtonLabel.test.tsx
  frontend/lib/src/components/shared/BaseButton/DynamicButtonLabel.tsx
  frontend/lib/src/components/shared/BaseButton/index.tsx
  frontend/lib/src/components/widgets/Button/Button.test.tsx
  frontend/lib/src/components/widgets/Button/Button.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
Labels: security-assessment-completed, change:bugfix, impact:users
