Repository streamlit/streamlit, pull requests merged in 2024-05, with the labels that each got.

#8588 Docstrings for 1.34.0
  lib/streamlit/commands/page_config.py
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/empty.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/progress.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/state/query_params_proxy.py
Labels: security-assessment-completed, impact:internal, change:docs

#8594 Migrate typography-cypress test to playwright
  e2e/scripts/st_sidebar.py
  e2e/scripts/typography.py
  e2e/specs/typography.spec.js
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-header_long_above_markdown_table[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-header_long_above_markdown_table[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-header_long_above_markdown_table[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_beside_widget[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_beside_widget[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_beside_widget[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_columns[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_columns[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_columns[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long-markdown-header-above-table[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long-markdown-header-above-table[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[light_theme-webkit].png
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  frontend/cypress/snapshots/linux/2x/typography.spec.js/column-widget-markdown.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/columns-markdown.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/columns-padded-markdown.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/main-sidebar-top.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/multiple-markdown-h1.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/multiple-markdown-h2.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/multiple-markdown-h3.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/multiple-markdown-h4.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/multiple-markdown-h5.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/multiple-markdown-h6.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/multiple-markdown-p.snap.png
  frontend/cypress/snapshots/linux/2x/typography.spec.js/single-markdown.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8601 Remove unused `dg._enqueue` parameters
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/delta_generator.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8602 Migrate st.caption cypress test to playwright
  e2e/specs/st_caption.spec.js
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_different_markdown_content[chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_different_markdown_content[firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_different_markdown_content[webkit].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_html_and_unsafe_html_true[chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_html_and_unsafe_html_true[firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_html_and_unsafe_html_true[webkit].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_tooltip[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_tooltip[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_tooltip[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_tooltip[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_tooltip[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_tooltip[light_theme-webkit].png
  e2e_playwright/st_caption.py
  e2e_playwright/st_caption_test.py
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-3.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-4.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-in-sidebar-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_caption.spec.js/caption-in-sidebar.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8605 Update vega frontend dependencies
  NOTICES
  frontend/lib/package.json
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/index.tsx
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#8596 Change embedded app URL for dialog
  lib/streamlit/elements/dialog_decorator.py
Labels: security-assessment-completed, impact:internal, change:docs

#8617 Fix Makefile and e2e_playwright test for CustomComponents
  Makefile
  e2e_playwright/custom_components/popular_components.py
  e2e_playwright/custom_components/popular_components_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8620 Fix standalone custom-component execution
  e2e_playwright/custom_components/popular_components_test.py
  lib/streamlit/components/v1/component_registry.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8599 Clear stale elements when st.rerun() is used
  frontend/app/src/App.tsx
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/forward_msg_queue.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/forward_msg_queue_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8623 Refactor Local Sources Watcher to not be instantiated in multiple places.
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/websocket_session_manager.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/web/server/server_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8621 Remove fullscreen button for `st.table`
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
Labels: security-assessment-completed, change:refactor, impact:users

#8614 Improve typing for query params `.update` and `.from_dict`
  lib/dev-requirements.txt
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/state/query_params_test.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:other, impact:users

#8624 Allow protobuf v5
  lib/setup.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:chore, impact:users

#8616 Run bare execution tests based on playwright scripts
  .github/workflows/python-bare-executions.yml
  .github/workflows/python-min-deps.yml
  .github/workflows/python-versions.yml
  Makefile
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_nested.py
  e2e_playwright/st_dialog_nested_test.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_expander.py
  e2e_playwright/st_plotly_chart_select.py
  e2e_playwright/st_status.py
  e2e_playwright/st_video.py
  lib/streamlit/runtime/state/session_state_proxy.py
  scripts/run_bare_execution_tests.py
Labels: security-assessment-completed, change:other, impact:internal

#8618 Migrate `tooltips_2` e2e test to playwright
  e2e/scripts/st_latex.py
  e2e/scripts/st_tooltips_2.py
  e2e/specs/st_tooltips_2.spec.js
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-ascii_art[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-ascii_art[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-ascii_art[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[webkit].png
  e2e_playwright/st_caption_test.py
  e2e_playwright/st_heading.py
  e2e_playwright/st_heading_test.py
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  e2e_playwright/st_text.py
  e2e_playwright/st_text_test.py
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipCaption.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipHeader.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipLatex.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipMarkdown.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipSubheader.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipText.snap.png
  frontend/cypress/snapshots/linux/2x/st_tooltips_2.spec.js/stTooltipTitle.snap.png
  frontend/lib/src/components/elements/TextElement/TextElement.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#8619 Refactor frontend for easy diff for MPA v2
  frontend/app/src/App.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#8628 Stabilize the vega-lite spec for altair-based charts
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[light_theme-webkit].png
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/elements/vega_charts_test.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:refactor, impact:users

#8593 Material icon for st.page_link
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[light_theme-webkit].png
  e2e_playwright/multipage_apps/mpa_configure_sidebar.py
  e2e_playwright/multipage_apps/pages/04_page_with_duplicate_name.py
  frontend/lib/src/components/elements/PageLink/PageLink.tsx
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, change:feature, impact:users

#8622 fix: #8500 bypass StrEnum 'index' to make position-indexable
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8634 Add e2e tests for the dataframe selections
  e2e_playwright/__snapshots__/linux/st_dataframe_selections_test/st_data_editor-multi_row_multi_column_selection[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_selections_test/st_data_editor-multi_row_multi_column_selection[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_selections_test/st_data_editor-multi_row_multi_column_selection[webkit].png
  e2e_playwright/st_dataframe_selections.py
  e2e_playwright/st_dataframe_selections_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8584 Download button host config
  frontend/app/src/App.tsx
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8641 Update scroll-margin-top
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: area:ux/ui, security-assessment-completed, change:bugfix, impact:users

#8411 Add dataframe row and column selections
  e2e_playwright/__snapshots__/linux/st_dataframe_selections_test/st_dataframe-multi_row_multi_column_selection[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_selections_test/st_dataframe-multi_row_multi_column_selection[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_selections_test/st_dataframe-multi_row_multi_column_selection[webkit].png
  e2e_playwright/st_dataframe_selections.py
  e2e_playwright/st_dataframe_selections_test.py
  frontend/lib/package.json
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/EditingState.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/index.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useSelectionHandler.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useSelectionHandler.ts
  frontend/yarn.lock
  lib/streamlit/elements/arrow.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  proto/streamlit/proto/Arrow.proto
Labels: security-assessment-completed, change:feature, impact:users

#8648 Stylistic refactoring of dataframe widget state loading
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#8631 Migrate frontend navigation to App Navigation Abstraction
  frontend/app/src/App.tsx
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#8639 Refactor page management to a PagesManager class
  e2e_playwright/hello_app.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/source_util.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/streamlit/web/bootstrap.py
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/tests/delta_generator_test_case.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/pages_manager_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/script_run_context_test.py
  lib/tests/streamlit/source_util_test.py
  lib/tests/streamlit/testing/app_test_test.py
  lib/tests/streamlit/user_info_test.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/streamlit/web/server/routes_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8650 Address Pages Manager lock behavior and types
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/source_util.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8647 Update address output in headless mode
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/web/bootstrap_test.py
Labels: area:debugging, security-assessment-completed, impact:users, change:docs

#8640 Fix cell error when data editor gets reconstructed
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-after_unmounting[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-after_unmounting[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-after_unmounting[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-selected_row_for_deletion[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-selected_row_for_deletion[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-selected_row_for_deletion[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-selected_row_for_deletion[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[light_theme-webkit].png
  e2e_playwright/st_dataframe_interactions.py
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/EditingState.test.ts
  frontend/lib/src/components/widgets/DataFrame/EditingState.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8656 Introduce concept of active script hash
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/core/Block/Block.test.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/Block/utils.test.ts
  frontend/lib/src/components/elements/Tabs/Tabs.test.tsx
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/tests/streamlit/script_run_context_test.py
  proto/streamlit/proto/ForwardMsg.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#8665 Migrate st_color_picker to playwright
  e2e/specs/st_color_picker.spec.js
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-0[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-0[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-0[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-0[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-0[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-0[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-1[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-1[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-1[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-1[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-1[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-1[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-2[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-2[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-2[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-2[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-2[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-2[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-3[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-4[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-4[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-4[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-4[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-4[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-4[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-clicked_new_color[chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-clicked_new_color[webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_hex_color[chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_hex_color[firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_hex_color[webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_hsl_color[chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_hsl_color[firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_hsl_color[webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_rgb_color[chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_rgb_color[firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-typed_new_rgb_color[webkit].png
  e2e_playwright/st_color_picker.py
  e2e_playwright/st_color_picker_test.py
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker0.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker1.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker2.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker3.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_color_picker.spec.js/colorpicker4.snap.png
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#8664 Rename select to selection in return value
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_dataframe_selections_test.py
  e2e_playwright/st_plotly_chart_select.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/plotly_chart_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8657 Include Main Script Hash info in App Nodes
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/pages_manager.py
  lib/tests/streamlit/proto_compatibility_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#8667 Simplify updateReport call to remove properties
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
  lib/tests/streamlit/script_run_context_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8658 Introduce a strategy design pattern for PagesManager and AppNavigation
  frontend/app/src/util/AppNavigation.ts
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/pages_manager_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8651 Disable selecting index columns
  e2e_playwright/st_dataframe_selections.py
  e2e_playwright/st_dataframe_selections_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useSelectionHandler.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useSelectionHandler.ts
Labels: security-assessment-completed, change:other, impact:internal

#8677 Ensure that column config is cloned
  e2e_playwright/st_dataframe_selections.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8678 Migrate st balloons to playwright
  e2e/specs/st_balloons.spec.js
  e2e_playwright/st_balloons.py
  e2e_playwright/st_balloons_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8670 Fix is_fragment_run page profile field
  frontend/app/src/App.tsx
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/runtime/metrics_util_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8680 Migrate st snow to playwright
  e2e/specs/st_snow.spec.js
  e2e_playwright/st_snow.py
  e2e_playwright/st_snow_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8452 Add fallback method for CSV download
  e2e_playwright/conftest.py
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/package.json
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataExporter.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataExporter.ts
  frontend/yarn.lock
Labels: security-assessment-completed, change:bugfix, impact:users

#8690 Add altair-selection tests for forms, callback, and fragment
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_dataframe_selections_test.py
Labels: feature:st.altair_chart, security-assessment-completed, impact:internal, change:chore

#8693 Convert Navigation position string type to enum
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
  lib/streamlit/commands/navigation.py
  lib/tests/streamlit/commands/navigation_test.py
  proto/streamlit/proto/Navigation.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#8694 Make the main script hash optional in AppRoot.empty()
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#8692 Add support for st.Page for switch_page and page_link
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/button.py
  lib/tests/streamlit/elements/page_link_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8679 Migrate st_set_page_config_icon to playwright
  assets/favicon.ico
  e2e/specs/st_set_page_config_icon.spec.js
  e2e_playwright/st_set_page_config_icon.py
  e2e_playwright/st_set_page_config_icon_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8691 set_page_config should override mpa-v2 Page properties
  frontend/app/src/App.tsx
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8688 Fix some flaky e2e tests
  Makefile
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[webkit].png
  e2e_playwright/custom_components/popular_components.py
  e2e_playwright/custom_components/popular_components_test.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_date_input_test.py
  e2e_playwright/st_dialog_test.py
Labels: type:enhancement, security-assessment-completed, impact:internal, change:chore

#8649 Fix st.logo doc link
  lib/streamlit/commands/logo.py
Labels: security-assessment-completed, impact:internal, change:docs

#8701 Revert "Allow protobuf v5"
  lib/setup.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:chore, impact:users

#8682 Migrate st_latex to st_markdown
  e2e/scripts/st_latex.py
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-50[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-50[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-50[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-50[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-50[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-50[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-51[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-51[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-51[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-51[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-51[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-51[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-52[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-52[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-52[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-52[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-52[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-52[light_theme-webkit].png
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8702 Retrieve pages for new session when ready to send the event
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8723 Migrate st_json to playwright
  e2e/specs/st_json.spec.js
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[webkit].png
  e2e_playwright/st_json.py
  e2e_playwright/st_json_test.py
  frontend/cypress/snapshots/linux/2x/st_json.spec.js/json-white-spaces-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_json.spec.js/json-white-spaces.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8728 Explicitly export experimental_dialog
  lib/streamlit/__init__.py
Labels: area:api, security-assessment-completed, change:refactor, impact:users

#8722 Migrate st_exception to playwright
  e2e/specs/st_exception.spec.js
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-webkit].png
  e2e_playwright/st_exception.py
  e2e_playwright/st_exception_test.py
  frontend/cypress/snapshots/linux/2x/st_exception.spec.js/long_exception-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_exception.spec.js/long_exception.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8721 Migrate experimental query params methods to Playwright
  e2e/specs/st_experimental_get_query_params.spec.js
  e2e/specs/st_experimental_set_query_params.spec.js
  e2e_playwright/st_experimental_get_query_params.py
  e2e_playwright/st_experimental_get_query_params_test.py
  e2e_playwright/st_experimental_set_query_params.py
  e2e_playwright/st_experimental_set_query_params_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8703 Migrate select slider to playwright
  e2e/specs/st_select_slider.spec.js
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-disabled[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-disabled[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-disabled[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-disabled[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-hidden_label[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-hidden_label[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-hidden_label[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-hidden_label[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-hidden_label[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-hidden_label[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-label_collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-label_collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-label_collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-label_collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-label_collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-label_collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-regular_with_help_and_format_func[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-regular_with_help_and_format_func[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-regular_with_help_and_format_func[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-regular_with_help_and_format_func[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-regular_with_help_and_format_func[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-regular_with_help_and_format_func[light_theme-webkit].png
  e2e_playwright/st_select_slider.py
  e2e_playwright/st_select_slider_test.py
  frontend/cypress/snapshots/linux/2x/st_select_slider.spec.js/collapsed-label-select-slider-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_select_slider.spec.js/collapsed-label-select-slider.snap.png
  frontend/cypress/snapshots/linux/2x/st_select_slider.spec.js/disabled-select-slider-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_select_slider.spec.js/disabled-select-slider.snap.png
  frontend/cypress/snapshots/linux/2x/st_select_slider.spec.js/hidden-label-select-slider-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_select_slider.spec.js/hidden-label-select-slider.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8711 Remove non-existent kwargs in ast.Call() call
  lib/streamlit/runtime/scriptrunner/magic.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8698 Don't notify pages change for MPAv2
  e2e_playwright/hello_app.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/source_util.py
  lib/streamlit/testing/v1/app_test.py
  lib/tests/conftest.py
  lib/tests/streamlit/commands/navigation_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/pages_manager_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/source_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8729 Remove default value for title of dialog_decorator
  lib/streamlit/elements/dialog_decorator.py
  lib/tests/streamlit/layouts_test.py
Labels: security-assessment-completed, impact:users, change:docs

#8735 Fix row selection when column is sorted
  e2e_playwright/st_dataframe_selections_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#8633 Allow passing on_change_callback for CustomComponents
  e2e_playwright/custom_components/popular_components.py
  e2e_playwright/custom_components/popular_components_test.py
  lib/streamlit/components/types/base_custom_component.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/runtime/state/common.py
  lib/tests/streamlit/components_test.py
Labels: area:api, security-assessment-completed, change:feature, impact:users

#8739 Add workflow that only runs playwright tests of changed files
  .github/workflows/playwright-changed-files.yml
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-complex_dict[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-complex_dict[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-complex_dict[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-complex_dict[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-complex_dict[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-complex_dict[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-empty_dict[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-empty_dict[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-empty_dict[webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-simple_dict[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-simple_dict[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-simple_dict[webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-simple_list[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-simple_list[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-simple_list[webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-with_white_spaces[light_theme-webkit].png
  e2e_playwright/main_menu.py
  e2e_playwright/st_json.py
  e2e_playwright/st_json_test.py
  e2e_playwright/st_select_slider_test.py
  e2e_playwright/st_snow_test.py
Labels: security-assessment-completed, change:other, impact:internal

#8745 Uncomment accidentally commented tests
  e2e_playwright/st_dataframe_selections_test.py
Labels: security-assessment-completed, change:other, impact:internal

#8746 Add internal config to indicate that its running as e2e test
  e2e_playwright/conftest.py
  lib/streamlit/config.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/config_test.py
Labels: security-assessment-completed, change:other, impact:internal

#8742 Remove `st_reuse_label` e2e test
  e2e/scripts/st_reuse_label.py
  e2e/specs/st_reuse_label.spec.js
Labels: security-assessment-completed, impact:internal, change:chore

#8741 Don't instantiate the LocalSourcesWatcher if file watching is disabled
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/runtime/app_session_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8750 Release 1.35.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#8743 Add E2E tests for MPA V2
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/collapsed-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/collapsed-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/dynamic-pages[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[webkit].png
  e2e_playwright/multipage_apps/mpa_v2_transition.py
  e2e_playwright/multipage_apps/mpa_v2_transition_test.py
  e2e_playwright/multipage_apps_v2/__init__.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  e2e_playwright/multipage_apps_v2/page_2.py
  e2e_playwright/multipage_apps_v2/page_3.py
  e2e_playwright/multipage_apps_v2/page_5.py
  e2e_playwright/multipage_apps_v2/page_6.py
  e2e_playwright/multipage_apps_v2/🦒_page_4.py
Labels: security-assessment-completed, impact:internal, change:chore

#8748 Use non-metric emitting fragment function in dialog
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/runtime/fragment.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8749 Extract dataframe e2e test selection utility
  e2e_playwright/shared/dataframe_utils.py
  e2e_playwright/st_dataframe_selections_test.py
Labels: security-assessment-completed, change:other, impact:internal

#8752 Remove unnecessary steps in playwright workflows
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/playwright.yml
  .github/workflows/python-bare-executions.yml
Labels: security-assessment-completed, change:other, impact:internal

#8737 Remove legacy caching logic
  e2e/scripts/st_image_replay_old_image.py
  e2e/scripts/st_media_replay.py
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-webkit].png
  e2e_playwright/app_hotkeys_test.py
  e2e_playwright/st_rerun.py
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  lib/streamlit/__init__.py
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/legacy_cache_api.py
  lib/streamlit/runtime/legacy_caching/__init__.py
  lib/streamlit/runtime/legacy_caching/caching.py
  lib/streamlit/runtime/legacy_caching/hashing.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/web/cli.py
  lib/test-requirements.txt
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/elements/cache_spinner_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
  lib/tests/streamlit/runtime/caching/legacy_cache_api_test.py
  lib/tests/streamlit/runtime/legacy_caching/__init__.py
  lib/tests/streamlit/runtime/legacy_caching/caching_test.py
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/scriptrunner/test_data/st_cache_script.py
  lib/tests/streamlit/runtime/scriptrunner/test_data/st_cache_script_changed.py
  lib/tests/streamlit/util_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, change:breaking, change:refactor, impact:users

#8708 Use raw number for number column overlay and copy
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-number_col_editor[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-number_col_editor[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-number_col_editor[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-number_col_editor[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-number_col_editor[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-number_col_editor[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-text_col_editor[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-text_col_editor[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-text_col_editor[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-text_col_editor[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-text_col_editor[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-text_col_editor[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-number_col_overlay[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-number_col_overlay[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-number_col_overlay[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-number_col_overlay[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-number_col_overlay[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-number_col_overlay[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-text_col_overlay[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-text_col_overlay[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-text_col_overlay[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-text_col_overlay[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-text_col_overlay[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-text_col_overlay[light_theme-webkit].png
  e2e_playwright/shared/app_utils.py
  e2e_playwright/shared/dataframe_utils.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_data_editor_config.py
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_interactions.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_dataframe_selections_test.py
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.ts
Labels: security-assessment-completed, change:feature, impact:users

#8774 Migrate form column association e2e test to playwright
  e2e/scripts/st_form_column_association.py
  e2e/specs/st_form_column_association.spec.js
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_form_container_association.py
  e2e_playwright/st_form_container_association_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8533 Change the `fragmentId` to be a required property in `WidgetStateManager`
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.test.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.test.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#8764 Move check_* utils to own file
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/elements/lib/utils.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/elements/element_policies_test.py
  lib/tests/streamlit/elements/element_utils_test.py
  lib/tests/streamlit/elements/number_input_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8780 Migrate expect help tooltip e2e logic into shared app utils
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_caption_test.py
  e2e_playwright/st_heading_test.py
  e2e_playwright/st_markdown_test.py
  e2e_playwright/st_text_input_test.py
  e2e_playwright/st_text_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8508 Add miscellaneous small changes
  e2e_playwright/st_set_page_config_icon.py
  e2e_playwright/test_assets/favicon.ico
  frontend/lib/src/util/UriUtil.test.ts
  frontend/lib/src/util/UriUtil.ts
  lib/entrypoint.sh
  lib/streamlit/elements/empty.py
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  proto/streamlit/proto/Arrow.proto
  proto/streamlit/proto/ForwardMsg.proto
  proto/streamlit/proto/Skeleton.proto
Labels: security-assessment-completed, change:other, impact:internal

#8778 Specify url path in st.Page
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  frontend/app/src/util/AppNavigation.ts
  lib/streamlit/commands/navigation.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/navigation/page.py
  lib/tests/streamlit/commands/navigation_test.py
  lib/tests/streamlit/elements/page_link_test.py
  lib/tests/streamlit/navigation/page_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8779 Ensure SessionInfo is set before performing an action
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8802 Make sure fragments maintain active page script hash on subsequent reruns
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/pages_manager.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8758 Migrate st pydeck to playwright
  e2e/scripts/st_pydeck_geo_layers.py
  e2e/specs/st_pydeck_chart.spec.js
  e2e/specs/st_pydeck_geo_layers.spec.js
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-continents[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-continents[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-continents[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-continents[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-empty[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-empty[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-empty[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-empty[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-geo_layers[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-geo_layers[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-geo_layers[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-geo_layers[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-no_overridden_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-no_overridden_theme[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-no_overridden_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-no_overridden_theme[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-san_francisco_overridden_light_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-san_francisco_overridden_light_theme[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-san_francisco_overridden_light_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-san_francisco_overridden_light_theme[light_theme-webkit].png
  e2e_playwright/st_pydeck_chart.py
  e2e_playwright/st_pydeck_chart_test.py
  frontend/cypress/snapshots/linux/2x/st_pydeck_geo_layers.spec.js/h3-hexagon-layer-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_pydeck_geo_layers.spec.js/h3-hexagon-layer.snap.png
Labels: security-assessment-completed, impact:internal, change:chore
