Repository streamlit/streamlit, pull requests merged in 2024-11, with the labels that each got.

#9760 Clean up hello app
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_closed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_closed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-landscape-sidebar_open[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_closed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-print_media-portrait-sidebar_open[light_theme-webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/hello_app_test.py
  lib/streamlit/hello/animation_demo.py
  lib/streamlit/hello/dataframe_demo.py
  lib/streamlit/hello/hello.py
  lib/streamlit/hello/mapping_demo.py
  lib/streamlit/hello/plotting_demo.py
  lib/streamlit/hello/streamlit_app.py
Labels: security-assessment-completed, change:other, impact:users

#9764 Fix update script to correctly wait for the failure status
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, change:other, impact:internal

#9725 Move image utils function into `lib/image_utils.py`
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  lib/streamlit/commands/logo.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/widgets/chat.py
  lib/tests/streamlit/commands/page_config_test.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/elements/pyplot_test.py
  proto/streamlit/proto/Image.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#9765 Docs for release 1.40.0
  lib/streamlit/commands/navigation.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/progress.py
  lib/streamlit/elements/text.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
Labels: security-assessment-completed, impact:internal, change:docs

#9714 Clean up global styles - part 2
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-no_permission[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-no_permission[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-header_long_above_markdown_table[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-header_long_above_markdown_table[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_beside_widget[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_columns[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[firefox].png
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9783 Follow ups for pathlib support
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/testing/v1/app_test.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/testing/app_test_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9676 Support primary color as text and background color in markdown
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-webkit].png
  e2e_playwright/st_markdown.py
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/theme/getColors.ts
Labels: security-assessment-completed, change:feature, impact:users

#9773 Fix chat input placeholder color
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[chromium].png
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
Labels: security-assessment-completed, change:other, impact:internal

#9768 Adds a timestamp into the file name for st.audio_input
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
Labels: security-assessment-completed, change:other, impact:users

#9774 Make checkbox label responsive to font size
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_checkbox-valid_markdown[chromium].png
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_checkbox-valid_markdown[firefox].png
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_checkbox-valid_markdown[webkit].png
  frontend/lib/src/components/widgets/Checkbox/Checkbox.tsx
Labels: security-assessment-completed, change:other, impact:internal

#9785 Update watchdog to include 6.x.x
  lib/setup.py
Labels: security-assessment-completed, change:other, impact:users

#9790 release/1.40.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#9674 Improve hover tooltips for `st.line_chart`
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-3[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-10[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-10[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-10[webkit].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-2[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-2[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-2[webkit].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-5[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-5[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-5[webkit].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-7[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-7[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-7[webkit].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-multi_line_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-multi_line_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-multi_line_hover[webkit].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-single_line_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-single_line_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-single_line_hover[webkit].png
  e2e_playwright/st_line_chart_test.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, change:feature, impact:users

#9755 Add a sleep to the st.audio_input in form e2e test
  e2e_playwright/st_audio_input_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#9795 Remove kbd style from global styles
  e2e_playwright/__snapshots__/linux/main_menu_test/record_screencast_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/record_screencast_dialog[light_theme-chromium].png
  frontend/app/src/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.tsx
  frontend/lib/src/components/shared/ErrorBoundary/ErrorBoundary.tsx
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9794 Remove table styles from global styling
  frontend/lib/src/components/elements/ArrowTable/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9753 Add support for ISO time/date format in st.time_input / st.date_input
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/elements/date_input_test.py
  lib/tests/streamlit/elements/time_input_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9807 Make number input controls responsive to font size
  frontend/lib/src/components/widgets/NumberInput/styled-components.ts
  frontend/lib/src/theme/primitives/sizes.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9782 Fix typo in docstring
  lib/tests/streamlit/web/server/browser_websocket_handler_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#9772 Cleanup global styles - part 3
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  frontend/lib/src/components/elements/Dialog/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/Heading.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9766 Fix #9763. Don't show text keyboard for number input on IOS
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9771 Ignore broken codeql rule
  .github/codeql-config.yml
Labels: security-assessment-completed, change:other, impact:internal

#9791 Fixes a bug where timezones with a non- x:00 utc offset would start at a non 00:00 timer for st.audio_input
  frontend/lib/src/components/widgets/AudioInput/formatTime.test.ts
  frontend/lib/src/components/widgets/AudioInput/formatTime.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9803 Fix dataframe fullscreen for large dataframes
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_collapsed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_collapsed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_expanded[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_expanded[webkit].png
  e2e_playwright/shared/toolbar_utils.py
  e2e_playwright/st_dataframe_interactions.py
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9813 fix #9810 Update to latest Material symbols font
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[light_theme-webkit].png
  e2e_playwright/latest_material_symbol.py
  e2e_playwright/latest_material_symbol_test.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
  scripts/update_material_icon_names.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9818 Fix exception element styling
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-webkit].png
  e2e_playwright/st_exception.py
  e2e_playwright/st_exception_test.py
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/ExceptionElement/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9826 [Fix] Prevent rerun for text_input when value did not change
  e2e_playwright/st_text_input.py
  e2e_playwright/st_text_input_test.py
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9809 Fix circular imports in type utils
  lib/streamlit/type_util.py
Labels: security-assessment-completed, change:other, impact:internal

#9808 Modernize unsupported browser dialog
  frontend/app/src/hocs/withScreencast/components/UnsupportedBrowserDialog/UnsupportedBrowserDialog.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9829 [Fix] Set text area value based on state
  e2e_playwright/st_text_area.py
  e2e_playwright/st_text_area_test.py
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9828 Correctly handle `DeltaGenerator` in `st.write`
  lib/streamlit/elements/write.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9831 Release/1.40.1
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#9843 Add vitest to recommended VSCode extensions
  .vscode/extensions.json
Labels: security-assessment-completed, change:other, impact:internal

#9840 Make bottom padding responsive to font size
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/st_chat_input_test.py
  frontend/app/src/components/AppView/styled-components.ts
  frontend/lib/src/theme/primitives/sizes.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9842 Make virtual dropdown responsive to font size
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.test.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/shared/Dropdown/styled-components.ts
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
  frontend/lib/src/mocks/mocks.ts
  frontend/lib/src/theme/primitives/sizes.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9835 Add new hook to update UI value from server (e.g. session_state)
  e2e_playwright/st_text_input.py
  e2e_playwright/st_text_input_test.py
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/Radio/Radio.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.tsx
  frontend/lib/src/hooks/useBasicWidgetState.ts
  frontend/lib/src/hooks/useUpdateUiValue.test.ts
  frontend/lib/src/hooks/useUpdateUiValue.ts
Labels: security-assessment-completed, impact:internal, change:chore

#9805 Make alert padding responsive to font size
  frontend/lib/src/components/shared/AlertContainer/AlertContainer.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9822 Migrate remaining code & pre global styles
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/ExceptionElement/styled-components.ts
  frontend/lib/src/components/shared/ErrorElement/ErrorElement.tsx
  frontend/lib/src/components/shared/ErrorElement/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9838 Make map zoom buttons responsive to font size
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_controls[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-zoom_out_hover[light_theme-webkit].png
  frontend/lib/src/components/elements/DeckGlJsonChart/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9833 Make all icons responsive to font size
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_different_markdown_content[chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_different_markdown_content[firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-with_different_markdown_content[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-formula[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_beside_widget[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_beside_widget[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_bold_syntax[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_columns[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_columns[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_columns[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_in_labeled_columns[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_joined_in_single_command[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-headers_via_multiple_commands[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[firefox].png
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/TooltipIcon/TooltipIcon.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9804 Remove unused global styles
  frontend/lib/src/components/elements/ArrowVegaLiteChart/styled-components.ts
  frontend/lib/src/components/elements/Expander/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9850 Rename jest with vi in useUpdateUiValue test
  frontend/lib/src/hooks/useUpdateUiValue.test.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#9839 Make some component styles more robust
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/MainMenu/styled-components.ts
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/lib/src/components/elements/TextElement/styled-components.ts
  frontend/lib/src/components/elements/Toast/styled-components.tsx
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/FileUploader/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9830 Move test to st_alert.py
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_alert-latest_material_symbol[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/latest_material_symbol_test/st_markdown-latest_material_symbol[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/latest_material_symbol.py
  e2e_playwright/latest_material_symbol_test.py
  e2e_playwright/st_alert.py
  e2e_playwright/st_alert_test.py
  scripts/update_material_icon_names.py
Labels: security-assessment-completed, impact:internal, change:chore

#9779 Use shared border color for `st.help`
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-0[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-0[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-0[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-1[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-1[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-1[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-2[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-2[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-2[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[webkit].png
  e2e_playwright/st_help.py
  e2e_playwright/st_help_test.py
  frontend/lib/src/components/elements/DocString/styled-components.ts
Labels: security-assessment-completed, change:other, impact:internal

#9855 Make json copy icon responsive to root font size
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-copy_icon_on_hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-copy_icon_on_hover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-copy_icon_on_hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-copy_icon_on_hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-copy_icon_on_hover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-copy_icon_on_hover[light_theme-webkit].png
  e2e_playwright/st_json_test.py
  frontend/lib/src/components/elements/Json/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9847 Add shared hooks for submitForm & inputChange
  e2e_playwright/st_text_area.py
  e2e_playwright/st_text_area_test.py
  e2e_playwright/st_text_input.py
  e2e_playwright/st_text_input_test.py
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/hooks/useOnInputChange.test.ts
  frontend/lib/src/hooks/useOnInputChange.ts
  frontend/lib/src/hooks/useSubmitFormViaEnterKey.test.ts
  frontend/lib/src/hooks/useSubmitFormViaEnterKey.ts
  frontend/lib/src/util/inputUtils.test.ts
  frontend/lib/src/util/inputUtils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9727 File uploader config
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[webkit].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[webkit].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/hostframe_app.py
  e2e_playwright/hostframe_app_test.py
  e2e_playwright/test_assets/hostframe.html
  frontend/app/src/App.tsx
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/hostframe.html
  frontend/lib/src/StreamlitEndpoints.ts
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/util/UriUtil.ts
Labels: security-assessment-completed, impact:internal, change:chore

#9801 Set the default selection mode to 'single' in the overload methods of pills and segmented_control
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/typing/pills.py
  lib/tests/streamlit/typing/segmented_control.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9861 Cleanup even more global styles
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9821 Move small and bold styles from global styles to markdown component
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_caption_test/st_caption-sidebar_caption[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-captions[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-captions[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-30[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-30[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-30[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[light_theme-webkit].png
  e2e_playwright/app_hotkeys_test.py
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowTable/styled-components.ts
  frontend/lib/src/components/elements/Toast/styled-components.tsx
  frontend/lib/src/components/shared/ErrorElement/ErrorElement.tsx
  frontend/lib/src/components/shared/ErrorElement/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/BaseWidget/WidgetLabel.test.tsx
  frontend/lib/src/components/widgets/DataFrame/Tooltip.test.tsx
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9865 Make dropdown menu responsive to root font size
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9868 [chore] Add no-debugger eslint rule
  frontend/.eslintrc.js
Labels: security-assessment-completed, impact:internal, change:chore

#9867 [fix] st.graphviz_chart rendering bug with use_container_width=True
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_use_container_width_true[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_use_container_width_true[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_use_container_width_true[webkit].png
  e2e_playwright/st_graphviz_chart.py
  e2e_playwright/st_graphviz_chart_test.py
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/shared/Toolbar/styled-components.ts
Labels: feature:st.graphviz_chart, security-assessment-completed, change:bugfix, impact:users

#9849 Support URLPattern-compatible patterns in allowed domain matching
  NOTICES
  frontend/lib/package.json
  frontend/lib/src/util/UriUtil.test.ts
  frontend/lib/src/util/UriUtil.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:bugfix

#9876 Fix issue with missing test-results in the e2e playwright workflow
  e2e_playwright/config_static_serving_test.py
  e2e_playwright/conftest.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_markdown_test.py
  e2e_playwright/websocket_disconnect_test.py
Labels: security-assessment-completed, change:other, impact:internal

#9881 Add `.venv` to gitignore
  .gitignore
Labels: security-assessment-completed, change:other, impact:internal

#9851 Rewrite StatusWidget as a functional component
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#9877 Add _repr_html_ support to st.html, and avoid throwing for non-paths
  lib/streamlit/elements/html.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/elements/html_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9880 Remove the stale bot workflow
  .github/workflows/stale.yml
Labels: security-assessment-completed, change:other, impact:internal

#9747 [chore] Update eslint rules for RTL
  frontend/.eslintrc.js
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/hocs/withScreencast/components/ScreencastDialog/ScreencastDialog.test.tsx
  frontend/app/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.test.tsx
  frontend/lib/src/components/elements/Dialog/Dialog.test.tsx
  frontend/lib/src/components/elements/Expander/Expander.test.tsx
  frontend/lib/src/components/elements/Markdown/Markdown.test.tsx
  frontend/lib/src/components/elements/PageLink/PageLink.test.tsx
  frontend/lib/src/components/elements/Popover/Popover.test.tsx
  frontend/lib/src/components/elements/TextElement/TextElement.test.tsx
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/shared/BaseButton/BaseButton.test.tsx
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Radio/Radio.test.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.test.tsx
  frontend/lib/src/components/shared/Tooltip/OverflowTooltip.test.tsx
  frontend/lib/src/components/shared/Tooltip/Tooltip.test.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInputActionButtons.test.tsx
  frontend/lib/src/components/widgets/Button/Button.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.test.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/Checkbox/Checkbox.test.tsx
  frontend/lib/src/components/widgets/ColorPicker/ColorPicker.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.test.tsx
  frontend/lib/src/components/widgets/FileUploader/withPagination/Pagination.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/Radio/Radio.test.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.test.tsx
  frontend/lib/src/hooks/useWidgetManagerElementState.test.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#9889 Upgrade frontend dependency to arrow 18
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#9891 Split up quiver module for arrow data handling
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ProgressColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/dataframes/arrowFormatUtils.test.ts
  frontend/lib/src/dataframes/arrowFormatUtils.ts
  frontend/lib/src/dataframes/arrowTypeUtils.test.ts
  frontend/lib/src/dataframes/arrowTypeUtils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9819 Use default value "today" for st.date_input
  lib/streamlit/elements/widgets/time_widgets.py
Labels: security-assessment-completed, impact:internal, change:chore

#9898 Fix wrong dataframe return typing
  lib/streamlit/elements/arrow.py
  lib/tests/streamlit/typing/dataframe_types.py
Labels: security-assessment-completed, change:bugfix, impact:users

#9769 [chore] Introduce Performance Lighthouse Metrics
  .github/workflows/performance-lighthouse.yml
  Makefile
  frontend/app/package.json
  frontend/app/performance/apps/__init__.py
  frontend/app/performance/apps/blank_app.py
  frontend/app/performance/apps/crud_app.py
  frontend/app/performance/lighthouse/.gitignore
  frontend/app/performance/lighthouse/LighthouseOrchestrator.mjs
  frontend/app/performance/lighthouse/constants.mjs
  frontend/app/performance/lighthouse/run.mjs
  frontend/yarn.lock
  scripts/check_license_headers.py
Labels: security-assessment-completed, impact:internal, change:chore, perf:lighthouse

#9903 [chore] Run Lighthouse on nightly builds
  .github/workflows/nightly.yml
  .github/workflows/performance-lighthouse.yml
Labels: security-assessment-completed, impact:internal, change:chore

#9897 Remove overflow to make dialog compatible with the toolbar
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[webkit].png
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  frontend/lib/src/components/shared/Modal/Modal.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#9815 Remove Segment
  Makefile
  NOTICES
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  frontend/app/src/vendor/Segment-LICENSE.txt
  frontend/app/src/vendor/Segment.ts
  lib/streamlit/runtime/metrics_util.py
  proto/streamlit/proto/PageProfile.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#9907 [fix] Typo in workflow input checking
  .github/workflows/performance-lighthouse.yml
Labels: security-assessment-completed, impact:internal, change:bugfix, perf:lighthouse

#9919 Set Python 3.9 as minimum version and remove unused type-ignore comment
  .github/scripts/build_info.py
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
Labels: security-assessment-completed, impact:internal, change:chore

#9925 Release/1.40.2
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#9926 [chore] Add more Lighthouse apps
  frontend/app/performance/apps/dashboard_app.py
  frontend/app/performance/apps/multipage/multipage_app.py
  frontend/app/performance/apps/multipage/pages/1_Animation_Demo.py
  frontend/app/performance/apps/multipage/pages/2_Mapping_Demo.py
  frontend/app/performance/apps/multipage/pages/3_Plotting_Demo.py
  frontend/app/performance/lighthouse/LighthouseOrchestrator.mjs
  frontend/app/performance/lighthouse/constants.mjs
  frontend/app/performance/lighthouse/run.mjs
Labels: security-assessment-completed, impact:internal, change:chore, perf:lighthouse

#9635 Set Python 3.13 as max version for Streamlit
  .github/scripts/build_info.py
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_inline_error[chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-webkit].png
  e2e_playwright/st_code_test.py
  e2e_playwright/st_dataframe_selections_test.py
  e2e_playwright/st_exception_test.py
  e2e_playwright/st_fragment_basics_test.py
  lib/setup.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, change:chore, impact:users

#9258 Update pytest version
  lib/test-requirements.txt
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:other, impact:internal

#9942 Revert "Update pytest version (#9258)"
  lib/test-requirements.txt
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:other, impact:internal

#9887 Refactor dataframe sizing to use values responsive to root font size
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9940 Update path-handling docstrings
  lib/streamlit/commands/logo.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/config.py
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/html.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/navigation/page.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/connection_factory.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/memory_session_storage.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/user_info.py
  lib/streamlit/watcher/util.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/elements/pyplot_test.py
Labels: security-assessment-completed, impact:internal, change:docs

#9535 Allow pinning dataframe columns via column config
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/EditingState.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ChartColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/CheckboxColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/CheckboxColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ImageColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ImageColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ListColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ListColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ObjectColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ObjectColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ProgressColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/TextColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/TextColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnSort.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomRenderer.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataExporter.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useSelectionHandler.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTooltips.test.ts
  lib/streamlit/elements/lib/column_types.py
  lib/tests/streamlit/elements/lib/column_types_test.py
Labels: security-assessment-completed, change:feature, impact:users
