Repository streamlit/streamlit, pull requests merged in 2024-06, with the labels that each got.

#8811 Migrate static file serving e2e test to playwright
  e2e/scripts/staticfiles_apps/static/streamlit-mark-color.png
  e2e/specs/staticfiles_app.spec.js
  e2e_playwright/config_static_serving.py
  e2e_playwright/config_static_serving_test.py
  e2e_playwright/conftest.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/static/streamlit-logo.png
  frontend/cypress/snapshots/linux/2x/staticfiles_app.spec.js/static_streamlit_logo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/staticfiles_app.spec.js/static_streamlit_logo.snap.png
  scripts/run_e2e_tests.py
Labels: security-assessment-completed, change:other, impact:internal

#8804 Migrate st_map from Cypress to Playwright
  e2e/specs/st_latex.spec.js
  e2e/specs/st_map.spec.js
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-empty[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-empty[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-empty[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-empty[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-map_with_color_and_size_layers[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-map_with_color_and_size_layers[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-map_with_color_and_size_layers[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-map_with_color_and_size_layers[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map_with_zoom[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map_with_zoom[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map_with_zoom[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_map_test/st_map-simple_map_with_zoom[light_theme-webkit].png
  e2e_playwright/st_map.py
  e2e_playwright/st_map_test.py
  frontend/cypress/snapshots/linux/2x/st_map.spec.js/stDeckGlJsonChart-complexMap-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_map.spec.js/stDeckGlJsonChart-complexMap.snap.png
  frontend/cypress/snapshots/linux/2x/st_map.spec.js/stDeckGlJsonChart-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_map.spec.js/stDeckGlJsonChart.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8659 Make st.write call st.json to display Streamlit secrets object
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/secrets.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, feature:st.write, change:feature, impact:users

#8809 Fix `use_container_width` docstring when default is `True`
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, impact:users, change:docs

#8816 Fix editable install in CI
  .github/workflows/python-min-deps.yml
  Makefile
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[webkit].png
  e2e_playwright/hello_app_test.py
Labels: security-assessment-completed, change:other, impact:internal

#8756 Don't allow writing widgets outside the fragment
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/tests/streamlit/elements/element_policies_test.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8689 Update GitHub actions versions
  .github/actions/make_init/action.yml
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
  .github/workflows/python-versions.yml
  .github/workflows/release.yml
Labels: security-assessment-completed, github_actions, impact:internal, change:chore

#8770 Fix element replay regression for plotly charts
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/markdown_test.py
  lib/tests/streamlit/elements/plotly_chart_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8753 Simplify min version CI workflow
  .github/actions/make_init/action.yml
  .github/workflows/python-min-deps.yml
  Makefile
  lib/min-constraints-gen.txt
  lib/setup.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:other, impact:internal

#8819 Lower the number of cypress workers to two
  .github/workflows/cypress.yml
Labels: security-assessment-completed, change:other, impact:internal

#8732 Migrate disconnect and disabled from cypress to playwright
  e2e/scripts/st_disconnect.py
  e2e/specs/st_disconnect.spec.js
  e2e_playwright/websocket_disconnect.py
  e2e_playwright/websocket_disconnect_test.py
  frontend/cypress/snapshots/linux/2x/st_disconnect.spec.js/disconnected-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_disconnect.spec.js/disconnected.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8828 Delete already migrated cypress e2e related files
  e2e/scripts/st_columns.py
  e2e/specs/st_disabled.spec.js
  e2e_playwright/st_altair_chart_test.py
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_markdown_in_alert_box.spec.js/stAlert-alert-3.snap.png
  frontend/cypress/snapshots/linux/2x/st_pyplot.spec.js/pyplot-check-if-cleared.snap.png
Labels: security-assessment-completed, change:other, impact:internal

#8817 Deprecate the `experimental_allow_widgets` caching parameter
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
Labels: security-assessment-completed, change:other, change:breaking, impact:users

#8775 Improve exception text when selectbox index larger than options
  lib/streamlit/elements/widgets/selectbox.py
  lib/tests/streamlit/elements/selectbox_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8794 Prevent images in markdown to go beyond the container width
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[webkit].png
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8839 Update snapshots for markdown test
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[webkit].png
Labels: security-assessment-completed, impact:internal, change:chore

#8709 Add langchain-community to test dependencies
  lib/streamlit/external/langchain/streamlit_callback_handler.py
  lib/test-requirements.txt
  lib/tests/streamlit/external/langchain/streamlit_callback_handler_test.py
  lib/tests/streamlit/external/langchain/test_data/alanis.pickle
Labels: security-assessment-completed, dev:upgrade-dependencies, change:other, impact:internal

#8843 Use label property for menu click event
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#8829 Update CI workflow job names
  .github/workflows/cli-regression.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/community-voting.yml
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/conda-build.yml
  .github/workflows/cypress-update-snapshots.yml
  .github/workflows/cypress.yml
  .github/workflows/ensure-relative-imports.yml
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/playwright.yml
  .github/workflows/py-prod-deps-smoke-test.yml
  .github/workflows/python-bare-executions.yml
  .github/workflows/python-min-deps.yml
  .github/workflows/python-tests.yml
  .github/workflows/release.yml
  .github/workflows/semgrep.yml
  .github/workflows/stale.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#8769 Enforce that only the outermost command is tracked
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/runtime/metrics_util_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8841 Remove check for new version of Streamlit
  lib/streamlit/version.py
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/version_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  scripts/pypi_nightly_create_tag.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8845 Revert "Handle Altair resolve_scale (#8497)"
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[light_theme-webkit].png
  e2e_playwright/st_altair_chart.py
  e2e_playwright/st_altair_chart_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8814 Migrate empty label test to playwright
  e2e/scripts/empty_labels.py
  e2e/specs/empty_labels.spec.js
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_selectbox-empty_label[chromium].png
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_selectbox-empty_label[firefox].png
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_selectbox-empty_label[webkit].png
  e2e_playwright/label_markdown.py
  e2e_playwright/label_markdown_test.py
  frontend/cypress/snapshots/linux/2x/empty_labels.spec.js/empty_labels-dark.snap.png
  frontend/cypress/snapshots/linux/2x/empty_labels.spec.js/empty_labels.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8858 Migrate widget state heavy usage to playwright
  e2e_playwright/widget_state_heavy_usage.py
  e2e_playwright/widget_state_heavy_usage_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8857 Migrate st_media_replay from cypress to playwright
  e2e/scripts/st_media_replay.py
  e2e/specs/st_media_replay.spec.js
  e2e_playwright/st_cache_data.py
  e2e_playwright/st_cache_data_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8871 Move all type-only imports to type checking condition
  .ruff.toml
  e2e_playwright/conftest.py
  lib/streamlit/commands/navigation.py
  lib/streamlit/components/lib/local_component_registry.py
  lib/streamlit/components/types/base_component_registry.py
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/code.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/lib/dialog.py
  lib/streamlit/elements/lib/mutable_status_container.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/lib/utils.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/streamlit/runtime/connection_factory.py
  lib/streamlit/runtime/forward_msg_queue.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/runtime_util.py
  lib/streamlit/runtime/scriptrunner/script_requests.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/runtime/state/widgets.py
  lib/streamlit/runtime/uploaded_file_manager.py
  lib/streamlit/runtime/websocket_session_manager.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/streamlit/user_info.py
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/streamlit/web/cache_storage_manager_config.py
  lib/streamlit/web/cli.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/streamlit/web/server/component_request_handler.py
  lib/streamlit/web/server/server_util.py
  lib/streamlit/web/server/stats_request_handler.py
  lib/streamlit/web/server/upload_file_request_handler.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8666 Update custom-components import paths and tests
  .github/workflows/playwright-changed-files.yml
  e2e_playwright/custom_components/popular_components.py
  e2e_playwright/custom_components/popular_components_test.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_components_v1_import_legacy_file.py
  e2e_playwright/st_components_v1_import_legacy_file_test.py
  e2e_playwright/st_components_v1_import_via_st.py
  e2e_playwright/st_components_v1_import_via_st_test.py
  lib/streamlit/__init__.py
  lib/streamlit/components/v1/custom_component.py
Labels: area:api, security-assessment-completed, change:bugfix, impact:users

#8876 Add missing java protoc options to AutoRerun.proto.
  proto/streamlit/proto/AutoRerun.proto
Labels: security-assessment-completed, change:other, impact:internal

#8879 Add a missing multi-license
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed, impact:internal, change:chore

#8878 Raise exception if st.Page is given an invalid path
  lib/streamlit/navigation/page.py
  lib/tests/streamlit/commands/navigation_test.py
  lib/tests/streamlit/elements/page_link_test.py
  lib/tests/streamlit/navigation/page_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8568 Add vertical alignment parameter to `st.columns`
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[webkit].png
  e2e_playwright/st_columns.py
  e2e_playwright/st_columns_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/widgets/Checkbox/Checkbox.tsx
  frontend/lib/src/components/widgets/Checkbox/styled-components.tsx
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/elements/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#8856 Migrate frontend session state sync to playwright
  e2e/specs/session_state_frontend_sync.spec.js
  e2e_playwright/st_session_state.py
  e2e_playwright/st_session_state_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8883 Migrate the image cache replay tests to playwright
  e2e/scripts/st_image_replay.py
  e2e/scripts/st_image_replay_old_image.py
  e2e/specs/st_image_replay.spec.js
  e2e/specs/st_image_replay_old_image.spec.js
  e2e/specs/widget_state_heavy_usage.spec.js
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_cache_data.py
  e2e_playwright/st_cache_data_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8884 Clean up system dependencies in CI
  .github/actions/make_init/action.yml
Labels: security-assessment-completed, change:other, impact:internal

#8887 Fix Changed-Files Playwright CI workflow
  .github/workflows/playwright-changed-files.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#8893 Add missing HostToGuestMessage type
  frontend/lib/src/hostComm/types.ts
Labels: security-assessment-completed, impact:internal, change:chore

#8894 Migrate redisplayed widgets test to playwright
  .github/workflows/playwright-changed-files.yml
  e2e/scripts/redisplayed_widgets.py
  e2e/specs/redisplayed_widgets.spec.js
  e2e_playwright/shared/app_utils.py
  e2e_playwright/widget_state.py
  e2e_playwright/widget_state_heavy_usage_test.py
  e2e_playwright/widget_state_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8716 Add `icon` parameter to st.expander
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_emoji_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_emoji_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_emoji_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_emoji_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_emoji_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_emoji_icon[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_material_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_material_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_material_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_material_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_material_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_material_icon[light_theme-webkit].png
  e2e_playwright/st_expander.py
  e2e_playwright/st_expander_test.py
  frontend/lib/src/components/elements/Expander/Expander.test.tsx
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/shared/Icon/DynamicIcon.test.tsx
  frontend/lib/src/components/shared/Icon/DynamicIcon.tsx
  frontend/lib/src/components/shared/Icon/Icon.tsx
  frontend/lib/src/components/shared/Icon/Material/MaterialFontIcon.tsx
  frontend/lib/src/components/shared/Icon/styled-components.ts
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/mutable_status_container.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/elements/layouts_test.py
Labels: feature:st.expander, security-assessment-completed, change:feature, impact:users

#8896 Revert accidental rich deprecation
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8704 Allow the parent frame of a streamlit app to terminate/restart its websocket
  e2e/specs/hostframe.spec.js
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-after.snap.png
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/theme-message-before.snap.png
  frontend/cypress/snapshots/linux/2x/hostframe.spec.js/toolbarActions.snap.png
  frontend/hostframe.html
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
Labels: security-assessment-completed, impact:internal, change:feature

#8900 Fix: Remove title appending · Streamlit
  frontend/app/src/App.test.tsx
  frontend/app/src/util/AppNavigation.ts
Labels: security-assessment-completed, change:chore, impact:users

#8831 Docstrings for 1.36.0
  README.md
  component-lib/README.md
  e2e_playwright/st_exception.py
  frontend/app/src/components/StreamlitDialog/DeployErrorDialogs/__snapshots__/NoRepositoryDetected.test.tsx.snap
  frontend/app/src/urls.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/MapboxTokenError.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
  frontend/lib/src/components/widgets/Form/Form.tsx
  frontend/lib/src/urls.ts
  lib/setup.py
  lib/streamlit/__init__.py
  lib/streamlit/commands/navigation.py
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/html.py
  lib/streamlit/elements/iframe.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/write.py
  lib/streamlit/hello/Mapping_Demo.py
  lib/streamlit/navigation/page.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/legacy_cache_api.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/runtime_util.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/secrets.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/state/session_state_proxy.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/user_info.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, impact:internal, change:docs

#8916 Don't immediately remove fragments added by callbacks
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8798 Fix st.rerun fragment thread reuse issue
  lib/streamlit/commands/execution_control.py
  lib/streamlit/delta_generator.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8923 Update emojis used for validation
  lib/streamlit/emojis.py
  scripts/update_emojis.py
Labels: security-assessment-completed, change:other, impact:users

#8755 Migrate st_tooltips to playwright
  e2e/scripts/st_tooltips.py
  e2e/specs/st_tooltips.spec.js
  e2e_playwright/st_checkbox.py
  e2e_playwright/st_checkbox_test.py
  e2e_playwright/st_color_picker_test.py
  e2e_playwright/st_date_input.py
  e2e_playwright/st_date_input_test.py
  e2e_playwright/st_metric_test.py
  e2e_playwright/st_multiselect.py
  e2e_playwright/st_multiselect_test.py
  e2e_playwright/st_number_input.py
  e2e_playwright/st_number_input_test.py
  e2e_playwright/st_radio_test.py
  e2e_playwright/st_select_slider_test.py
  e2e_playwright/st_text_area_test.py
  e2e_playwright/st_time_input_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8926 Fix flaky slider test by waiting on the result text
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-time_value[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-time_value[light_theme-firefox].png
  e2e_playwright/conftest.py
  e2e_playwright/st_slider.py
  e2e_playwright/st_slider_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8940 Add support for numpy 2.x
  .github/workflows/pr-preview.yml
  lib/setup.py
  lib/test-requirements.txt
  lib/tests/streamlit/elements/bokeh_test.py
  lib/tests/streamlit/elements/image_test.py
Labels: security-assessment-completed, dev:upgrade-dependencies, change:other, impact:users

#8931 Set ctx.current_fragment_id in both full script and fragment runs
  e2e_playwright/st_fragments_nested.py
  e2e_playwright/st_fragments_nested_test.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8947 Update links to "Streamlit Components" in the main README.md
  README.md
Labels: security-assessment-completed, impact:internal, change:docs

#8948 Add 'apt update' command to Nightly Build to fix workflow
  .github/workflows/nightly.yml
Labels: security-assessment-completed, impact:internal, change:chore

#8872 Activate PYI linting rule for improved type linting
  .ruff.toml
  e2e_playwright/shared/dataframe_utils.py
  e2e_playwright/st_write.py
Labels: security-assessment-completed, change:other, impact:internal

#8918 Migrate st_session_state to playwright
  e2e/specs/st_session_state.spec.js
  e2e_playwright/st_session_state.py
  e2e_playwright/st_session_state_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8920 Migrate st tabs to playwright
  e2e/specs/st_tabs.spec.js
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-many[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-many[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-many[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-many[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-many[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-many[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-sidebar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-sidebar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-sidebar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-sidebar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-sidebar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-sidebar[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-text_input[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-text_input[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-text_input[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-text_input[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-text_input[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-text_input[light_theme-webkit].png
  e2e_playwright/st_tabs.py
  e2e_playwright/st_tabs_test.py
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#8943 Remove a bunch of deprecated experimental features
  lib/streamlit/__init__.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/rerun_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:chore, impact:users

#8968 Fix pandas deprecation warnings by using `.loc` for overwriting column
  lib/streamlit/elements/lib/built_in_chart_utils.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8945 Stacking options - `st.bar_chart`
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-13[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-13[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-13[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-14[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-14[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-14[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-15[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-15[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-15[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-16[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-16[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-16[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-17[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-17[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-17[webkit].png
  e2e_playwright/st_bar_chart.py
  e2e_playwright/st_bar_chart_test.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed, change:feature, impact:users

#8996 Add script to update material icon names
  lib/streamlit/material_icon_names.py
  scripts/update_material_icon_names.py
Labels: security-assessment-completed, change:other, impact:internal

#8993 Support `graphviz.sources.Source` object for `st.graphviz_chart`
  lib/streamlit/elements/graphviz_chart.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/elements/graphviz_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8874 Activate pylint convention rules in ruff
  .ruff.toml
  e2e_playwright/st_graphviz_chart.py
  lib/dev-requirements.txt
  lib/streamlit/components/v1/components.py
  lib/streamlit/testing/v1/element_tree.py
Labels: security-assessment-completed, change:other, impact:internal

#8998 Migrate custom icons from material outlined to rounded
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link-hover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_configure_sidebar_test/page-link[light_theme-webkit].png
  frontend/app/src/assets/css/icon-fonts.scss
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Outlined.woff2
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  frontend/lib/src/components/elements/Favicon/Favicon.test.tsx
  frontend/lib/src/components/elements/Favicon/Favicon.tsx
  frontend/lib/src/components/shared/Icon/Material/styled-components.ts
  lib/streamlit/commands/page_config.py
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/navigation/page.py
  scripts/update_material_icon_names.py
Labels: security-assessment-completed, change:refactor, impact:users

#8988 Support non-unix style paths for MPA loading
  lib/streamlit/web/server/routes.py
Labels: security-assessment-completed, change:bugfix, impact:users
