Repository streamlit/streamlit, pull requests merged in 2024-04, with the labels that each got.

#8278 Offset dates in vega if no timezone information is attached.
  e2e/specs/st_arrow_chart_utc_time.spec.js
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_area_chart[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_area_chart[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_area_chart[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_area_chart[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_area_chart[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_area_chart[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_bar_chart[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_bar_chart[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_bar_chart[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_bar_chart[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_bar_chart[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_bar_chart[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_line_chart[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_line_chart[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_line_chart[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_line_chart[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_line_chart[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_arrow_chart_utc_time_test/st_altair_chart-utc_line_chart[light_theme-webkit].png
  e2e_playwright/st_arrow_chart_utc_time.py
  e2e_playwright/st_arrow_chart_utc_time_test.py
  frontend/cypress/snapshots/linux/2x/st_arrow_chart_utc_time.spec.js/arrowChartUTCTime-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_chart_utc_time.spec.js/arrowChartUTCTime-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_chart_utc_time.spec.js/arrowChartUTCTime-2.snap.png
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.test.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/mocks/arrow/index.ts
  frontend/lib/src/mocks/arrow/types/datetime.ts
  lib/streamlit/elements/arrow_altair.py
  lib/tests/streamlit/elements/arrow_altair_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8397 Docs/release 1.33
  lib/streamlit/elements/html.py
  lib/streamlit/elements/media.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
Labels: security-assessment-completed, impact:internal, change:docs

#8274 Update modal styles
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/record_screencast_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/record_screencast_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-webkit].png
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/lib/src/components/shared/Modal/Modal.tsx
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
Labels: area:layout, security-assessment-completed, change:chore, impact:users

#8421 Fixing failing session gc test in CI
  lib/tests/streamlit/runtime/app_session_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8408 Fix issues with fragments writing to containers and the sidebar
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/spinner.py
  lib/streamlit/elements/widgets/chat.py
  lib/tests/streamlit/delta_generator_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8417 Fix unixodbc-dev dependency
  .github/actions/make_init/action.yml
  .github/workflows/python-min-deps.yml
Labels: area:infra, security-assessment-completed, impact:internal, change:bugfix

#8418 Construct paths relative to file for html tests
  lib/tests/streamlit/elements/html_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8396 Only apply widget id if on_select is true
  lib/streamlit/elements/arrow_vega_lite.py
Labels: security-assessment-completed, impact:internal, change:chore

#8419 Fix usage of functional string
  lib/streamlit/delta_generator.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8377 Fix Plotly State when double clicking when a selection is present
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8255 Add e2e tests for Plotly
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-double_select[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-double_select[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-double_select[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-single_select[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-single_select[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-single_select[webkit].png
  e2e_playwright/st_plotly_chart_select.py
  e2e_playwright/st_plotly_chart_select_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8404 Use decamelize instead of helper function and other miscellaneous code changes
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, impact:internal, change:chore

#8379 Fix CI conda build
  .github/workflows/conda-build.yml
  lib/conda-recipe/meta.yaml
Labels: security-assessment-completed, impact:internal, change:chore

#8420 Cleanup legacy cache dependencies
  .github/actions/make_init/action.yml
  .github/workflows/python-min-deps.yml
  lib/test-requirements.txt
  lib/tests/streamlit/runtime/legacy_caching/hashing_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8442 Remove flaky cypress e2e test folder
  .pre-commit-config.yaml
  e2e_flaky/scripts/st_empty.py
  e2e_flaky/scripts/st_pyplot_kwargs.py
  e2e_flaky/specs/st_empty.spec.ts
  e2e_flaky/specs/st_pyplot_kwargs.spec.ts
  frontend/package.json
  scripts/check_license_headers.py
  scripts/run_e2e_tests.py
Labels: security-assessment-completed, change:other, impact:internal

#8444 Remove already migrated cache e2e test
  e2e/scripts/cached_widget_replay_widget_key.py
Labels: security-assessment-completed, change:other, impact:internal

#8433 Move toasts to top right and make them prettier
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-with-chat[light_theme-webkit].png
  e2e_playwright/st_toast_test.py
  frontend/app/src/components/EventContainer/EventContainer.tsx
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
  frontend/lib/src/components/elements/Toast/styled-components.tsx
Labels: security-assessment-completed, change:other, impact:users

#8434 Make check for component ready dynamic
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/CustomComponent/componentUtils.test.ts
  frontend/lib/src/components/widgets/CustomComponent/componentUtils.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8304 Fix concatenated charts and no name altair selection objects
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/yarn.lock
  lib/streamlit/elements/arrow_vega_lite.py
Labels: security-assessment-completed, change:feature, impact:users

#8391 Interactive selection concatenated charts e2e tests for Altair
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[light_theme-webkit].png
  e2e_playwright/st_altair_chart_concatenated_select.py
  e2e_playwright/st_altair_chart_concatenated_select_test.py
  lib/streamlit/elements/arrow_vega_lite.py
Labels: security-assessment-completed, impact:internal, change:chore

#8423 [InteractiveCharts] Basic E2E Altair Charts
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_double_selection_greyed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_double_selection_greyed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_double_selection_greyed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_double_selection_greyed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_double_selection_greyed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_double_selection_greyed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_interval_selection_greyed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_interval_selection_greyed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_interval_selection_greyed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_interval_selection_greyed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_interval_selection_greyed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_interval_selection_greyed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_single_selection_greyed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_single_selection_greyed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_single_selection_greyed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_single_selection_greyed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_single_selection_greyed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_basic_select_test/st_altair_chart-scatter_single_selection_greyed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-hconcat_chart_interval[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_original[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-layered_chart_point_selection_greyed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_interval_selection[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-repeat_scatter_single_selection[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_concatenated_select_test/st_altair_chart-vconcat_chart_interval[light_theme-webkit].png
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_altair_chart_concatenated_select.py
  e2e_playwright/st_altair_chart_concatenated_select_test.py
  lib/streamlit/elements/arrow_vega_lite.py
Labels: security-assessment-completed, impact:internal, change:chore

#8445 Scale down cypress CI workers
  .github/workflows/cypress.yml
Labels: security-assessment-completed, change:other, impact:internal

#8447 Upgrade plotly and plotly types versioning
  NOTICES
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#8451 Remove camera input cypress tests (already migrated to playwright)
  e2e/scripts/st_camera_input.py
  e2e/specs/st_camera_input.spec.js
  frontend/cypress/snapshots/linux/2x/st_camera_input.spec.js/disabled-camera-input-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_camera_input.spec.js/disabled-camera-input.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8446 Remove file_uploader cypress tests (already migrated to playwright).
  e2e/scripts/st_file_uploader.py
  e2e/specs/st_file_uploader.spec.js
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/collapsed_label_file_uploader-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/collapsed_label_file_uploader.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/disabled_file_uploader-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/disabled_file_uploader.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/file_uploader-error-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/file_uploader-error.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/hidden_label_file_uploader-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/hidden_label_file_uploader.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/multi_file_uploader-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/multi_file_uploader-uploaded-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/multi_file_uploader-uploaded.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/multi_file_uploader.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/single_file_uploader-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/single_file_uploader-uploaded-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/single_file_uploader-uploaded.snap.png
  frontend/cypress/snapshots/linux/2x/st_file_uploader.spec.js/single_file_uploader.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8460 Update nightly release to OpenID Connect
  .github/workflows/nightly.yml
Labels: security-assessment-completed, impact:internal, change:chore

#8353 Check for selection objects properly within altair / vega lite json
  lib/streamlit/constants.py
  lib/streamlit/elements/arrow_altair.py
  lib/streamlit/elements/arrow_vega_lite.py
Labels: security-assessment-completed, impact:internal, change:chore

#8469 Update Auto Theme after print dialog if necessary
  frontend/app/src/util/useThemeManager.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8472 Add BlueOak to acceptable licenses
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed, change:other, impact:internal

#8467 Change proto size field type to uint64 to allow large files (>4gb)
  proto/streamlit/proto/Common.proto
Labels: security-assessment-completed, impact:internal, change:bugfix

#8040 Add st.dialog
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-in-main[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-in-main[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-in-main[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-in-sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-in-sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-in-sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-with-large-width[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-with-large-width[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-with-large-width[webkit].png
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_nested.py
  e2e_playwright/st_dialog_nested_test.py
  e2e_playwright/st_dialog_test.py
  frontend/app/src/util/useThemeManager.ts
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/IsDialogContext.ts
  frontend/lib/src/components/elements/Dialog/Dialog.test.tsx
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  frontend/lib/src/components/elements/Dialog/index.tsx
  frontend/lib/src/components/elements/Dialog/styled-components.ts
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/index.ts
  lib/streamlit/__init__.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/dialog.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/layouts_test.py
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#8449 Cleanup for st.toast changes
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[light_theme-webkit].png
  e2e_playwright/st_toast_test.py
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/EventContainer/EventContainer.test.tsx
  frontend/app/src/components/EventContainer/EventContainer.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
  frontend/lib/src/theme/primitives/breakpoints.ts
Labels: security-assessment-completed, impact:internal, change:chore

#8462 Fix Double Clicking Behavior to maintain correct Altair state
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8487 Fix plotly playwright snapshots on develop
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line-chart-specific-height-width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line-chart-specific-height-width[light_theme-firefox].png
Labels: security-assessment-completed, impact:internal, change:chore

#8425 Reset widget state on page change
  e2e_playwright/multipage_apps/mpa_basics_test.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/session_state.py
Labels: feature:multipage-apps, security-assessment-completed, change:bugfix, impact:users

#8470 from_dict for query params
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/state/query_params_proxy_test.py
  lib/tests/streamlit/runtime/state/query_params_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8492 Switch back to using undeprecated pillow constant
  lib/streamlit/elements/image.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8493 Fix double script/callback run when replacing a file
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8074 Add internal skeleton element
  .pre-commit-config.yaml
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_table_test.py
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/withMapboxToken.tsx
  frontend/lib/src/components/elements/Skeleton/Skeleton.test.tsx
  frontend/lib/src/components/elements/Skeleton/Skeleton.tsx
  frontend/lib/src/components/elements/Skeleton/styled-components.ts
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/util/utils.ts
  lib/streamlit/elements/empty.py
  lib/tests/streamlit/elements/doc_string_test.py
  lib/tests/streamlit/elements/empty_test.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/runtime/script_data_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/secrets_test.py
  lib/tests/streamlit/source_util_test.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/streamlit/web/cli_test.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
  lib/tests/streamlit/web/server/routes_test.py
  lib/tests/streamlit/web/server/server_test.py
  proto/streamlit/proto/Element.proto
  proto/streamlit/proto/Skeleton.proto
  scripts/run_in_subdirectory.py
Labels: security-assessment-completed, impact:internal, change:feature

#8448 Add new widget state manager methods to store frontend-only element state
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
Labels: security-assessment-completed, impact:internal, change:chore

#8484 [Plotly Selections] Refactor Keeping Zoom State to use new ElementState
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line-chart-specific-height-width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-line-chart-specific-height-width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-template-customization[dark_theme-chromium].png
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#8512 Rename snapshots of st.dialog e2e playwright tests
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-with-large-width[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/dialog-with-large-width[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[webkit].png
  e2e_playwright/st_dialog_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8513 Migrate hello app e2e tests to playwright
  e2e/specs/st_hello.spec.js
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-animation_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-home_page[webkit].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[chromium].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[firefox].png
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-plotting_demo_page[webkit].png
  e2e_playwright/hello_app.py
  e2e_playwright/hello_app_test.py
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/animation-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/dataframe-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/hello-mpa-sidebar-nav-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/hello-mpa-sidebar-nav.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/mapping-demo.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_hello.spec.js/welcome-streamlit.snap.png
Labels: security-assessment-completed, impact:internal, change:refactor

#8491 Use `cache_data` instead of `memo` decorator name
  lib/streamlit/runtime/caching/cached_message_replay.py
Labels: security-assessment-completed, impact:internal, change:chore

#8510 Fix escaping in docstrings
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, impact:users, change:docs

#8520 Fix typo in fragments docstring
  lib/streamlit/runtime/fragment.py
Labels: security-assessment-completed, impact:internal, change:docs

#8522 Add tests and remove onDoubleClick for selection state for Plotly
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-zoomed_in_reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-zoomed_in_reset[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-zoomed_in_reset[webkit].png
  e2e_playwright/st_plotly_chart_select_test.py
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  lib/tests/streamlit/elements/plotly_chart_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8369 Fix empty state for `st.status`
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-empty_state[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-empty_state[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-empty_state[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-empty_state[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-empty_state[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-empty_state[light_theme-webkit].png
  frontend/lib/src/components/elements/Expander/Expander.test.tsx
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/Expander/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8471 Fix `st.multiselect` usage with empty sets or tuples
  lib/streamlit/elements/widgets/multiselect.py
  lib/tests/streamlit/elements/multiselect_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8526 Remove outdated examples folder
  Makefile
  examples/animation.py
  examples/audio.py
  examples/caching.py
  examples/data/REMOVE_FOLDER_ON_2020_09_01
  examples/data/bart_path_stats.json
  examples/data/bart_path_stats.md
  examples/data/bart_stop_stats.json
  examples/data/bart_stop_stats.md
  examples/data/bike_rental_stats.json
  examples/data/bike_rental_stats.md
  examples/file_uploader.py
  examples/images.py
  examples/lists.py
  examples/mnist-cnn.py
  examples/plotly_example.py
  examples/run_on_save.py
  examples/syntax_error.py
  examples/syntax_hilite.py
  examples/video.py
  lib/tests/streamlit/url_util_test.py
  scripts/cli_regression_tests.py
  scripts/run_all_examples.py
Labels: security-assessment-completed, change:other, impact:internal

#8523 Update release to OpenID Connect
  .github/workflows/release.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#8497 Handle Altair resolve_scale
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-resolve-scale-independent[light_theme-webkit].png
  e2e_playwright/st_altair_chart.py
  e2e_playwright/st_altair_chart_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8537 Fix vega_lite_test as it was using altair_chart
  lib/tests/streamlit/elements/arrow_vega_lite_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8519 Adjust default date for st.date_input if today's date is out of bounds
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/elements/date_input_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8538 Remove snowflake extras python restriction
  lib/setup.py
Labels: security-assessment-completed, change:other, impact:users

#8527 Migrate st arrow empty charts to playwright
  e2e/scripts/st_arrow_empty_charts.py
  e2e/specs/st_arrow_empty_charts.spec.js
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-empty[chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-empty[firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-empty[webkit].png
  e2e_playwright/st_pyplot.py
  e2e_playwright/st_pyplot_test.py
  e2e_playwright/st_vega_lite_chart.py
  e2e_playwright/st_vega_lite_chart_test.py
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-2.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_arrow_empty_charts.spec.js/arrowVegaLiteChart-3.snap.png
  lib/tests/streamlit/elements/arrow_altair_test.py
  lib/tests/streamlit/elements/arrow_vega_lite_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8478 Enable configuring the __webpack_public_path__
  frontend/app/src/index.tsx
  frontend/app/src/setWebpackPublicPath.ts
Labels: security-assessment-completed, impact:internal, change:feature

#8529 Handle setting session state keys to None for supported widgets
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/elements/date_input_test.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/elements/radio_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  lib/tests/streamlit/elements/text_area_test.py
  lib/tests/streamlit/elements/text_input_test.py
  lib/tests/streamlit/elements/time_input_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8515 Evaluate different mechanism to keep plotly state
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-zoomed_in_reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-zoomed_in_reset[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-zoomed_in_reset[webkit].png
  e2e_playwright/st_plotly_chart_select_test.py
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  lib/streamlit/elements/plotly_chart.py
  lib/tests/streamlit/elements/plotly_chart_test.py
  proto/streamlit/proto/PlotlyChart.proto
Labels: security-assessment-completed, impact:internal, change:chore

#8525 Attempt to remove bool for on select param
  e2e_playwright/st_plotly_chart_select.py
  lib/streamlit/elements/plotly_chart.py
  lib/tests/streamlit/elements/plotly_chart_test.py
Labels: security-assessment-completed, change:chore, impact:users

#8543 Remove html comment from PR template
  .github/pull_request_template.md
Labels: security-assessment-completed, change:other, impact:internal

#8539 Migrate st_empty to playwright
  e2e/scripts/st_empty.py
  e2e/specs/st_empty.spec.js
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-no_vertical_space_taken[chromium].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-no_vertical_space_taken[firefox].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-no_vertical_space_taken[webkit].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-order_after_replacement[chromium].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-order_after_replacement[firefox].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-order_after_replacement[webkit].png
  e2e_playwright/st_empty.py
  e2e_playwright/st_empty_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#8550 Fix typechecking for Interactive Plotly Charts
  lib/streamlit/elements/plotly_chart.py
Labels: security-assessment-completed, impact:internal, change:chore

#8548 Migrate st_markdown to playwright
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-heading_and_markdown_combinations[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-heading_and_markdown_combinations[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-heading_and_markdown_combinations[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long-markdown-header-above-table[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long-markdown-header-above-table[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long-markdown-header-above-table[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-num_elements_displayed[light_theme-webkit].png
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8551 Fix Python tests for Interactive Plotly Charts
  lib/streamlit/elements/plotly_chart.py
  lib/tests/streamlit/elements/plotly_chart_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8481 Add support for autoplaying `st.audio` and `st.video` media
  e2e_playwright/st_audio.py
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_video.py
  e2e_playwright/st_video_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/Audio/Audio.test.tsx
  frontend/lib/src/components/elements/Audio/Audio.tsx
  frontend/lib/src/components/elements/Video/Video.test.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  lib/streamlit/elements/media.py
  lib/tests/streamlit/elements/audio_test.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/elements/video_test.py
  proto/streamlit/proto/Audio.proto
  proto/streamlit/proto/Video.proto
Labels: feature:st.audio, feature:st.video, security-assessment-completed, change:feature, impact:users

#8557 Add Interactive Plotly typescript unit tests
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#8561 Fix double click Plotly behavior
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-bar_chart_reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-bar_chart_reset[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-bar_chart_reset[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-panned_reset[webkit].png
  e2e_playwright/st_plotly_chart_select_test.py
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8560 Fix empty generator usage with `st.write_stream`
  lib/streamlit/elements/write.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8570 Add tests for selection_mode and fix bug where single selection mode wasn't working
  e2e_playwright/st_plotly_chart_select.py
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8422 Enable the usage of the pydeck-carto package with st.pydeck_chart
  NOTICES
  frontend/lib/package.json
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/declarations.d.ts
  frontend/yarn.lock
Labels: security-assessment-completed, dev:full-matrix, dev:upgrade-dependencies, change:feature, impact:users

#8574 Deactivate point selection if selection mode doesn't include points
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8577 Fix plotly tab change flickering
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, change:other, change:bugfix

#8573 Lower cypress workers to four
  .github/workflows/cypress.yml
Labels: security-assessment-completed, change:other, impact:internal

#8580 Fix broken python github actions
  lib/test-requirements.txt
Labels: security-assessment-completed, impact:internal, change:chore

#8579 Fix Interactive Plotly e2e playwright nits
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-reset[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-unmounted_still_has_selection[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-unmounted_still_has_selection[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_select_test/st_plotly_chart-unmounted_still_has_selection[webkit].png
  e2e_playwright/st_plotly_chart_select.py
  e2e_playwright/st_plotly_chart_select_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8583 Move material icon styling to styled component
  frontend/app/src/assets/css/icon-fonts.scss
  frontend/lib/src/components/shared/Icon/Material/MaterialFontIcon.tsx
  frontend/lib/src/components/shared/Icon/Material/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:chore

#8585 Add unit test for box and lasso selection
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#8549 [InteractiveChartsAltair] Form support for Interactive charts altair
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  lib/streamlit/elements/arrow_altair.py
  proto/streamlit/proto/ArrowVegaLiteChart.proto
Labels: security-assessment-completed, change:feature, impact:users

#8590 Update Codeowners to represent the team
  .github/CODEOWNERS
Labels: security-assessment-completed, impact:internal, change:chore

#8581 feat: support set mysql connection query from secrets.toml
  lib/streamlit/connections/sql_connection.py
  lib/tests/streamlit/connections/sql_connection_test.py
Labels: security-assessment-completed, change:feature, impact:users
