Repository streamlit/streamlit, pull requests merged in 2024-03, with the labels that each got.

#8221 Change youtube url regex to match youtube urls more formats
  lib/streamlit/elements/media.py
  lib/tests/streamlit/elements/video_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8228 Make st.help more resilient with conditional members
  lib/streamlit/elements/doc_string.py
  lib/tests/streamlit/elements/doc_string_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8218 Add an isFragmentRun field for page profiling
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  proto/streamlit/proto/PageProfile.proto
Labels: security-assessment-completed, impact:internal, change:feature

#8219 Add basic e2e tests for @st.experimental_fragment
  e2e_playwright/st_experimental_fragment_basics.py
  e2e_playwright/st_experimental_fragment_basics_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8229 Release 1.32.0 docstrings
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/write.py
  lib/streamlit/testing/v1/app_test.py
Labels: security-assessment-completed, impact:internal, change:docs

#8232 Fix flaky e2e test
  e2e_playwright/st_popover.py
Labels: security-assessment-completed, change:other, impact:internal

#7998 Migrate `LinkColumn` to native implementation in glide-data-grid
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-link_column[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_link_display_value[light_theme-webkit].png
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/cells/LinkCell.test.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/LinkCell.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/UriOverlayEditor.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/uri-overlay-editor-style.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/index.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#8193 ComponentRegistry Abstract
  lib/streamlit/components/lib/__init__.py
  lib/streamlit/components/lib/local_component_registry.py
  lib/streamlit/components/types/__init__.py
  lib/streamlit/components/types/base_component_registry.py
  lib/streamlit/components/types/base_custom_component.py
  lib/streamlit/components/v1/__init__.py
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/web/server/component_request_handler.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/runtime_threading_test.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8241 Move dg_stack into delta_generator.py and ensure it's never empty
  lib/streamlit/__init__.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/form.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8205 explicit update() method for query_params
  .pre-commit-config.yaml
  lib/streamlit/runtime/forward_msg_queue.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/state/query_params_proxy_test.py
  lib/tests/streamlit/runtime/state/query_params_test.py
  scripts/mypy
  scripts/run_in_subdirectory.py
Labels: security-assessment-completed, change:feature, impact:users

#8243 Update `st.popover` styling
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-container[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-container[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-container[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-container[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-container[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-container[light_theme-webkit].png
  frontend/lib/src/components/elements/Popover/Popover.tsx
Labels: security-assessment-completed, change:other, impact:internal

#8189 AppTest format_func
  lib/streamlit/config.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/testing/element_tree_test.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#8160 Migrate stale PR handling to Github Actions
  .github/stale.yml
  .github/workflows/stale.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#8238 Require explicit suggestion of unsafe_allow_html in st.write
  e2e_playwright/__snapshots__/linux/st_write_test/write_datetime[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_datetime[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_datetime[webkit].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_int[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_int[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_int[webkit].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_multi_line_monospace_block[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_multi_line_monospace_block[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_multi_line_monospace_block[webkit].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_none[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_none[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_none[webkit].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_np_float[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_np_float[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_np_float[webkit].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_single_line_monospace_block[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_single_line_monospace_block[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_test/write_single_line_monospace_block[webkit].png
  e2e_playwright/st_write.py
  e2e_playwright/st_write_test.py
  lib/streamlit/elements/write.py
  lib/streamlit/string_util.py
  lib/tests/streamlit/string_util_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:breaking, change:bugfix, impact:users

#8257 Upgrade decamelize
  NOTICES
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#8260 Fix bug with elements not always being cleared correctly in fragment runs
  frontend/app/src/App.tsx
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/fragment_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8258 Url decode link column display values if regex is used
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8264 Fix infinite loop when `rerun` and triggered widgets are used together in AppTest
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/tests/streamlit/testing/app_test_test.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#8256 Release 1.32.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#8267 Stop pruning empty blocks in clearStaleNodes
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, impact:internal, change:feature

#8266 Use the button width as minimum for `st.popover` container
  e2e_playwright/st_popover_test.py
  frontend/lib/src/components/elements/Popover/Popover.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8155 Associate label with input to make label click focus input
  frontend/lib/src/components/widgets/BaseWidget/WidgetLabel.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, change:feature, impact:users

#8281 Revert "Expire session storage cache on an async timer (#8083)"
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py
  lib/streamlit/runtime/memory_session_storage.py
  lib/streamlit/util.py
  lib/tests/streamlit/util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8021 Allow custom themes to override embed options query parameter
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-template-customization[dark_theme-chromium].png
  frontend/app/src/App.tsx
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8286 Make Text Input Ids more stable for testing purposes
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#8287 Add linting to ensure lodash imports are correct
  frontend/.eslintrc.js
  frontend/app/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#8203 Media elements improvements
  e2e_playwright/st_audio.py
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_video.py
  e2e_playwright/st_video_test.py
  frontend/lib/src/components/elements/Audio/Audio.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  lib/streamlit/elements/media.py
  lib/tests/streamlit/elements/audio_test.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/elements/video_test.py
  proto/streamlit/proto/Audio.proto
  proto/streamlit/proto/Video.proto
Labels: feature:st.audio, feature:st.video, security-assessment-completed, change:feature, impact:users

#8292 Skip flaky audio tests for webkit
  e2e_playwright/st_audio_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8280 Page switching in AppTest
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/tests/streamlit/testing/app_test_test.py
  lib/tests/streamlit/testing/test_data/main.py
  lib/tests/streamlit/testing/test_data/pages/page1.py
Labels: security-assessment-completed, change:feature, impact:users, feature:app-testing

#8290 Fix initial iframe height for custom component
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8299 Release 1.32.2
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#8305 Don't reset title and favicon when running fragment
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:feature, impact:users

#8298 Have fragment rerun requests not interrupt the current script
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/scriptrunner/script_requests.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_requests_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8312 Migrate st_spinner to playwright
  e2e_playwright/st_spinner.py
  e2e_playwright/st_spinner_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8314 Migrate st_help to playwright
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-0[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-0[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-0[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-1[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-1[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-1[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-2[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-2[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-2[webkit].png
  e2e_playwright/st_help.py
  e2e_playwright/st_help_test.py
  frontend/cypress/snapshots/linux/2x/st_help.spec.js/help-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_help.spec.js/help-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_help.spec.js/help-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_help.spec.js/help-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_help.spec.js/help-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_help.spec.js/help-2.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8324 Remove specs that were removed in other PRs
  e2e/specs/st_help.spec.js
  e2e/specs/st_spinner.spec.js
Labels: security-assessment-completed, impact:internal, change:chore

#8309 Update dependabot to valid settings
  .github/dependabot.yml
Labels: security-assessment-completed, impact:internal, change:chore

#8279 Fullscreen Button Overflow Horizontally
  e2e/specs/st_columns_layout.spec.js
  e2e_playwright/__snapshots__/linux/responsive_test/page_fullscreen_button_edge_case[chromium].png
  e2e_playwright/__snapshots__/linux/responsive_test/page_fullscreen_button_edge_case[firefox].png
  e2e_playwright/__snapshots__/linux/responsive_test/page_fullscreen_button_edge_case[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-horizontal[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-horizontal[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-horizontal[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-horizontal[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-horizontal[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-horizontal[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-vertical[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-vertical[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-vertical[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-vertical[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-vertical[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-layout-vertical[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-with-one-element[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-with-one-element[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-with-one-element[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-with-one-element[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-with-one-element[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_layout_test/columns-with-one-element[light_theme-webkit].png
  e2e_playwright/responsive.py
  e2e_playwright/responsive_test.py
  e2e_playwright/st_columns_layout.py
  e2e_playwright/st_columns_layout_test.py
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/styled-components.ts
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8242 Fix white components backgrounds when OS is using dark theme
  e2e_playwright/st_components_v1_test.py
  frontend/lib/src/components/elements/IFrame/IFrame.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/elements/PlotlyChart/__snapshots__/PlotlyChart.test.tsx.snap
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/elements/Video/__snapshots__/Video.test.tsx.snap
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#8316 Migrate st_magic to playwright
  e2e/specs/st_magic.spec.js
  e2e_playwright/st_magic.py
  e2e_playwright/st_magic_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8313 Migrate st_divider to playwright
  e2e/specs/st_divider.spec.js
  e2e_playwright/__snapshots__/linux/st_divider_test/st_divider[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_divider_test/st_divider[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_divider_test/st_divider[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_divider_test/st_divider[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_divider_test/st_divider[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_divider_test/st_divider[light_theme-webkit].png
  e2e_playwright/st_divider.py
  e2e_playwright/st_divider_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8339 Fix typo, use toml format instead of python
  lib/streamlit/runtime/credentials.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8325 Migrate st_progress to playwright
  e2e/specs/st_progress.spec.js
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-0[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-0[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-0[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-0[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-0[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-0[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-1[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-1[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-1[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-1[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-1[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-1[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-2[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-2[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-2[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-2[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-2[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_progress_test/st_progress-2[light_theme-webkit].png
  e2e_playwright/st_progress.py
  e2e_playwright/st_progress_test.py
  frontend/cypress/snapshots/linux/2x/st_progress.spec.js/progresbar-0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_progress.spec.js/progresbar-0.snap.png
  frontend/cypress/snapshots/linux/2x/st_progress.spec.js/progresbar-1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_progress.spec.js/progresbar-1.snap.png
  frontend/cypress/snapshots/linux/2x/st_progress.spec.js/progresbar-2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_progress.spec.js/progresbar-2.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8333 Remove or resolve a few misc TODOs in the feature branch
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
Labels: security-assessment-completed, change:feature, impact:users

#8332 Take fragments into account when clearing stale widgets
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/state/widgets.py
  lib/tests/streamlit/runtime/state/session_state_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8341 Teach frontend that several fragments can run in one script run
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/Block/utils.test.ts
  frontend/lib/src/components/core/Block/utils.ts
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  frontend/lib/src/test_util.tsx
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#8340 Add metrics tracking for toolbar item clicks
  frontend/app/src/App.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.test.tsx
  frontend/app/src/components/ToolbarActions/ToolbarActions.tsx
Labels: security-assessment-completed, change:other, impact:internal

#8356 migrate st_rerun to playwright
  e2e/specs/st_rerun.spec.js
  e2e_playwright/st_rerun.py
  e2e_playwright/st_rerun_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8315 Migrate st_echo to playwright
  e2e/specs/st_echo.spec.js
  e2e_playwright/__snapshots__/linux/st_echo_test/st_echo-code_location_above_and_below[chromium].png
  e2e_playwright/__snapshots__/linux/st_echo_test/st_echo-code_location_above_and_below[firefox].png
  e2e_playwright/__snapshots__/linux/st_echo_test/st_echo-code_location_above_and_below[webkit].png
  e2e_playwright/st_echo.py
  e2e_playwright/st_echo_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8359 Remove st_message_deduping as it doesn't actually check anything
  e2e/scripts/st_message_deduping.py
  e2e/specs/st_message_deduping.spec.js
Labels: security-assessment-completed, impact:internal, change:chore

#8358 Migrate st_stop to playwright
  e2e/specs/st_stop.spec.js
  e2e_playwright/st_stop.py
  e2e_playwright/st_stop_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8361 Don't forget to set fragmentIdsThisRun on full script runs too
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:feature, impact:users

#8354 Migrate st_text to playwright
  e2e/specs/st_text.spec.js
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-ascii_art[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-ascii_art[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-ascii_art[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[webkit].png
  e2e_playwright/st_text.py
  e2e_playwright/st_text_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8338 Allow packaging 24.x
  lib/setup.py
Labels: security-assessment-completed, change:other, impact:users

#8311 Add simple fix to update container status after llm complete
  lib/streamlit/external/langchain/streamlit_callback_handler.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8337 Simplify toast message truncation to use character limit directly
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
Labels: security-assessment-completed, feature:st.toast, change:bugfix, impact:users

#8374 Migrate st_nested_columns to playwright
  e2e/specs/st_nested_columns_1.spec.js
  e2e_playwright/__snapshots__/linux/st_columns_nested_1_test/st_columns-widget_layout_left_graph_right[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_1_test/st_columns-widget_layout_left_graph_right[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_1_test/st_columns-widget_layout_left_graph_right[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_1_test/st_columns-widget_layout_left_graph_right[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_1_test/st_columns-widget_layout_left_graph_right[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_1_test/st_columns-widget_layout_left_graph_right[light_theme-webkit].png
  e2e_playwright/st_columns_nested_1.py
  e2e_playwright/st_columns_nested_1_test.py
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_0.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_1.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_2.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_3.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_4.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_5.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_6.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_7-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_7.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_1.spec.js/nested_columns_1_8.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8348 Add ability to use timedelta and stings to `start_time` and `end_time`.
  lib/streamlit/elements/media.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/runtime_util.py
  lib/tests/streamlit/elements/audio_test.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/runtime/caching/cache_utils_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8383 Migrate st_columns_nested_3 to playwright
  e2e/specs/st_nested_columns_3.spec.js
  e2e_playwright/st_columns_nested_3.py
  e2e_playwright/st_columns_nested_3_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8385 Migrate st_columns_nested_4 to playwright
  e2e/specs/st_nested_columns_4.spec.js
  e2e_playwright/st_columns_nested_4.py
  e2e_playwright/st_columns_nested_4_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8384 Migrate st_nested_columns_2 to playwright
  e2e/specs/st_nested_columns_2.spec.js
  e2e_playwright/__snapshots__/linux/st_columns_nested_2_test/st_columns-long_texts[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_2_test/st_columns-long_texts[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_2_test/st_columns-long_texts[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_2_test/st_columns-long_texts[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_2_test/st_columns-long_texts[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_nested_2_test/st_columns-long_texts[light_theme-webkit].png
  e2e_playwright/st_columns_nested_2.py
  e2e_playwright/st_columns_nested_2_test.py
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_0.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_1.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_2.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_3.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_4.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_5.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_6.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_7-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_7.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_nested_columns_2.spec.js/nested_columns_2_8.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8389 Revert "ComponentRegistry Abstract"
  lib/streamlit/components/lib/__init__.py
  lib/streamlit/components/lib/local_component_registry.py
  lib/streamlit/components/types/__init__.py
  lib/streamlit/components/types/base_component_registry.py
  lib/streamlit/components/types/base_custom_component.py
  lib/streamlit/components/v1/__init__.py
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/components/v1/components.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/web/server/component_request_handler.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_test_case.py
  lib/tests/streamlit/runtime/runtime_threading_test.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8392 Readd mistakenly removed line and add explanatory comment
  lib/streamlit/runtime/fragment.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8393 Add more complex e2e tests for @st.experimental_fragment
  e2e_playwright/__snapshots__/linux/st_experimental_fragment_chat_response_test/chart_after_fragment_rerun[chromium].png
  e2e_playwright/__snapshots__/linux/st_experimental_fragment_chat_response_test/chart_before_fragment_rerun[chromium].png
  e2e_playwright/st_experimental_fragment_chat_response.py
  e2e_playwright/st_experimental_fragment_chat_response_test.py
  e2e_playwright/st_experimental_fragment_dynamic_form.py
  e2e_playwright/st_experimental_fragment_dynamic_form_test.py
  e2e_playwright/st_experimental_fragment_multiple_fragments.py
  e2e_playwright/st_experimental_fragment_multiple_fragments_test.py
  e2e_playwright/st_experimental_fragment_run_every.py
  e2e_playwright/st_experimental_fragment_run_every_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#8366 Feature: `st.html`
  .pre-commit-config.yaml
  NOTICES
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-inline_styles[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-inline_styles[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-inline_styles[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-inline_styles[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-inline_styles[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-inline_styles[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-script_tags[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tags[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tags[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tags[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tags[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tags[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tags[light_theme-webkit].png
  e2e_playwright/st_html.py
  e2e_playwright/st_html_test.py
  frontend/lib/package.json
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/elements/Html/Html.test.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
  frontend/lib/src/components/elements/Html/index.tsx
  frontend/yarn.lock
  lib/streamlit/__init__.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/html.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/html_test.py
  lib/tests/streamlit/elements/test_html.js
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/Element.proto
  proto/streamlit/proto/Html.proto
  scripts/check_license_headers.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#8395 Gather metrics on `get_option`
  lib/streamlit/__init__.py
Labels: security-assessment-completed, impact:internal, change:chore
