Repository streamlit/streamlit, pull requests merged in 2024-01, with the labels that each got.

#7887 Prevent incompatible column config serialization
  lib/streamlit/elements/lib/column_config_utils.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7888 Prevent hiding required editable columns
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7827 Disable the ability to submit form if a submit button is disabled
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7893 Group by stats for `_stcore/metrics` endpoint to avoid duplicate rows
  lib/streamlit/runtime/stats.py
  lib/tests/streamlit/runtime/stats_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7774 st.query_params
  e2e/specs/st_experimental_get_query_params.spec.js
  e2e_playwright/conftest.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/st_both_query_params_error.py
  e2e_playwright/st_both_query_params_error_test.py
  e2e_playwright/st_query_params.py
  e2e_playwright/st_query_params_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  lib/streamlit/__init__.py
  lib/streamlit/commands/experimental_query_params.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/state/__init__.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/util.py
  lib/tests/streamlit/commands/experimental_query_params_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/runtime/state/query_params_proxy_test.py
  lib/tests/streamlit/runtime/state/query_params_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/script_run_context_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/util_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#7852 Config - MPA Sidebar Page Navigation
  e2e_playwright/multipage_apps/mpa_configure_sidebar_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_test.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#7853 Feature - `st.switch_page`
  e2e_playwright/multipage_apps/mpa_basics.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/multipage_apps/pages/02_page2.py
  e2e_playwright/multipage_apps/pages/06_page_6.py
  lib/streamlit/__init__.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/runtime/scriptrunner/script_run_context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/delta_generator_test_case.py
  lib/tests/exception_capturing_thread.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/script_run_context_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/user_info_test.py
  lib/tests/testutil.py
Labels: security-assessment-completed, QA-Done, change:feature, impact:users

#7902 Remove show footer embed option
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/styled-components.ts
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_expanded.snap.png
  frontend/cypress/snapshots/linux/2x/iframe_resizer.spec.js/unembedded_iframe_with_min_height_expanded.snap.png
  frontend/lib/src/index.ts
  frontend/lib/src/theme/primitives/sizes.ts
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, change:other, impact:internal

#7903 Run observer effect when scroll behaviour changes
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-added_chat_message[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-added_chat_message[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-added_chat_message[webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_chat[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-scroll_container_chat[firefox].png
  e2e_playwright/st_container.py
  e2e_playwright/st_container_test.py
  frontend/lib/src/components/core/Block/Block.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#7904 Fix flickering effect when changing tabs
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7596 Fix shrunk icon size in st.expander
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/stExpander-long-expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-help-and-ellipses[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-collapse[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-collapse[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-collapse[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-collapse[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-collapse[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-collapse[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-hidden[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-hidden[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-hidden[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-hidden[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-hidden[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/metric-label-hidden[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-gray[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-green[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/stMetric-red[light_theme-webkit].png
  e2e_playwright/st_expander.py
  e2e_playwright/st_expander_test.py
  frontend/lib/src/components/shared/Icon/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7840 Add check that individual elements are "python comparable"
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7901 Use commonpath rather than common prefix for more secure access
  lib/streamlit/web/server/app_static_file_handler.py
  lib/streamlit/web/server/component_request_handler.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7905 Don't disable tab on stale flag
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7909 Update the frontend audit exceptions
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed, change:other, impact:internal

#7907 Reduce e2e test flakiness by using waiting methods
  e2e_playwright/st_both_query_params_error_test.py
  e2e_playwright/st_graphviz_chart_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7916 Docstrings for release 1.30.0
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/state/query_params_proxy.py
Labels: security-assessment-completed, impact:internal, change:docs

#7918 Fix embed params being dropped in page swaps
  e2e_playwright/multipage_apps/mpa_basics_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
  lib/streamlit/commands/execution_control.py
  lib/streamlit/commands/experimental_query_params.py
  lib/streamlit/constants.py
  lib/streamlit/runtime/state/query_params.py
  lib/tests/streamlit/runtime/state/query_params_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7914 Reuse style element for theme injection into custom components
  component-lib/src/streamlit.test.ts
  component-lib/src/streamlit.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7881 Optional file uploader jwt token
  e2e/specs/hostframe.spec.js
  frontend/app/src/App.tsx
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/hostframe.html
  frontend/lib/src/StreamlitEndpoints.ts
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
  frontend/lib/src/index.ts
Labels: security-assessment-completed, impact:internal, change:chore

#7921 Group by stats rework
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/memory_media_file_storage.py
  lib/streamlit/runtime/memory_uploaded_file_manager.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/stats.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/forward_msg_cache_test.py
  lib/tests/streamlit/runtime/memory_media_file_storage_test.py
  lib/tests/streamlit/runtime/stats_test.py
  lib/tests/streamlit/runtime/uploaded_file_manager_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7923 Handle out of order blocks when parsing element tree
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/testing/app_test_test.py
Labels: security-assessment-completed, change:bugfix, impact:users, feature:app-testing

#7925 Support latest importlib-metadata v7
  lib/setup.py
Labels: security-assessment-completed, dev:full-matrix, dev:upgrade-dependencies, change:chore, impact:users

#7928 Migrate deploy button spec to playwright
  e2e_playwright/__snapshots__/linux/deploy_button_test/deploy_button[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_button_test/deploy_button[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_button_test/deploy_button[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/deploy_button_test/deploy_button[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_button_test/deploy_button[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_button_test/deploy_button[light_theme-webkit].png
  e2e_playwright/deploy_button.py
  e2e_playwright/deploy_button_test.py
  frontend/app/src/components/DeployButton/DeployButton.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7929 Migrate app_hotkeys to playwright
  e2e/specs/app_hotkeys.spec.js
  e2e_playwright/app_hotkeys.py
  e2e_playwright/app_hotkeys_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7932 Remove deploy button spec
  e2e/specs/deploy_button.spec.js
Labels: security-assessment-completed, impact:internal, change:chore

#7927 Migrate alert spec to playwright
  e2e/specs/st_alert.spec.js
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_error[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_error[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_error[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_error[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_error[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_error[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_info[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_info[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_info[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_info[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_info[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_info[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_success[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_success[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_success[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_success[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_success[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_success[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_warning[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_warning[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_warning[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_warning[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_warning[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert_warning[light_theme-webkit].png
  e2e_playwright/st_alert.py
  e2e_playwright/st_alert_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7919 Make Snowpark dependency truly optional for SnowflakeConnection
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/util.py
  lib/tests/streamlit/connections/util_test.py
Labels: security-assessment-completed, change:chore, impact:users

#7936 Fix embed query params flakiness e2e test
  e2e_playwright/multipage_apps/mpa_basics_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7939 Fix deploy dialog e2e test
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/deploy_dialog_test/deploy_dialog[light_theme-webkit].png
  e2e_playwright/deploy_dialog.py
  e2e_playwright/deploy_dialog_test.py
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7938 Remove redundant alert tests
  e2e/scripts/st_error.py
  e2e/scripts/st_info.py
  e2e/scripts/st_success.py
  e2e/scripts/st_warning.py
  e2e/specs/st_error.spec.js
  e2e/specs/st_info.spec.js
  e2e/specs/st_success.spec.js
  e2e/specs/st_warning.spec.js
Labels: security-assessment-completed, impact:internal, change:chore

#7941 Fix flaky scroll container e2e test
  e2e_playwright/st_container_test.py
  frontend/lib/src/components/core/Block/Block.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7940 Lower number of cypress workers
  .github/workflows/cypress.yml
Labels: security-assessment-completed, impact:internal, change:chore

#7935 Migrate cached_widget_replay e2e test to playwright
  e2e/specs/cached_widget_replay_widget_key.spec.js
  e2e_playwright/st_cache_data.py
  e2e_playwright/st_cache_data_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7945 Prevent CacheKeyNotFoundError printouts when exception raised
  lib/streamlit/runtime/caching/cache_utils.py
Labels: security-assessment-completed, impact:internal, change:chore

#7942 Up version to 1.30.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#7962 Migrate `st.write` e2e test
  e2e/scripts/st_write.py
  e2e/specs/st_write.spec.js
  e2e_playwright/st_write.py
  e2e_playwright/st_write_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7953 Fix progress bar float input bug
  lib/streamlit/elements/progress.py
  lib/tests/streamlit/elements/progress_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#7963 Migrate Screencast to RTL
  e2e/specs/modals.spec.js
  frontend/app/src/components/Countdown/Countdown.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.test.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7910 Migrate App.test.tsx to React-Testing-Library
  frontend/app/src/App.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/mainMenuTestHelpers.ts
  frontend/lib/src/mocks/mocks.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#7975 Remove screenshots that we aren't using as tests have migrated to playwright
  frontend/cypress/snapshots/linux/2x/component_template.spec.js/iframe-template-reactless0.snap.png
  frontend/cypress/snapshots/linux/2x/component_template.spec.js/iframe-template-reactless1.snap.png
  frontend/cypress/snapshots/linux/2x/component_template.spec.js/iframe-template0.snap.png
  frontend/cypress/snapshots/linux/2x/component_template.spec.js/iframe-template1.snap.png
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_button-dark.snap.png
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_button.snap.png
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_dialog_opened-dark.snap.png
  frontend/cypress/snapshots/linux/2x/deploy_button.spec.js/deploy_dialog_opened.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert-spacing-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert-spacing.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert0-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert0.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert1-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert1.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert2-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert2.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert3-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert3.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert4-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert4.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert5-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert5.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert6-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert6.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert7-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert7.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert8-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert8.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert9-dark.snap.png
  frontend/cypress/snapshots/linux/2x/st_alert.spec.js/alert9.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#7951 Don't pass query parameters from parent page into iframes
  e2e_playwright/st_components_v1.py
  e2e_playwright/st_components_v1_test.py
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#7952 add ability for host to toggle widgets disabled state
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
Labels: security-assessment-completed, impact:internal, change:feature

#7974 Migrate forward_msg_cache cypress test to playwright
  e2e/specs/forward_msg_cache.spec.js
  e2e_playwright/conftest.py
  e2e_playwright/forward_msg_cache.py
  e2e_playwright/forward_msg_cache_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7959 Migrate file_uploader test to RTL
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#7984 Fix tests related to deprecated config options
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/bootstrap_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7983 Fix CI, postpone config options deprecation expiration_dates
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:chore

#7988 Fix period type support for Pandas 2.2.0
  frontend/lib/src/dataframes/Quiver.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7996 Only ignore hiding required columns in dynamic mode
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#7985 Fix config option expiration behaviour
  lib/streamlit/config_option.py
  lib/streamlit/config_util.py
  lib/tests/streamlit/config_option_test.py
Labels: security-assessment-completed, change:other, impact:internal

#7997 Set deprecated config options expiration date back to Jan 20
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:chore

#7964 Docstring corrections and additions
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/streamlit/user_info.py
Labels: security-assessment-completed, impact:internal, change:docs

#7970 Convert ThemedApp to React Testing Library
  frontend/app/package.json
  frontend/app/src/App.tsx
  frontend/app/src/ThemedApp.test.tsx
  frontend/app/src/ThemedApp.tsx
  frontend/app/src/util/useThemeManager.test.ts
  frontend/app/src/util/useThemeManager.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#7971 Convert ComponentInstance.test.tsx to RTL
  e2e_playwright/st_components_v1_test.py
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#7980 Refactoring: Remove an unnecessary form field `sessionId` from the file upload client
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
Labels: security-assessment-completed, change:other, impact:internal

#8003 Fix Readme broken link to gallery
  README.md
Labels: security-assessment-completed, impact:internal, change:chore

#8011 Migrate st_audio to playwright
  e2e/specs/st_audio.spec.js
  e2e_playwright/st_audio.py
  e2e_playwright/st_audio_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#7976 Migrate modals cypress test to playwright
  e2e/scripts/modals.py
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/record_screencast_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/record_screencast_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-webkit].png
  e2e_playwright/main_menu_test.py
  frontend/cypress/snapshots/linux/2x/modals.spec.js/about-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/about.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/cache-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/cache.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/screencast-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/screencast.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/settings-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/settings.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/theme-dark.snap.png
  frontend/cypress/snapshots/linux/2x/modals.spec.js/theme.snap.png
Labels: security-assessment-completed, impact:internal, change:chore

#8018 Clean-up a couple of aspects in playwright e2e tests
  e2e/specs/modals.spec.js
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-5[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-5[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-5[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-5[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-5[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-5[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-default_theming[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-default_theming[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-default_theming[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-default_theming[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-default_theming[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-default_theming[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-interactive[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-user_supplied_colors[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-user_supplied_colors[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-user_supplied_colors[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-user_supplied_colors[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-user_supplied_colors[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-user_supplied_colors[light_theme-webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/forward_msg_cache_test.py
  e2e_playwright/st_arrow_vega_lite_chart_test.py
  e2e_playwright/st_vega_lite_chart.py
  e2e_playwright/st_vega_lite_chart_test.py
Labels: security-assessment-completed, change:other, impact:internal

#8024 Disable watchdog suggestion for `none` or `poll` watcher type
  lib/streamlit/watcher/path_watcher.py
  lib/tests/streamlit/watcher/path_watcher_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8002 Add option to apply automatic dataframe truncation
  e2e_playwright/config_arrow_truncation.py
  e2e_playwright/config_arrow_truncation_test.py
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/dataframes/Quiver.ts
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/config.py
  lib/streamlit/type_util.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/type_util_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#7906 Add `st.write_stream` command to handle generators or OpenAI output
  e2e_playwright/__snapshots__/linux/st_write_stream_test/st_write_stream-generator_output[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_stream_test/st_write_stream-generator_output[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_stream_test/st_write_stream-generator_output[webkit].png
  e2e_playwright/st_write.py
  e2e_playwright/st_write_stream.py
  e2e_playwright/st_write_stream_test.py
  e2e_playwright/st_write_test.py
  lib/streamlit/__init__.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:feature, impact:users

#8028 Support markdown links in`st.radio` options
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_radio-supports_links_in_options[chromium].png
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_radio-supports_links_in_options[firefox].png
  e2e_playwright/__snapshots__/linux/label_markdown_test/st_radio-supports_links_in_options[webkit].png
  e2e_playwright/label_markdown.py
  e2e_playwright/label_markdown_test.py
  frontend/lib/src/components/shared/Radio/Radio.tsx
Labels: security-assessment-completed, change:feature, impact:users

#8026 Allow setting disableFullscreenMode dynamically
  e2e_playwright/__snapshots__/linux/host_config_test/host_config-dataframe_disabled_fullscreen_mode[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/host_config-dataframe_disabled_fullscreen_mode[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/host_config-dataframe_disabled_fullscreen_mode[webkit].png
  e2e_playwright/host_config.py
  e2e_playwright/host_config_test.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_image.py
  e2e_playwright/st_image_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/Block/utils.ts
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.test.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/FullScreenWrapper.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.test.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#8030 Add support for converting `st.query_params` to string
  e2e_playwright/st_query_params.py
  e2e_playwright/st_query_params_test.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/state/query_params_proxy_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#8034 Fix custom dataframe scrollbars in Chrome
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#8036 Improve error handling in `st.write_stream`
  lib/streamlit/elements/write.py
Labels: security-assessment-completed, change:feature, impact:users

#8033 Fix #5571
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/elements/date_input_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#8044 Docstrings for chat improvements
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/write.py
Labels: security-assessment-completed, impact:internal, change:docs

#8051 Migrate file_uploader works inside form test to playwright
  e2e_playwright/st_file_uploader_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#8048 Remove unused logger in hello
  lib/streamlit/hello/Hello.py
Labels: security-assessment-completed, impact:internal, change:chore, feature:cli
