Repository streamlit/streamlit, pull requests merged in 2025-08, with the labels that each got.

#12049 Fix stop signal issue on windows
  lib/streamlit/runtime/runtime.py
  lib/tests/streamlit/runtime/runtime_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#12095 feat: Add commit SHA to playwright test result artifact names
  .github/workflows/performance.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/playwright.yml
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, impact:internal, change:feature

#11885 [refactor] Simplify NumberInput state handling
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#12094 Clean-up pytest warnings
  lib/pytest.ini
  lib/tests/streamlit/connections/util_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12093 Log warning instead of assert when config file is present
  lib/tests/conftest.py
Labels: security-assessment-completed, change:other, impact:internal

#12100 [fix] Skeleton width should be full screen.
  frontend/lib/src/components/core/Block/StyledElementContainerLayoutWrapper.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#12096 Extend button unit test coverage
  lib/tests/streamlit/elements/button_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12114 [feat] Add JSON5 validation in pre-commit
  .pre-commit-config.yaml
Labels: security-assessment-completed, impact:internal, change:feature

#11979 Misc docs fixes
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/user_info.py
Labels: security-assessment-completed, impact:internal, change:docs

#12126 Release/1.48.0
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#12132 [fix] st.chat_input collapses after submit
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-expanded_multiline_state[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-expanded_multiline_state[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-expanded_multiline_state[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-initial_compact_state[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-initial_compact_state[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-initial_compact_state[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-reset_after_submit[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-reset_after_submit[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-reset_after_submit[webkit].png
  e2e_playwright/st_chat_input_test.py
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/hooks/useTextInputAutoExpand.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12134 [fix] Utilize moduleResolution: bundler
  frontend/app/tsconfig.json
  frontend/app/vite.config.ts
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/tsconfig.json
  frontend/lib/vite.config.ts
  frontend/typescript-config/base.tsconfig.json
  frontend/utils/package.json
Labels: security-assessment-completed, impact:internal, change:bugfix

#12140 Fix ty dianostic warnings
  lib/streamlit/commands/navigation.py
  lib/streamlit/runtime/websocket_session_manager.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12125 Attempt to fix flaky selectbox unit test
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
Labels: security-assessment-completed, change:other, impact:internal

#12131 Refactor text area e2e test
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-horizontal_layout[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-horizontal_layout[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-horizontal_layout[webkit].png
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_text_area.py
  e2e_playwright/st_text_area_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12141 [feat] Simplify all copy to clipboard handling
  NOTICES
  e2e_playwright/conftest.py
  e2e_playwright/st_dialog_test.py
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/eslint.config.mjs
  frontend/lib/package.json
  frontend/lib/src/components/elements/CodeBlock/CopyButton.test.tsx
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/Json/Json.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnMenu.tsx
  frontend/lib/src/hooks/useCopyToClipboard.test.tsx
  frontend/lib/src/hooks/useCopyToClipboard.ts
  frontend/lib/src/hooks/useTimeout.test.ts
  frontend/lib/src/hooks/useTimeout.tsx
  frontend/lib/src/index.ts
  frontend/yarn.lock
Labels: security-assessment-completed, change:feature, impact:users

#12142 [feat] Implement configurable trusted headers.
  lib/streamlit/config.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/config_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12148 [fix] iframe and html change in default width when no width specified.
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html-iframe-in-vertical-container[chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html-iframe-in-vertical-container[firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html-iframe-in-vertical-container[webkit].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html-no-width-height-container[chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html-no-width-height-container[firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-html-no-width-height-container[webkit].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe-fixed-width-height[chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe-fixed-width-height[firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe-fixed-width-height[webkit].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe-no-width-height[chromium].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe-no-width-height[firefox].png
  e2e_playwright/__snapshots__/linux/st_components_v1_test/st_components-iframe-no-width-height[webkit].png
  e2e_playwright/st_components_v1.py
  e2e_playwright/st_components_v1_test.py
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/elements/IFrame/IFrame.test.tsx
  frontend/lib/src/components/elements/IFrame/IFrame.tsx
  frontend/lib/src/components/elements/IFrame/styled-components.ts
  lib/streamlit/elements/iframe.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/elements/iframe_test.py
  proto/streamlit/proto/IFrame.proto
Labels: security-assessment-completed, change:bugfix, impact:users, autofix

#11872 Allow setting `duration` for `st.toast`
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[webkit].png
  e2e_playwright/st_toast.py
  e2e_playwright/st_toast_test.py
  frontend/app/src/components/EventContainer/EventContainer.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
  lib/streamlit/elements/toast.py
  lib/streamlit/errors.py
  lib/tests/streamlit/toast_test.py
  proto/streamlit/proto/Toast.proto
Labels: security-assessment-completed, change:feature, impact:users

#12160 [Fix] `st.toast` handles custom theming
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-custom-theme[chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-custom-theme[webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-default[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-material-icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-material-icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-material-icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-material-icon[light_theme-webkit].png
  e2e_playwright/shared/theme_utils.py
  e2e_playwright/st_toast_test.py
  frontend/lib/src/components/elements/Toast/Toast.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11930 [AdvancedLayouts] Updates dataframe and data editor to the new style for width and height.
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-content-width[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-content-width[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-content-width[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-fixed-dimensions[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-fixed-dimensions[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-fixed-dimensions[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-stretch-width[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-stretch-width[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_dimensions_test/st_dataframe-stretch-width[webkit].png
  e2e_playwright/st_data_editor_column_types.py
  e2e_playwright/st_data_editor_config.py
  e2e_playwright/st_dataframe_dimensions.py
  e2e_playwright/st_dataframe_dimensions_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/Block/StyledElementContainerLayoutWrapper.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/layout_utils.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/tests/streamlit/elements/arrow_dataframe_dimensions_test.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  proto/streamlit/proto/Arrow.proto
Labels: security-assessment-completed, change:feature, impact:users

#12174 Attempt to fix some flakiness with toast unit test
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
Labels: security-assessment-completed, change:other, impact:internal

#12176 [Fix]: Playwright artifact upload SHA ordering issue
  .github/workflows/playwright-custom-components.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#11532 Added st.pdf
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-base64_encoding[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-base64_encoding[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-base64_encoding[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-basic_functionality[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-basic_functionality[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-basic_functionality[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-bytes_io[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-bytes_io[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-bytes_io[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-custom_size[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-custom_size[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-custom_size[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-error_handling[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-error_handling[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-error_handling[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-file_upload_no_file[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-file_upload_no_file[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-file_upload_no_file[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_default[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_default[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_default[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_maximum[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_maximum[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_maximum[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_minimum[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_minimum[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-height_minimum[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-in_columns[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-in_columns[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-in_columns[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-interactive_after_reset[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-interactive_after_reset[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-interactive_after_reset[webkit].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-interactive_initial[chromium].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-interactive_initial[firefox].png
  e2e_playwright/__snapshots__/linux/pdf_component_test/st_pdf-interactive_initial[webkit].png
  e2e_playwright/custom_components/components-e2e-requirements.txt
  e2e_playwright/custom_components/pdf_component.py
  e2e_playwright/custom_components/pdf_component_test.py
  lib/setup.py
  lib/streamlit/__init__.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/pdf.py
  lib/test-requirements.txt
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/pdf_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12196 Fix nightly CI
  .github/actions/make_init/action.yml
  lib/test-requirements.txt
Labels: security-assessment-completed, impact:internal, change:bugfix

#12185 Release/1.48.1
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#12181 Update `st.page_link` radii config
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-custom-theme[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-custom-theme[webkit].png
  e2e_playwright/st_page_link.py
  e2e_playwright/st_page_link_test.py
  frontend/lib/src/components/elements/PageLink/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12162 Single mark charts use first of `chartCategoricalColors`
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-custom-theme[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-custom-theme[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-custom-theme[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-custom-theme[webkit].png
  e2e_playwright/st_line_chart_test.py
  e2e_playwright/st_plotly_chart_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#12192 [fix] File Upload Drop Target truncates subtext
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-many_file_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-many_file_types[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-many_file_types[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-many_file_types[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-many_file_types[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-many_file_types[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[chromium].png
  e2e_playwright/st_file_uploader.py
  e2e_playwright/st_file_uploader_test.py
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.tsx
  frontend/lib/src/components/widgets/FileUploader/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12060 Refactor chart config e2e testing
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors-sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors-sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors-sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors[chromium].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors[firefox].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors[webkit].png
  e2e_playwright/__snapshots__/linux/theme_chart_colors_test/custom_chart_colors-sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/theme_chart_colors_test/custom_chart_colors-sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/theme_chart_colors_test/custom_chart_colors-sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/theme_chart_colors_test/custom_chart_colors[chromium].png
  e2e_playwright/__snapshots__/linux/theme_chart_colors_test/custom_chart_colors[firefox].png
  e2e_playwright/__snapshots__/linux/theme_chart_colors_test/custom_chart_colors[webkit].png
  e2e_playwright/__snapshots__/linux/theme_sequential_test/custom_sequential_colors[chromium].png
  e2e_playwright/__snapshots__/linux/theme_sequential_test/custom_sequential_colors[firefox].png
  e2e_playwright/__snapshots__/linux/theme_sequential_test/custom_sequential_colors[webkit].png
  e2e_playwright/theming/theme_chart_colors.py
  e2e_playwright/theming/theme_chart_colors_app.py
  e2e_playwright/theming/theme_chart_colors_test.py
  e2e_playwright/theming/theme_sequential.py
  e2e_playwright/theming/theme_sequential_app.py
  e2e_playwright/theming/theme_sequential_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10311 Add toolbar action to show underlying vega chart data
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-show_chart_data[chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-show_chart_data[firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-show_chart_data[webkit].png
  e2e_playwright/st_altair_chart_test.py
  frontend/eslint-plugin-streamlit-custom/no-hardcoded-theme-values.js
  frontend/eslint-plugin-streamlit-custom/no-hardcoded-theme-values.test.js
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.test.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.test.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/ReadOnlyGrid.test.tsx
  frontend/lib/src/components/widgets/DataFrame/ReadOnlyGrid.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
  frontend/lib/src/components/widgets/DataFrame/index.ts
  frontend/lib/src/components/widgets/Form/FormClearHelper.ts
  frontend/lib/src/hooks/useCalculatedWidth.ts
  frontend/lib/src/hooks/useResizeObserver.ts
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/tests/streamlit/elements/arrow_add_rows_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12200 Fix PDF test flakiness by improving loading detection
  e2e_playwright/custom_components/pdf_component_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11952 [AdvancedLayouts] Updates to st.image width/height and adding width/height to st.pyplot.
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-markdown_caption_support[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-markdown_caption_support[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_content_large[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_content_large[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_content_large[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_content_small[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_content_small[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_content_small[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_stretch_large[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_stretch_large[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_stretch_large[webkit].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_stretch_small[chromium].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_stretch_small[firefox].png
  e2e_playwright/__snapshots__/linux/st_image_test/st_image-width_stretch_small[webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_content[chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_content[firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_content[webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_pixel[chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_pixel[firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_pixel[webkit].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_pyplot_test/st_pyplot-width_stretch[webkit].png
  e2e_playwright/st_image.py
  e2e_playwright/st_image_test.py
  e2e_playwright/st_pyplot.py
  e2e_playwright/st_pyplot_test.py
  frontend/lib/src/components/core/Block/StyledElementContainerLayoutWrapper.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.test.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  lib/streamlit/commands/logo.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/widgets/chat.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/elements/pyplot_test.py
  proto/streamlit/proto/Image.proto
Labels: security-assessment-completed, change:feature, impact:users

#12219 [fix] Selectbox with accept_new_options on mobile shows keyboard
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#12222 [fix] PlotlyChart with null value selection works properly
  frontend/lib/src/components/elements/PlotlyChart/utils.test.ts
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12214 [refactor] Make `useCalculatedWidth` into `useCalculatedDimensions` and return height as well.
  frontend/lib/src/components/core/Layout/withCalculatedWidth.tsx
  frontend/lib/src/components/elements/Html/Html.test.tsx
  frontend/lib/src/components/elements/Metric/Metric.test.tsx
  frontend/lib/src/components/elements/Metric/Metric.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/shared/ElementFullscreen/ElementFullscreenWrapper.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/hooks/useCalculatedDimensions.test.ts
  frontend/lib/src/hooks/useCalculatedDimensions.ts
  frontend/lib/src/hooks/useCalculatedWidth.test.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11837 Clarify column configuration: positional index references and index columns
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/widgets/data_editor.py
Labels: security-assessment-completed, impact:internal, change:docs

#12137 Add explicit support for Pydantic models in cache_data/resource
  lib/streamlit/runtime/caching/hashing.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12218 Update glide-data-grid to alpha 19
  NOTICES
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#12231 [refactor] Use useCalculatedDimensions in VegaLite.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/hooks/useCalculatedDimensions.test.ts
  frontend/lib/src/hooks/useCalculatedDimensions.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#12228 [chore] Add tests for loading animation and skeleton.
  frontend/app/src/App.test.tsx
  frontend/lib/src/components/core/Block/StyledElementContainerLayoutWrapper.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#12264 Update material symbols
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, change:other, impact:users

#12236 Refactor date input e2e test
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_date_input.py
  e2e_playwright/st_date_input_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12164 Allow select all/ deselect all when hiding dataframe columns from UI
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_visibility_menu[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_visibility_menu[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_visibility_menu[webkit].png
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnVisibilityMenu.test.tsx
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnVisibilityMenu.tsx
Labels: feature:st.dataframe, security-assessment-completed, change:feature, impact:users

#12175 Fix code usage in markdown labels
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_code_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_code_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_code_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_code_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_code_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-with_code_block[light_theme-webkit].png
  e2e_playwright/st_expander.py
  e2e_playwright/st_expander_test.py
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/Expander/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9223 Add `MultiselectColumn` for `st.dataframe` and `st.data_editor`
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_col_editor[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_col_editor[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_col_editor[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_col_editor[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_col_editor[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_col_editor[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-multiselect_column[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column_overlay[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column_overlay[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-multiselect_column_overlay[webkit].png
  e2e_playwright/st_data_editor_config.py
  e2e_playwright/st_data_editor_config_test.py
  e2e_playwright/st_data_editor_index_types.py
  e2e_playwright/st_data_editor_input_data.py
  e2e_playwright/st_dataframe_column_types.py
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  e2e_playwright/st_dataframe_index_types.py
  e2e_playwright/st_dataframe_input_data.py
  e2e_playwright/st_dataframe_interactions.py
  e2e_playwright/st_dataframe_selections.py
  e2e_playwright/st_dataframe_styler_support.py
  frontend/lib/src/components/widgets/DataFrame/columns/MultiselectColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/MultiselectColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/index.ts
  lib/streamlit/column_config.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/lib/column_types.py
  lib/tests/streamlit/elements/lib/column_types_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12239 Add support for source directly in theming font configs
  NOTICES
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_fonts_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_fonts_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_fonts_app[webkit].png
  e2e_playwright/theming/custom_theme_fonts.py
  e2e_playwright/theming/custom_theme_fonts_test.py
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/ThemedApp.tsx
  frontend/app/src/components/FontSources/FontSources.tsx
  frontend/app/src/components/FontSources/index.ts
  frontend/app/src/index.tsx
  frontend/app/src/util/useThemeManager.test.ts
  frontend/app/src/util/useThemeManager.ts
  frontend/yarn.lock
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/theme_util.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/theme_util_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#12313 [feat] Add `default` param to `st.tabs`
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.test.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/elements/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#12327 Docs for release 1.49.0
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/bokeh_chart.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/pdf.py
  lib/streamlit/elements/pyplot.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
Labels: security-assessment-completed, impact:internal, change:docs

#12296 [refactor] Simplification of `st.graphviz_chart` rendering logic
  e2e_playwright/st_graphviz_chart_test.py
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#12343 Ensure markdown images keep the aspect ratio
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_100px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_100px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_100px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_100px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_content[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_content[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_content[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_content[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_content[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_content[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_300px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_300px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_300px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_300px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_content[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_content[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_content[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_content[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_caption-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_200px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_200px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_200px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_200px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_content[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_content[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_content[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_content[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[webkit].png
  e2e_playwright/st_markdown.py
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11796 Add `border` parameter to `st.table`
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-33[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-33[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-33[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-34[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-34[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-34[webkit].png
  e2e_playwright/st_table.py
  e2e_playwright/st_table_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.test.tsx
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowTable/styled-components.ts
  lib/streamlit/elements/arrow.py
  lib/tests/streamlit/elements/arrow_table_test.py
  proto/streamlit/proto/Arrow.proto
Labels: security-assessment-completed, change:feature, impact:users

#12348 [feat] Hover, active, focus-visible states for CopyButton
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/hooks/useCopyToClipboard.ts
Labels: security-assessment-completed, change:feature, impact:users

#12351 Fix issue with typing formatted values into `st.number_input`
  e2e_playwright/st_number_input_test.py
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#12354 [fix] `html` with float height.
  lib/streamlit/elements/lib/layout_utils.py
  lib/tests/streamlit/elements/lib/layout_utils_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#12328 Release/1.49.0
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#12346 Refactor `st.button` e2e test
  e2e_playwright/st_button.py
  e2e_playwright/st_button_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12333 [refactor] Speed up Playwright Installs in CI
  .github/actions/make_init/action.yml
  .github/actions/playwright_install/action.yml
  .github/workflows/performance.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/playwright.yml
  Makefile
Labels: security-assessment-completed, impact:internal, change:refactor

#12329 Fix logo pushing out collapse button
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-large_w_sidebar_expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-large_w_sidebar_expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-large_w_sidebar_expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-large_w_sidebar_expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-large_w_sidebar_expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-large_w_sidebar_expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-medium_w_sidebar_expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-navbar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-navbar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-navbar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-navbar[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-small_w_sidebar_collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-small_w_sidebar_expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-small_w_sidebar_expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-small_w_sidebar_expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_logo_test/logo-small_w_sidebar_expanded[light_theme-webkit].png
  e2e_playwright/st_logo_test.py
  frontend/app/src/components/Logo/LogoComponent.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12332 Use `key` as main identity for button widgets
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_updated[webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_updated[webkit].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit_button-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit_button-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit_button-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit_button-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit_button-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form_submit_button-dynamic_updated[webkit].png
  e2e_playwright/st_button.py
  e2e_playwright/st_button_test.py
  e2e_playwright/st_download_button.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_form.py
  e2e_playwright/st_form_test.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/dialog.py
  lib/streamlit/elements/lib/utils.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/button_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12362 Refactor the `st.checkbox` e2e test
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_checkbox.py
  e2e_playwright/st_checkbox_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12369 Support whitelisting command kwargs for ID computation with key
  lib/streamlit/elements/lib/utils.py
  lib/tests/streamlit/delta_generator_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12339 Add `sort` parameter to `st.bar_chart`
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-horizontal_sort_by_categories_asc[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-horizontal_sort_by_categories_asc[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-horizontal_sort_by_categories_asc[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-horizontal_sort_by_values_asc[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-horizontal_sort_by_values_asc[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-horizontal_sort_by_values_asc[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_categories_asc[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_categories_asc[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_categories_asc[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_categories_desc[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_categories_desc[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_categories_desc[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_other_column_asc[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_other_column_asc[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_other_column_asc[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_values_asc[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_values_asc[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_values_asc[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_values_desc[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_values_desc[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_by_values_desc[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_false[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_false[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_false[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_true[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_true[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-sort_true[webkit].png
  e2e_playwright/st_bar_chart.py
  e2e_playwright/st_bar_chart_test.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12370 Fix long-words overflowing markdown container
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long_word_in_container[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long_word_in_container[firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-long_word_in_container[webkit].png
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12291 refactor: deprecate kwargs in st.plotly_chart and add config dict instead
  lib/streamlit/elements/plotly_chart.py
  lib/tests/streamlit/elements/plotly_chart_test.py
Labels: security-assessment-completed, change:breaking, change:feature, impact:users, status:product-approved
