Repository streamlit/streamlit, pull requests merged in 2025-03, with the labels that each got.

#10593 Docstrings for navigation and download button
  lib/streamlit/commands/navigation.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/widgets/button.py
Labels: security-assessment-completed, impact:internal, change:docs

#10566 add theming config `showSidebarSeparator`
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/theming/custom_theme_test.py
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/lib/src/mocks/mockTheme.ts
  frontend/lib/src/theme/emotionBaseTheme/index.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#10619 [refactor] Stabilize pydeck selection tests
  e2e_playwright/shared/pydeck_utils.py
  e2e_playwright/st_pydeck_chart_select_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10597 Improve pytest coverage reporting
  .github/workflows/performance.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/playwright.yml
  .github/workflows/python-min-deps.yml
  .github/workflows/python-tests.yml
  .gitignore
  Makefile
  e2e_playwright/.coveragerc
  e2e_playwright/custom_components/components-e2e-requirements.txt
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  e2e_playwright/pytest.ini
  lib/.coveragerc
  scripts/check_license_headers.py
Labels: security-assessment-completed, change:other, impact:internal

#10630 Update dependabot ignore list
  .github/dependabot.yml
Labels: security-assessment-completed, change:other, impact:internal

#10563 Add locale to the st.context
  e2e_playwright/st_context.py
  e2e_playwright/st_context_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  lib/streamlit/runtime/context.py
  proto/streamlit/proto/ClientState.proto
Labels: security-assessment-completed, change:chore, impact:users

#10561 Add support for Pandas styler tooltips to `st.table`
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-31[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-31[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-31[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-styler_tooltip[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-styler_tooltip[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-styler_tooltip[webkit].png
  e2e_playwright/st_table.py
  e2e_playwright/st_table_test.py
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/dataframes/pandasStylerUtils.test.ts
  frontend/lib/src/dataframes/pandasStylerUtils.ts
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/arrow_table_test.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10635 Add test execution time to e2e performance tracking
  e2e_playwright/shared/performance.py
Labels: security-assessment-completed, change:other, impact:internal

#10646 Make test get_min_versions script works with nightly builds
  scripts/get_min_versions.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10596 Add benchmarking and CI check for import time
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10650 Enable better exception logging if `rich` is installed
  lib/streamlit/config.py
Labels: security-assessment-completed, change:feature, impact:users

#10638 Add forward message cache performance tracking
  e2e_playwright/forward_msg_cache.py
  e2e_playwright/forward_msg_cache_test.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/shared/performance.py
  e2e_playwright/st_number_input_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10642 [Fix] Disable scroll within `st.number_input`
  e2e_playwright/st_number_input_test.py
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10658 [Fix]: Button commands breakage with `help`
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-just_help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-just_help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-just_help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-just_help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-just_help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-just_help[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-help[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-submit_button_just_help[chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-submit_button_just_help[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-submit_button_just_help[webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-help[light_theme-webkit].png
  e2e_playwright/st_button.py
  e2e_playwright/st_button_test.py
  e2e_playwright/st_download_button.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_form.py
  e2e_playwright/st_form_test.py
  e2e_playwright/st_link_button.py
  e2e_playwright/st_link_button_test.py
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/lib/src/components/elements/LinkButton/BaseLinkButton.tsx
  frontend/lib/src/components/elements/LinkButton/LinkButton.test.tsx
  frontend/lib/src/components/elements/LinkButton/LinkButton.tsx
  frontend/lib/src/components/elements/LinkButton/styled-components.ts
  frontend/lib/src/components/elements/PageLink/PageLink.tsx
  frontend/lib/src/components/elements/PageLink/styled-components.ts
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/shared/BaseButton/BaseButton.test.tsx
  frontend/lib/src/components/shared/BaseButton/BaseButton.tsx
  frontend/lib/src/components/shared/BaseButton/BaseButtonTooltip.tsx
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/shared/Tooltip/Tooltip.tsx
  frontend/lib/src/components/shared/TooltipIcon/TooltipIcon.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInputActionButtons.tsx
  frontend/lib/src/components/widgets/Button/Button.test.tsx
  frontend/lib/src/components/widgets/Button/Button.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10662 Fix support for dask data objects
  lib/streamlit/dataframe_util.py
  lib/tests/streamlit/dataframe_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10663 [fix] Fix custom component flickering
  e2e_playwright/st_camera_input_test.py
  e2e_playwright/st_video_test.py
  frontend/lib/src/components/elements/Video/Video.test.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10672 [fix] withCalculatedWidth fallback
  frontend/lib/src/components/core/Layout/withCalculatedWidth.test.tsx
  frontend/lib/src/components/core/Layout/withCalculatedWidth.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10680 Add test for rich error handling
  lib/tests/streamlit/error_util_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10573 Activate additional ruff linting rules
  .ruff.toml
  e2e_playwright/st_components_v1_test.py
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_fragments_nested_test.py
  e2e_playwright/st_markdown_test.py
  lib/streamlit/auth_util.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/doc_string.py
  lib/streamlit/elements/lib/color_util.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
  lib/tests/streamlit/elements/video_test.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10509 CVE-2025-1684: Improper Restriction of File Upload Type in st.file_uploader
  lib/streamlit/elements/lib/file_uploader_utils.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/tests/streamlit/elements/audio_input_test.py
  lib/tests/streamlit/elements/camera_input_test.py
  lib/tests/streamlit/elements/file_uploader_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10664 Remove Deprecated Code Function
  lib/streamlit/elements/markdown.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10681 Use min python version for min-dependency tests
  .github/workflows/python-tests.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#10671 Build Streamlit wheel file only for Python3
  Makefile
Labels: security-assessment-completed, impact:internal, change:chore

#9964 Add more correct out of bounds checks for min_value and max_value for st.number_input and st.slider, related to st.session_state
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/errors.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/elements/slider_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10692 remove unused _LOGGER definitions
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/source_util.py
Labels: security-assessment-completed, impact:internal, change:chore

#10493 Deprecated StringTriggerValue proto field, and remove code related to it
  frontend/lib/src/WidgetStateManager.test.ts
  frontend/lib/src/WidgetStateManager.ts
  lib/streamlit/runtime/scriptrunner_utils/script_requests.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  proto/streamlit/proto/Common.proto
  proto/streamlit/proto/WidgetStates.proto
Labels: security-assessment-completed, impact:internal, change:chore

#10695 Add `autofix` command to Makefile
  Makefile
Labels: security-assessment-completed, change:other, impact:internal

#10712 [fix] Fix width flickering in some components
  frontend/lib/src/components/core/Layout/withCalculatedWidth.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/shared/ElementFullscreen/ElementFullscreenWrapper.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/hooks/useCalculatedWidth.test.ts
  frontend/lib/src/hooks/useCalculatedWidth.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10078 Add links for Google and ChatGPT to exceptions
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_inline_error[chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-0[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-1[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-2[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-3[light_theme-webkit].png
  e2e_playwright/st_exception_test.py
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/ExceptionElement/styled-components.ts
  frontend/lib/src/components/shared/ErrorElement/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10709 Popover with help and use_container_width is rendered correctly
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width_with_help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width_with_help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width_with_help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width_with_help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width_with_help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-use_container_width_with_help[light_theme-webkit].png
  e2e_playwright/st_popover.py
  e2e_playwright/st_popover_test.py
  frontend/lib/src/components/elements/Popover/Popover.test.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10717 Update material icons to latest version
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, change:chore, impact:users

#10690 [Fix]: `st.page_link` - current vs. non-current page visuals & width
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-container-width-true[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-container-width-true[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-container-width-true[webkit].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-default[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-default[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-default[webkit].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-icon[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-icon[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-icon[webkit].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-container-width-false[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-container-width-false[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-container-width-false[webkit].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-default[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-default[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-default[webkit].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-icon[chromium].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-icon[firefox].png
  e2e_playwright/__snapshots__/linux/st_page_link_test/st_page_link-sidebar-icon[webkit].png
  e2e_playwright/st_page_link.py
  e2e_playwright/st_page_link_test.py
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
  frontend/lib/src/components/elements/PageLink/PageLink.test.tsx
  frontend/lib/src/components/elements/PageLink/PageLink.tsx
  frontend/lib/src/components/elements/PageLink/styled-components.ts
  frontend/lib/src/components/shared/BaseButton/BaseButtonTooltip.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10685 Update ruff to 0.9.10
  .pre-commit-config.yaml
  lib/dev-requirements.txt
  lib/test-requirements.txt
Labels: security-assessment-completed, change:other, impact:internal

#10687 Release/1.43.1
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#10718 Activate ruff linting & formatting for entire repo
  .ruff.toml
  scripts/audit_frontend_licenses.py
  scripts/check_license_headers.py
  scripts/check_new_emojis.py
  scripts/check_new_material_symbols.py
  scripts/cli_regression_tests.py
  scripts/cli_smoke_tests.py
  scripts/create_release.py
  scripts/get_min_versions.py
  scripts/get_release_branch.py
  scripts/pypi_nightly_create_tag.py
  scripts/run_bare_execution_tests.py
  scripts/run_in_subdirectory.py
  scripts/slack_notifications.py
  scripts/update_e2e_snapshots.py
  scripts/update_emojis.py
  scripts/update_material_icon_font_and_names.py
  scripts/update_name.py
  scripts/update_version.py
Labels: security-assessment-completed, change:other, impact:internal

#10723 Release/1.43.2
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#10698 [Fix]: inconsistent error messages for st.secrets attribute assignment
  lib/streamlit/runtime/secrets.py
  lib/tests/streamlit/runtime/secrets_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10508 Allow user to choose whether to print error finding secrets
  lib/streamlit/errors.py
  lib/streamlit/runtime/secrets.py
  lib/tests/streamlit/runtime/connection_factory_test.py
  lib/tests/streamlit/runtime/secrets_test.py
Labels: security-assessment-completed, change:breaking, change:bugfix, impact:users

#10654 [refactor] Add eslint-react to uplevel React best practices
  frontend/.eslintrc.js
  frontend/app/package.json
  frontend/app/src/App.tsx
  frontend/app/src/components/Sidebar/SidebarNavLink.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/app/src/util/useThemeManager.ts
  frontend/lib/src/components/core/Block/Block.test.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.test.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.test.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.test.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  frontend/lib/src/components/elements/Video/Video.test.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.test.tsx
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInputButton.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.test.tsx
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnMenu.tsx
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnVisibilityMenu.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/components/widgets/FileUploader/withPagination/withPagination.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/hooks/useScrollToBottom.ts
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#10726 [fix] Fix no-leaked-event-listener lint errors
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnMenu.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/hooks/useScrollToBottom.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10728 [fix] Fix no-nested-components lint errors
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10725 [fix] Fix existing no-leaked-conditional-rendering and prefer-use-state-lazy-initialization lint errors
  frontend/app/src/components/Sidebar/SidebarNavLink.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/util/useThemeManager.ts
  frontend/lib/src/components/widgets/CameraInput/CameraInputButton.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/FileUploader/withPagination/withPagination.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10753 [fix] Multipage app symlinks for Lighthouse tests
  frontend/app/performance/apps/multipage/multipage_app.py
  frontend/app/performance/apps/multipage/pages/1_Animation_Demo.py
  frontend/app/performance/apps/multipage/pages/2_Mapping_Demo.py
  frontend/app/performance/apps/multipage/pages/3_Plotting_Demo.py
Labels: area:performance, security-assessment-completed, impact:internal, change:bugfix

#10090 Add `st.badge` and Markdown badges
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[webkit].png
  e2e_playwright/markdown_features.py
  e2e_playwright/markdown_features_test.py
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  lib/streamlit/__init__.py
  lib/streamlit/elements/markdown.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/markdown_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10077 Add `streamlit init` command
  lib/streamlit/web/cli.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10700 Add a GitHub comment for the `pr-preview` job
  .github/workflows/pr-preview.yml
Labels: security-assessment-completed, impact:internal, change:chore

#10771 Fix flaky test tracking
  e2e_playwright/__snapshots__/linux/st_dataframe_column_types_test/st_dataframe-interval_types[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-area_chart_column[dark_theme-chromium].png
  e2e_playwright/config_arrow_truncation_test.py
  e2e_playwright/conftest.py
  e2e_playwright/multipage_apps/mpa_configure_sidebar_test.py
  e2e_playwright/multipage_apps/mpa_v2_custom_theme_test.py
  e2e_playwright/pytest.ini
  e2e_playwright/st_camera_input_test.py
  e2e_playwright/st_experimental_get_query_params_test.py
  e2e_playwright/st_query_params_test.py
  e2e_playwright/theming/custom_theme_test.py
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10783 Activate import naming conventions linting rule via ruff
  .ruff.toml
  e2e_playwright/st_pyplot.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/elements/plotly_chart.py
  lib/tests/streamlit/elements/pyplot_test.py
  lib/tests/streamlit/streamlit_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10784 Use string path for page `__file__`
  lib/streamlit/navigation/page.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10789 Fix usage of "sans serife" as font
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10755 [fix] Stabilize pydeck-select e2e tests
  e2e_playwright/shared/pydeck_utils.py
  e2e_playwright/st_pydeck_chart_select.py
  e2e_playwright/st_pydeck_chart_select_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10791 Temporarly skipping more dataframe firefox tests to lower flakiness
  e2e_playwright/st_dataframe_interactions_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10699 Add automated comment on wheel size changes
  .github/workflows/pr-preview.yml
Labels: security-assessment-completed, change:other, impact:internal

#10792 Revamp playwright changed files workflow
  .github/workflows/playwright-changed-files.yml
  e2e_playwright/st_dataframe_dimensions.py
  e2e_playwright/st_dataframe_dimensions_test.py
  e2e_playwright/st_dataframe_input_data.py
  e2e_playwright/st_dataframe_interactions_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10793 Use commit hash as version identifier for third-party actions
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#10795 Replace third-party github action in community voting workflow
  .github/workflows/community-voting.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#10804 Activate `eslint:recommended` rule set
  frontend/.eslintrc.js
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/app/src/components/ToolbarActions/styled-components.ts
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
  frontend/lib/src/components/shared/Icon/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/styled-components.ts
Labels: security-assessment-completed, change:other, impact:internal

#10686 Move bokeh to integration tests and add custom component test
  .github/workflows/playwright-changed-files.yml
  e2e_playwright/custom_components/components-e2e-requirements.txt
  e2e_playwright/custom_components/popular_components.py
  e2e_playwright/custom_components/popular_components_test.py
  e2e_playwright/lazy_loaded_modules.py
  e2e_playwright/lazy_loaded_modules_test.py
  e2e_playwright/st_bokeh_chart.py
  e2e_playwright/st_bokeh_chart_test.py
  lib/integration-requirements.txt
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/media.py
  lib/test-requirements.txt
  lib/tests/streamlit/elements/bokeh_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10760 Extend `host_config` endpoint with `blockErrorDialogs`
  e2e_playwright/host_config.py
  e2e_playwright/host_config_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/index.ts
  frontend/connection/src/types.ts
  frontend/lib/src/hostComm/types.ts
  lib/streamlit/web/server/routes.py
  lib/tests/streamlit/web/server/routes_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10813 Update material symbols font to latest
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, change:chore, impact:users

#10794 Replace third-party github action in required labels check
  .github/workflows/require-labels.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#10823 [chore] Update Playwright to 1.51
  e2e_playwright/__snapshots__/linux/host_config_test/host_config-dataframe_disabled_fullscreen_mode[chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz-after_exit_fullscreen[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz-chart_dot_string[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-osage[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-patchwork[chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-markdown_labels[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-markdown_labels[light_theme-webkit].png
  lib/test-requirements.txt
Labels: security-assessment-completed, impact:internal, change:chore

#10772 support sidebar custom theme
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[chromium].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[firefox].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  e2e_playwright/theming/sidebar_custom_theme.py
  e2e_playwright/theming/sidebar_custom_theme_test.py
  e2e_playwright/theming/snowflake_dark_theme_test.py
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
  lib/streamlit/config.py
  lib/streamlit/config_option.py
  lib/streamlit/config_util.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_option_test.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/config_util_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#10826 Log script compilation error via error log level
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:other, impact:users

#10825 [fix] HTML in tabs content render fixes
  e2e_playwright/st_tabs.py
  e2e_playwright/st_tabs_test.py
  frontend/lib/src/components/elements/Html/Html.test.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10839 Update glide-data-grid dependencies to version `6.0.4-alpha9`
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#10838 Add dependency groups for dependabot
  .github/dependabot.yml
Labels: security-assessment-completed, change:other, impact:internal

#10836 set `color` for StyledSidebar
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[chromium].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[firefox].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  e2e_playwright/theming/sidebar_custom_theme_test.py
  frontend/app/src/components/Sidebar/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10848 Fix some sidebar theming aspects
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[chromium].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[firefox].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  e2e_playwright/theming/sidebar_custom_theme_test.py
  frontend/app/src/App.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10847 Update ruff to 0.11
  .github/codeql-config.yml
  .pre-commit-config.yaml
  e2e_playwright/st_map.py
  e2e_playwright/st_pydeck_chart.py
  lib/dev-requirements.txt
  lib/streamlit/auth_util.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/connections/snowpark_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/connections/util.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/deprecation_util.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/html.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/color_util.py
  lib/streamlit/elements/lib/dialog.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/lib/mutable_status_container.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/elements/write.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/metrics_util.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/scriptrunner_utils/script_requests.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/runtime/websocket_session_manager.py
  lib/streamlit/string_util.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/tests/streamlit/elements/exception_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  scripts/audit_frontend_licenses.py
Labels: security-assessment-completed, impact:internal, change:chore

#10854 Fix issue with background color handling in sidebar theming
  e2e_playwright/theming/sidebar_custom_theme_test.py
  frontend/app/src/components/Sidebar/ThemedSidebar.test.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10835 Fix boolean theme configs getting skipped
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/runtime/app_session_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10855 Fix `createTheme` overriding active theme's baseweb props
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[chromium].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[firefox].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10837 Send `postMessage` on media load errors
  e2e_playwright/custom_components/component_errors_test.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_file_uploader_test.py
  e2e_playwright/st_image_test.py
  e2e_playwright/st_video_test.py
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/connection/src/DefaultStreamlitEndpoints.test.ts
  frontend/connection/src/DefaultStreamlitEndpoints.ts
  frontend/connection/src/types.ts
  frontend/lib/src/StreamlitEndpoints.ts
  frontend/lib/src/components/elements/Audio/Audio.test.tsx
  frontend/lib/src/components/elements/Audio/Audio.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.test.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/Video/Video.test.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentRegistry.test.ts
  frontend/lib/src/components/widgets/CustomComponent/ComponentRegistry.ts
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/lib/src/hostComm/types.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10858 rename theming options `showWidgetBorder` and `showSidebarBorder`
  e2e_playwright/theming/custom_theme_test.py
  e2e_playwright/theming/sidebar_custom_theme_test.py
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme_test.py
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/lib/src/mocks/mockTheme.ts
  frontend/lib/src/theme/emotionBaseTheme/index.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:refactor, impact:users

#10830 unhide new custom theme options
  lib/streamlit/config.py
Labels: security-assessment-completed, change:feature, impact:users

#10859 Add `theme.codeBackgroundColor` theming config option
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/theming/custom_theme_test.py
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/theme/getColors.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#10866 Add a comment about built-in "tomllib" in setup.py
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#10861 Fix `tabs` and `link_button` from getting disabled on disconnect
  e2e_playwright/websocket_disconnect.py
  e2e_playwright/websocket_disconnect_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/LinkButton/LinkButton.test.tsx
  frontend/lib/src/components/elements/LinkButton/LinkButton.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.test.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10846 Update pytest to latest version
  lib/test-requirements.txt
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10752 [Fix] Being unable to determine the form a current element is in
  lib/streamlit/delta_generator.py
  lib/tests/streamlit/form_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10761 Add `icon` to `st.text_input`
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-emoji_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-emoji_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-emoji_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-emoji_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-emoji_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-emoji_icon[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-material_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-material_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-material_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-material_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-material_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-material_icon[light_theme-webkit].png
  e2e_playwright/st_text_input.py
  e2e_playwright/st_text_input_test.py
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  lib/streamlit/elements/widgets/text_widgets.py
  lib/tests/streamlit/elements/text_input_test.py
  proto/streamlit/proto/TextInput.proto
Labels: security-assessment-completed, change:feature, impact:users

#10889 Fix/sqlite test repeatable
  lib/tests/streamlit/dataframe_util_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10877 Add total asset load size to performance tracking
  e2e_playwright/basic_app.py
  e2e_playwright/basic_app_test.py
  e2e_playwright/shared/performance.py
Labels: security-assessment-completed, change:other, impact:internal

#10871 [refactor] Add enforce-memo eslint rule
  frontend/.eslintrc.js
  frontend/eslint-plugin-streamlit-custom/enforce-memo.js
  frontend/eslint-plugin-streamlit-custom/enforce-memo.test.js
  frontend/eslint-plugin-streamlit-custom/index.js
  frontend/eslint-plugin-streamlit-custom/package.json
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/MapboxTokenError.tsx
  frontend/lib/src/components/elements/LinkButton/BaseLinkButton.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInputErrorState.tsx
  frontend/lib/src/components/widgets/AudioInput/NoMicPermissions.tsx
  frontend/lib/src/components/widgets/AudioInput/Placeholder.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInputButton.tsx
  frontend/lib/src/components/widgets/CameraInput/SwitchFacingModeButton.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatFileUploadButton.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatFileUploadDropzone.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatUploadedFile.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatUploadedFiles.tsx
  frontend/lib/src/components/widgets/DataFrame/Tooltip.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/cells/JsonViewer.tsx
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.tsx
  frontend/lib/src/components/widgets/FileUploader/FileDropzoneInstructions.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFile.tsx
  frontend/lib/src/components/widgets/FileUploader/UploadedFiles.tsx
  frontend/lib/src/components/widgets/FileUploader/withPagination/Pagination.tsx
  frontend/yarn.lock
Labels: area:performance, security-assessment-completed, impact:internal, change:refactor

#10711 Add `icon` to `st.number_input`
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-emoji_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-emoji_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-emoji_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-emoji_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-emoji_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-emoji_icon[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-material_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-material_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-material_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-material_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-material_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-material_icon[light_theme-webkit].png
  e2e_playwright/st_number_input.py
  e2e_playwright/st_number_input_test.py
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  lib/streamlit/elements/widgets/number_input.py
  lib/tests/streamlit/elements/number_input_test.py
  proto/streamlit/proto/NumberInput.proto
Labels: security-assessment-completed, change:feature, impact:users

#10898 Add checks and tracking for websocket messages size
  e2e_playwright/basic_app_test.py
  e2e_playwright/forward_msg_cache.py
  e2e_playwright/forward_msg_cache_test.py
  e2e_playwright/shared/performance.py
Labels: security-assessment-completed, change:other, impact:internal

#10903 Update material icons
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, impact:internal, change:chore

#10891 Preserve selectbox frontend state when clicking away and don't rerun until selecting option
  e2e_playwright/st_selectbox.py
  e2e_playwright/st_selectbox_test.py
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10894 Docstrings/1.44.0
  lib/streamlit/config.py
  lib/streamlit/elements/exception.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/runtime/context.py
Labels: security-assessment-completed, impact:internal, change:docs

#10921 Fix `showErrorDetails` showing wrong value in `streamlit config show`
  lib/streamlit/config.py
  lib/tests/streamlit/config_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10922 Migrate issue views badge to different provider
  .github/workflows/community-voting.yml
Labels: security-assessment-completed, change:other, impact:internal

#9886 Keep SessionInfo active after initialization, but include connection information
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/MetricsManager.ts
  frontend/app/src/StreamlitLib.test.tsx
  frontend/lib/src/SessionInfo.ts
  frontend/lib/src/mocks/mocks.ts
  proto/streamlit/proto/MetricsEvent.proto
Labels: security-assessment-completed, change:chore, impact:users

#10916 [theming] Unify `st.help` border colors
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[webkit].png
  frontend/lib/src/components/elements/DocString/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10926 Migrate issue view counter badge to own provider
  .github/workflows/community-voting.yml
Labels: security-assessment-completed, change:other, impact:internal

#10925 [fix] Slugify Markdown anchors
  NOTICES
  frontend/lib/package.json
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/yarn.lock
Labels: security-assessment-completed, change:breaking, change:bugfix, impact:users

#10788 Allow adding new options to selectbox / multiselect dynamically
  e2e_playwright/st_multiselect.py
  e2e_playwright/st_multiselect_test.py
  e2e_playwright/st_selectbox.py
  e2e_playwright/st_selectbox_test.py
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.test.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.tsx
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/testing/v1/element_tree.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/elements/lib/options_selector_utils_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  lib/tests/streamlit/typing/multiselect_types.py
  lib/tests/streamlit/typing/selectbox_types.py
  proto/streamlit/proto/MultiSelect.proto
  proto/streamlit/proto/Selectbox.proto
Labels: security-assessment-completed, change:feature, impact:users

#10930 [theming] Use dark mix for hovered color instead of `theme.colors.secondaryBg`
  frontend/app/src/components/MainMenu/styled-components.ts
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/styled-components.ts
  frontend/lib/src/components/shared/Dropdown/styled-components.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
Labels: security-assessment-completed, change:feature, impact:users

#10552 Fix typos
  component-lib/src/StreamlitReact.test.tsx
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-long_label[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-long_label[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-long_label[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-long_label[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-long_label[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-long_label[light_theme-webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/st_checkbox_test.py
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_stable_rendering_test.py
  e2e_playwright/st_time_input_test.py
  e2e_playwright/st_toggle.py
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/shared/Modal/Modal.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/styled-components.ts
  frontend/lib/src/dataframes/arrowFormatUtils.ts
Labels: security-assessment-completed, impact:internal, change:chore

#10951 Add PR comment on Python coverage changes
  .github/workflows/python-tests.yml
Labels: security-assessment-completed, change:other, impact:internal

#10931 [RFC] fix chat input height for multi-line placeholder
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_after_clear[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_after_clear[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_after_clear[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_with_text[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_with_text[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_with_text[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[webkit].png
  e2e_playwright/st_chat_input.py
  e2e_playwright/st_chat_input_test.py
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10944 [theming] use `borderColor` in `theme.sidebar` for sidebar border
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  frontend/app/src/components/Sidebar/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10963 Fix python coverage comment
  .github/workflows/python-tests.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#10958 Don't disable element when empty options but accept_new_options is true
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-no_options[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-no_options[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-no_options[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-no_options[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-no_options[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-no_options[light_theme-webkit].png
  e2e_playwright/st_multiselect.py
  e2e_playwright/st_multiselect_test.py
  e2e_playwright/st_selectbox.py
  e2e_playwright/st_selectbox_test.py
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed, change:feature, impact:users

#10968 Use vite proxy for dev server backend connection
  frontend/app/vite.config.ts
  frontend/connection/src/DefaultStreamlitEndpoints.ts
  frontend/connection/src/constants.ts
  frontend/connection/src/utils.ts
  lib/streamlit/web/server/server.py
Labels: security-assessment-completed, change:other, impact:internal

#10971 Only show links to google/ChatGPT if the site is localhost
  frontend/app/src/App.tsx
  frontend/app/src/showDevelopmentOptions.ts
  frontend/app/src/util/deploymentInfo.test.ts
  frontend/app/src/util/deploymentInfo.ts
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.test.tsx
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/utils/src/uri/index.test.ts
  frontend/utils/src/uri/index.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10946 [Fix] Disable sidebar page nav links when app not connected
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[webkit].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[webkit].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[webkit].png
  e2e_playwright/hostframe_app_test.py
  e2e_playwright/test_assets/hostframe.html
  e2e_playwright/websocket_disconnect.py
  e2e_playwright/websocket_disconnect_test.py
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/SidebarNavLink.test.tsx
  frontend/app/src/components/Sidebar/SidebarNavLink.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/hostframe.html
Labels: security-assessment-completed, change:bugfix, impact:users

#10976 [fix] st.html resize handling
  e2e_playwright/__snapshots__/linux/st_html_wide_mode_test/st_html_wide_mode-sidebar_closed[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_wide_mode_test/st_html_wide_mode-sidebar_closed[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_wide_mode_test/st_html_wide_mode-sidebar_closed[webkit].png
  e2e_playwright/__snapshots__/linux/st_html_wide_mode_test/st_html_wide_mode-sidebar_open[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_wide_mode_test/st_html_wide_mode-sidebar_open[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_wide_mode_test/st_html_wide_mode-sidebar_open[webkit].png
  e2e_playwright/st_html_wide_mode.py
  e2e_playwright/st_html_wide_mode_test.py
  frontend/lib/src/components/elements/Html/Html.test.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
  frontend/lib/src/components/elements/Html/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users
