Repository streamlit/streamlit, pull requests merged in 2025-07, with the labels that each got.

#10166 Add quick select to date input
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_two_dates_calendar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_two_dates_calendar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_two_dates_calendar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_two_dates_calendar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_two_dates_calendar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_two_dates_calendar[light_theme-webkit].png
  e2e_playwright/st_date_input_test.py
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
Labels: security-assessment-completed, change:feature, impact:users

#11469 Add show_time parameter to st.cache_data parameter to caching functions and tests
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/tests/streamlit/elements/cache_spinner_test.py
Labels: security-assessment-completed, change:feature, impact:users, status:product-approved

#11787 [fix] Refactor Header component to remove `isTransparentBackground` prop and adjust background logic
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_desktop_expanded[webkit-auto-viewport1-True-deploy_button_desktop_expanded].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[webkit].png
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[webkit].png
  frontend/app/src/App.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Header/Header.test.tsx
  frontend/app/src/components/Header/Header.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11673 Cleanup SidebarNav.test.tsx(s)
  frontend/app/src/components/Navigation/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
Labels: security-assessment-completed, change:other, impact:internal

#11461 Make the running man icon match theme colors
  frontend/app/src/assets/img/icon_running.gif
  frontend/app/src/components/StatusWidget/IconRunning.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/components/StatusWidget/styled-components.ts
Labels: security-assessment-completed, change:refactor, impact:users

#11807 [Fix] Altair/Vega/built-in charts don't stretch to full width in fullscreen mode
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/shared/Toolbar/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11814 [fix] Fixing the sidebar font weight and spacing for sections
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_collapsed[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-sidebar_nav_expanded[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/sidebar-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_custom_theme_test/sidebar-nav-custom-theme[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_top_nav_test/st_navigation-mobile_sidebar_sections[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_top_nav_test/st_navigation-mobile_sidebar_sections[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_top_nav_test/st_navigation-mobile_sidebar_sections[webkit].png
  frontend/app/src/components/Navigation/NavSection.tsx
  frontend/app/src/components/Navigation/styled-components.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11838 Add support for setting the column config width to pixels
  e2e_playwright/st_dataframe_config.py
  lib/streamlit/elements/lib/column_types.py
  lib/tests/streamlit/elements/lib/column_types_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11682 Make dataframe error indicator adapt to sizing from theme
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomRenderer.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11846 Fix e2e tests
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-list_column_overlay[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-list_column_overlay[light_theme-chromium].png
  e2e_playwright/st_dataframe_config.py
Labels: security-assessment-completed, change:other, impact:internal

#11840 Clean up makefile - part 2
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/ensure-relative-imports.yml
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/notify-about-new-emojis-material-icons.yml
  .github/workflows/python-tests.yml
  Makefile
Labels: security-assessment-completed, impact:internal, change:refactor

#11777 Add `headingFontWeights` theming config option
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[chromium].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[firefox].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[webkit].png
  e2e_playwright/theming/theme_font_weights.py
  e2e_playwright/theming/theme_font_weights_test.py
  e2e_playwright/theming/theme_weight_test_app.py
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#11821 Remove `CachedFunc` protocol and improve type annotations on the cache classes and functions
  lib/streamlit/elements/doc_string.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/cached_message_replay.py
Labels: security-assessment-completed, impact:internal, change:refactor

#11781 [Fix] Mark wrap as transient prop
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#11851 Clean up makefile - part 3
  .cursor/rules/python_tests.mdc
  .devcontainer/devcontainer.json
  .github/actions/make_init/action.yml
  .github/copilot-instructions.md
  .github/workflows/js-tests.yml
  .github/workflows/performance.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright.yml
  .github/workflows/python-tests.yml
  Makefile
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  scripts/get_min_versions.py
Labels: security-assessment-completed, impact:internal, change:refactor

#11685 Fix progress column label measurement
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_format_changed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_format_changed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_format_changed[webkit].png
  e2e_playwright/st_dataframe_config.py
  frontend/lib/src/components/widgets/DataFrame/columns/ProgressColumn.ts
  lib/streamlit/elements/lib/column_types.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11841 Make file watcher more error-resistant
  lib/streamlit/errors.py
  lib/streamlit/runtime/secrets.py
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/streamlit/watcher/polling_path_watcher.py
  lib/streamlit/watcher/util.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11868 Fix mypy typing check
  lib/streamlit/auth_util.py
Labels: security-assessment-completed, change:other, impact:internal

#11864 Add `headingFontSizes` theming config option
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[chromium].png
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[firefox].png
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[webkit].png
  e2e_playwright/theming/theme_header_sizes.py
  e2e_playwright/theming/theme_header_sizes_test.py
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/Heading.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#11861 [fix] No more sidebar flickering when initial_sidebar_state="collapsed"
  e2e_playwright/hello_app_test.py
  e2e_playwright/multipage_apps_v2/mpa_v2_top_nav_test.py
  e2e_playwright/st_sidebar_flicker.py
  e2e_playwright/st_sidebar_flicker_test.py
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11860 Add repo overview and make commands cursor rule
  .cursor/.gitignore
  .cursor/rules/make_commands.mdc
  .cursor/rules/overview.mdc
  .github/copilot-instructions.md
  .pre-commit-config.yaml
  Makefile
  scripts/generate_cursor_rules.py
Labels: security-assessment-completed, change:other, impact:internal

#11870 Fix initial page MPA regression
  e2e_playwright/hostframe_app_test.py
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11468 [AdvancedLayouts] Adds a width/height parameters to st.container and st.columns
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_large[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-variable_width_absolute[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-width_configuration_fixed[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-width_configuration_fixed[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-width_configuration_fixed[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-width_configuration_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-width_configuration_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-width_configuration_stretch[webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-columns[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-columns[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-content_and_fixed_height[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-content_and_fixed_height[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-content_and_fixed_height[webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-fixed_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-fixed_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-fixed_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-stretch_and_fixed_height[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-stretch_and_fixed_height[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-stretch_and_fixed_height[webkit].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-stretch_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-stretch_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_container_test/st_container-stretch_width[webkit].png
  e2e_playwright/st_columns.py
  e2e_playwright/st_columns_test.py
  e2e_playwright/st_container.py
  e2e_playwright/st_container_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/core/Block/utils.test.ts
  frontend/lib/src/components/core/Block/utils.ts
  frontend/lib/src/components/core/Layout/useLayoutStyles.test.ts
  frontend/lib/src/components/core/Layout/useLayoutStyles.ts
  frontend/lib/src/components/elements/ArrowTable/styled-components.ts
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/elements/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:breaking, change:feature, impact:users

#11916 Correctly reset chat input session state value
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-file_upload_shift_enter_new_line[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-file_upload_shift_enter_new_line[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-file_uploaded_error[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-file_uploaded_error[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_300px[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_300px[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_stretch[firefox].png
  e2e_playwright/st_chat_input.py
  e2e_playwright/st_chat_input_test.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/runtime/state/safe_session_state.py
  lib/streamlit/runtime/state/session_state.py
  lib/tests/streamlit/runtime/state/session_state_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11917 Fix chart colors not applied in sidebar
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors-sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors-sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors-sidebar[webkit].png
  e2e_playwright/theming/theme_categorical_test.py
  e2e_playwright/theming/theme_chart_app.py
  frontend/app/src/components/Sidebar/ThemedSidebar.test.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11913 [fix] Make the topPadding also look to see if there's a sidebar so that it stays consistent
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11909 Add files generated in CI to gitignore
  .gitignore
Labels: security-assessment-completed, change:other, impact:internal

#11953 [fix] flaky video end test
  e2e_playwright/st_video_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11929 Fix cache spinner test flakiness
  lib/tests/streamlit/elements/cache_spinner_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11964 Change button styles
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/clear_cache_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_hover[webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-on_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-on_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-on_hover[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-order_after_replacement[chromium].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-order_after_replacement[firefox].png
  e2e_playwright/__snapshots__/linux/st_empty_test/st_empty-order_after_replacement[webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-default_hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-default_hover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-default_hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-default_hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-default_hover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-default_hover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-primary_hover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-primary_hover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-primary_hover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-primary_hover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-primary_hover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_link_button_test/st_link_button-primary_hover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[webkit].png
  e2e_playwright/st_button_test.py
  frontend/lib/src/components/elements/LinkButton/styled-components.ts
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#11935 Release 1.47.0
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#12007 Clean-up and fix gitignore
  .gitignore
Labels: security-assessment-completed, change:other, impact:internal

#11999 Hide quickselect in `date_input` if min date is more than 2 years ago
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#12012 Add ty python type checker
  Makefile
  e2e_playwright/conftest.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_map.py
  e2e_playwright/st_pyplot.py
  e2e_playwright/st_table.py
  lib/dev-requirements.txt
  lib/streamlit/cli_util.py
  lib/streamlit/commands/echo.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/components/v1/component_arrow.py
  lib/streamlit/config.py
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/deprecation_util.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/write.py
  lib/streamlit/env_util.py
  lib/streamlit/file_util.py
  lib/streamlit/git_util.py
  lib/streamlit/logger.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/temporary_directory.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/type_util.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/streamlit/web/cli.py
  lib/streamlit/web/server/server.py
  scripts/run_bare_execution_tests.py
  scripts/run_in_subdirectory.py
  scripts/update_e2e_snapshots.py
  ty.toml
Labels: security-assessment-completed, change:other, impact:internal

#12024 [fix] Sidebar toggle state reset on page resize.
  e2e_playwright/st_main_layout_test.py
  e2e_playwright/st_sidebar_test.py
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12021 [feat] Add IDE Testing Integration for playwright, pytest, and vitest
  .devcontainer/devcontainer.json
  .gitignore
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  scripts/sync_vscode_devcontainer.py
Labels: security-assessment-completed, impact:internal, change:feature

#12034 Add support for rerunning app when dialog gets dismissed
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/Dialog/Dialog.test.tsx
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/dialog.py
  lib/tests/streamlit/elements/layouts_test.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#11901 Make st.logout use end_session_endpoint if provided in OIDC config
  lib/streamlit/user_info.py
  lib/streamlit/web/server/oauth_authlib_routes.py
  lib/tests/streamlit/web/server/oauth_authlib_routes_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#12055 [fix] Better cleanup for Toast tests
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#12059 Add cooldown to dependabot config
  .github/dependabot.yml
Labels: security-assessment-completed, change:other, impact:internal

#12014 Make Download URL configurable & allow preventing download attribute
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/components/Logo/LogoComponent.test.tsx
  frontend/connection/src/ConnectionManager.ts
  frontend/connection/src/DefaultStreamlitEndpoints.test.ts
  frontend/connection/src/DefaultStreamlitEndpoints.ts
  frontend/connection/src/testUtils.ts
  frontend/connection/src/types.ts
  frontend/connection/src/utils.ts
  frontend/lib/src/FileUploadClient.test.ts
  frontend/lib/src/StreamlitEndpoints.ts
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentRegistry.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataExporter.ts
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.test.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/lib/src/hooks/useDownloadUrl.ts
  frontend/lib/src/mocks/mocks.ts
  frontend/lib/src/util/createDownloadLinkElement.test.ts
  frontend/lib/src/util/createDownloadLinkElement.ts
  frontend/utils/src/types/index.ts
  frontend/utils/src/uri/index.ts
Labels: security-assessment-completed, change:other, impact:internal

#12056 Make `codeFontWeight` separately configurable in sidebar
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[chromium].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[firefox].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[webkit].png
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[chromium].png
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[firefox].png
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[webkit].png
  e2e_playwright/theming/size_and_weight_test_app.py
  e2e_playwright/theming/theme_font_weights.py
  e2e_playwright/theming/theme_font_weights_test.py
  e2e_playwright/theming/theme_header_sizes.py
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/app_session_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12073 [feat] Update TypeScript Tests LLM rules
  .cursor/rules/typescript_tests.mdc
  .github/copilot-instructions.md
Labels: security-assessment-completed, impact:internal, change:feature

#12077 [Fix] Allow fractional heading font sizes
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[chromium].png
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[firefox].png
  e2e_playwright/__snapshots__/linux/theme_header_sizes_test/custom_header_font_sizes[webkit].png
  e2e_playwright/theming/theme_header_sizes_test.py
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12091 [fix] Make toolbar still show custom menu items when in MINIMAL mode
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users
