Repository streamlit/streamlit, pull requests merged in 2025-02, with the labels that each got.

#10246 Add `theme.roundness` theming option
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/custom_theme.py
  e2e_playwright/custom_theme_test.py
  e2e_playwright/test_assets/hostframe.html
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/hostframe.html
  frontend/lib/src/components/elements/Spinner/styled-components.ts
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
  frontend/lib/src/theme/createThemeUtil.ts
  frontend/lib/src/theme/primitives/radii.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#10303 Convert `withScreencast` to functional style
  frontend/app/src/hocs/withScreencast/withScreencast.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#10259 Add `theme.borderColor` and `theme.showBorderAroundInputs` config options
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/custom_theme.py
  e2e_playwright/custom_theme_test.py
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
  frontend/lib/src/theme/getColors.ts
  frontend/lib/src/theme/types.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#10319 fix typo in script name
  .github/workflows/notify-about-new-emojis-material-icons.yml
Labels: security-assessment-completed, impact:internal, change:chore

#10316 Misc docstrings for 1.42.0
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/code.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/spinner.py
  lib/streamlit/elements/text.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/elements/write.py
  lib/streamlit/user_info.py
Labels: security-assessment-completed, impact:internal, change:docs

#10325 Fix codeql error for needing type string
  frontend/app/src/connection/promiseWithResolversPolyfill.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10327 Update material symbols with icon pack, also fix workflow for notification
  .github/workflows/notify-about-new-emojis-material-icons.yml
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, impact:internal, change:chore

#10272 Use compact file uploader based on element width
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-compact[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-compact[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-compact[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-compact[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-compact[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-compact[light_theme-webkit].png
  e2e_playwright/st_file_uploader.py
  e2e_playwright/st_file_uploader_test.py
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/components/widgets/FileUploader/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10323 Hide the top colored line for custom themes
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:other, impact:users

#10334 Activate venv before pip install
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/ensure-relative-imports.yml
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/notify-about-new-emojis-material-icons.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/pr-preview.yml
  .github/workflows/python-min-deps.yml
  .github/workflows/python-tests.yml
Labels: security-assessment-completed, impact:internal, change:chore

#10320 Remove `rich` from required dependencies
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/config.py
  lib/test-requirements.txt
Labels: security-assessment-completed, change:refactor, impact:users

#10313 Remove duplicate word typo
  lib/streamlit/hello/animation_demo.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10332 Deprecate widget and skeleton background color options
  e2e_playwright/test_assets/hostframe.html
  frontend/app/src/util/useThemeManager.test.ts
  frontend/hostframe.html
  frontend/lib/src/components/elements/Skeleton/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
  frontend/lib/src/components/widgets/NumberInput/styled-components.ts
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
  frontend/lib/src/mocks/mockTheme.ts
  frontend/lib/src/theme/createThemeUtil.ts
  frontend/lib/src/theme/emotionBaseTheme/themeColors.ts
  frontend/lib/src/theme/utils.ts
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#10338 Release/1.42.0
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#10333 Add more e2e test cases for custom theming
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[webkit].png
  e2e_playwright/custom_theme.py
  e2e_playwright/theming/custom_theme.py
  e2e_playwright/theming/custom_theme_test.py
  e2e_playwright/theming/snowflake_dark_theme.py
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme.py
  e2e_playwright/theming/snowflake_light_theme_test.py
  e2e_playwright/theming/theme_tester_app.py
Labels: security-assessment-completed, change:other, impact:internal

#10340 Add venv activate for static deploy workflow
  .github/workflows/static-deploy.yml
Labels: security-assessment-completed, impact:internal, change:chore

#10330 Refactor docstring and progress colors
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-class_no_docs[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-globals[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-long_docs[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-mixed_docs[webkit].png
  frontend/lib/src/components/elements/DocString/styled-components.ts
  frontend/lib/src/components/elements/Progress/Progress.tsx
  frontend/lib/src/components/elements/Progress/styled-components.ts
  frontend/lib/src/theme/getColors.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#9863 Use default element height for `st.audio`
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-unified_height[light_theme-webkit].png
  e2e_playwright/st_audio.py
  e2e_playwright/st_audio_test.py
  frontend/lib/src/components/elements/Audio/Audio.tsx
  frontend/lib/src/components/elements/Audio/styled-components.ts
Labels: security-assessment-completed, change:other, impact:internal

#10328 Refactor & simplify sidenav theming
  frontend/app/src/components/Sidebar/SidebarNavLink.tsx
  frontend/app/src/components/Sidebar/styled-components.ts
  frontend/lib/src/components/elements/PageLink/PageLink.tsx
  frontend/lib/src/components/shared/Icon/DynamicIcon.tsx
  frontend/lib/src/components/shared/Icon/Icon.tsx
  frontend/lib/src/components/shared/Icon/index.tsx
  frontend/lib/src/components/shared/Icon/styled-components.ts
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/theme/emotionDarkTheme/themeColors.ts
  frontend/lib/src/theme/emotionLightTheme/themeColors.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10349 Fix issue with active pills & segmented control label font-size
  frontend/lib/src/components/shared/BaseButton/DynamicButtonLabel.tsx
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10343 Refactor `createThemeUtil`
  frontend/lib/src/mocks/mockTheme.ts
  frontend/lib/src/theme/baseui.ts
  frontend/lib/src/theme/createBaseUiTheme.ts
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10355 [fix] Prevent baseui warnings for chat input border
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10354 [cache_utils] Fallback to bytecode upon any Excepton
  lib/streamlit/runtime/caching/cache_utils.py
Labels: security-assessment-completed, impact:internal, change:chore

#10345 Add theming options to configure custom fonts
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[webkit].png
  e2e_playwright/shared/app_utils.py
  e2e_playwright/theming/custom_theme_test.py
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme_test.py
  e2e_playwright/theming/theme_tester_app.py
  frontend/app/src/App.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#10359 Fix the usage of dataframe column menu in dialog
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[webkit].png
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10360 Raise an exception when provider name contains underscore
  lib/streamlit/auth_util.py
  lib/tests/streamlit/user_info_test.py
Labels: security-assessment-completed, change:chore, impact:users

#10367 Adjustments to App and Sidebar to follow the react-refresh linter rule
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/FontFaceDeclaration/index.ts
  frontend/app/src/components/Header/index.ts
  frontend/app/src/components/MainMenu/index.ts
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/index.ts
  frontend/app/src/components/StatusWidget/index.ts
Labels: security-assessment-completed, impact:internal, change:chore

#9812 Wrap many element components in lib with memo
  frontend/.eslintrc.js
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.test.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/AlertElement/AlertElement.tsx
  frontend/lib/src/components/elements/Audio/Audio.tsx
  frontend/lib/src/components/elements/BokehChart/BokehChart.tsx
  frontend/lib/src/components/elements/ChatMessage/ChatMessage.tsx
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  frontend/lib/src/components/elements/DocString/DocString.tsx
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
  frontend/lib/src/components/elements/IFrame/IFrame.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/Json/Json.tsx
  frontend/lib/src/components/elements/LinkButton/LinkButton.tsx
  frontend/lib/src/components/elements/Markdown/Markdown.tsx
  frontend/lib/src/components/elements/Metric/Metric.tsx
  frontend/lib/src/components/elements/PageLink/PageLink.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/elements/Progress/Progress.tsx
  frontend/lib/src/components/elements/Spinner/Spinner.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  frontend/lib/src/components/elements/TextElement/TextElement.tsx
  frontend/lib/src/components/elements/Toast/Toast.test.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/widgets/Button/Button.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/components/widgets/Form/Form.test.tsx
  frontend/lib/src/components/widgets/Form/Form.tsx
  frontend/lib/src/components/widgets/Form/index.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.tsx
  frontend/lib/src/hooks/useWidgetManagerElementState.test.tsx
Labels: security-assessment-completed, impact:internal, change:refactor, perf:lighthouse

#10362 [chore] Stabilize Lighthouse in Performance suite
  frontend/app/performance/lighthouse/LighthouseOrchestrator.mjs
Labels: security-assessment-completed, impact:internal, change:chore

#10224 Apply default rounding to graphviz charts
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart-theming[light_theme-webkit].png
  e2e_playwright/st_graphviz_chart_test.py
  frontend/lib/src/components/elements/GraphVizChart/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10375 Add `theme.baseFontSize` theming config option
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[webkit].png
  e2e_playwright/test_assets/hostframe.html
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme_test.py
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/hostframe.html
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  frontend/lib/src/components/elements/PlotlyChart/CustomTheme.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/widgets/BaseWidget/WidgetLabel.test.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
  frontend/lib/src/index.ts
  frontend/lib/src/theme/globalStyles.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#10364 [fix] chat input multi-line shrinks after drag and drop
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9549 Allow configuring the row height for `st.dataframe` and `st.data_editor`
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-row_height[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-row_height[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-row_height[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-row_height[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-row_height[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-row_height[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  frontend/lib/src/components/widgets/DataFrame/columns/ObjectColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/TextColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
  lib/tests/streamlit/elements/data_editor_test.py
  proto/streamlit/proto/Arrow.proto
Labels: security-assessment-completed, change:feature, impact:users

#10372 Fix typo in set_page_config doc string
  lib/streamlit/commands/page_config.py
Labels: security-assessment-completed, impact:users, change:docs

#10381 Refactor popover e2e test
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_popover_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10390 Enable automated dependency updates
  .github/dependabot.yml
Labels: security-assessment-completed, change:other, impact:internal

#10377 Fix: `st.logo` unmounts with use of `st.fragment`
  frontend/app/src/App.test.tsx
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/AppNode.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10398 Prevent showing tooltips on trailing dataframe row
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useTooltips.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTooltips.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10400 Remove old typescript from lib package.json
  Makefile
  NOTICES
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#10405 Always scroll to bottom when adding new rows in data editor
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-added_rows_via_toolbar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-added_rows_via_toolbar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-added_rows_via_toolbar[webkit].png
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:feature, impact:users

#10331 request script rerun when host explicitly requests reconnect
  e2e_playwright/hostframe_app_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10404 fix warning for custom streamlit mime type
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10401 [chore] Properly classify the swc/plugin-emotion dependency
  NOTICES
  frontend/lib/package.json
Labels: security-assessment-completed, impact:internal, change:chore

#10413 Update hashlib usage for FIPS compliance
  .ruff.toml
  lib/streamlit/elements/bokeh_chart.py
  lib/streamlit/elements/graphviz_chart.py
  lib/streamlit/elements/lib/subtitle_utils.py
  lib/streamlit/elements/lib/utils.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/memory_media_file_storage.py
  lib/streamlit/testing/v1/app_test.py
  lib/streamlit/util.py
  lib/streamlit/watcher/util.py
  lib/tests/streamlit/elements/video_test.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10337 Add .xml to the list of allowed static file extensions
  lib/streamlit/web/server/app_static_file_handler.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10179 Add pre-defined formats to `st.column_config`
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-progress_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-progress_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-progress_column[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_formatting[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_formatting[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_formatting[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_formatting[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_formatting[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_formatting[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ProgressColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  lib/streamlit/elements/lib/column_types.py
Labels: security-assessment-completed, change:feature, impact:users

#10335 Allow static serving for common font files
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme_test.py
  e2e_playwright/theming/static/Inter-Black.woff2
  e2e_playwright/theming/static/Inter-Bold.woff2
  e2e_playwright/theming/static/Inter-Regular.woff2
  e2e_playwright/theming/static/Inter-SemiBold.woff2
  lib/streamlit/web/server/app_static_file_handler.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10418 Increase heap size for lib build
  frontend/lib/package.json
Labels: security-assessment-completed, impact:internal, change:chore

#10427 Increase number of automated dependency updates
  .github/dependabot.yml
Labels: security-assessment-completed, change:other, impact:internal

#10417 Add json to the list of safe static files
  lib/streamlit/web/server/app_static_file_handler.py
  lib/tests/streamlit/web/server/app_static_file_handler_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10422 Render code in st.write with white-space: pre-wrap for correct display
  e2e_playwright/__snapshots__/linux/st_write_markdown_test/write_inline_code[chromium].png
  e2e_playwright/__snapshots__/linux/st_write_markdown_test/write_inline_code[firefox].png
  e2e_playwright/__snapshots__/linux/st_write_markdown_test/write_inline_code[webkit].png
  e2e_playwright/st_write_markdown.py
  e2e_playwright/st_write_markdown_test.py
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:chore

#10395 add transparent file upload drop target to chat input
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[webkit].png
  e2e_playwright/st_chat_input_test.py
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatFileUploadButton.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatFileUploadDropzone.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10435 [fix] Fixes JS unit tests in createRoot mode
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/hostComm/HostCommunicationManager.test.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10374 Update Bokeh error message to redirect to streamlit-bokeh custom component
  lib/streamlit/elements/bokeh_chart.py
Labels: security-assessment-completed, change:feature, impact:users

#10440 Remove remaining widget background color theme
  frontend/lib/src/components/widgets/ChatInput/fileUpload/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:chore

#10444 Fix dataframe webkit e2e test flakiness
  e2e_playwright/st_dataframe_input_data.py
  e2e_playwright/st_dataframe_input_data_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10443 Fix console error when using rem in svg width & height attributes
  frontend/lib/src/components/elements/CodeBlock/CopyButton.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/TooltipIcon/TooltipIcon.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10450 Update "click immediately with onBlur" test to reduce flakiness
  e2e_playwright/widget_state.py
  e2e_playwright/widget_state_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10439 [fix] File uploader state management with createRoot
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10441 Revamp disabled state for chat input
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[webkit].png
  e2e_playwright/st_chat_input.py
  e2e_playwright/st_chat_input_test.py
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatFileUploadButton.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10455 [Fix] Reuse event loop logic
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/web/bootstrap_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10467 Ignore eslint & eslint-plugin dependency updates
  .github/dependabot.yml
Labels: security-assessment-completed, impact:internal, change:chore

#10473 Fix dependabot alerts
  NOTICES
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/connection/package.json
  frontend/connection/src/DefaultStreamlitEndpoints.test.ts
  frontend/lib/package.json
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/package.json
  frontend/utils/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#10456 [Fix]: `st.altair_chart` selection interval showing `true` tooltip
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10410 Time formatting logic update: seconds/minutes/hours display
  frontend/lib/src/components/widgets/AudioInput/formatTime.test.ts
  frontend/lib/src/components/widgets/AudioInput/formatTime.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10474 [fix] Chat Input measurement with createRoot
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10472 Release/1.42.2
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#10476 Add autosize option to dataframe column menu
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-autosized_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-autosized_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-autosized_column[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-webkit].png
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.test.tsx
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:feature, impact:users

#10296 Download button: Allow to not trigger rerun
  e2e_playwright/st_download_button.py
  e2e_playwright/st_download_button_test.py
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  lib/streamlit/elements/widgets/button.py
  lib/tests/streamlit/elements/download_button_test.py
  proto/streamlit/proto/DownloadButton.proto
Labels: security-assessment-completed, change:feature, impact:users

#10095 Transition `submittedEmail` event
  lib/streamlit/runtime/credentials.py
  lib/tests/streamlit/runtime/credentials_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10428 Use named exports in various components
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#10420 Change dataframe column format from UI
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-date_column_format_changed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-date_column_format_changed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-date_column_format_changed[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-date_column_formatting_menu[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-date_column_formatting_menu[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-date_column_formatting_menu[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_column_format_changed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_column_format_changed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_column_format_changed[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_column_formatting_menu[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_column_formatting_menu[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-datetime_column_formatting_menu[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_column_format_changed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_column_format_changed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_column_format_changed[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_column_formatting_menu[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_column_formatting_menu[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_column_formatting_menu[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_format_changed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_format_changed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_format_changed[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_formatting_menu[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_formatting_menu[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-progress_column_formatting_menu[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-time_column_format_changed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-time_column_format_changed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-time_column_format_changed[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-time_column_formatting_menu[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-time_column_formatting_menu[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-time_column_formatting_menu[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-webkit].png
  e2e_playwright/st_dataframe_config_test.py
  e2e_playwright/st_dataframe_interactions.py
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.test.tsx
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/FormattingMenu.test.tsx
  frontend/lib/src/components/widgets/DataFrame/FormattingMenu.tsx
  frontend/lib/src/components/widgets/DataFrame/columnConfigUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columnConfigUtils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/index.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnFormatting.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnFormatting.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnPinning.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
  frontend/lib/src/components/widgets/DataFrame/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10484 Fix deprecation with `fillna` pandas method
  lib/streamlit/dataframe_util.py
Labels: security-assessment-completed, change:other, impact:users

#10487 Allow small text in Markdown
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-webkit].png
  e2e_playwright/st_markdown.py
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  lib/streamlit/elements/markdown.py
Labels: security-assessment-completed, change:feature, impact:users

#10497 Adjustments to Spinner.tsx to support react-refresh linter rule.
  frontend/lib/src/components/elements/Spinner/Spinner.test.tsx
  frontend/lib/src/components/elements/Spinner/Spinner.tsx
  frontend/lib/src/components/elements/Spinner/utils.test.ts
  frontend/lib/src/components/elements/Spinner/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10463 feat: add warning log in _get_user_info for missing script run context
  lib/streamlit/user_info.py
Labels: security-assessment-completed, impact:internal, change:chore

#10502 Add bokeh component note
  lib/streamlit/elements/bokeh_chart.py
Labels: security-assessment-completed, impact:internal, change:docs

#10494 Adjustments to PlotlyChart to follow the react-refresh linting rule.
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.test.tsx
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
  frontend/lib/src/components/elements/PlotlyChart/utils.test.ts
  frontend/lib/src/components/elements/PlotlyChart/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10507 Fix flakiness of code e2e tests
  e2e_playwright/st_code_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10408 Support polars dataframe/series hashing
  .github/workflows/performance.yml
  lib/streamlit/runtime/caching/hashing.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10512 Change default for constraints to be turned off
  .github/actions/build_info/action.yml
  .github/scripts/build_info.py
  .github/workflows/python-tests.yml
  .github/workflows/release.yml
  Makefile
Labels: security-assessment-completed, impact:internal, change:chore

#10518 Change the autosize column menu icon
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-webkit].png
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnMenu.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#10336 Add timezone and timezone_offset to the st.context
  e2e_playwright/st_context.py
  e2e_playwright/st_context_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/vitest.setup.ts
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/context.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/scriptrunner_utils/script_requests.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  proto/streamlit/proto/ClientState.proto
Labels: security-assessment-completed, change:feature, impact:users

#10445 Fix regression with column order not getting updated
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-column_order_changed[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-column_order_changed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-column_order_changed[webkit].png
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10526 Add back support for showing chat input border
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/theming/custom_theme_test.py
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10527 Mark `theme.showBorderAroundInputs` config option as hidden
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10520 Add docs for chat input file uploader
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/file_uploader.py
Labels: security-assessment-completed, impact:internal, change:docs

#10533 [fix] Tabs content flickering
  frontend/lib/src/components/core/Block/Block.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10534 Revamp the dataframe search bar to be more responsive
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-trigger_search_via_toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-trigger_search_via_toolbar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-trigger_search_via_toolbar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-trigger_search_via_toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-trigger_search_via_toolbar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-trigger_search_via_toolbar[light_theme-webkit].png
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10542 Remove unused frontend dependencies
  NOTICES
  frontend/app/package.json
  frontend/lib/package.json
  frontend/utils/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#10540 Update dependabot ignore list
  .github/dependabot.yml
Labels: security-assessment-completed, impact:internal, change:chore

#10458 Remove MPAv1 code
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/streamlit/source_util.py
  lib/tests/conftest.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/pages_manager_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
  lib/tests/streamlit/source_util_test.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
  proto/streamlit/proto/ForwardMsg.proto
  proto/streamlit/proto/PagesChanged.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#10541 Update deckgl dependencies
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#10548 Fix react warning about wrong usage of `key` in dataframe component
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
Labels: security-assessment-completed, change:other, impact:internal

#10530 support file size limit error for chat input
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-file_uploaded_error[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-file_uploaded_error[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-file_uploaded_error[webkit].png
  e2e_playwright/st_chat_input.py
  e2e_playwright/st_chat_input_test.py
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatUploadedFile.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/createDropHandler.ts
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/util/FileHelper.ts
  lib/streamlit/elements/widgets/chat.py
  proto/streamlit/proto/ChatInput.proto
Labels: security-assessment-completed, change:feature, impact:users

#10551 Remove unused chat input test delays
  e2e_playwright/st_chat_input_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10554 Docstrings for column config, dataframes, context, and misc
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/runtime/context.py
  lib/streamlit/user_info.py
Labels: security-assessment-completed, impact:internal, change:docs
