Repository streamlit/streamlit, pull requests merged in 2025-06, with the labels that each got.

#11048 [FIX] - Negative Values not displayed in ChartColumn in #10411
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-bar_chart_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-bar_chart_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-line_chart_column[chromium].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-line_chart_column[firefox].png
  e2e_playwright/__snapshots__/linux/st_data_editor_config_test/st_data_editor-line_chart_column[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-area_chart_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-area_chart_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-area_chart_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-area_chart_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-area_chart_column[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-bar_chart_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-bar_chart_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-bar_chart_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-bar_chart_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-bar_chart_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-line_chart_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-line_chart_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-line_chart_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-line_chart_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-line_chart_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-line_chart_column[light_theme-webkit].png
  frontend/lib/src/components/widgets/DataFrame/columns/ChartColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ChartColumn.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11167 [AdvancedLayouts] Adds a width parameter to st.text
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-content-width[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-content-width[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-content-width[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-fixed-width[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-fixed-width[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-fixed-width[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-no_formatting_applied[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-rendering[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-rendering[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-rendering[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-stretch-width[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-stretch-width[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_test/st_text-stretch-width[webkit].png
  e2e_playwright/st_text.py
  e2e_playwright/st_text_test.py
  lib/streamlit/elements/text.py
  lib/tests/streamlit/elements/text_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11525 Allow usage of 3000 as app port
  lib/streamlit/config.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/server_util.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10972 Add theme field to context, it would contain only `type` field for now "light" or "dark"
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[chromium].png
  e2e_playwright/hostframe_app.py
  e2e_playwright/hostframe_app_test.py
  e2e_playwright/st_context.py
  e2e_playwright/st_context_test.py
  e2e_playwright/test_assets/hostframe.html
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/lib/event_utils.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/runtime/context.py
  lib/streamlit/util.py
  proto/streamlit/proto/ClientState.proto
Labels: security-assessment-completed, impact:internal, change:chore

#11498 Fixed issue gh-11327: Plotly chart reset axes not working after reset
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_reset_axis[webkit].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_zoomed_selection[chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_zoomed_selection[firefox].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-fullscreen_zoomed_selection[webkit].png
  e2e_playwright/st_plotly_chart_test.py
  frontend/lib/src/components/elements/PlotlyChart/PlotlyChart.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11529 Use CSS class naming pattern in markdown
  .cursor/rules/typescript.mdc
  e2e_playwright/st_button_test.py
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11539 Update test to only run on Chromium browser due to flakiness on WebKit and Firefox
  e2e_playwright/st_plotly_chart_select_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11538 Add/reference licenses for font files
  e2e_playwright/theming/static/Inter.LICENSE
  e2e_playwright/theming/static/NotoSans.LICENSE
Labels: security-assessment-completed, impact:internal, change:chore

#11549 [refactor] More robust cleanup for websocket connection
  frontend/connection/src/DoInitPings.tsx
  frontend/connection/src/WebsocketConnection.test.tsx
  frontend/connection/src/WebsocketConnection.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#11537 Make document basepath configurable via window variable
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/connection/src/DoInitPings.tsx
  frontend/connection/src/index.ts
  frontend/connection/src/utils.test.ts
  frontend/connection/src/utils.ts
  frontend/utils/src/types/index.ts
Labels: security-assessment-completed, impact:internal, change:feature

#11520 Fix number column rounding issue
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11514 Update vega interpreter dependency to fix datetime issue
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#11511 Use private token in `st.map`
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/map_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11564 Fix types for np.repeat
  e2e_playwright/st_cache_data.py
  e2e_playwright/st_columns.py
  e2e_playwright/st_image.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10388 Fix watcher metaclass conflict with torch.classes
  lib/streamlit/watcher/local_sources_watcher.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11521 Add context info to switch page rerun
  lib/streamlit/commands/execution_control.py
  lib/tests/streamlit/commands/execution_control_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11049 [Fix] Enum formatting not working with styled dataframes
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/tests/streamlit/elements/arrow_dataframe_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11571 [fix] Maintain tracked directory with make clean
  Makefile
Labels: security-assessment-completed, impact:internal, change:bugfix

#11506 Fixed bug 11330 st.context.timezone becomes empty
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/scriptrunner/script_runner_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11574 Add new CUSTOM_COMPONENT_CLIENT_ID global
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/utils/src/types/index.ts
Labels: security-assessment-completed, impact:internal, change:feature

#11552 [fix] Scroll element into view race condition fix
  e2e_playwright/conftest.py
  e2e_playwright/multipage_apps_v2/mpa_v2_anchors.py
  e2e_playwright/multipage_apps_v2/mpa_v2_anchors_test.py
  e2e_playwright/st_markdown_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11586 [Fix] Remove `fireEvent` test usage in `st.multiselect`
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#11593 [fix] Utilize userEvent in StatusWidget tests
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#11595 [fix] Mark a number of e2e tests as flaky
  e2e_playwright/st_chat_input_test.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_plotly_chart_select_test.py
  e2e_playwright/st_pydeck_chart_select_test.py
  e2e_playwright/st_radio_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11594 [fix] Attempt to stabilize test_set_value_correctly_when_click test
  e2e_playwright/st_radio_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11578 [Fix] Render `st.toast` messages above dialogs
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[chromium].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[firefox].png
  e2e_playwright/__snapshots__/linux/st_toast_test/toast-above-dialog[webkit].png
  e2e_playwright/st_toast.py
  e2e_playwright/st_toast_test.py
  frontend/lib/src/theme/primitives/zIndices.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11585 [fix] st.altair_chart rendering with long titles
  e2e_playwright/__snapshots__/linux/st_altair_chart_title_test/st_altair_chart_title-long_title_rendering_use_container_width_false[chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_title_test/st_altair_chart_title-long_title_rendering_use_container_width_false[firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_title_test/st_altair_chart_title-long_title_rendering_use_container_width_false[webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_title_test/st_altair_chart_title-long_title_rendering_use_container_width_true[chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_title_test/st_altair_chart_title-long_title_rendering_use_container_width_true[firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_title_test/st_altair_chart_title-long_title_rendering_use_container_width_true[webkit].png
  e2e_playwright/st_altair_chart_test.py
  e2e_playwright/st_altair_chart_title.py
  e2e_playwright/st_altair_chart_title_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaElementPreprocessor.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaElementPreprocessor.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11553 [fix] Upgrade markdown dependencies
  .github/dependabot.yml
  NOTICES
  e2e_playwright/markdown_features_test.py
  frontend/lib/package.json
  frontend/lib/src/components/core/Layout/withCalculatedWidth.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/Heading.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/yarn.lock
Labels: security-assessment-completed, change:bugfix, impact:users

#11618 [Fix] Remove unused icon button code
  frontend/lib/src/components/shared/BaseButton/BaseButton.tsx
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#11622 [Fix] Utilize userEvent in Sidebar tests
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#11616 Attempt to fix some flakiness with radio and download button e2e tests
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_radio_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11632 [Fix] Reconcile chat & number input placeholder colors
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_after_clear[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_after_clear[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-long_placeholder_after_clear[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_300px[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_300px[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_300px[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-width_stretch[webkit].png
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11628 Add support for font faces from window preamble
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[chromium].png
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[firefox].png
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[webkit].png
  e2e_playwright/theming/theme_from_window.py
  e2e_playwright/theming/theme_from_window_test.py
  frontend/app/src/ThemedApp.tsx
  frontend/app/src/util/useThemeManager.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11612 Support pandas styler coloring for list and link column
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_text_color[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_text_color[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_text_color[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_text_color[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_text_color[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_text_color[light_theme-webkit].png
  e2e_playwright/st_dataframe_styler_support.py
  e2e_playwright/st_dataframe_styler_support_test.py
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11634 [Fix] Remove unused dialog style declaration
  frontend/app/src/components/StreamlitDialog/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10969 fix #10824 : allow text wrapping when there is no whitespace
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-wrap[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-wrap[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-wrap[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-wrap[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-wrap[light_theme-webkit].png
  e2e_playwright/st_code.py
  e2e_playwright/st_code_test.py
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/ExceptionElement/ExceptionElement.tsx
  frontend/lib/src/components/shared/ErrorElement/ErrorElement.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/__snapshots__/StreamlitMarkdown.test.tsx.snap
Labels: security-assessment-completed, change:bugfix, impact:users

#11646 Update `index.html` preload to variable font
  frontend/app/index.html
  frontend/app/src/FontPreload.test.tsx
Labels: security-assessment-completed, change:refactor, impact:users

#11635 Only store media data if in cached function
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11625 Fix the height of horizontal scrollbars in safari
  e2e_playwright/__snapshots__/linux/hello_app_test/hello_app-dataframe_demo_page[webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-error_long_code[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-success_long_code[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-no_wrap[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-numbers-no_wrap[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-long-single-word-string-no-wrap[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-auto_sized_columns[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-pinned_columns[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-after_unmounting[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_expanded[webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-raised_with_traceback[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-raised_with_traceback[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-with_markdown[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_exception_test/st_exception-with_markdown[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-fixed_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-stretch_width_explicit[webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-keep_bounds[webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-width_pixels[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-width_pixels[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-webkit].png
  frontend/lib/src/theme/globalStyles.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11505 [AdvancedLayouts] Adds a width parameter to st.html
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-file_path[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-file_path[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-file_str[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-file_str[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tags[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_300px[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_300px[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_300px[webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_content[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_content[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_content[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_content[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_content[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_content[webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-width_stretch[webkit].png
  e2e_playwright/st_html.py
  e2e_playwright/st_html_test.py
  lib/streamlit/elements/html.py
  lib/tests/streamlit/elements/html_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11655 Fix pandas deprecation warning in test
  lib/tests/streamlit/elements/arrow_dataframe_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#11657 Remove stretch height from public api
  e2e_playwright/st_form.py
  e2e_playwright/st_form_test.py
  lib/streamlit/elements/code.py
  lib/streamlit/elements/form.py
  lib/tests/streamlit/elements/code_test.py
  lib/tests/streamlit/form_test.py
Labels: security-assessment-completed, change:other, impact:users

#11395 Add config option to disable email prompt
  lib/streamlit/config.py
  lib/streamlit/runtime/credentials.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11648 Add more safeguards to prevent flakiness
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-webkit].png
  e2e_playwright/basic_app_test.py
  e2e_playwright/custom_components/component_errors_test.py
  e2e_playwright/forward_msg_cache_test.py
  e2e_playwright/host_config_test.py
  e2e_playwright/i18n_test.py
  e2e_playwright/mega_tester_app_test.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_altair_chart_test.py
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_chat_input_test.py
  e2e_playwright/st_dataframe_config_test.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_file_uploader_test.py
  e2e_playwright/st_image.py
  e2e_playwright/st_image_test.py
  e2e_playwright/st_sidebar_test.py
  e2e_playwright/st_text_input_test.py
  e2e_playwright/st_video_test.py
  e2e_playwright/theming/custom_theme_test.py
  e2e_playwright/theming/font_style_test.py
  e2e_playwright/theming/font_unicode_range_test.py
  e2e_playwright/theming/font_weight_test.py
  e2e_playwright/theming/sidebar_custom_theme_test.py
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme_test.py
  e2e_playwright/theming/theme_from_window_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11484 Update mypy to 1.16 and fix typing issues
  e2e_playwright/st_markdown.py
  lib/dev-requirements.txt
  lib/streamlit/dataframe_util.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/lib/color_util.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/state/session_state.py
Labels: security-assessment-completed, change:other, impact:internal

#11656 Docs for 1.46.0
  lib/streamlit/commands/navigation.py
  lib/streamlit/commands/page_config.py
  lib/streamlit/config.py
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/code.py
  lib/streamlit/elements/doc_string.py
  lib/streamlit/elements/exception.py
  lib/streamlit/elements/form.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/progress.py
  lib/streamlit/elements/spinner.py
  lib/streamlit/elements/text.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/runtime/context.py
  lib/streamlit/runtime/state/query_params_proxy.py
Labels: security-assessment-completed, impact:internal, change:docs

#11650 Generate copilot instructions from cursor rules
  .github/copilot-instructions.md
  .pre-commit-config.yaml
  scripts/check_license_headers.py
  scripts/generate_copilot_instructions.py
Labels: security-assessment-completed, change:other, impact:internal

#11664 `st.set_page_config`: enable sidebar/layout configs to be None
  e2e_playwright/st_set_page_config.py
  e2e_playwright/st_set_page_config_test.py
  frontend/app/src/App.tsx
  lib/streamlit/commands/page_config.py
  lib/tests/streamlit/commands/page_config_test.py
  proto/streamlit/proto/PageConfig.proto
Labels: security-assessment-completed, change:bugfix, impact:users

#11681 Update ruff to 0.12 and fix linting issues
  .pre-commit-config.yaml
  .ruff.toml
  e2e_playwright/shared/data_mocks.py
  lib/dev-requirements.txt
  lib/streamlit/components/types/base_custom_component.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/runtime/uploaded_file_manager.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/web/server/oidc_mixin.py
  lib/tests/streamlit/elements/data_editor_test.py
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, change:other, impact:internal

#11688 Support reruns specified in local flaky marker for `assert_snapshot`
  e2e_playwright/conftest.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11692 Fix runtime error with event based watcher
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/tests/streamlit/watcher/event_based_path_watcher_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11695 [perf] Remove react-device-detect dependency
  NOTICES
  frontend/app/package.json
  frontend/app/src/components/Navigation/SidebarNav.test.tsx
  frontend/app/src/components/Navigation/SidebarNav.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/lib/package.json
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.test.tsx
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/util/isMobile.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#11560 Add `linkUnderline` theming config option
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[chromium].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[firefox].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  e2e_playwright/theming/sidebar_custom_theme_test.py
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
  frontend/lib/src/mocks/mockTheme.ts
  frontend/lib/src/theme/emotionBaseTheme/index.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#11712 Fix wrong parameter in flaky decorator
  e2e_playwright/multipage_apps/mpa_basics_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11694 [perf] Reduce bundle size by not duplicating workspace packages
  .github/workflows/ensure-relative-imports.yml
  Makefile
  frontend/README.md
  frontend/app/package.json
  frontend/app/tsconfig.json
  frontend/app/vite.config.ts
  frontend/lib/tsconfig.json
  frontend/package.json
Labels: security-assessment-completed, impact:internal, change:refactor

#11696 Add `baseFontWeight` theming config option
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[chromium].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[firefox].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[webkit].png
  e2e_playwright/theming/theme_font_weights.py
  e2e_playwright/theming/theme_font_weights_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/theme/globalStyles.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#11727 Add `dataframeHeaderBackgroundColor` theming config option
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/theming/custom_theme_test.py
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
  frontend/lib/src/theme/getColors.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#11698 Support proxying requests to fetch custom component assets
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  lib/streamlit/components/types/base_custom_component.py
  lib/streamlit/components/v1/component_registry.py
  lib/streamlit/config.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/config_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#11756 Fixed timer bug
  frontend/lib/src/components/elements/Spinner/Spinner.test.tsx
  frontend/lib/src/components/elements/Spinner/Spinner.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11736 Update Makefile: punctuate lighthouse message correctly
  Makefile
Labels: security-assessment-completed, change:other, impact:internal

#11735 Add `codeFontWeight` theming config option
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[chromium].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[firefox].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[webkit].png
  e2e_playwright/theming/theme_font_weights_test.py
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  frontend/lib/src/components/elements/DocString/styled-components.ts
  frontend/lib/src/components/elements/Json/Json.tsx
  frontend/lib/src/components/shared/ErrorElement/styled-components.ts
  frontend/lib/src/theme/primitives/typography.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#11744 [AdvancedLayouts] Adds a height parameter to `st.metric`.
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-content_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-content_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-content_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-content_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-content_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-content_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-height_in_container[chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-height_in_container[firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-height_in_container[webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_height[chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_height[firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_height[webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-pixel_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_metric_test/st_metric-stretch_width[webkit].png
  e2e_playwright/st_metric.py
  e2e_playwright/st_metric_test.py
  frontend/lib/src/components/elements/Metric/styled-components.ts
  lib/streamlit/elements/metric.py
  lib/tests/streamlit/elements/metric_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11730 [AdvancedLayouts] Adds a width parameters to multiselect elements.
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_300px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_300px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_300px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_300px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_300px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_300px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_multiselect_test/st_multiselect-width_stretch[light_theme-webkit].png
  e2e_playwright/st_multiselect.py
  e2e_playwright/st_multiselect_test.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/tests/streamlit/elements/multiselect_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10091 Hide about dialog if not explicitly set
  e2e_playwright/main_menu_test.py
  e2e_playwright/st_set_page_config_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/lib/src/theme/primitives/spacing.ts
Labels: security-assessment-completed, change:feature, impact:users

#11732 [fix] Resolving some regressions introduced via top nav
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_collapsed[chromium-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_collapsed[firefox-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_collapsed[webkit-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_expanded[chromium-auto-viewport1-True-auto_desktop_expanded].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_expanded[firefox-auto-viewport1-True-auto_desktop_expanded].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_expanded[webkit-auto-viewport1-True-auto_desktop_expanded].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_responsive[chromium-auto-viewport_config2].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_responsive[firefox-auto-viewport_config2].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_desktop_responsive[webkit-auto-viewport_config2].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_collapsed[chromium-auto-viewport0-False-auto_mobile_collapsed].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_collapsed[firefox-auto-viewport0-False-auto_mobile_collapsed].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_collapsed[webkit-auto-viewport0-False-auto_mobile_collapsed].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_expanded[chromium-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_expanded[firefox-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_expanded[webkit-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_responsive[chromium-auto-viewport_config0].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_responsive[firefox-auto-viewport_config0].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_mobile_responsive[webkit-auto-viewport_config0].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_tablet_responsive[chromium-auto-viewport_config1].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_tablet_responsive[firefox-auto-viewport_config1].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_tablet_responsive[webkit-auto-viewport_config1].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_wide_responsive[chromium-auto-viewport_config3].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_wide_responsive[firefox-auto-viewport_config3].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-auto_wide_responsive[webkit-auto-viewport_config3].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-collapsed_desktop[chromium-collapsed-viewport3-False-collapsed_desktop].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-collapsed_desktop[firefox-collapsed-viewport3-False-collapsed_desktop].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-collapsed_desktop[webkit-collapsed-viewport3-False-collapsed_desktop].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-collapsed_mobile[chromium-collapsed-viewport2-False-collapsed_mobile].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-collapsed_mobile[firefox-collapsed-viewport2-False-collapsed_mobile].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-collapsed_mobile[webkit-collapsed-viewport2-False-collapsed_mobile].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_desktop_expanded[chromium-auto-viewport1-True-deploy_button_desktop_expanded].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_desktop_expanded[firefox-auto-viewport1-True-deploy_button_desktop_expanded].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_desktop_expanded[webkit-auto-viewport1-True-deploy_button_desktop_expanded].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_desktop_manually_collapsed[chromium-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_desktop_manually_collapsed[firefox-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_desktop_manually_collapsed[webkit-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_mobile_collapsed[chromium-auto-viewport0-False-deploy_button_mobile_collapsed].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_mobile_collapsed[firefox-auto-viewport0-False-deploy_button_mobile_collapsed].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-deploy_button_mobile_collapsed[webkit-auto-viewport0-False-deploy_button_mobile_collapsed].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-expanded_desktop[chromium-expanded-viewport5-True-expanded_desktop].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-expanded_desktop[firefox-expanded-viewport5-True-expanded_desktop].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-expanded_desktop[webkit-expanded-viewport5-True-expanded_desktop].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-expanded_mobile[chromium-expanded-viewport4-True-expanded_mobile].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-expanded_mobile[firefox-expanded-viewport4-True-expanded_mobile].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-expanded_mobile[webkit-expanded-viewport4-True-expanded_mobile].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-responsive_mobile_final[chromium-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-responsive_mobile_final[firefox-auto].png
  e2e_playwright/__snapshots__/linux/st_main_layout_test/st_main_layout-responsive_mobile_final[webkit-auto].png
  e2e_playwright/conftest.py
  e2e_playwright/st_main_layout.py
  e2e_playwright/st_main_layout_test.py
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/AppView/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11765 [fix] Ensure proper versions of node are being used in CI
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/js-tests.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#11723 Add `corepack enable` to makefile along with `corepack install`
  Makefile
Labels: security-assessment-completed, impact:internal, change:refactor

#11768 [fix] Attempt to stabilize some flaky e2e tests
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/st_number_input_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#11759 Make sure that no loading skeletons exist before running e2e tests
  e2e_playwright/conftest.py
  e2e_playwright/custom_components/component_errors_test.py
  e2e_playwright/st_components_v1.py
  e2e_playwright/st_components_v1_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11705 Add support for pandas styler font-weight in `st.dataframe`
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_styler_support_test/st_dataframe-styler_background_and_font[light_theme-webkit].png
  e2e_playwright/st_dataframe_styler_support.py
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  lib/streamlit/elements/arrow.py
Labels: security-assessment-completed, change:feature, impact:users

#11747 Apply font weight to dataframe
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[chromium].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[firefox].png
  e2e_playwright/__snapshots__/linux/theme_font_weights_test/custom_weights_app[webkit].png
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
Labels: security-assessment-completed, change:feature, impact:users

#11763 Add Markdown support to `st.dialog` title
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_long_title[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_long_title[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_long_title[webkit].png
  e2e_playwright/markdown_features.py
  e2e_playwright/markdown_features_test.py
  e2e_playwright/st_dialog.py
  e2e_playwright/st_dialog_test.py
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  frontend/lib/src/components/elements/Dialog/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  lib/streamlit/elements/dialog_decorator.py
Labels: security-assessment-completed, change:feature, impact:users

#11690 Add support for setting a display icon in `LinkColumn`
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-link_column[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  frontend/lib/src/components/shared/Icon/DynamicIcon.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/ChartColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ProgressColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/TextColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  lib/streamlit/elements/lib/column_types.py
Labels: security-assessment-completed, change:feature, impact:users

#11783 Release/1.46.1
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#11288 Add `bytes` formatting option to number and progress column
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-number_formatting[light_theme-webkit].png
  e2e_playwright/st_dataframe_config.py
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ProgressColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  lib/streamlit/elements/lib/column_types.py
Labels: security-assessment-completed, change:feature, impact:users

#11793 Type annotations for the `.clear()` method on cached functions
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_resource_api.py
  lib/tests/streamlit/typing/cache_types.py
Labels: security-assessment-completed, change:other, impact:users

#11672 Removing obsolete snapshots
  .github/workflows/snapshot-hygiene.yml
  e2e_playwright/__snapshots__/linux/mpa_basics_test/collapsed-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/collapsed-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-collapsed-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-collapsed-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/large-collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-collapsed-header-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-collapsed-header-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-collapsed-header-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-collapsed-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-collapsed-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_basics_test/small-collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/collapsed-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/collapsed-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/collapsed-logo[webkit].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-v2-collapsed-header-logo[chromium].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-v2-collapsed-header-logo[firefox].png
  e2e_playwright/__snapshots__/linux/mpa_v2_basics_test/mpa-v2-collapsed-header-logo[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_collapsed[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-fullscreen_expanded[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-stretch_height[chromium].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-stretch_height[firefox].png
  e2e_playwright/__snapshots__/linux/st_form_test/st_form-stretch_height[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_collapsed[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_collapsed[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_expanded[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-fullscreen_expanded[webkit].png
  scripts/snapshot_cleanup.py
Labels: security-assessment-completed, change:other, impact:internal

#11734 Add `chartCategoricalColors` theming config option
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors[chromium].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors[firefox].png
  e2e_playwright/__snapshots__/linux/theme_categorical_test/custom_categorical_colors[webkit].png
  e2e_playwright/theming/theme_categorical.py
  e2e_playwright/theming/theme_categorical_test.py
  e2e_playwright/theming/theme_chart_app.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  frontend/lib/src/components/elements/PlotlyChart/CustomTheme.tsx
  frontend/lib/src/theme/getColors.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users
