Repository streamlit/streamlit, pull requests merged in 2025-10, with the labels that each got.

#12627 [feat] Add protofiles for CCv2
  proto/streamlit/proto/ArrowData.proto
  proto/streamlit/proto/BidiComponent.proto
  proto/streamlit/proto/Element.proto
  proto/streamlit/proto/WidgetStates.proto
Labels: security-assessment-completed, impact:internal, change:feature

#12704 Ignore flaky e2e color picker test for firefox
  e2e_playwright/st_color_picker_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12679 [test] Add e2e test for `st.audio_input` timer display
  e2e_playwright/st_audio_input_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12680 Custom Dark Theme - add light/dark section configurations for `theme` & `theme.sidebar`
  lib/streamlit/config.py
  lib/streamlit/config_util.py
  lib/streamlit/errors.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/config_util_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#12706 Refactor `st.pills` e2e test
  e2e_playwright/st_pills_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12710 Refactor `st.feedback` e2e test
  e2e_playwright/st_feedback.py
  e2e_playwright/st_feedback_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12652 Patching WT_SESSION so that Credentails test does not fail on Windows…
  lib/tests/streamlit/runtime/credentials_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12713 Refactor `st.chat_input` e2e test
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_chat_input.py
  e2e_playwright/st_chat_input_test.py
Labels: security-assessment-completed, impact:internal, change:refactor
