Repository streamlit/streamlit, pull requests merged in 2025-09, with the labels that each got.

#12393 Make git utilities more robust
  lib/streamlit/git_util.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/git_util_test.py
  lib/tests/streamlit/web/bootstrap_test.py
Labels: security-assessment-completed, change:refactor, impact:users

#12371 Refactor `st.number_input` e2e test
  e2e_playwright/st_number_input_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12372 Use `key` as main identity for `st.checkbox` & `st.toggle`
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-dynamic_updated[webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_toggle_test/st_toggle-dynamic_updated[webkit].png
  e2e_playwright/st_checkbox.py
  e2e_playwright/st_checkbox_test.py
  e2e_playwright/st_toggle.py
  e2e_playwright/st_toggle_test.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/tests/streamlit/elements/checkbox_test.py
Labels: security-assessment-completed, change:breaking, change:feature, impact:users

#12405 Add theme background color config options
  e2e_playwright/__snapshots__/linux/custom_background_colors_test/custom_background_colors_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_background_colors_test/custom_background_colors_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_background_colors_test/custom_background_colors_app[webkit].png
  e2e_playwright/__snapshots__/linux/custom_main_colors_test/custom_main_colors_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_main_colors_test/custom_main_colors_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_main_colors_test/custom_main_colors_app[webkit].png
  e2e_playwright/theming/custom_background_colors.py
  e2e_playwright/theming/custom_background_colors_test.py
  e2e_playwright/theming/custom_main_colors_test.py
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#12436 Attempt to fix some e2e test flakiness
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-altair_chart_cut_off_legend_title_none[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-altair_chart_cut_off_legend_title_none[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_bar_chart_streamlit_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_bar_chart_streamlit_theme[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_bar_chart_streamlit_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_bar_chart_streamlit_theme[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-tooltip_styling[chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-vconcat_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-vconcat_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_download_button_test/st_download_button-dynamic_updated[firefox].png
  e2e_playwright/main_menu_test.py
  e2e_playwright/st_altair_chart.py
  e2e_playwright/st_altair_chart_test.py
  e2e_playwright/st_button.py
  e2e_playwright/st_chat_input_test.py
  e2e_playwright/st_dataframe_dimensions_test.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_download_button.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_file_uploader_test.py
  e2e_playwright/st_layouts_container_various_elements_test.py
  e2e_playwright/st_plotly_chart_select_test.py
  e2e_playwright/st_pyplot_test.py
  e2e_playwright/st_radio_test.py
  e2e_playwright/st_video_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12437 Use `key` as main identity for `st.number_input`
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_updated[webkit].png
  e2e_playwright/st_number_input.py
  e2e_playwright/st_number_input_test.py
  lib/streamlit/elements/widgets/number_input.py
  lib/tests/streamlit/elements/number_input_test.py
Labels: security-assessment-completed, change:breaking, change:feature, impact:users

#12441 Attempt to fix some e2e test flakiness - part 2
  e2e_playwright/main_menu_test.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/st_chat_input_test.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_file_uploader_test.py
  e2e_playwright/st_layouts_container_various_elements_test.py
  e2e_playwright/st_text_input_test.py
  e2e_playwright/st_video_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12397 Use `key` as main identity for `st.text_area` & `st.text_input`
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-dynamic_updated[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-dynamic_updated[webkit].png
  e2e_playwright/st_text_area.py
  e2e_playwright/st_text_area_test.py
  e2e_playwright/st_text_input.py
  e2e_playwright/st_text_input_test.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/tests/streamlit/elements/text_area_test.py
  lib/tests/streamlit/elements/text_input_test.py
Labels: security-assessment-completed, change:breaking, change:feature, impact:users

#12463 Attempt to fix WebcamCompont unit test flakiness
  frontend/lib/src/components/widgets/CameraInput/WebcamComponent.test.tsx
Labels: security-assessment-completed, change:other, impact:internal

#12464 Use `key` as main identity for `st.time_input` & `st.date_input`
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-dynamic_updated[webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-dynamic_initial[chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-dynamic_initial[webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-dynamic_updated[firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-dynamic_updated[webkit].png
  e2e_playwright/st_date_input.py
  e2e_playwright/st_date_input_test.py
  e2e_playwright/st_time_input.py
  e2e_playwright/st_time_input_test.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/elements/date_input_test.py
  lib/tests/streamlit/elements/time_input_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12466 Refactor the `st.slider` e2e test
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_slider.py
  e2e_playwright/st_slider_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#12450 Attempt to reduce e2e flakiness - part 3
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-altair_chart_cut_off_legend_title_none[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-altair_chart_cut_off_legend_title_none[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-altair_chart_cut_off_legend_title_none[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-altair_chart_cut_off_legend_title_none[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-grouped_layered_line_chart_streamlit_theme[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-vconcat_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-vconcat_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-vconcat_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_altair_chart_test/st_altair_chart-vconcat_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_initial[firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_updated[chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-dynamic_updated[firefox].png
  e2e_playwright/st_altair_chart.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_altair_chart_test.py
  e2e_playwright/st_chat_input_test.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_form_test.py
  e2e_playwright/st_layouts_container_various_elements_test.py
  e2e_playwright/st_number_input_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12482 [chore] Prefer optional chain
  .cursor/rules/typescript.mdc
  .github/instructions/typescript.instructions.md
  frontend/AGENTS.md
  frontend/app/src/App.tsx
  frontend/app/src/components/Navigation/SidebarNav.tsx
  frontend/app/src/components/StreamlitDialog/themeUtils.ts
  frontend/connection/src/ForwardMessageCache.ts
  frontend/eslint.config.mjs
  frontend/lib/src/AppNode.ts
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/utils.ts
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/BokehChart/BokehChart.test.tsx
  frontend/lib/src/components/elements/BokehChart/BokehChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/dataframes/arrowFormatUtils.ts
  frontend/lib/src/dataframes/pandasStylerUtils.ts
  frontend/lib/src/theme/utils.ts
  frontend/lib/src/util/uploadFiles.ts
Labels: security-assessment-completed, impact:internal, change:chore

#12508 [feat] Add Release Tag and PR Creation workflow
  .github/workflows/release-branch-creation.yml
  .github/workflows/release-tag-and-pr-creation.yml
  scripts/slack_notifications.py
Labels: security-assessment-completed, impact:internal, change:feature

#12529 [fix] MediaStream track cleanup on error
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
Labels: security-assessment-completed, change:other, impact:internal

#12535 [chore] Updating material icons
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, change:chore, impact:users

#12538 Add support for new ruff rules
  .ruff.toml
  e2e_playwright/hostframe_app_test.py
  lib/tests/streamlit/commands/execution_control_test.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/config_option_test.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/date_input_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/elements/radio_test.py
  lib/tests/streamlit/elements/slider_test.py
  lib/tests/streamlit/elements/text_area_test.py
  lib/tests/streamlit/elements/text_input_test.py
  lib/tests/streamlit/elements/time_input_test.py
  lib/tests/streamlit/git_util_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/websocket_session_manager_test.py
  lib/tests/streamlit/source_util_test.py
Labels: security-assessment-completed, change:other, impact:internal

#12509 [feat] Add Patch Release Branch Creation workflow
  .github/workflows/patch-release-branch-creation.yml
Labels: security-assessment-completed, impact:internal, change:feature

#12543 [fix] Suppress type checker warning in data_editor._parse_value
  lib/streamlit/elements/widgets/data_editor.py
Labels: security-assessment-completed, impact:internal, change:chore

#11911 Fix vega chart unrecognized dataset error
  e2e_playwright/__snapshots__/linux/st_scatter_chart_test/st_scatter_chart-add_rows_preserves_styling[chromium].png
  e2e_playwright/__snapshots__/linux/st_scatter_chart_test/st_scatter_chart-add_rows_preserves_styling[firefox].png
  e2e_playwright/__snapshots__/linux/st_scatter_chart_test/st_scatter_chart-add_rows_preserves_styling[webkit].png
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#12517 [AdvancedLayouts] Add width to `st.vega_lite_chart`
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_400px[chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_400px[firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_400px[webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_content[chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_content[firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_content[webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_charts_dimensions_test/st_vega_charts_dimensions-width_stretch[webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-2[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-2[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-2[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-2[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-3[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-3[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-3[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-3[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-4[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-4[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-4[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-4[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-6[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-7[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-8[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_10[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_6[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_6[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_6[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_6[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_7[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_7[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_7[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_7[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-theming_9[light_theme-firefox].png
  e2e_playwright/shared/vega_utils.py
  e2e_playwright/st_vega_charts_dimensions.py
  e2e_playwright/st_vega_charts_dimensions_test.py
  e2e_playwright/st_vega_lite_chart.py
  e2e_playwright/st_vega_lite_chart_test.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12565 [fix] Prevent the snapshot hygiene workflow from spamming comments
  .github/workflows/snapshot-hygiene.yml
Labels: security-assessment-completed, impact:internal, change:chore

#12562 Add `codeTextColor` config & update `linkColor`
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_fonts_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_fonts_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_fonts_app[webkit].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[chromium].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[firefox].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[chromium].png
  e2e_playwright/__snapshots__/linux/snowflake_dark_theme_test/snowflake_dark_theme[firefox].png
  e2e_playwright/__snapshots__/linux/snowflake_light_theme_test/snowflake_light_theme[chromium].png
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[chromium].png
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[firefox].png
  e2e_playwright/__snapshots__/linux/theme_from_window_test/theme_from_window_variable[webkit].png
  e2e_playwright/theming/custom_theme_test.py
  e2e_playwright/theming/sidebar_custom_theme_test.py
  e2e_playwright/theming/theme_tester_app.py
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#12534 Tweak and optimize agent rules
  .cursor/rules/e2e_playwright.mdc
  .cursor/rules/overview.mdc
  .cursor/rules/protobuf.mdc
  .cursor/rules/python.mdc
  .cursor/rules/python_lib.mdc
  .cursor/rules/python_tests.mdc
  .cursor/rules/typescript.mdc
  .github/copilot-instructions.md
  .github/instructions/e2e_playwright.instructions.md
  .github/instructions/protobuf.instructions.md
  .github/instructions/python.instructions.md
  .github/instructions/python_lib.instructions.md
  .github/instructions/python_tests.instructions.md
  .github/instructions/typescript.instructions.md
  .gitignore
  AGENTS.md
  e2e_playwright/AGENTS.md
  frontend/AGENTS.md
  lib/AGENTS.md
  lib/streamlit/AGENTS.md
  lib/tests/AGENTS.md
  proto/streamlit/proto/AGENTS.md
Labels: security-assessment-completed, change:other, impact:internal

#12540 [test] Remove problematic 5000ms wait in the e2e's st_audio_input stop_recording
  e2e_playwright/st_audio_input_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#12598 Add `type` argument to `st.popover` to match `st.button`
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-primary[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-primary[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-primary[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-primary[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-primary[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-primary[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-tertiary[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-tertiary[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-tertiary[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-tertiary[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-tertiary[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_popover_test/st_popover-tertiary[light_theme-webkit].png
  e2e_playwright/st_popover.py
  e2e_playwright/st_popover_test.py
  frontend/lib/src/components/elements/Popover/Popover.tsx
  lib/streamlit/elements/layouts.py
  proto/streamlit/proto/Block.proto
Labels: security-assessment-completed, change:feature, impact:users

#12542 [test] Simplify `st.audio_input` test suite
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-error_state[chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-error_state[firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-hidden_label[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-hidden_label[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-hidden_label[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-hidden_label[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-hidden_label[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-hidden_label[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-no_permission[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-no_permission[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[light_theme-webkit].png
  e2e_playwright/st_audio_input_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#12608 [AdvancedLayouts] Add width to st.altair_chart
  e2e_playwright/st_altair_chart.py
  e2e_playwright/st_altair_chart_basic_select.py
  e2e_playwright/st_altair_chart_title.py
  e2e_playwright/st_vega_charts_width.py
  e2e_playwright/st_vega_charts_width_test.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12544 [chore] Add stop hook for Claude Code quality checks
  .claude/settings.json
  .claude/stop_hook.py
Labels: security-assessment-completed, impact:internal, change:chore

#12572 Reusable Custom Themes via `theme.base` config
  e2e_playwright/__snapshots__/linux/custom_url_base_test/custom_theme_with_url_base[chromium].png
  e2e_playwright/__snapshots__/linux/custom_url_base_test/custom_theme_with_url_base[firefox].png
  e2e_playwright/__snapshots__/linux/custom_url_base_test/custom_theme_with_url_base[webkit].png
  e2e_playwright/theming/custom_url_base.py
  e2e_playwright/theming/custom_url_base_test.py
  lib/streamlit/config.py
  lib/streamlit/config_util.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/config_util_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12599 Make `streamlit run` with no args mean `streamlit run streamlit_app.py`
  lib/streamlit/web/cli.py
  lib/tests/streamlit/web/cli_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12578 Allow st.feedback to have a default initial value (#9469) -> #9658
  e2e_playwright/st_feedback.py
  e2e_playwright/st_feedback_test.py
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/elements/button_group_test.py
Labels: security-assessment-completed, change:feature, impact:users, autofix, status:product-approved

#12630 [AdvancedLayouts] Add height to st.altair_chart
  e2e_playwright/st_vega_charts_height.py
  e2e_playwright/st_vega_charts_height_test.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12643 [chore] Set up Cursor Commands gitignore like we have for Rules
  .cursor/.gitignore
Labels: security-assessment-completed, impact:internal, change:chore

#12613 [AdvancedLayouts] Modernize height parameter for st.pydeck_chart
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_50px[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_50px[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_default[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_default[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_stretch[webkit].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_stretch_outside_container[chromium].png
  e2e_playwright/__snapshots__/linux/st_pydeck_chart_test/st_pydeck_chart-height_stretch_outside_container[webkit].png
  e2e_playwright/hello_app_test.py
  e2e_playwright/st_pydeck_chart.py
  e2e_playwright/st_pydeck_chart_test.py
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/styled-components.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/types.ts
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/pydeck_test.py
  proto/streamlit/proto/DeckGlJsonChart.proto
Labels: security-assessment-completed, change:feature, impact:users

#12665 [fix] Fixing Claude Code stop hook
  .claude/stop_hook.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#12667 [feat] Add Python Parameterize Test Cursor Command
  .cursor/.gitignore
  .cursor/commands/py-parameterize-test.md
Labels: security-assessment-completed, impact:internal, change:feature

#12648 Settings menu updates
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_theme_settings_dialog[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_theme_settings_dialog[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_fonts_test/custom_theme_settings_dialog[webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/edit_active_theme_dialog[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/main_menu_test/settings_dialog[light_theme-webkit].png
  e2e_playwright/main_menu_test.py
  e2e_playwright/theming/custom_theme_fonts_test.py
  frontend/app/src/App.tsx
  frontend/app/src/components/StreamlitContextProvider.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/app/src/components/StreamlitDialog/styled-components.ts
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/test_util.tsx
  frontend/lib/src/theme/themeConfigs.ts
Labels: security-assessment-completed, change:refactor, impact:users

#12658 [AdvancedLayouts] Update width and height on st.map
  e2e_playwright/st_map.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/map.py
  lib/tests/streamlit/elements/map_test.py
Labels: security-assessment-completed, change:feature, impact:users

#12659 [AdvancedLayouts] Modernize width/height parameters for st.scatter_chart
  e2e_playwright/st_scatter_chart.py
  e2e_playwright/st_vega_charts_height.py
  e2e_playwright/st_vega_charts_height_test.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:feature, impact:users
