Repository streamlit/streamlit, pull requests merged in 2025-05, with the labels that each got.

#11220 Add logging if an error happened during auth flow
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/streamlit/web/server/oauth_authlib_routes.py
Labels: security-assessment-completed, impact:internal, change:chore

#11233 [AdvancedLayouts] Adds a width parameter to st.slider, st.select_slider
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_300px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_300px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_300px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_300px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_300px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_300px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_select_slider_test/st_select_slider-width_stretch[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_300px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_300px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_300px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_300px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_300px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_300px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_slider_test/st_slider-width_stretch[light_theme-webkit].png
  e2e_playwright/st_select_slider.py
  e2e_playwright/st_select_slider_test.py
  e2e_playwright/st_slider.py
  e2e_playwright/st_slider_test.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/slider.py
  lib/tests/streamlit/elements/select_slider_test.py
  lib/tests/streamlit/elements/slider_test.py
  proto/streamlit/proto/Slider.proto
Labels: security-assessment-completed, change:feature, impact:users

#11246 [AdvancedLayouts] Adds a width parameter to st.camera_input and st.file_uploader
  e2e_playwright/__snapshots__/linux/st_camera_input_test/st_camera_input-width_300px[chromium].png
  e2e_playwright/__snapshots__/linux/st_camera_input_test/st_camera_input-width_300px[firefox].png
  e2e_playwright/__snapshots__/linux/st_camera_input_test/st_camera_input-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_camera_input_test/st_camera_input-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-width_300px[chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-width_300px[firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-width_300px[webkit].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-width_stretch[webkit].png
  e2e_playwright/st_camera_input.py
  e2e_playwright/st_camera_input_test.py
  e2e_playwright/st_file_uploader.py
  e2e_playwright/st_file_uploader_test.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/tests/streamlit/elements/camera_input_test.py
  lib/tests/streamlit/elements/file_uploader_test.py
  proto/streamlit/proto/CameraInput.proto
  proto/streamlit/proto/FileUploader.proto
Labels: security-assessment-completed, change:feature, impact:users

#11255 [AdvancedLayouts] Adds a width parameter to st.text_input and st.text_area
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_200px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_200px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_200px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_200px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_200px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_200px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_area_test/st_text_area-width_stretch[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_200px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_200px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_200px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_200px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_200px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_200px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_text_input_test/st_text_input-width_stretch[light_theme-webkit].png
  e2e_playwright/st_text_area.py
  e2e_playwright/st_text_area_test.py
  e2e_playwright/st_text_input.py
  e2e_playwright/st_text_input_test.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/tests/streamlit/elements/text_area_test.py
  lib/tests/streamlit/elements/text_input_test.py
  proto/streamlit/proto/TextArea.proto
  proto/streamlit/proto/TextInput.proto
Labels: security-assessment-completed, change:feature, impact:users

#11257 [AdvancedLayouts] Adds a width parameter to st.number_input and st.selectbox
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_200px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_200px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_200px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_200px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_200px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_200px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_number_input_test/st_number_input-width_stretch[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_200px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_200px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_200px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_200px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_200px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_200px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_selectbox_test/st_selectbox-width_stretch[light_theme-webkit].png
  e2e_playwright/st_number_input.py
  e2e_playwright/st_number_input_test.py
  e2e_playwright/st_selectbox.py
  e2e_playwright/st_selectbox_test.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  proto/streamlit/proto/NumberInput.proto
  proto/streamlit/proto/Selectbox.proto
Labels: security-assessment-completed, change:feature, impact:users

#11229 Activate ruff-specific linting rules
  .pre-commit-config.yaml
  .ruff.toml
  e2e_playwright/markdown_features_test.py
  e2e_playwright/st_map.py
  e2e_playwright/st_pydeck_chart.py
  lib/dev-requirements.txt
  lib/streamlit/column_config.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/components/v1/components.py
  lib/streamlit/connections/__init__.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/json.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/progress.py
  lib/streamlit/runtime/__init__.py
  lib/streamlit/runtime/caching/__init__.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/connection_factory.py
  lib/streamlit/runtime/credentials.py
  lib/streamlit/runtime/scriptrunner/__init__.py
  lib/streamlit/runtime/secrets.py
  lib/streamlit/runtime/state/__init__.py
  lib/streamlit/web/bootstrap.py
  lib/streamlit/web/server/__init__.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/delta_generator_singletons_test.py
  lib/tests/streamlit/elements/alert_test.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
  lib/tests/streamlit/elements/lib/subtitle_utils_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/state/query_params_test.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  scripts/run_bare_execution_tests.py
  scripts/update_material_icon_font_and_names.py
Labels: security-assessment-completed, change:other, impact:internal

#11258 Ensure script lifecycle occurs for MPAv1 use case
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/multipage_apps/pages/12_page12.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/st_segmented_control_test.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11261 Ensure filename extension check is normalized
  lib/streamlit/elements/lib/file_uploader_utils.py
  lib/tests/streamlit/file_uploader_utils_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11260 [AdvancedLayouts] Adds a width parameter to st.date_input and st.time_input
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_200px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_200px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_200px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_200px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_200px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_200px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-width_stretch[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_200px[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_200px[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_200px[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_200px[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_200px[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_200px[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_stretch[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_stretch[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_stretch[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_stretch[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_stretch[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-width_stretch[light_theme-webkit].png
  e2e_playwright/st_date_input.py
  e2e_playwright/st_date_input_test.py
  e2e_playwright/st_time_input.py
  e2e_playwright/st_time_input_test.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/elements/date_input_test.py
  lib/tests/streamlit/elements/time_input_test.py
  proto/streamlit/proto/DateInput.proto
  proto/streamlit/proto/TimeInput.proto
Labels: security-assessment-completed, change:feature, impact:users

#11282 Activate rules to prevent exception handling anti-patterns
  .ruff.toml
  lib/streamlit/connections/base_connection.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/elements/lib/js_number.py
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/storage/cache_storage_protocol.py
  lib/streamlit/runtime/credentials.py
  lib/streamlit/runtime/fragment.py
  lib/streamlit/runtime/metrics_util.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/web/bootstrap.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/streamlit/web/server/component_request_handler.py
  lib/streamlit/web/server/media_file_handler.py
  lib/streamlit/web/server/oauth_authlib_routes.py
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/streamlit/web/server/websocket_headers.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/web/bootstrap_test.py
  lib/tests/streamlit/web/server/server_test.py
  scripts/update_version.py
Labels: security-assessment-completed, change:other, impact:internal

#11271 Enforce a maximum line length via ruff
  .devcontainer/devcontainer.json
  .ruff.toml
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-long_label[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-long_label[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-long_label[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-long_label[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-long_label[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_checkbox_test/st_checkbox-long_label[light_theme-webkit].png
  e2e_playwright/host_config_test.py
  e2e_playwright/hostframe_app_test.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_both_query_params_error_test.py
  e2e_playwright/st_checkbox.py
  e2e_playwright/st_columns.py
  e2e_playwright/st_data_editor_config.py
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_image_test.py
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  e2e_playwright/st_multiselect.py
  e2e_playwright/st_pydeck_chart_select_test.py
  e2e_playwright/st_segmented_control.py
  e2e_playwright/st_set_page_config_test.py
  e2e_playwright/st_slider.py
  e2e_playwright/st_text.py
  e2e_playwright/st_toast.py
  e2e_playwright/st_toast_test.py
  e2e_playwright/st_toggle.py
  e2e_playwright/theming/snowflake_dark_theme_test.py
  e2e_playwright/theming/snowflake_light_theme_test.py
  lib/streamlit/__init__.py
  lib/streamlit/column_config.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/commands/logo.py
  lib/streamlit/connections/snowflake_connection.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/exception.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/lib/dialog.py
  lib/streamlit/elements/media.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/runtime_util.py
  lib/streamlit/runtime/secrets.py
  lib/streamlit/string_util.py
  lib/streamlit/web/cli.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/elements/layouts_test.py
  scripts/slack_notifications.py
  scripts/update_material_icon_font_and_names.py
Labels: security-assessment-completed, change:other, impact:internal

#11272 Allow nesting expander, columns, popover and chat_message
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-18[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-18[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-18[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-18[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-18[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_message_test/st_chat_message-18[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-nested[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-nested[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-nested[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-nested[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-nested[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-nested[light_theme-webkit].png
  e2e_playwright/st_chat_message.py
  e2e_playwright/st_chat_message_test.py
  e2e_playwright/st_columns.py
  e2e_playwright/st_columns_test.py
  e2e_playwright/st_expander.py
  e2e_playwright/st_expander_nested.py
  e2e_playwright/st_expander_nested_test.py
  e2e_playwright/st_expander_test.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/layouts.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/chat_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10942 Fix #10475: Warn when modifying elements inside fragment callback
  lib/streamlit/delta_generator.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/streamlit/runtime/state/session_state.py
  lib/tests/streamlit/runtime/state/session_state_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11290 Add logging if cookie content is too large
  lib/streamlit/web/server/oauth_authlib_routes.py
Labels: security-assessment-completed, change:chore, impact:users

#11307 Allow the ability to add case sensitive options to select and multiselect
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.test.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11278 Move `formsData` to new `FormsContext`
  frontend/app/src/components/StreamlitContextProvider.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/lib/src/components/core/Block/Block.test.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/FormsContext.tsx
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/elements/PageLink/PageLink.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/test_util.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#11306 Handle visual glitch for duplicated options
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10071 Scroll long latex formulas horizontally
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_badge-examples[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-latex[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long-help[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-long[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_latex-sympy[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-many_elements_in_one_block[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[chromium].png
  e2e_playwright/__snapshots__/linux/st_markdown_test/st_markdown-with_large_image[firefox].png
  e2e_playwright/st_markdown.py
  e2e_playwright/st_markdown_test.py
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11284 [refactor] Activate @typescript-eslint/no-shadow eslint rule
  frontend/.eslintrc.js
  frontend/app/src/App.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/util/useThemeManager.ts
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaLiteSelections.ts
  frontend/lib/src/components/elements/Audio/Audio.tsx
  frontend/lib/src/components/elements/BokehChart/BokehChart.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/elements/DocString/DocString.test.tsx
  frontend/lib/src/components/elements/Video/Video.tsx
  frontend/lib/src/components/shared/Dropdown/Selectbox.test.tsx
  frontend/lib/src/components/shared/InputInstructions/InputInstructions.test.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/DataFrame/EditingState.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataExporter.ts
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/hooks/useScrollAnimation.ts
  frontend/lib/src/theme/utils.ts
  frontend/lib/src/util/performance/fns.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11310 [refactor] Activate no-prototype-builtins eslint rule
  frontend/.eslintrc.js
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentRegistry.ts
  frontend/lib/src/components/widgets/CustomComponent/componentUtils.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11302 Add safeguard for cached messages cleanup
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11285 [refactor] Activate import/no-named-as-default-member eslint rule
  frontend/.eslintrc.js
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/StreamlitDialog/SettingsDialog.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/connection/src/DefaultStreamlitEndpoints.test.ts
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/FormsContext.tsx
  frontend/lib/src/components/core/IsDialogContext.ts
  frontend/lib/src/components/core/IsSidebarContext.ts
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/core/Portal/PortalContext.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/DeckGlJsonChart.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/components/elements/Expander/Expander.tsx
  frontend/lib/src/components/elements/Json/Json.tsx
  frontend/lib/src/components/elements/PageLink/PageLink.tsx
  frontend/lib/src/components/elements/Popover/Popover.tsx
  frontend/lib/src/components/elements/Spinner/Spinner.tsx
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/shared/ErrorBoundary/ErrorBoundary.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/Heading.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/Tooltip/OverflowTooltip.tsx
  frontend/lib/src/components/widgets/AudioInput/AudioInput.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/createFileUploadHandler.ts
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/Tooltip.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/cells/JsonViewer.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnFormatting.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnPinning.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnReordering.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnSizer.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnSort.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnVisibility.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomRenderer.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataExporter.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useRowHover.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useSelectionHandler.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTableSizer.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useTooltips.ts
  frontend/lib/src/components/widgets/DataFrame/menus/ColumnMenu.tsx
  frontend/lib/src/components/widgets/DownloadButton/DownloadButton.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/lib/src/components/widgets/Slider/Slider.tsx
  frontend/lib/src/hooks/useDownloadUrl.ts
  frontend/lib/src/util/utils.ts
  frontend/lib/src/util/withTimezones.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10882 Add mega tester app to e2e tests to check for console and CSP errors
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/mega_tester_app.py
  e2e_playwright/mega_tester_app_test.py
  e2e_playwright/test_assets/flower.webm
  e2e_playwright/test_assets/hostframe.html
  e2e_playwright/test_assets/streamlit-logo-small.png
  e2e_playwright/test_assets/streamlit-logo.png
  frontend/hostframe.html
Labels: security-assessment-completed, change:other, impact:internal

#11311 Fix typos in multiple files
  e2e_playwright/st_expander_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/widgets/BaseWidget/WidgetLabel.tsx
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/styled-components.ts
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/NumberInput/styled-components.ts
  frontend/lib/src/hooks/useScrollToBottom.ts
  frontend/lib/src/hooks/useUpdateUiValue.test.ts
  frontend/lib/src/util/utils.test.ts
  lib/streamlit/commands/execution_control.py
  lib/streamlit/commands/navigation.py
  lib/streamlit/delta_generator_singletons.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/code.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/metric.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/git_util.py
  lib/streamlit/runtime/connection_factory.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/streamlit/vendor/pympler/asizeof.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/elements/exception_test.py
  lib/tests/streamlit/elements/json_test.py
  lib/tests/streamlit/elements/lib/options_selector_utils_test.py
  lib/tests/streamlit/external/langchain/capturing_callback_handler.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  lib/tests/streamlit/streamlit_test.py
  proto/streamlit/proto/DataFrame.proto
  proto/streamlit/proto/NamedDataSet.proto
Labels: security-assessment-completed, impact:internal, change:chore

#11286 Remove `set_page_config` restrictions
  e2e_playwright/st_set_page_config.py
  e2e_playwright/st_set_page_config_test.py
  frontend/app/src/App.tsx
  lib/streamlit/commands/page_config.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/tests/streamlit/commands/page_config_test.py
  lib/tests/streamlit/runtime/scriptrunner_utils/script_run_context_test.py
  proto/streamlit/proto/PageConfig.proto
Labels: security-assessment-completed, change:feature, impact:users

#11318 Reduce flaky test: text_input_limits
  e2e_playwright/st_text_input_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10488 Modernize pathlib watcher
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  lib/streamlit/watcher/polling_path_watcher.py
Labels: security-assessment-completed, impact:internal, change:chore

#11297 [Fix]: Update `st.column_config` "localized" option
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-localized_date_and_number_formatting[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-localized_date_and_number_formatting[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_config_test/st_dataframe-localized_date_and_number_formatting[webkit].png
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_dataframe_config_test.py
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11321 [AdvancedLayouts] Adds st.column(gap="none")
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_none[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_none[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-column_gap_none[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-nested_one_level[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-nested_one_level[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_center[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[chromium].png
  e2e_playwright/st_columns.py
  e2e_playwright/st_columns_test.py
  frontend/lib/src/components/core/Block/styled-components.ts
  lib/streamlit/elements/layouts.py
  lib/streamlit/errors.py
  lib/tests/streamlit/elements/layouts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11263 [AdvancedLayouts] Adds a width parameter to st.video and st.audio
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-width_300px[chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-width_300px[webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_test/st_audio-width_stretch[webkit].png
  e2e_playwright/__snapshots__/linux/st_video_test/st_video-width_400px[chromium].png
  e2e_playwright/__snapshots__/linux/st_video_test/st_video-width_400px[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/st_video-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_video_test/st_video-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_video_test/video_element_webm_with_subtitles[chromium].png
  e2e_playwright/conftest.py
  e2e_playwright/st_audio.py
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_video.py
  e2e_playwright/st_video_test.py
  lib/streamlit/elements/media.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/elements/media_test.py
  proto/streamlit/proto/Audio.proto
  proto/streamlit/proto/Video.proto
Labels: security-assessment-completed, change:feature, impact:users

#11334 [refactor] Upgrade eslint-plugin-react-hooks to v6 RC
  .github/dependabot.yml
  frontend/.eslintrc.js
  frontend/app/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#11336 [refactor] Upgrade React Testing Library to 16.3.0
  .github/dependabot.yml
  frontend/app/package.json
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#11335 [refactor] Upgrade to TypeScript 5.8.3
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  frontend/app/src/App.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/connection/src/DefaultStreamlitEndpoints.test.ts
  frontend/lib/src/util/utils.test.ts
  frontend/typescript-config/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#11347 Activate rules to prevent return statement anti-patterns
  .ruff.toml
  e2e_playwright/shared/animation_utils.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/shared/dataframe_utils.py
  lib/streamlit/commands/execution_control.py
  lib/streamlit/elements/heading.py
  lib/streamlit/elements/html.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/lib/options_selector_utils.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/lib/subtitle_utils.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/toast.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/navigation/page.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py
  lib/streamlit/runtime/context.py
  lib/streamlit/runtime/media_file_manager.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/testing/v1/element_tree.py
  lib/streamlit/testing/v1/local_script_runner.py
  lib/streamlit/url_util.py
  lib/tests/streamlit/elements/doc_string_test.py
  lib/tests/streamlit/elements/map_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/test_data/cached_widget_replay.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
  lib/tests/streamlit/web/server/server_test_case.py
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, change:other, impact:internal

#11362 [refactor] Improve rendering perf of StreamlitMarkdown
  frontend/lib/src/components/shared/StreamlitMarkdown/Heading.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#11295 Update mypy version and fix typing issues
  lib/dev-requirements.txt
  lib/streamlit/connections/sql_connection.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/slider.py
  lib/tests/streamlit/elements/number_input_test.py
  lib/tests/streamlit/typing/number_input_types.py
  lib/tests/streamlit/typing/slider_types.py
Labels: security-assessment-completed, change:other, impact:internal

#11374 Optimize mypy typing setup
  .devcontainer/devcontainer.json
  e2e_playwright/st_altair_chart.py
  e2e_playwright/st_pills.py
  e2e_playwright/st_pyplot.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/string_util.py
  mypy.ini
Labels: security-assessment-completed, change:other, impact:internal

#11366 Nicer handling of connection errors
  frontend/app/src/App.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/constants.ts
  frontend/app/src/components/StreamlitDialog/index.ts
  frontend/connection/src/ConnectionManager.ts
  frontend/connection/src/DoInitPings.tsx
  frontend/connection/src/WebsocketConnection.test.tsx
  frontend/connection/src/constants.ts
Labels: security-assessment-completed, change:refactor, impact:users

#11378 Allow backend URLs to be configurable via window variables
  frontend/app/src/App.tsx
  frontend/connection/src/DefaultStreamlitEndpoints.test.ts
  frontend/connection/src/DoInitPings.tsx
  frontend/connection/src/WebsocketConnection.test.tsx
  frontend/connection/src/types.ts
  frontend/connection/src/utils.test.ts
  frontend/connection/src/utils.ts
  frontend/lib/src/util/utils.ts
  frontend/utils/src/uri/index.test.ts
  frontend/utils/src/uri/index.ts
Labels: security-assessment-completed, impact:internal, change:feature

#11405 Tweak VS Code devcontainer settings
  .devcontainer/devcontainer.json
Labels: security-assessment-completed, change:other, impact:internal

#11404 Remove empty pipfile
  .gitignore
  lib/Pipfile
Labels: security-assessment-completed, impact:internal, change:refactor

#11403 Remove custom constraint setup
  .github/workflows/nightly.yml
  .github/workflows/python-tests.yml
  .github/workflows/release.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#11363 [Fix] `st.dataframe`: clear row selections on dropdown sort
  e2e_playwright/st_dataframe_selections.py
  e2e_playwright/st_dataframe_selections_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11428 [refactor] Update no-unused-vars eslint rule to be stricter
  frontend/.eslintrc.js
  frontend/app/src/App.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/connection/src/DefaultStreamlitEndpoints.ts
  frontend/connection/src/testUtils.ts
  frontend/lib/src/WidgetStateManager.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/colors.test.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/hooks/useBasicWidgetState.ts
  frontend/lib/src/mocks/mocks.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11425 Update PR template with screenshot
  .github/pull_request_template.md
Labels: security-assessment-completed, impact:internal, change:chore

#11427 `font` -> `family` in theme.fontFaces docs
  lib/streamlit/config.py
Labels: security-assessment-completed, impact:internal, change:docs

#11377 Add a new config option to configure a CORS allowlist
  lib/streamlit/config.py
  lib/streamlit/web/server/__init__.py
  lib/streamlit/web/server/component_request_handler.py
  lib/streamlit/web/server/media_file_handler.py
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server_util.py
  lib/streamlit/web/server/stats_request_handler.py
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/web/server/component_request_handler_test.py
  lib/tests/streamlit/web/server/media_file_handler_test.py
  lib/tests/streamlit/web/server/routes_test.py
  lib/tests/streamlit/web/server/server_util_test.py
  lib/tests/streamlit/web/server/upload_file_request_handler_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11443 [fix] RTL eslint rule scoping
  frontend/.eslintrc.js
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#11444 [fix] Flakiness in WebsocketConnection tests
  frontend/connection/src/WebsocketConnection.test.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#11440 Exclude tornado 6.5.0 version
  lib/setup.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11414 [Fix] Add rows preserves styling properties
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-add_rows_preserves_styling[chromium].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-add_rows_preserves_styling[firefox].png
  e2e_playwright/__snapshots__/linux/st_area_chart_test/st_area_chart-add_rows_preserves_styling[webkit].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-add_rows_preserves_styling[chromium].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-add_rows_preserves_styling[firefox].png
  e2e_playwright/__snapshots__/linux/st_bar_chart_test/st_bar_chart-add_rows_preserves_styling[webkit].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-add_rows_preserves_styling[chromium].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-add_rows_preserves_styling[firefox].png
  e2e_playwright/__snapshots__/linux/st_line_chart_test/st_line_chart-add_rows_preserves_styling[webkit].png
  e2e_playwright/__snapshots__/linux/st_scatter_chart_test/st_scatter_chart-add_rows_preserves_styling[chromium].png
  e2e_playwright/__snapshots__/linux/st_scatter_chart_test/st_scatter_chart-add_rows_preserves_styling[firefox].png
  e2e_playwright/__snapshots__/linux/st_scatter_chart_test/st_scatter_chart-add_rows_preserves_styling[webkit].png
  e2e_playwright/st_area_chart.py
  e2e_playwright/st_area_chart_test.py
  e2e_playwright/st_bar_chart.py
  e2e_playwright/st_bar_chart_test.py
  e2e_playwright/st_line_chart.py
  e2e_playwright/st_line_chart_test.py
  e2e_playwright/st_scatter_chart.py
  e2e_playwright/st_scatter_chart_test.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/vega_charts.py
  lib/tests/streamlit/elements/vega_charts_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11455 Prevent formatted strings in logging statements
  .ruff.toml
  lib/streamlit/config.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/storage/local_disk_cache_storage.py
  lib/streamlit/runtime/runtime_util.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/streamlit/web/server/oauth_authlib_routes.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#11460 Enforce max line length in unit tests
  .ruff.toml
  lib/tests/streamlit/commands/page_config_test.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/connections/base_connection_test.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/audio_test.py
  lib/tests/streamlit/elements/help_test.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/elements/link_button_test.py
  lib/tests/streamlit/elements/metric_test.py
  lib/tests/streamlit/elements/plotly_chart_test.py
  lib/tests/streamlit/elements/vega_charts_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
  lib/tests/streamlit/runtime/caching/storage/local_disk_cache_storage_test.py
  lib/tests/streamlit/runtime/fragment_test.py
  lib/tests/streamlit/runtime/media_file_manager_test.py
  lib/tests/streamlit/runtime/secrets_test.py
  lib/tests/streamlit/toast_test.py
  lib/tests/streamlit/web/server/server_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#11448 Fix crash when editing df index with data editor
  lib/streamlit/elements/widgets/data_editor.py
  lib/tests/streamlit/elements/data_editor_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11462 Serve manifest.json from static asset handler
  .github/workflows/pr-preview.yml
  Makefile
  frontend/app/vite.config.ts
Labels: security-assessment-completed, change:feature, impact:users

#11445 [AdvancedLayouts] Adds a width parameter to st.tabs and st.expander
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-fixed_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-fixed_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-fixed_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-fixed_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-fixed_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-fixed_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-stretch_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-stretch_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-stretch_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-stretch_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-stretch_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_expander_test/st_expander-stretch_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-fixed_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-fixed_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-fixed_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-fixed_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-fixed_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_tabs_test/st_tabs-fixed_width[light_theme-webkit].png
  e2e_playwright/st_chat_message_test.py
  e2e_playwright/st_expander.py
  e2e_playwright/st_expander_test.py
  e2e_playwright/st_tabs.py
  e2e_playwright/st_tabs_test.py
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/elements/Expander/styled-components.ts
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  frontend/lib/src/components/elements/Tabs/styled-components.ts
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/layout_utils.py
  lib/tests/streamlit/elements/layouts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11472 [refactor] Upgrade vite and swc deps
  .github/dependabot.yml
  frontend/app/package.json
  frontend/lib/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#11473 [refactor] Upgrade Prettier to v3
  .cursor/rules/typescript.mdc
  .github/dependabot.yml
  frontend/.prettierrc
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.test.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/colors.test.ts
  frontend/lib/src/components/elements/DeckGlJsonChart/utils/colors.ts
  frontend/lib/src/components/elements/Video/Video.test.tsx
  frontend/lib/src/components/shared/Tooltip/useTooltipMeasurementSideEffect.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/EditingState.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/hooks/useBasicWidgetState.ts
  frontend/lib/src/hooks/useCalculatedWidth.ts
  frontend/lib/src/hooks/useScrollSpy.ts
  frontend/lib/src/theme/utils.ts
  frontend/lib/src/util/utils.ts
  frontend/utils/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#11466 [AdvancedLayouts] Adds a width parameter to st.status
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-fixed_pixel_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-fixed_pixel_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-fixed_pixel_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-fixed_pixel_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-fixed_pixel_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-fixed_pixel_width[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-stretch_width[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-stretch_width[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-stretch_width[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-stretch_width[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-stretch_width[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_status_test/st_status-stretch_width[light_theme-webkit].png
  e2e_playwright/st_status.py
  e2e_playwright/st_status_test.py
  lib/streamlit/elements/layouts.py
  lib/streamlit/elements/lib/mutable_status_container.py
  lib/tests/streamlit/elements/layouts_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11464 Add `buttonRadius` theming config option
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[chromium].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[firefox].png
  e2e_playwright/__snapshots__/linux/sidebar_custom_theme_test/sidebar_custom_theme[webkit].png
  e2e_playwright/theming/custom_theme_test.py
  e2e_playwright/theming/sidebar_custom_theme_test.py
  frontend/lib/src/components/elements/LinkButton/styled-components.ts
  frontend/lib/src/components/elements/PageLink/styled-components.ts
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/theme/primitives/radii.ts
  frontend/lib/src/theme/utils.test.ts
  frontend/lib/src/theme/utils.ts
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, change:feature, impact:users

#11487 Pin mypy to 1.15 to resolve CI issue
  lib/dev-requirements.txt
Labels: security-assessment-completed, change:other, impact:internal

#11481 Rename backend base url window variables to use __streamlit object
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/connection/src/DoInitPings.tsx
  frontend/connection/src/WebsocketConnection.test.tsx
  frontend/connection/src/types.ts
  frontend/connection/src/utils.test.ts
  frontend/connection/src/utils.ts
  frontend/lib/src/theme/utils.ts
  frontend/utils/src/types/index.ts
Labels: security-assessment-completed, change:feature, impact:users
