Repository streamlit/streamlit, pull requests merged in 2025-04, with the labels that each got.

#10989 Add permissions to python tests workflow in release
  .github/workflows/release.yml
Labels: security-assessment-completed, impact:internal, change:bugfix

#10981 [Fix] Nightly build permissions
  .github/workflows/nightly.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#10985 Optimize `st.write` usage with single string arg
  lib/streamlit/elements/write.py
  lib/tests/streamlit/write_test.py
Labels: security-assessment-completed, change:feature, impact:users

#9562 Refactor forward message cache
  Makefile
  e2e_playwright/forward_msg_cache.py
  e2e_playwright/forward_msg_cache_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/connection/src/ConnectionManager.ts
  frontend/connection/src/DefaultStreamlitEndpoints.test.ts
  frontend/connection/src/DefaultStreamlitEndpoints.ts
  frontend/connection/src/ForwardMessageCache.test.ts
  frontend/connection/src/ForwardMessageCache.ts
  frontend/connection/src/WebsocketConnection.test.tsx
  frontend/connection/src/WebsocketConnection.tsx
  frontend/connection/src/testUtils.ts
  frontend/connection/src/types.ts
  frontend/lib/src/FileUploadClient.test.ts
  frontend/lib/src/StreamlitEndpoints.ts
  frontend/lib/src/mocks/mocks.ts
  lib/streamlit/commands/execution_control.py
  lib/streamlit/config.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/forward_msg_queue.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/runtime_util.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/scriptrunner_utils/script_requests.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/tests/streamlit/commands/execution_control_test.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/message_mocks.py
  lib/tests/streamlit/runtime/forward_msg_cache_test.py
  lib/tests/streamlit/runtime/runtime_test.py
  lib/tests/streamlit/runtime/runtime_util_test.py
  lib/tests/streamlit/runtime/scriptrunner_utils/script_run_context_test.py
  lib/tests/streamlit/web/server/routes_test.py
  proto/streamlit/proto/ClientState.proto
  proto/streamlit/proto/ForwardMsg.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#10196 Tweak arrow handling to allow more type flexibility
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/dataframes/arrowFormatUtils.test.ts
  frontend/lib/src/dataframes/arrowFormatUtils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11003 Remove unused global variable
  lib/streamlit/web/server/routes.py
Labels: security-assessment-completed, change:other, impact:internal

#11004 Include context_test.py to run when call `make pytest`
  lib/tests/streamlit/runtime/context_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#11007 Use github token for downloading develop coverage
  .github/workflows/python-tests.yml
  lib/tests/streamlit/runtime/caching/hashing_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11009 Exclude dot files and __init__.py from pages
  e2e_playwright/multipage_apps/pages/.dotfile.py
  e2e_playwright/multipage_apps/pages/__init__.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10996 [Fix]: Button hover color overwrites colored text
  e2e_playwright/st_button.py
  e2e_playwright/st_button_test.py
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10977 Release/1.44.1
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/protobuf/package.json
  frontend/typescript-config/package.json
  frontend/utils/package.json
  lib/setup.py
Labels: security-assessment-completed, change:chore, impact:users

#11016 Fix vite dev server proxy to work with multi page apps
  frontend/app/vite.config.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10651 Add `ip_address` to `st.context`
  lib/streamlit/runtime/context.py
  lib/tests/streamlit/runtime/context_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10990 [theming] Fix radio button visual for different `baseFontSize`
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-callback_help[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-callback_help[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-captions[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-captions[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-captions[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-captions[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-collapsed_label[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-collapsed_label[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-collapsed_label[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-dataframe_options[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-dataframe_options[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-default[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-default[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-disabled[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-disabled[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-disabled[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-empty_selection[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-empty_selection[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-formatted_options[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-formatted_options[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-hidden_label[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-hidden_label[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-hidden_label[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-horizontal[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-horizontal[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-horizontal_captions[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-horizontal_captions[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-markdown_label[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-markdown_label[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-markdown_options[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-markdown_options[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-markdown_options[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-markdown_options[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-no_options[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-no_options[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-no_options[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_radio_test/st_radio-no_options[light_theme-firefox].png
  frontend/lib/src/components/shared/Radio/Radio.tsx
  frontend/lib/src/theme/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10994 [feat] Add frontend Cursor Rules
  .cursor/.gitignore
  .cursor/rules/typescript.mdc
  .cursor/rules/typescript_tests.mdc
  scripts/check_license_headers.py
Labels: security-assessment-completed, impact:internal, change:feature

#10857 Allow auto-reload of config on exceptions
  lib/streamlit/config.py
  lib/tests/streamlit/config_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11027 Add python-related cursor rules
  .cursor/.gitignore
  .cursor/rules/protobuf.mdc
  .cursor/rules/python.mdc
  .cursor/rules/python_lib.mdc
  .cursor/rules/python_tests.mdc
  .cursor/rules/typescript.mdc
  .cursor/rules/typescript_tests.mdc
  lib/tests/streamlit/typing/readme.md
Labels: security-assessment-completed, change:other, impact:internal

#11026 Activate additional pre-commit rules
  .pre-commit-config.yaml
  .ruff.toml
  NOTICES
  frontend/.yarn/patches/@protobufjs-inquire-npm-1.1.0-3c7759e9ce.patch
  frontend/app/src/assets/img/Open-Iconic.LICENSE
  lib/conda-recipe/LICENSE
  lib/dev-requirements.txt
  lib/tests/streamlit/elements/html_test.py
  lib/tests/streamlit/elements/support_files/__init__.py
  lib/tests/streamlit/elements/test_html.js
  lib/tests/streamlit/runtime/scriptrunner_utils/__init__.py
  proto/streamlit/proto/Arrow.proto
  proto/streamlit/proto/AudioInput.proto
  proto/streamlit/proto/CameraInput.proto
  proto/streamlit/proto/Image.proto
  proto/streamlit/proto/PageLink.proto
Labels: security-assessment-completed, change:other, impact:internal

#11028 Update blinker min version and protobuf max version
  lib/min-constraints-gen.txt
  lib/setup.py
Labels: security-assessment-completed, impact:internal, change:chore

#11015 [fix] st.fragment interaction with st.{balloons,snow}
  e2e_playwright/shared/animation_utils.py
  e2e_playwright/st_effects_with_fragment_interactions.py
  e2e_playwright/st_effects_with_fragment_interactions_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11022 Remove deprecated `pkg_resources` usage
  scripts/get_min_versions.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10962 Revamp mypy typing checks - part 1
  e2e_playwright/custom_components/component_errors.py
  e2e_playwright/custom_components/popular_components.py
  e2e_playwright/shared/app_utils.py
  e2e_playwright/shared/data_mocks.py
  e2e_playwright/st_data_editor_input_data.py
  e2e_playwright/st_dataframe_input_data_test.py
  e2e_playwright/st_dataframe_interactions_test.py
  lib/mypy.ini
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/event_utils.py
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/write.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed, dev:full-matrix, impact:internal, change:refactor

#11039 Fix precommit CI issue
  lib/mypy.ini
Labels: security-assessment-completed, impact:internal, change:bugfix

#11034 [theming] replace danger and success colors in non-notif components
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-error[chromium].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-error[firefox].png
  e2e_playwright/__snapshots__/linux/st_file_uploader_test/st_file_uploader-error[webkit].png
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.tsx
  frontend/lib/src/components/widgets/FileUploader/styled-components.ts
Labels: security-assessment-completed, change:chore, impact:users

#10764 [Fix] FE validation for `st.date_input`
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_date_input_error[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_date_input_error[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_date_input_error[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_date_input_error[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_date_input_error[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-range_date_input_error[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-single_date_error[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-single_date_error[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-single_date_error[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-single_date_error[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-single_date_error[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_date_input_test/st_date_input-single_date_error[light_theme-webkit].png
  e2e_playwright/st_date_input_test.py
  frontend/lib/src/components/shared/Tooltip/Tooltip.test.tsx
  frontend/lib/src/components/shared/Tooltip/Tooltip.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.test.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#10653 [chore] Opt in to React StrictMode
  frontend/app/src/index.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#11054 Add automated PR comment for frontend coverage
  .github/workflows/js-tests.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: security-assessment-completed, change:other, impact:internal

#11056 [docs] correct toast position
  lib/streamlit/elements/toast.py
Labels: security-assessment-completed, impact:users, change:docs

#11017 Clean up the makefile - part 1
  .github/workflows/cli-regression.yml
  .github/workflows/ensure-relative-imports.yml
  .github/workflows/playwright-custom-components.yml
  .github/workflows/static-deploy.yml
  Makefile
  scripts/cli_regression_tests.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10979 [Fix] Refactor `st.html` for style tags
  .pre-commit-config.yaml
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-file_str[chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-file_str[firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_html_test/st_html-style_tag_spacing[light_theme-webkit].png
  e2e_playwright/st_html.py
  e2e_playwright/st_html_test.py
  e2e_playwright/test_assets/test.css
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/elements/Html/Html.test.tsx
  frontend/lib/src/components/elements/Html/Html.tsx
  lib/streamlit/elements/html.py
  lib/tests/streamlit/elements/html_test.py
  lib/tests/streamlit/elements/test_html.css
  scripts/check_license_headers.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11055 Add `is_embedded` to st.context
  e2e_playwright/hostframe_app.py
  e2e_playwright/hostframe_app_test.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  lib/streamlit/runtime/context.py
  proto/streamlit/proto/ClientState.proto
Labels: security-assessment-completed, change:feature, impact:users

#11079 Update material icons
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/st_alert.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, impact:internal, change:chore

#11078 Activate pylint warnings linting rules via ruff
  .ruff.toml
  e2e_playwright/conftest.py
  lib/streamlit/config.py
  lib/streamlit/config_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/deprecation_util.py
  lib/streamlit/elements/lib/dicttools.py
  lib/streamlit/elements/lib/policies.py
  lib/streamlit/elements/write.py
  lib/streamlit/logger.py
  lib/streamlit/net_util.py
  lib/streamlit/runtime/metrics_util.py
  lib/streamlit/runtime/runtime_util.py
  lib/streamlit/runtime/state/session_state_proxy.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/streamlit/web/server/server_util.py
  scripts/cli_regression_tests.py
  scripts/cli_smoke_tests.py
  scripts/update_e2e_snapshots.py
  scripts/update_name.py
  scripts/update_version.py
Labels: security-assessment-completed, change:other, impact:internal

#10975 Add devcontainer configuration
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  Makefile
Labels: security-assessment-completed, change:other, impact:internal

#11084 Add cursor rules for e2e playwright tests
  .cursor/.gitignore
  .cursor/rules/e2e_playwright.mdc
Labels: security-assessment-completed, change:other, impact:internal

#11105 Remove st.experimental_audio_input
  e2e_playwright/st_experimental_audio_input.py
  e2e_playwright/st_experimental_audio_input_test.py
  lib/streamlit/__init__.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/tests/streamlit/element_mocks.py
  lib/tests/streamlit/elements/audio_input_test.py
  lib/tests/streamlit/runtime/caching/cache_data_api_test.py
  lib/tests/streamlit/runtime/caching/cache_resource_api_test.py
Labels: security-assessment-completed, change:chore, impact:users

#11098 BugFix 11097: Update FontFaceDeclaration to support customizable font styles
  e2e_playwright/__snapshots__/linux/font_style_test/font_style-font_styles[chromium].png
  e2e_playwright/__snapshots__/linux/font_style_test/font_style-font_styles[firefox].png
  e2e_playwright/__snapshots__/linux/font_style_test/font_style-font_styles[webkit].png
  e2e_playwright/theming/font_style.py
  e2e_playwright/theming/font_style_test.py
  e2e_playwright/theming/static/NotoSans-Italics_only_letters_and_numbers.woff2
  e2e_playwright/theming/static/NotoSans-only_letters_and_numbers.woff2
  frontend/app/src/components/FontFaceDeclaration/FontFaceDeclaration.tsx
Labels: feature:config, security-assessment-completed, change:bugfix, impact:users

#11096 Fix various typos
  e2e_playwright/widget_state_test.py
  lib/streamlit/deprecation_util.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/cache_errors.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed, impact:internal, change:chore

#11095 Deexperimentalization of st.user
  e2e_playwright/auth.py
  e2e_playwright/st_write_objects.py
  lib/streamlit/__init__.py
  lib/streamlit/type_util.py
  lib/streamlit/user_info.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/user_info_test.py
Labels: security-assessment-completed, change:chore, impact:users

#11043 Fix: Handle Multi-Part Extensions Like .tar.gz in File Upload Validation
  lib/streamlit/elements/lib/file_uploader_utils.py
  lib/tests/streamlit/file_uploader_utils_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11119 Update workflows to support packageManager in package.json
  .github/actions/make_init/action.yml
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/enforce-pre-commit.yml
  .github/workflows/js-tests.yml
Labels: security-assessment-completed, impact:internal, change:refactor

#11063 BugFix 11062: Sidebar resizing
  e2e_playwright/st_sidebar_test.py
  frontend/app/src/components/Sidebar/Sidebar.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11118 [Fix] `st.audio_input` actions styling
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-default[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-label_visibility_disabled[light_theme-webkit].png
  e2e_playwright/st_audio_input_test.py
  frontend/lib/src/components/widgets/AudioInput/AudioInputActionButtons.test.tsx
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
Labels: security-assessment-completed, change:chore, impact:users

#11116 [Fix] `st.camera_input` disabled button styling
  e2e_playwright/st_camera_input_test.py
  frontend/lib/src/components/widgets/CameraInput/CameraInputButton.test.tsx
  frontend/lib/src/components/widgets/CameraInput/styled-components.ts
Labels: security-assessment-completed, change:chore, impact:users

#11066 Refactor Streamlit Contexts
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Header/Header.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/app/src/components/Sidebar/SidebarNavLink.test.tsx
  frontend/app/src/components/Sidebar/SidebarNavLink.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.tsx
  frontend/app/src/components/StreamlitContextProvider.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/lib/src/index.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11124 When the page fails to load or returns a non-200 status, print some debugging messages.
  e2e_playwright/conftest.py
Labels: security-assessment-completed, change:other, impact:internal

#11127 Reduce flaky potential of st_columns_test by adding expects checks before asserting the snapshots.
  e2e_playwright/st_columns_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11129 Reduce flakiness of st_radio_test by adding an expect before clicking.
  e2e_playwright/st_radio_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11130 Reduce flaky potential of st_button_test
  e2e_playwright/st_button_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11121 Introduce stableRandomMachineId to metrics by resurrecting old machine_id_v2 code
  frontend/app/src/App.test.tsx
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/util/AppNavigation.test.ts
  frontend/lib/src/SessionInfo.test.ts
  frontend/lib/src/SessionInfo.ts
  frontend/lib/src/mocks/mocks.ts
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  proto/streamlit/proto/MetricsEvent.proto
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#11128 Unpin nwsapi
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#11131 [chore] Ensure all 3rd party libraries have types
  .github/workflows/js-tests.yml
  Makefile
  component-lib/package.json
  component-lib/yarn.lock
  frontend/app/package.json
  frontend/connection/package.json
  frontend/lib/package.json
  frontend/protobuf/package.json
  frontend/utils/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#11125 Refactor `AppContext` values
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Header/Header.test.tsx
  frontend/app/src/components/Header/Header.tsx
  frontend/app/src/components/Header/styled-components.ts
  frontend/app/src/components/Sidebar/SidebarNavLink.test.tsx
  frontend/app/src/components/StreamlitContextProvider.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#11132 [chore] Add noImplicitOverride for enhanced type safety
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.test.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/withMapboxToken/withMapboxToken.tsx
  frontend/lib/src/components/shared/ErrorBoundary/ErrorBoundary.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.tsx
  frontend/typescript-config/base.tsconfig.json
Labels: security-assessment-completed, impact:internal, change:chore

#11134 [chore] Update caniuse-lite
  component-lib/yarn.lock
  frontend/yarn.lock
Labels: security-assessment-completed, change:chore, impact:users

#11135 [Fix] Element toolbar papercuts
  e2e_playwright/__snapshots__/linux/host_config_test/host_config-dataframe_disabled_fullscreen_mode[chromium].png
  e2e_playwright/__snapshots__/linux/host_config_test/host_config-dataframe_disabled_fullscreen_mode[firefox].png
  e2e_playwright/__snapshots__/linux/host_config_test/host_config-dataframe_disabled_fullscreen_mode[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-row_deletion_toolbar[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_data_editor-toolbar[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_visibility_menu[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_visibility_menu[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-toolbar_hover_search[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-default[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-in_sidebar[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-shows_full_dataframe_toolbar[webkit].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_inline_error[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_dialog_test/st_dialog-with_large_width[webkit].png
  frontend/lib/src/components/elements/Dialog/Dialog.tsx
  frontend/lib/src/components/shared/Modal/Modal.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.test.tsx
  frontend/lib/src/components/shared/Toolbar/Toolbar.tsx
  frontend/lib/src/components/shared/Toolbar/styled-components.ts
Labels: security-assessment-completed, change:chore, impact:users

#11113 Preserve context_info fields on rerun triggered by `st.rerun`
  e2e_playwright/st_context.py
  e2e_playwright/st_context_test.py
  lib/streamlit/commands/execution_control.py
  lib/tests/streamlit/commands/execution_control_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#11081 [Refactor] [AdvancedLayouts] Simplify width styling on VerticalBlock
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_radio_test.py
  frontend/lib/src/components/core/Block/Block.test.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/Block/StyledElementContainerLayoutWrapper.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
  frontend/lib/src/components/core/Layout/useLayoutStyles.test.tsx
  frontend/lib/src/components/core/Layout/useLayoutStyles.ts
  frontend/lib/src/components/core/Layout/withCalculatedWidth.test.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.test.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/elements/ImageList/ImageList.test.tsx
  frontend/lib/src/components/elements/Video/Video.test.tsx
  frontend/lib/src/components/shared/FullScreenWrapper/withFullScreenWrapper.test.tsx
  frontend/lib/src/components/widgets/CameraInput/CameraInput.test.tsx
  frontend/lib/src/components/widgets/ChatInput/ChatInput.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.test.tsx
  frontend/lib/src/components/widgets/FileUploader/FileUploader.test.tsx
  frontend/lib/src/components/widgets/NumberInput/NumberInput.test.tsx
  frontend/lib/src/components/widgets/Slider/Slider.test.tsx
  frontend/lib/src/components/widgets/TextArea/TextArea.test.tsx
  frontend/lib/src/components/widgets/TextInput/TextInput.test.tsx
  frontend/lib/src/hooks/useCalculatedWidth.test.ts
  frontend/lib/src/hooks/useResizeObserver.test.tsx
  frontend/lib/src/hooks/useResizeObserver.ts
  frontend/lib/src/hooks/useScrollToBottom.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#11138 Rename stable_random_machine_id to machine_id_v4 / installation_id_v4
  frontend/app/src/App.test.tsx
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/util/AppNavigation.test.ts
  frontend/lib/src/SessionInfo.test.ts
  frontend/lib/src/SessionInfo.ts
  frontend/lib/src/mocks/mocks.ts
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/metrics_util.py
  lib/tests/streamlit/proto_compatibility_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  proto/streamlit/proto/MetricsEvent.proto
  proto/streamlit/proto/NewSession.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#11137 Refactor `AppView` props
  frontend/app/src/App.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/app/src/components/Sidebar/SidebarNavLink.test.tsx
  frontend/app/src/components/Sidebar/ThemedSidebar.test.tsx
  frontend/app/src/components/StreamlitContextProvider.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#11107 st.context.url improvement for multipage app
  e2e_playwright/hostframe_app_test.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics.py
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  e2e_playwright/st_context_test.py
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
  lib/streamlit/runtime/context.py
  lib/streamlit/runtime/context_util.py
  lib/tests/streamlit/runtime/context_test.py
  lib/tests/streamlit/runtime/context_util_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#11100 BugFix 11064: st.dataframe({}) shouldn't show errors
  e2e_playwright/st_dataframe_input_data_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#11146 `EventContainer` & toast cleanup
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/EventContainer/EventContainer.test.tsx
  frontend/app/src/components/EventContainer/EventContainer.tsx
  frontend/lib/src/components/elements/Toast/Toast.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#11162 Add isWebdriver to metrics.
  e2e_playwright/basic_app_test.py
  frontend/app/src/MetricsManager.test.ts
  frontend/app/src/MetricsManager.ts
  proto/streamlit/proto/MetricsEvent.proto
Labels: security-assessment-completed, impact:internal, change:refactor

#11148 Refactor `AppView` props - Part 2
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/StreamlitContextProvider.tsx
  frontend/lib/src/components/core/Block/Block.test.tsx
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.test.tsx
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/core/Block/utils.ts
  frontend/lib/src/components/core/LibContext.tsx
  frontend/lib/src/components/elements/Balloons/Balloons.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.test.tsx
  frontend/lib/src/components/elements/Particles/Particles.tsx
  frontend/lib/src/components/elements/Tabs/Tabs.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/Form/Form.test.tsx
  frontend/lib/src/components/widgets/Form/Form.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.test.tsx
  frontend/lib/src/components/widgets/Form/FormSubmitButton.tsx
  frontend/lib/src/hooks/useWidgetManagerElementState.test.tsx
  frontend/lib/src/test_util.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#11089 Clarify file creation instruction in Quickstart section of README.md
  README.md
Labels: security-assessment-completed, impact:users, change:docs

#11171 Remove anchor along with query params from the url
  frontend/lib/src/util/utils.test.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, change:chore, impact:users

#11172 Docstrings for st.context
  lib/streamlit/runtime/context.py
Labels: security-assessment-completed, impact:internal, change:docs

#11149 Update the frontend packages to refer to `eslint-plugin-streamlit-custom` via the workspace protocol
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:chore

#11188 Reduce flaky potential of `test st_form_test`
  e2e_playwright/st_form_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11189 Reduce flaky potential of `st_sidebar_test`
  e2e_playwright/st_sidebar_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11152 Fix content alignment for dataframe columns
  frontend/lib/src/components/widgets/DataFrame/columns/ChartColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/CheckboxColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/DateTimeColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ImageColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/JsonColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/LinkColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ListColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ObjectColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/ProgressColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/TextColumn.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#11184 Activate additional ruff linting rules
  .ruff.toml
  e2e_playwright/theming/__init__.py
Labels: security-assessment-completed, change:other, impact:internal

#11185 Activate perf linting rules via ruff
  .ruff.toml
  lib/streamlit/commands/navigation.py
  lib/streamlit/config_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/secrets.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/watcher/util.py
  lib/streamlit/web/server/upload_file_request_handler.py
Labels: security-assessment-completed, change:other, impact:internal

#11193 Docstrings for 1.45.0
  lib/streamlit/elements/alert.py
  lib/streamlit/elements/exception.py
  lib/streamlit/elements/html.py
  lib/streamlit/elements/iframe.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/user_info.py
Labels: security-assessment-completed, impact:internal, change:docs

#11191 Move min constraints to script folder to allow automated dependency updates
  .github/dependabot.yml
  .github/workflows/python-tests.yml
  .pre-commit-config.yaml
  Makefile
  scripts/assets/license-template.txt
  scripts/assets/min-constraints-gen.txt
  scripts/check_license_headers.py
Labels: security-assessment-completed, change:other, impact:internal

#11201 Always test with all supported Python versions
  .github/actions/build_info/action.yml
  .github/scripts/build_info.py
  .github/workflows/python-tests.yml
Labels: security-assessment-completed, change:other, impact:internal

#11209 Activate pep8 naming linting rules
  .ruff.toml
  e2e_playwright/multipage_apps/mpa_configure_sidebar.py
  e2e_playwright/st_color_picker_test.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/st_pyplot.py
  e2e_playwright/st_session_state_test.py
  lib/streamlit/elements/doc_string.py
  lib/streamlit/elements/lib/column_types.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/hello/dataframe_demo.py
  lib/streamlit/navigation/page.py
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/tests/streamlit/elements/image_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11210 Activate ruff linting rule to prevent commented-out code
  .ruff.toml
  e2e_playwright/hello_app_test.py
  e2e_playwright/shared/data_mocks.py
  e2e_playwright/st_altair_chart_basic_select_test.py
  e2e_playwright/st_audio_test.py
  e2e_playwright/st_data_editor_index_types.py
  e2e_playwright/st_dataframe_config.py
  e2e_playwright/st_image_test.py
  e2e_playwright/st_pyplot_test.py
  lib/streamlit/config.py
  lib/streamlit/elements/doc_string.py
  lib/streamlit/elements/lib/built_in_chart_utils.py
  lib/streamlit/elements/lib/column_config_utils.py
  lib/streamlit/elements/lib/pandas_styler_utils.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/git_util.py
  lib/streamlit/runtime/forward_msg_queue.py
  lib/streamlit/runtime/scriptrunner/magic.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/type_util.py
  lib/streamlit/web/bootstrap.py
  lib/streamlit/web/cli.py
  lib/tests/streamlit/components_test.py
  lib/tests/streamlit/elements/layouts_test.py
  lib/tests/streamlit/logger_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/caching/cache_errors_test.py
  lib/tests/streamlit/runtime/caching/common_cache_test.py
  lib/tests/streamlit/runtime/caching/hashing_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/typing/number_input_types.py
  lib/tests/streamlit/typing/slider_types.py
Labels: security-assessment-completed, change:other, impact:internal

#11211 Activate unused arguments linting rules in ruff
  .ruff.toml
  e2e_playwright/auth_test.py
  e2e_playwright/multipage_apps/mpa_configure_sidebar_test.py
  e2e_playwright/st_chat_input_test.py
  e2e_playwright/st_dataframe_styler_support.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_download_button_test.py
  e2e_playwright/websocket_disconnect_test.py
  lib/streamlit/auth_util.py
  lib/streamlit/components/v1/custom_component.py
  lib/streamlit/delta_generator.py
  lib/streamlit/deprecation_util.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/elements/widgets/button_group.py
  lib/streamlit/elements/widgets/camera_input.py
  lib/streamlit/elements/widgets/chat.py
  lib/streamlit/elements/widgets/checkbox.py
  lib/streamlit/elements/widgets/color_picker.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/elements/widgets/file_uploader.py
  lib/streamlit/elements/widgets/multiselect.py
  lib/streamlit/elements/widgets/number_input.py
  lib/streamlit/elements/widgets/radio.py
  lib/streamlit/elements/widgets/select_slider.py
  lib/streamlit/elements/widgets/selectbox.py
  lib/streamlit/elements/widgets/slider.py
  lib/streamlit/elements/widgets/text_widgets.py
  lib/streamlit/elements/widgets/time_widgets.py
  lib/streamlit/external/langchain/streamlit_callback_handler.py
  lib/streamlit/runtime/caching/cached_message_replay.py
  lib/streamlit/runtime/caching/legacy_cache_api.py
  lib/streamlit/runtime/caching/storage/dummy_cache_storage.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/state/common.py
  lib/streamlit/runtime/state/session_state.py
  lib/streamlit/web/bootstrap.py
  lib/streamlit/web/server/media_file_handler.py
  lib/tests/streamlit/elements/button_group_test.py
  lib/tests/streamlit/elements/multiselect_test.py
  lib/tests/streamlit/elements/selectbox_test.py
  lib/tests/streamlit/runtime/pages_manager_test.py
  lib/tests/streamlit/runtime/state/session_state_test.py
  lib/tests/streamlit/runtime/state/strategies.py
  lib/tests/streamlit/runtime/state/widgets_test.py
  scripts/cli_regression_tests.py
Labels: security-assessment-completed, change:other, impact:internal

#9656 added server.FolderWatchList to cli + LocalSourcesWatcher
  lib/streamlit/config.py
  lib/streamlit/watcher/event_based_path_watcher.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
Labels: security-assessment-completed, change:feature, impact:users

#11176 [AdvancedLayouts] Adds a width parameter to st.code
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-width_pixels[chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-width_pixels[firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-width_pixels[webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-width_stretch[webkit].png
  e2e_playwright/st_code.py
  e2e_playwright/st_code_test.py
  lib/streamlit/elements/code.py
  lib/tests/streamlit/elements/code_test.py
  proto/streamlit/proto/Code.proto
Labels: security-assessment-completed, change:feature, impact:users

#11216 Activate pylint refactoring linting rule set in ruff
  .ruff.toml
  e2e_playwright/conftest.py
  lib/streamlit/commands/experimental_query_params.py
  lib/streamlit/elements/arrow.py
  lib/streamlit/elements/deck_gl_json_chart.py
  lib/streamlit/elements/dialog_decorator.py
  lib/streamlit/elements/image.py
  lib/streamlit/elements/lib/image_utils.py
  lib/streamlit/elements/map.py
  lib/streamlit/elements/plotly_chart.py
  lib/streamlit/elements/vega_charts.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/error_util.py
  lib/streamlit/logger.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/hashing.py
  lib/streamlit/runtime/context.py
  lib/streamlit/runtime/forward_msg_queue.py
  lib/streamlit/runtime/runtime_util.py
  lib/streamlit/web/cli.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/elements/element_policies_test.py
  lib/tests/streamlit/elements/image_test.py
  lib/tests/streamlit/elements/lib/column_config_utils_test.py
  lib/tests/streamlit/elements/pydeck_test.py
  lib/tests/streamlit/repr_test.py
  lib/tests/streamlit/runtime/app_session_test.py
  lib/tests/streamlit/runtime/scriptrunner/magic_test.py
  lib/tests/streamlit/runtime/state/query_params_test.py
  lib/tests/streamlit/source_util_test.py
  lib/tests/streamlit/web/server/server_util_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11198 Update warnings to mention st.user instead of experimental_user
  lib/streamlit/user_info.py
Labels: security-assessment-completed, change:chore, impact:users

#11200 Enable python integration tests for all PRs
  .cursor/rules/python_tests.mdc
  .github/workflows/python-tests.yml
  lib/tests/streamlit/dataframe_util_test.py
Labels: security-assessment-completed, change:other, impact:internal

#11236 Increase the dependabot PR limit for Python
  .github/dependabot.yml
Labels: security-assessment-completed, change:other, impact:internal

#11169 fix incorrect comment in `_make_function_key` used by cache_* APIs
  lib/streamlit/runtime/caching/cache_utils.py
Labels: security-assessment-completed, impact:internal, change:chore

#11177 [AdvancedLayouts] Adds a width parameter to st.json
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-keep_bounds[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-width_pixels[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-width_pixels[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-width_pixels[webkit].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_json_test/st_json-width_stretch[webkit].png
  e2e_playwright/st_json.py
  e2e_playwright/st_json_test.py
  lib/streamlit/elements/json.py
  lib/tests/streamlit/elements/json_test.py
  proto/streamlit/proto/Json.proto
Labels: security-assessment-completed, change:feature, impact:users

#11181 [AdvancedLayouts] Adds a width parameter to st.help
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-fixed_width[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-fixed_width[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-fixed_width[webkit].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-stretch_width_explicit[chromium].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-stretch_width_explicit[firefox].png
  e2e_playwright/__snapshots__/linux/st_help_test/st_help-stretch_width_explicit[webkit].png
  e2e_playwright/st_help.py
  e2e_playwright/st_help_test.py
  lib/streamlit/elements/doc_string.py
  lib/tests/streamlit/elements/doc_string_test.py
  proto/streamlit/proto/DocString.proto
Labels: security-assessment-completed, change:feature, impact:users

#11243 [AdvancedLayouts] Adds a width parameter to st.audio_input
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_300px[webkit].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[chromium].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[firefox].png
  e2e_playwright/__snapshots__/linux/st_audio_input_test/st_audio_input-width_stretch[webkit].png
  e2e_playwright/st_audio_input.py
  e2e_playwright/st_audio_input_test.py
  lib/streamlit/elements/widgets/audio_input.py
  lib/tests/streamlit/elements/audio_input_test.py
  proto/streamlit/proto/AudioInput.proto
Labels: security-assessment-completed, change:feature, impact:users
