Repository streamlit/streamlit, pull requests merged in 2025-01, with the labels that each got.

#10081 Add `make update-snapshots-changed` to update snapshots for changed files
  Makefile
  scripts/update_e2e_snapshots.py
Labels: security-assessment-completed, change:other, impact:internal

#10097 Ensure that error is only logged once with rich installed
  lib/streamlit/error_util.py
  lib/tests/streamlit/error_util_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10047 Update chat input widget border radius
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[webkit].png
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
  frontend/lib/src/theme/primitives/radii.ts
Labels: security-assessment-completed, change:feature, impact:users

#10104 Add row hover color to dataframe component
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-row_hover_highlight[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-row_hover_highlight[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-row_hover_highlight[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-row_hover_highlight[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-row_hover_highlight[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-row_hover_highlight[light_theme-webkit].png
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/index.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useCustomTheme.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useRowHover.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useRowHover.ts
Labels: security-assessment-completed, change:feature, impact:users

#10108 Update outdated snapshots to get CI working again
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[webkit].png
Labels: security-assessment-completed, change:other, impact:internal

#10060 Prevent showing 0 for small numbers in dataframe
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#9620 Refine `st.date_input` to ensure consistent and accurate return types
  lib/streamlit/elements/widgets/time_widgets.py
  lib/tests/streamlit/typing/date_input_types.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10113 Auth authlib lazy authlib import
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/auth_util.py
  lib/streamlit/web/server/server.py
  lib/test-requirements.txt
Labels: security-assessment-completed, impact:internal, change:chore

#10110 Change wording for auth exception messages
  lib/streamlit/auth_util.py
  lib/tests/streamlit/user_info_test.py
Labels: security-assessment-completed, impact:internal, change:docs

#10080 Add `height` parameter to `st.code`
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-long-code[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-long-code[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-long-code[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-long-code[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-long-code[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-long-code[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-short-code[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-short-code[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-short-code[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-short-code[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-short-code[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_code_test/st_code-height-short-code[light_theme-webkit].png
  e2e_playwright/st_code.py
  e2e_playwright/st_code_test.py
  frontend/lib/src/components/core/Block/ElementNodeRenderer.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.test.tsx
  frontend/lib/src/components/elements/CodeBlock/StreamlitSyntaxHighlighter.tsx
  frontend/lib/src/components/elements/CodeBlock/styled-components.ts
  lib/streamlit/elements/code.py
  proto/streamlit/proto/Code.proto
Labels: security-assessment-completed, change:feature, impact:users

#10116 Fix CI issues with ubuntu 24 update
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
  .github/workflows/python-min-deps.yml
Labels: security-assessment-completed, change:other, impact:internal

#10087 In st.multiselect, make mouse cursor only be a pointer when hovering the X
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
Labels: security-assessment-completed, change:bugfix, impact:users

#9920 Refactor arrow formatting utils to reduce reliance on pandas metadata
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-10[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-11[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-12[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-13[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-14[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-15[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-15[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-15[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-16[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-16[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-16[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-17[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-17[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-17[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-18[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-19[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-20[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-21[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-22[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-23[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-24[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-25[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-26[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-27[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-28[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-29[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-30[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-30[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-30[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-4[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-5[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-6[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-7[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-7[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-7[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-8[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-9[webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-themed[light_theme-webkit].png
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/dataframes/arrowFormatUtils.test.ts
  frontend/lib/src/dataframes/arrowFormatUtils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10118 Move arrow parsing logic to dedicated utils module
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/dataframes/arrowParseUtils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10109 Upgrade d3 dependencies to fix dependabot alert
  NOTICES
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz-chart_dot_string[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz-chart_dot_string[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz-chart_dot_string[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-circo[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-dot[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-fdp[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-fdp[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-fdp[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-neato[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-neato[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-neato[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-osage[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-osage[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-osage[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-patchwork[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-twopi[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-twopi[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_engine-twopi[webkit].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_use_container_width_true[chromium].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_use_container_width_true[firefox].png
  e2e_playwright/__snapshots__/linux/st_graphviz_chart_test/st_graphviz_chart_use_container_width_true[webkit].png
  frontend/lib/package.json
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/elements/GraphVizChart/styled-components.ts
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#9973 Auth authlib ALTERNATIVE API
  e2e_playwright/auth.py
  lib/min-constraints-gen.txt
  lib/setup.py
  lib/streamlit/__init__.py
  lib/streamlit/auth_util.py
  lib/streamlit/user_info.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/streamlit/web/server/oauth_authlib_routes.py
  lib/streamlit/web/server/server.py
  lib/test-requirements.txt
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/user_info_test.py
  lib/tests/streamlit/web/server/oauth_authlib_routes_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#9959 Refactor vega lite chart component to a React functional component
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.test.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/ArrowVegaLiteChart.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaElementPreprocessor.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaElementPreprocessor.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaLiteSelections.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaLiteSelections.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10124 Fix typo in function name
  lib/streamlit/elements/markdown.py
  lib/streamlit/elements/write.py
  lib/streamlit/type_util.py
Labels: security-assessment-completed, impact:internal, change:chore

#8786 Auth feature
  e2e_playwright/auth.py
  e2e_playwright/auth_test.py
  e2e_playwright/conftest.py
  e2e_playwright/shared/oidc_mock_server.py
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/hostframe.html
  frontend/lib/src/hostComm/HostCommunicationManager.tsx
  frontend/lib/src/hostComm/types.ts
  lib/streamlit/__init__.py
  lib/streamlit/auth_util.py
  lib/streamlit/errors.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/runtime.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/runtime/scriptrunner_utils/script_run_context.py
  lib/streamlit/runtime/session_manager.py
  lib/streamlit/runtime/websocket_session_manager.py
  lib/streamlit/url_util.py
  lib/streamlit/user_info.py
  lib/streamlit/web/server/authlib_tornado_integration.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/streamlit/web/server/oauth_authlib_routes.py
  lib/streamlit/web/server/oidc_mixin.py
  lib/streamlit/web/server/routes.py
  lib/streamlit/web/server/server.py
  lib/streamlit/web/server/server_util.py
  lib/streamlit/web/server/upload_file_request_handler.py
  lib/test-requirements.txt
  lib/tests/delta_generator_test_case.py
  lib/tests/streamlit/auth_util_test.py
  lib/tests/streamlit/delta_generator_test.py
  lib/tests/streamlit/runtime/metrics_util_test.py
  lib/tests/streamlit/streamlit_test.py
  lib/tests/streamlit/user_info_test.py
  lib/tests/streamlit/web/server/authlib_tornado_integration_test.py
  lib/tests/streamlit/web/server/oauth_authlib_routes_test.py
  lib/tests/streamlit/web/server/oidc_mixin_test.py
  proto/streamlit/proto/AuthRedirect.proto
  proto/streamlit/proto/ForwardMsg.proto
Labels: security-assessment-completed, change:feature, impact:users

#10052 [test] Add dedicated playwright-performance CI job
  .github/workflows/playwright-performance.yml
  Makefile
  e2e_playwright/pytest.ini
  e2e_playwright/st_form_test.py
  lib/test-requirements.txt
Labels: security-assessment-completed, impact:internal, change:chore

#10072 Show elapsed time on `st.spinner`
  e2e_playwright/st_spinner.py
  e2e_playwright/st_spinner_test.py
  frontend/lib/src/components/elements/Spinner/Spinner.test.tsx
  frontend/lib/src/components/elements/Spinner/Spinner.tsx
  frontend/lib/src/components/elements/Spinner/styled-components.ts
  lib/streamlit/elements/spinner.py
  lib/tests/streamlit/spinner_test.py
  proto/streamlit/proto/Spinner.proto
Labels: security-assessment-completed, change:feature, impact:users

#10125 Remove shortcut to data checking and substitute with a rough hash
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-after_update[chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-after_update[firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-after_update[webkit].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-before_update[chromium].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-before_update[firefox].png
  e2e_playwright/__snapshots__/linux/st_vega_lite_chart_test/st_vega_lite_chart-before_update[webkit].png
  e2e_playwright/st_vega_lite_chart.py
  e2e_playwright/st_vega_lite_chart_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
  frontend/lib/src/dataframes/Quiver.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10142 Enforce d3-color 3.1 dependency
  NOTICES
  frontend/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, change:other, impact:internal

#10134 Clean up vendored ipython logic
  Makefile
  NOTICES
  lib/streamlit/runtime/scriptrunner/exec_code.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/vendor/ipython/IPython-LICENSE.txt
  lib/streamlit/vendor/ipython/__init__.py
  lib/streamlit/vendor/ipython/modified_sys_path.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10123 Simplify arrow utility by renaming to more descriptive names
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.test.ts
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/SelectboxColumn.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/dataframes/arrowConcatUtils.ts
  frontend/lib/src/dataframes/arrowFormatUtils.ts
  frontend/lib/src/dataframes/arrowParseUtils.ts
  frontend/lib/src/dataframes/arrowTypeUtils.test.ts
  frontend/lib/src/dataframes/arrowTypeUtils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10140 [test] Add targeted Playwright perf tests
  e2e_playwright/multipage_apps_v2/mpa_v2_basics_test.py
  e2e_playwright/st_dataframe_interactions_test.py
  e2e_playwright/st_dialog_test.py
  e2e_playwright/st_slider_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10013 Changes needed for public notebooks to record protobufs
  lib/streamlit/runtime/forward_msg_queue.py
  lib/tests/streamlit/runtime/forward_msg_queue_test.py
  proto/streamlit/proto/ForwardMsg.proto
Labels: security-assessment-completed, impact:internal, change:feature

#10149 Update emojis used for validation
  lib/streamlit/emojis.py
  scripts/update_emojis.py
Labels: security-assessment-completed, change:other, impact:users

#10147 Don't request_rerun for fragments that do not exist anymore
  lib/streamlit/runtime/app_session.py
  lib/tests/streamlit/runtime/app_session_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#9834 Use dynamic button label for button group
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-multiselect[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_pills_test/st_pills-singleselect_icon_only[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-multiselect[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_segmented_control_test/st_segmented_control-singleselect_icon_only[light_theme-firefox].png
  e2e_playwright/st_segmented_control_test.py
  frontend/lib/src/components/shared/BaseButton/DynamicButtonLabel.tsx
  frontend/lib/src/components/shared/BaseButton/styled-components.ts
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.tsx
  lib/streamlit/elements/widgets/button_group.py
  lib/tests/streamlit/elements/button_group_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10150 Refactor various aspects of arrow handling in frontend
  frontend/lib/src/AppNode.test.ts
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowVegaLiteChart/arrowUtils.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/columns/NumberColumn.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.test.ts
  frontend/lib/src/components/widgets/DataFrame/columns/utils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.test.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/dataframes/arrowConcatUtils.ts
  frontend/lib/src/dataframes/arrowFormatUtils.test.ts
  frontend/lib/src/dataframes/arrowFormatUtils.ts
  frontend/lib/src/dataframes/arrowParseUtils.ts
  frontend/lib/src/dataframes/arrowTypeUtils.test.ts
  frontend/lib/src/dataframes/arrowTypeUtils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10133 Activating linting rule for more consistent usage of built-in logging
  .ruff.toml
  lib/streamlit/config.py
  lib/streamlit/config_option.py
  lib/streamlit/dataframe_util.py
  lib/streamlit/delta_generator.py
  lib/streamlit/elements/exception.py
  lib/streamlit/elements/widgets/data_editor.py
  lib/streamlit/runtime/app_session.py
  lib/streamlit/runtime/caching/cache_data_api.py
  lib/streamlit/runtime/caching/cache_utils.py
  lib/streamlit/runtime/caching/storage/local_disk_cache_storage.py
  lib/streamlit/runtime/credentials.py
  lib/streamlit/runtime/forward_msg_cache.py
  lib/streamlit/runtime/pages_manager.py
  lib/streamlit/runtime/scriptrunner/script_runner.py
  lib/streamlit/watcher/local_sources_watcher.py
  lib/streamlit/web/server/browser_websocket_handler.py
  lib/tests/streamlit/runtime/credentials_test.py
  lib/tests/streamlit/watcher/local_sources_watcher_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10159 Remove protobuf version restriction in conda recipe
  lib/conda-recipe/meta.yaml
Labels: security-assessment-completed, impact:internal, change:chore

#9989 Upgrade yarn to latest
  .github/CODEOWNERS
  .github/actions/make_init/action.yml
  .github/workflows/component-template-e2e-tests.yml
  .github/workflows/enforce-pre-commit.yml
  .github/workflows/js-tests.yml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  NOTICES
  component-lib/.yarnrc.yml
  component-lib/package.json
  component-lib/yarn.lock
  frontend/.yarn/patches/@protobufjs-inquire-npm-1.1.0-3c7759e9ce.patch
  frontend/.yarn/plugins/@yarnpkg/plugin-licenses.cjs
  frontend/.yarnrc.yml
  frontend/app/package.json
  frontend/lib/package.json
  frontend/package.json
  frontend/yarn.lock
  scripts/audit_frontend_licenses.py
  scripts/check_license_headers.py
  scripts/update_version.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10083 Make widget dropdowns look more consistent + convert `BaseColorPicker` to functional component
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_before[webkit].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-toolbar_items[webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-popover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-popover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-popover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-popover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-popover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_color_picker_test/st_color_picker-popover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_sidebar_test/st_sidebar-date_popover[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-menu_colors[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-selection_dropdown[chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-selection_dropdown[firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-selection_dropdown[webkit].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-step_60_dropdown[chromium].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-step_60_dropdown[firefox].png
  e2e_playwright/__snapshots__/linux/st_time_input_test/st_time_input-step_60_dropdown[webkit].png
  e2e_playwright/hostframe_app.py
  e2e_playwright/hostframe_app_test.py
  e2e_playwright/st_color_picker_test.py
  frontend/lib/src/components/shared/BaseColorPicker/BaseColorPicker.tsx
  frontend/lib/src/components/shared/BaseColorPicker/styled-components.ts
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/widgets/DateInput/DateInput.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/TimeInput/TimeInput.tsx
  frontend/lib/src/declarations.d.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10177 split up WebsocketConnection.tsx to pass lint rule
  frontend/app/src/connection/DoInitPings.tsx
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/app/src/connection/constants.ts
  frontend/app/src/connection/types.ts
Labels: security-assessment-completed, impact:internal, change:chore

#10122 Remove usage of private snowflake-connector APIs
  lib/integration-requirements.txt
  lib/setup.py
  lib/streamlit/connections/snowflake_connection.py
  lib/tests/streamlit/connections/snowflake_connection_test.py
Labels: security-assessment-completed, change:refactor, impact:users

#10185 make `update-snapshots` for st.chat_input
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[webkit].png
Labels: security-assessment-completed, change:other, impact:internal

#10148 Add retry to watcher.util.path_modification_time to try and fix race condition.
  lib/streamlit/watcher/util.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10183 Refactor Pandas styler handling in frontend
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-31[chromium].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-31[firefox].png
  e2e_playwright/__snapshots__/linux/st_table_test/st_table-31[webkit].png
  e2e_playwright/st_table.py
  e2e_playwright/st_table_test.py
  frontend/lib/src/components/elements/ArrowTable/ArrowTable.tsx
  frontend/lib/src/components/elements/ArrowTable/styled-components.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.test.ts
  frontend/lib/src/components/widgets/DataFrame/arrowUtils.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataLoader.ts
  frontend/lib/src/dataframes/Quiver.test.ts
  frontend/lib/src/dataframes/Quiver.ts
  frontend/lib/src/dataframes/arrowFormatUtils.test.ts
  frontend/lib/src/dataframes/arrowParseUtils.ts
  frontend/lib/src/dataframes/pandasStylerUtils.test.ts
  frontend/lib/src/dataframes/pandasStylerUtils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10163 Make MPAv2 work with pure Python and with ProcessPoolExecutor
  lib/streamlit/commands/navigation.py
  lib/streamlit/elements/widgets/button.py
  lib/streamlit/navigation/page.py
  scripts/run_bare_execution_tests.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10164 Allow reusing existing event loop for server
  lib/streamlit/web/bootstrap.py
  lib/tests/streamlit/web/bootstrap_test.py
Labels: security-assessment-completed, change:feature, impact:users

#10187 fix element paddings and margins
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-callback[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-in_column_disabled[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[webkit].png
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10184 Consolidate border radii value and remove redundant css attr
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:refactor, impact:users

#10073 Preserve scroll position for `st.selectbox` and `st.multiselect`
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
Labels: security-assessment-completed, change:feature, impact:users

#10012 Increment Script Run Count on Fragment Run Finished in Addition to Run Finished
  lib/streamlit/config.py
  lib/streamlit/runtime/runtime.py
  lib/tests/streamlit/config_test.py
  lib/tests/streamlit/runtime/runtime_test.py
Labels: security-assessment-completed, impact:internal, change:bugfix

#10202 Add type annotations so st.altair_chart supports all Altair chart types.
  lib/streamlit/elements/vega_charts.py
Labels: security-assessment-completed, change:other, impact:users

#10180 [feat] Add pytest performance test suite
  .github/workflows/performance.yml
  .github/workflows/playwright-changed-files.yml
  .github/workflows/playwright-performance.yml
  .github/workflows/playwright.yml
  .gitignore
  Makefile
  e2e_playwright/shared/performance.py
  frontend/app/performance/lighthouse/LighthouseOrchestrator.mjs
  lib/pytest.ini
  lib/test-requirements.txt
  lib/tests/conftest.py
  lib/tests/streamlit/dataframe_util_test.py
  lib/tests/streamlit/elements/balloons_test.py
  lib/tests/streamlit/repr_test.py
Labels: security-assessment-completed, impact:internal, change:feature

#10222 [chore] Remove unnecessary nightly performance step
  .github/workflows/nightly.yml
Labels: security-assessment-completed, impact:internal, change:chore

#10206 Allow pinning dataframe columns from UI
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_pinned[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_pinned[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_pinned[webkit].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_unpinned[chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_unpinned[firefox].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_unpinned[webkit].png
  e2e_playwright/st_dataframe_interactions_test.py
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.test.tsx
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.tsx
  frontend/lib/src/components/widgets/DataFrame/DataFrame.tsx
  frontend/lib/src/components/widgets/DataFrame/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10225 Fix the chat input border radius
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
  frontend/lib/src/theme/primitives/radii.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10189 File upload drag and drop UI
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10223 Add support for borders to audio & file input
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[chromium].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[firefox].png
  e2e_playwright/__snapshots__/linux/hostframe_app_test/hostframe_app-theme_message_after[webkit].png
  frontend/lib/src/components/widgets/AudioInput/styled-components.ts
  frontend/lib/src/components/widgets/FileUploader/styled-components.ts
Labels: security-assessment-completed, change:other, impact:internal

#10228 Use rem sizes for charts to be responsive to the root font size
  e2e_playwright/hello_app_test.py
  frontend/lib/src/components/elements/ArrowVegaLiteChart/CustomTheme.tsx
  frontend/lib/src/components/elements/DeckGlJsonChart/useDeckGl.tsx
  frontend/lib/src/theme/primitives/sizes.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10238 Revert PR-10073: Preserve scrollposition for selectbox and multiselect
  frontend/lib/src/components/shared/Dropdown/Selectbox.tsx
  frontend/lib/src/components/shared/Dropdown/VirtualDropdown.tsx
  frontend/lib/src/components/widgets/Multiselect/Multiselect.tsx
  frontend/lib/src/components/widgets/Selectbox/Selectbox.test.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10200 Authentication docstrings
  lib/streamlit/user_info.py
Labels: security-assessment-completed, impact:internal, change:docs

#10241 Follow-up on variable rename
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
Labels: security-assessment-completed, impact:internal, change:chore

#10243 add italic label for upload button, bolded drag and drop text
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:feature, impact:users

#10237 Use `attribute` word instead of `key` in case of AttributeError in st.query_params
  lib/streamlit/runtime/state/query_params.py
  lib/streamlit/runtime/state/query_params_proxy.py
  lib/tests/streamlit/runtime/state/query_params_proxy_test.py
Labels: security-assessment-completed, change:bugfix, impact:users

#10247 Update material symbols font and test
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[chromium].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[firefox].png
  e2e_playwright/__snapshots__/linux/st_alert_test/st_alert-latest_material_symbol[webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_icon[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_icon[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_icon[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_icon[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_icon[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_icon[light_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_markdown[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_markdown[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_markdown[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_markdown[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_markdown[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_button_test/st_button-material_icon_1k_markdown[light_theme-webkit].png
  e2e_playwright/st_alert.py
  e2e_playwright/st_button.py
  e2e_playwright/st_button_test.py
  frontend/app/src/assets/fonts/MaterialSymbols/MaterialSymbols-Rounded.woff2
  frontend/lib/src/components/shared/Icon/Material/MaterialFontIcon.tsx
  frontend/lib/src/components/widgets/ButtonGroup/ButtonGroup.test.tsx
  lib/streamlit/material_icon_names.py
Labels: security-assessment-completed, change:chore, impact:users

#10250 Revert "add italic label for upload button, bolded drag and drop text"
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.test.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/StreamlitMarkdown.tsx
  frontend/lib/src/components/shared/StreamlitMarkdown/styled-components.ts
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10209 `StaticConnection` for FE-only streamlit apps
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[chromium].png
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[firefox].png
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/pytest.ini
  e2e_playwright/static_app.py
  e2e_playwright/static_app_test.py
  frontend/app/src/App.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/ConnectionState.ts
  frontend/app/src/connection/StaticConnection.test.tsx
  frontend/app/src/connection/StaticConnection.tsx
Labels: security-assessment-completed, impact:internal, change:feature

#10248 Add e2e test for custom theming
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[chromium].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[firefox].png
  e2e_playwright/__snapshots__/linux/custom_theme_test/custom_themed_app[webkit].png
  e2e_playwright/conftest.py
  e2e_playwright/custom_theme.py
  e2e_playwright/custom_theme_test.py
  e2e_playwright/multipage_apps/mpa_basics_test.py
  e2e_playwright/st_chat_input_test.py
Labels: security-assessment-completed, change:other, impact:internal

#10252 Fix file_uploader in chat_input backend merge
  lib/streamlit/runtime/state/widgets.py
Labels: security-assessment-completed, impact:internal, change:chore

#10261 Chat input with file uploader e2e tests
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_embedded_with_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[light_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-grows[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-max_chars[light_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shift_enter_new_line[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single-file[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[firefox].png
  e2e_playwright/st_chat_input.py
  e2e_playwright/st_chat_input_test.py
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/UploadedFile/ChatUploadedFiles.tsx
Labels: security-assessment-completed, change:other, impact:internal

#10262 Fix hover on column menu
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_dataframe_interactions_test/st_dataframe-column_menu[light_theme-chromium].png
  frontend/lib/src/components/widgets/DataFrame/ColumnMenu.tsx
Labels: security-assessment-completed, impact:internal, change:bugfix

#10263 import fix
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/UploadedFile/ChatUploadedFile.tsx
  frontend/lib/src/components/widgets/ChatInput/UploadedFile/ChatUploadedFileIconTooltip.tsx
  frontend/lib/src/components/widgets/ChatInput/UploadedFile/ChatUploadedFiles.tsx
  frontend/lib/src/components/widgets/ChatInput/UploadedFile/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:bugfix

#10267 [lint fix] use FilePayload object for playwright file chooser
  e2e_playwright/st_file_uploader_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10268 Apply top margin in top-aligned columns to first element instead of last
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_bottom[webkit].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[chromium].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[firefox].png
  e2e_playwright/__snapshots__/linux/st_columns_test/st_columns-vertical_alignment_top[webkit].png
  e2e_playwright/st_columns.py
  e2e_playwright/st_columns_test.py
  frontend/lib/src/components/core/Block/styled-components.ts
Labels: security-assessment-completed, change:bugfix, impact:users

#10260 Remove reading user info from `X-Streamlit-User` header
  lib/streamlit/web/server/browser_websocket_handler.py
Labels: security-assessment-completed, change:chore, impact:users

#10278 [Fix] Resolve flaky static app e2e test
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[chromium].png
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[firefox].png
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[webkit].png
  e2e_playwright/static_app_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10280 Update plotly snapshots to fix CI
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-sunburst_custom_color[dark_theme-chromium].png
  e2e_playwright/__snapshots__/linux/st_plotly_chart_test/st_plotly_chart-sunburst_custom_color[light_theme-chromium].png
Labels: security-assessment-completed, change:other, impact:internal

#10277 Handle media for `StaticConnection`
  e2e_playwright/static_app_test.py
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/app/src/connection/StaticConnection.test.tsx
  frontend/app/src/connection/StaticConnection.tsx
  frontend/lib/src/FileUploadClient.test.ts
  frontend/lib/src/ForwardMessageCache.test.ts
  frontend/lib/src/StreamlitEndpoints.ts
  frontend/lib/src/mocks/mocks.ts
Labels: security-assessment-completed, impact:internal, change:feature

#10284 upgrade react-dropzone to latest
  frontend/lib/package.json
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.tsx
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#10286 [Fix] Remove static app e2e test (temporarily)
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[chromium].png
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[firefox].png
  e2e_playwright/__snapshots__/linux/static_app_test/example_static_app[webkit].png
  e2e_playwright/static_app.py
  e2e_playwright/static_app_test.py
Labels: security-assessment-completed, impact:internal, change:refactor

#10274 Add static deploy GHA workflow
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
  .github/workflows/static-deploy.yml
Labels: security-assessment-completed, change:other, impact:internal

#10288 Update file uploader to uses new `accept` value
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.tsx
Labels: security-assessment-completed, change:refactor, impact:users

#10291 Split `FileUploadArea` and handlers out from `ChatInput`
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatUploadedFile.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatUploadedFileIconTooltip.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/ChatUploadedFiles.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/FileUploadArea.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/createDropHandler.ts
  frontend/lib/src/components/widgets/ChatInput/fileUpload/createFileUploadHandler.ts
  frontend/lib/src/components/widgets/ChatInput/fileUpload/styled-components.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10292 use new mimetype utils for dropzone `accept` value
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/FileUploader/FileDropzone.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#10289 [Fix] `MetricsManager` parse error
  frontend/app/src/MetricsManager.ts
Labels: security-assessment-completed, impact:internal, change:chore

#10266 use FilePayload object & fix timeout for filechooser
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-app_bottom[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-focused[dark_theme-firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-inline[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple-files[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-multiple_files_uploaded[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-shrinks[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[chromium].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[firefox].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-single_file_uploaded[webkit].png
  e2e_playwright/__snapshots__/linux/st_chat_input_test/st_chat_input-submit_hover[chromium].png
  e2e_playwright/st_chat_input_test.py
Labels: security-assessment-completed, impact:internal, change:chore

#10269 File upload for chat button tooltip
  frontend/lib/src/components/widgets/ChatInput/ChatInput.tsx
  frontend/lib/src/components/widgets/ChatInput/fileUpload/FileUploadArea.tsx
Labels: security-assessment-completed, change:feature, impact:users

#10295 Upgrade typescript to latest (5.7.3)
  frontend/app/package.json
  frontend/lib/src/FileUploadClient.test.ts
  frontend/lib/src/util/utils.test.ts
  frontend/typescript-config/base.tsconfig.json
  frontend/typescript-config/package.json
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#10294 Utilize new protobuf package in @streamlit/app and remove the export from @streamlit/lib
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/MetricsManager.ts
  frontend/app/src/SessionEventDispatcher.ts
  frontend/app/src/StreamlitLib.test.tsx
  frontend/app/src/components/AppContext.tsx
  frontend/app/src/components/AppView/AppView.test.tsx
  frontend/app/src/components/AppView/AppView.tsx
  frontend/app/src/components/MainMenu/MainMenu.test.tsx
  frontend/app/src/components/MainMenu/MainMenu.tsx
  frontend/app/src/components/Sidebar/Sidebar.test.tsx
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/SidebarNav.test.tsx
  frontend/app/src/components/Sidebar/SidebarNav.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.test.tsx
  frontend/app/src/components/StatusWidget/StatusWidget.tsx
  frontend/app/src/components/StreamlitDialog/DeployDialog/DeployDialog.tsx
  frontend/app/src/components/StreamlitDialog/StreamlitDialog.tsx
  frontend/app/src/components/StreamlitDialog/ThemeCreatorDialog.test.tsx
  frontend/app/src/components/StreamlitDialog/themeUtils.test.ts
  frontend/app/src/components/StreamlitDialog/themeUtils.ts
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/app/src/connection/StaticConnection.test.tsx
  frontend/app/src/connection/StaticConnection.tsx
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/app/src/showDevelopmentOptions.ts
  frontend/app/src/util/AppNavigation.test.ts
  frontend/app/src/util/AppNavigation.ts
  frontend/app/src/util/useThemeManager.ts
  frontend/lib/src/index.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#10287 Replace logging with loglevel
  frontend/app/package.json
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/MetricsManager.ts
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/DoInitPings.tsx
  frontend/app/src/connection/StaticConnection.test.tsx
  frontend/app/src/connection/StaticConnection.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/app/src/hocs/withScreencast/withScreencast.tsx
  frontend/app/src/index.tsx
  frontend/app/src/util/ScreenCastRecorder.ts
  frontend/lib/package.json
  frontend/lib/src/FileUploadClient.ts
  frontend/lib/src/ForwardMessageCache.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaEmbed.ts
  frontend/lib/src/components/elements/ArrowVegaLiteChart/useVegaLiteSelections.ts
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.test.tsx
  frontend/lib/src/components/elements/GraphVizChart/GraphVizChart.tsx
  frontend/lib/src/components/elements/PlotlyChart/CustomTheme.tsx
  frontend/lib/src/components/shared/ErrorBoundary/ErrorBoundary.tsx
  frontend/lib/src/components/widgets/AudioInput/convertAudioToWav.ts
  frontend/lib/src/components/widgets/CameraInput/CameraInput.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.test.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentInstance.tsx
  frontend/lib/src/components/widgets/CustomComponent/ComponentRegistry.ts
  frontend/lib/src/components/widgets/CustomComponent/componentUtils.tsx
  frontend/lib/src/components/widgets/DataFrame/hooks/useColumnLoader.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataEditor.ts
  frontend/lib/src/components/widgets/DataFrame/hooks/useDataExporter.ts
  frontend/lib/src/components/widgets/NumberInput/NumberInput.tsx
  frontend/lib/src/dataframes/arrowFormatUtils.ts
  frontend/lib/src/index.ts
  frontend/lib/src/profiler/PerformanceEvents.ts
  frontend/lib/src/theme/utils.ts
  frontend/lib/src/util/log.ts
  frontend/yarn.lock
Labels: security-assessment-completed, impact:internal, change:refactor

#10297 Decouple SessionInfo from connection
  frontend/app/src/App.tsx
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
Labels: security-assessment-completed, impact:internal, change:refactor

#10293 Remove BaseUriParts type in favor of standard Location
  frontend/app/src/App.test.tsx
  frontend/app/src/App.tsx
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.test.ts
  frontend/app/src/connection/DefaultStreamlitEndpoints.ts
  frontend/app/src/connection/DoInitPings.tsx
  frontend/app/src/connection/StaticConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/lib/src/baseconsts.ts
  frontend/lib/src/index.ts
  frontend/lib/src/util/UriUtil.test.ts
  frontend/lib/src/util/UriUtil.ts
  frontend/lib/src/util/utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10298 Remove PerformanceEvents
  frontend/app/src/App.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/lib/src/index.ts
  frontend/lib/src/profiler/PerformanceEvents.ts
  frontend/lib/src/profiler/RerunAnalyzer.ts
  frontend/lib/src/profiler/Utils.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10301 Remove React from connection logic
  frontend/app/src/App.tsx
  frontend/app/src/connection/ConnectionManager.ts
  frontend/app/src/connection/DoInitPings.tsx
  frontend/app/src/connection/WebsocketConnection.test.tsx
  frontend/app/src/connection/WebsocketConnection.tsx
  frontend/app/src/connection/constants.ts
  frontend/app/src/connection/types.ts
Labels: security-assessment-completed, impact:internal, change:refactor

#10230 Converting sidebar to functional component
  frontend/app/src/components/Sidebar/Sidebar.tsx
  frontend/app/src/components/Sidebar/utils.test.ts
  frontend/app/src/components/Sidebar/utils.ts
Labels: security-assessment-completed, impact:internal, change:chore

#10305 Vertical and horizontal positioning according to product spec
  frontend/lib/src/components/core/Block/Block.tsx
  frontend/lib/src/components/core/Block/styled-components.ts
Labels: security-assessment-completed
